import _archAwsAppConfig16Svg from './Arch_AWS-AppConfig_16.svg';
import _archAwsApplicationAutoScaling16Svg from './Arch_AWS-Application-Auto-Scaling_16.svg';
import _archAwsAutoScaling16Svg from './Arch_AWS-Auto-Scaling_16.svg';
import _archAwsBackintAgent16Svg from './Arch_AWS-Backint-Agent_16.svg';
import _archAwsChatbot16Svg from './Arch_AWS-Chatbot_16.svg';
import _archAwsCloudFormation16Svg from './Arch_AWS-CloudFormation_16.svg';
import _archAwsCloudTrail16Svg from './Arch_AWS-CloudTrail_16.svg';
import _archAwsConfig16Svg from './Arch_AWS-Config_16.svg';
import _archAwsControlTower16Svg from './Arch_AWS-Control-Tower_16.svg';
import _archAwsDistroForOpenTelemetry16Svg from './Arch_AWS-Distro-for-OpenTelemetry_16.svg';
import _archAwsFaultInjectionSimulator16Svg from './Arch_AWS-Fault-Injection-Simulator_16.svg';
import _archAwsLaunchWizard16Svg from './Arch_AWS-Launch-Wizard_16.svg';
import _archAwsLicenseManager16Svg from './Arch_AWS-License-Manager_16.svg';
import _archAwsManagementConsole16Svg from './Arch_AWS-Management-Console_16.svg';
import _archAwsOpsWorks16Svg from './Arch_AWS-OpsWorks_16.svg';
import _archAwsOrganizations16Svg from './Arch_AWS-Organizations_16.svg';
import _archAwsPersonalHealthDashboard16Svg from './Arch_AWS-Personal-Health-Dashboard_16.svg';
import _archAwsProton16Svg from './Arch_AWS-Proton_16.svg';
import _archAwsResilienceHub16Svg from './Arch_AWS-Resilience-Hub_16.svg';
import _archAwsServiceCatalog16Svg from './Arch_AWS-Service-Catalog_16.svg';
import _archAwsSystemsManagerIncidentManager16Svg from './Arch_AWS-Systems-Manager-Incident-Manager_16.svg';
import _archAwsSystemsManager16Svg from './Arch_AWS-Systems-Manager_16.svg';
import _archAwsTrustedAdvisor16Svg from './Arch_AWS-Trusted-Advisor_16.svg';
import _archAwsWellArchitectedTool16Svg from './Arch_AWS-Well-Architected-Tool_16.svg';
import _archAmazonCloudWatch16Svg from './Arch_Amazon-CloudWatch_16.svg';
import _archAmazonManagedGrafana16Svg from './Arch_Amazon-Managed-Grafana_16.svg';
import _archAmazonManagedServiceForPrometheus16Svg from './Arch_Amazon-Managed-Service-for-Prometheus_16.svg';

export const archAwsAppConfig16Svg = { id: "archAwsAppConfig16Svg", name: "AWS AppConfig", icon: _archAwsAppConfig16Svg };
export const archAwsApplicationAutoScaling16Svg = { id: "archAwsApplicationAutoScaling16Svg", name: "AWS Application Auto Scaling", icon: _archAwsApplicationAutoScaling16Svg };
export const archAwsAutoScaling16Svg = { id: "archAwsAutoScaling16Svg", name: "AWS Auto Scaling", icon: _archAwsAutoScaling16Svg };
export const archAwsBackintAgent16Svg = { id: "archAwsBackintAgent16Svg", name: "AWS Backint Agent", icon: _archAwsBackintAgent16Svg };
export const archAwsChatbot16Svg = { id: "archAwsChatbot16Svg", name: "AWS Chatbot", icon: _archAwsChatbot16Svg };
export const archAwsCloudFormation16Svg = { id: "archAwsCloudFormation16Svg", name: "AWS CloudFormation", icon: _archAwsCloudFormation16Svg };
export const archAwsCloudTrail16Svg = { id: "archAwsCloudTrail16Svg", name: "AWS CloudTrail", icon: _archAwsCloudTrail16Svg };
export const archAwsConfig16Svg = { id: "archAwsConfig16Svg", name: "AWS Config", icon: _archAwsConfig16Svg };
export const archAwsControlTower16Svg = { id: "archAwsControlTower16Svg", name: "AWS Control Tower", icon: _archAwsControlTower16Svg };
export const archAwsDistroForOpenTelemetry16Svg = { id: "archAwsDistroForOpenTelemetry16Svg", name: "AWS Distro for OpenTelemetry", icon: _archAwsDistroForOpenTelemetry16Svg };
export const archAwsFaultInjectionSimulator16Svg = { id: "archAwsFaultInjectionSimulator16Svg", name: "AWS Fault Injection Simulator", icon: _archAwsFaultInjectionSimulator16Svg };
export const archAwsLaunchWizard16Svg = { id: "archAwsLaunchWizard16Svg", name: "AWS Launch Wizard", icon: _archAwsLaunchWizard16Svg };
export const archAwsLicenseManager16Svg = { id: "archAwsLicenseManager16Svg", name: "AWS License Manager", icon: _archAwsLicenseManager16Svg };
export const archAwsManagementConsole16Svg = { id: "archAwsManagementConsole16Svg", name: "AWS Management Console", icon: _archAwsManagementConsole16Svg };
export const archAwsOpsWorks16Svg = { id: "archAwsOpsWorks16Svg", name: "AWS OpsWorks", icon: _archAwsOpsWorks16Svg };
export const archAwsOrganizations16Svg = { id: "archAwsOrganizations16Svg", name: "AWS Organizations", icon: _archAwsOrganizations16Svg };
export const archAwsPersonalHealthDashboard16Svg = { id: "archAwsPersonalHealthDashboard16Svg", name: "AWS Personal Health Dashboard", icon: _archAwsPersonalHealthDashboard16Svg };
export const archAwsProton16Svg = { id: "archAwsProton16Svg", name: "AWS Proton", icon: _archAwsProton16Svg };
export const archAwsResilienceHub16Svg = { id: "archAwsResilienceHub16Svg", name: "AWS Resilience Hub", icon: _archAwsResilienceHub16Svg };
export const archAwsServiceCatalog16Svg = { id: "archAwsServiceCatalog16Svg", name: "AWS Service Catalog", icon: _archAwsServiceCatalog16Svg };
export const archAwsSystemsManagerIncidentManager16Svg = { id: "archAwsSystemsManagerIncidentManager16Svg", name: "AWS Systems Manager Incident Manager", icon: _archAwsSystemsManagerIncidentManager16Svg };
export const archAwsSystemsManager16Svg = { id: "archAwsSystemsManager16Svg", name: "AWS Systems Manager", icon: _archAwsSystemsManager16Svg };
export const archAwsTrustedAdvisor16Svg = { id: "archAwsTrustedAdvisor16Svg", name: "AWS Trusted Advisor", icon: _archAwsTrustedAdvisor16Svg };
export const archAwsWellArchitectedTool16Svg = { id: "archAwsWellArchitectedTool16Svg", name: "AWS Well Architected Tool", icon: _archAwsWellArchitectedTool16Svg };
export const archAmazonCloudWatch16Svg = { id: "archAmazonCloudWatch16Svg", name: "Amazon CloudWatch", icon: _archAmazonCloudWatch16Svg };
export const archAmazonManagedGrafana16Svg = { id: "archAmazonManagedGrafana16Svg", name: "Amazon Managed Grafana", icon: _archAmazonManagedGrafana16Svg };
export const archAmazonManagedServiceForPrometheus16Svg = { id: "archAmazonManagedServiceForPrometheus16Svg", name: "Amazon Managed Service for Prometheus", icon: _archAmazonManagedServiceForPrometheus16Svg };
