import _resAwsBackupAwsBackupSupportForAmazonFsxForNetAppOntap48DarkSvg from './Res_AWS-Backup_AWS-Backup-support-for-Amazon-FSx-for-NetApp-ONTAP_48_Dark.svg';
import _resAwsBackupAwsBackupSupportForAmazonS348DarkSvg from './Res_AWS-Backup_AWS-Backup-support-for-Amazon-S3_48_Dark.svg';
import _resAwsBackupAwsBackupSupportForVmwareWorkloads48DarkSvg from './Res_AWS-Backup_AWS-Backup-support-for-VMware-Workloads_48_Dark.svg';
import _resAwsBackupBackupPlan48DarkSvg from './Res_AWS-Backup_Backup-Plan_48_Dark.svg';
import _resAwsBackupBackupRestore48DarkSvg from './Res_AWS-Backup_Backup-Restore_48_Dark.svg';
import _resAwsBackupBackupVault48DarkSvg from './Res_AWS-Backup_Backup-Vault_48_Dark.svg';
import _resAwsBackupComplianceReporting48DarkSvg from './Res_AWS-Backup_Compliance-Reporting_48_Dark.svg';
import _resAwsBackupCompute48DarkSvg from './Res_AWS-Backup_Compute_48_Dark.svg';
import _resAwsBackupDatabase48DarkSvg from './Res_AWS-Backup_Database_48_Dark.svg';
import _resAwsBackupGateway48DarkSvg from './Res_AWS-Backup_Gateway_48_Dark.svg';
import _resAwsBackupRecoveryPointObjective48DarkSvg from './Res_AWS-Backup_Recovery-Point-Objective_48_Dark.svg';
import _resAwsBackupRecoveryTimeObjective48DarkSvg from './Res_AWS-Backup_Recovery-Time-Objective_48_Dark.svg';
import _resAwsBackupStorage48DarkSvg from './Res_AWS-Backup_Storage_48_Dark.svg';
import _resAwsBackupVirtualMachineMonitor48DarkSvg from './Res_AWS-Backup_Virtual-Machine-Monitor_48_Dark.svg';
import _resAwsBackupVirtualMachine48DarkSvg from './Res_AWS-Backup_Virtual-Machine_48_Dark.svg';
import _resAwsSnowballSnowballImportExport48DarkSvg from './Res_AWS-Snowball_Snowball-Import-Export_48_Dark.svg';
import _resAwsStorageGatewayAmazonFsxFileGateway48DarkSvg from './Res_AWS-Storage-Gateway_Amazon-FSx-File-Gateway_48_Dark.svg';
import _resAwsStorageGatewayAmazonS3FileGateway48DarkSvg from './Res_AWS-Storage-Gateway_Amazon-S3-File-Gateway_48_Dark.svg';
import _resAwsStorageGatewayCachedVolume48DarkSvg from './Res_AWS-Storage-Gateway_Cached-Volume_48_Dark.svg';
import _resAwsStorageGatewayFileGateway48DarkSvg from './Res_AWS-Storage-Gateway_File-Gateway_48_Dark.svg';
import _resAwsStorageGatewayNoncachedVolume48DarkSvg from './Res_AWS-Storage-Gateway_Noncached-Volume_48_Dark.svg';
import _resAwsStorageGatewayTapeGateway48DarkSvg from './Res_AWS-Storage-Gateway_Tape-Gateway_48_Dark.svg';
import _resAwsStorageGatewayVirtualTapeLibrary48DarkSvg from './Res_AWS-Storage-Gateway_Virtual-Tape-Library_48_Dark.svg';
import _resAwsStorageGatewayVolumeGateway48DarkSvg from './Res_AWS-Storage-Gateway_Volume-Gateway_48_Dark.svg';
import _resAmazonElasticBlockStoreAmazonDataLifecycleManager48DarkSvg from './Res_Amazon-Elastic-Block-Store_Amazon-Data-Lifecycle-Manager_48_Dark.svg';
import _resAmazonElasticBlockStoreMultipleVolumes48DarkSvg from './Res_Amazon-Elastic-Block-Store_Multiple-Volumes_48_Dark.svg';
import _resAmazonElasticBlockStoreSnapshot48DarkSvg from './Res_Amazon-Elastic-Block-Store_Snapshot_48_Dark.svg';
import _resAmazonElasticBlockStoreVolumeGp348DarkSvg from './Res_Amazon-Elastic-Block-Store_Volume-gp3_48_Dark.svg';
import _resAmazonElasticBlockStoreVolume48DarkSvg from './Res_Amazon-Elastic-Block-Store_Volume_48_Dark.svg';
import _resAmazonElasticFileSystemFileSystem48DarkSvg from './Res_Amazon-Elastic-File-System_File-System_48_Dark.svg';
import _resAmazonElasticFileSystemIntelligentTiering48DarkSvg from './Res_Amazon-Elastic-File-System_Intelligent-Tiering_48_Dark.svg';
import _resAmazonElasticFileSystemOneZoneInfrequentAccess48DarkSvg from './Res_Amazon-Elastic-File-System_One-Zone-Infrequent-Access_48_Dark.svg';
import _resAmazonElasticFileSystemOneZone48DarkSvg from './Res_Amazon-Elastic-File-System_One-Zone_48_Dark.svg';
import _resAmazonElasticFileSystemStandardInfrequentAccess48DarkSvg from './Res_Amazon-Elastic-File-System_Standard-Infrequent-Access_48_Dark.svg';
import _resAmazonElasticFileSystemStandard48DarkSvg from './Res_Amazon-Elastic-File-System_Standard_48_Dark.svg';
import _resAmazonSimpleStorageServiceGlacierArchive48DarkSvg from './Res_Amazon-Simple-Storage-Service-Glacier_Archive_48_Dark.svg';
import _resAmazonSimpleStorageServiceGlacierVault48DarkSvg from './Res_Amazon-Simple-Storage-Service-Glacier_Vault_48_Dark.svg';
import _resAmazonSimpleStorageServiceBucketWithObjects48DarkSvg from './Res_Amazon-Simple-Storage-Service_Bucket-With-Objects_48_Dark.svg';
import _resAmazonSimpleStorageServiceBucket48DarkSvg from './Res_Amazon-Simple-Storage-Service_Bucket_48_Dark.svg';
import _resAmazonSimpleStorageServiceGeneralAccessPoints48DarkSvg from './Res_Amazon-Simple-Storage-Service_General-Access-Points_48_Dark.svg';
import _resAmazonSimpleStorageServiceObject48DarkSvg from './Res_Amazon-Simple-Storage-Service_Object_48_Dark.svg';
import _resAmazonSimpleStorageServiceS3GlacierDeepArchive48DarkSvg from './Res_Amazon-Simple-Storage-Service_S3-Glacier-Deep-Archive_48_Dark.svg';
import _resAmazonSimpleStorageServiceS3GlacierFlexibleRetrieval48DarkSvg from './Res_Amazon-Simple-Storage-Service_S3-Glacier-Flexible-Retrieval_48_Dark.svg';
import _resAmazonSimpleStorageServiceS3GlacierInstantRetrieval48DarkSvg from './Res_Amazon-Simple-Storage-Service_S3-Glacier-Instant-Retrieval_48_Dark.svg';
import _resAmazonSimpleStorageServiceS3IntelligentTiering48DarkSvg from './Res_Amazon-Simple-Storage-Service_S3-Intelligent-Tiering_48_Dark.svg';
import _resAmazonSimpleStorageServiceS3ObjectLambdaAccessPoints48DarkSvg from './Res_Amazon-Simple-Storage-Service_S3-Object-Lambda-Access-Points_48_Dark.svg';
import _resAmazonSimpleStorageServiceS3ObjectLambda48DarkSvg from './Res_Amazon-Simple-Storage-Service_S3-Object-Lambda_48_Dark.svg';
import _resAmazonSimpleStorageServiceS3OnOutposts48DarkSvg from './Res_Amazon-Simple-Storage-Service_S3-On-Outposts_48_Dark.svg';
import _resAmazonSimpleStorageServiceS3OneZoneIa48DarkSvg from './Res_Amazon-Simple-Storage-Service_S3-One-Zone-IA_48_Dark.svg';
import _resAmazonSimpleStorageServiceS3ReplicationTimeControl48DarkSvg from './Res_Amazon-Simple-Storage-Service_S3-Replication-Time-Control_48_Dark.svg';
import _resAmazonSimpleStorageServiceS3Replication48DarkSvg from './Res_Amazon-Simple-Storage-Service_S3-Replication_48_Dark.svg';
import _resAmazonSimpleStorageServiceS3StandardIa48DarkSvg from './Res_Amazon-Simple-Storage-Service_S3-Standard-IA_48_Dark.svg';
import _resAmazonSimpleStorageServiceS3Standard48DarkSvg from './Res_Amazon-Simple-Storage-Service_S3-Standard_48_Dark.svg';
import _resAmazonSimpleStorageServiceS3StorageLens48DarkSvg from './Res_Amazon-Simple-Storage-Service_S3-Storage-Lens_48_Dark.svg';
import _resAmazonSimpleStorageServiceVpcAccessPoints48DarkSvg from './Res_Amazon-Simple-Storage-Service_VPC-Access-Points_48_Dark.svg';

export const resAwsBackupAwsBackupSupportForAmazonFsxForNetAppOntap48DarkSvg = { id: "resAwsBackupAwsBackupSupportForAmazonFsxForNetAppOntap48DarkSvg", name: "AWS Backup | AWS Backup support for Amazon FSx for NetApp ONTAP", icon: _resAwsBackupAwsBackupSupportForAmazonFsxForNetAppOntap48DarkSvg };
export const resAwsBackupAwsBackupSupportForAmazonS348DarkSvg = { id: "resAwsBackupAwsBackupSupportForAmazonS348DarkSvg", name: "AWS Backup | AWS Backup support for Amazon S3", icon: _resAwsBackupAwsBackupSupportForAmazonS348DarkSvg };
export const resAwsBackupAwsBackupSupportForVmwareWorkloads48DarkSvg = { id: "resAwsBackupAwsBackupSupportForVmwareWorkloads48DarkSvg", name: "AWS Backup | AWS Backup support for VMware Workloads", icon: _resAwsBackupAwsBackupSupportForVmwareWorkloads48DarkSvg };
export const resAwsBackupBackupPlan48DarkSvg = { id: "resAwsBackupBackupPlan48DarkSvg", name: "AWS Backup | Backup Plan", icon: _resAwsBackupBackupPlan48DarkSvg };
export const resAwsBackupBackupRestore48DarkSvg = { id: "resAwsBackupBackupRestore48DarkSvg", name: "AWS Backup | Backup Restore", icon: _resAwsBackupBackupRestore48DarkSvg };
export const resAwsBackupBackupVault48DarkSvg = { id: "resAwsBackupBackupVault48DarkSvg", name: "AWS Backup | Backup Vault", icon: _resAwsBackupBackupVault48DarkSvg };
export const resAwsBackupComplianceReporting48DarkSvg = { id: "resAwsBackupComplianceReporting48DarkSvg", name: "AWS Backup | Compliance Reporting", icon: _resAwsBackupComplianceReporting48DarkSvg };
export const resAwsBackupCompute48DarkSvg = { id: "resAwsBackupCompute48DarkSvg", name: "AWS Backup | Compute", icon: _resAwsBackupCompute48DarkSvg };
export const resAwsBackupDatabase48DarkSvg = { id: "resAwsBackupDatabase48DarkSvg", name: "AWS Backup | Database", icon: _resAwsBackupDatabase48DarkSvg };
export const resAwsBackupGateway48DarkSvg = { id: "resAwsBackupGateway48DarkSvg", name: "AWS Backup | Gateway", icon: _resAwsBackupGateway48DarkSvg };
export const resAwsBackupRecoveryPointObjective48DarkSvg = { id: "resAwsBackupRecoveryPointObjective48DarkSvg", name: "AWS Backup | Recovery Point Objective", icon: _resAwsBackupRecoveryPointObjective48DarkSvg };
export const resAwsBackupRecoveryTimeObjective48DarkSvg = { id: "resAwsBackupRecoveryTimeObjective48DarkSvg", name: "AWS Backup | Recovery Time Objective", icon: _resAwsBackupRecoveryTimeObjective48DarkSvg };
export const resAwsBackupStorage48DarkSvg = { id: "resAwsBackupStorage48DarkSvg", name: "AWS Backup | Storage", icon: _resAwsBackupStorage48DarkSvg };
export const resAwsBackupVirtualMachineMonitor48DarkSvg = { id: "resAwsBackupVirtualMachineMonitor48DarkSvg", name: "AWS Backup | Virtual Machine Monitor", icon: _resAwsBackupVirtualMachineMonitor48DarkSvg };
export const resAwsBackupVirtualMachine48DarkSvg = { id: "resAwsBackupVirtualMachine48DarkSvg", name: "AWS Backup | Virtual Machine", icon: _resAwsBackupVirtualMachine48DarkSvg };
export const resAwsSnowballSnowballImportExport48DarkSvg = { id: "resAwsSnowballSnowballImportExport48DarkSvg", name: "AWS Snowball | Snowball Import Export", icon: _resAwsSnowballSnowballImportExport48DarkSvg };
export const resAwsStorageGatewayAmazonFsxFileGateway48DarkSvg = { id: "resAwsStorageGatewayAmazonFsxFileGateway48DarkSvg", name: "AWS Storage Gateway | Amazon FSx File Gateway", icon: _resAwsStorageGatewayAmazonFsxFileGateway48DarkSvg };
export const resAwsStorageGatewayAmazonS3FileGateway48DarkSvg = { id: "resAwsStorageGatewayAmazonS3FileGateway48DarkSvg", name: "AWS Storage Gateway | Amazon S3 File Gateway", icon: _resAwsStorageGatewayAmazonS3FileGateway48DarkSvg };
export const resAwsStorageGatewayCachedVolume48DarkSvg = { id: "resAwsStorageGatewayCachedVolume48DarkSvg", name: "AWS Storage Gateway | Cached Volume", icon: _resAwsStorageGatewayCachedVolume48DarkSvg };
export const resAwsStorageGatewayFileGateway48DarkSvg = { id: "resAwsStorageGatewayFileGateway48DarkSvg", name: "AWS Storage Gateway | File Gateway", icon: _resAwsStorageGatewayFileGateway48DarkSvg };
export const resAwsStorageGatewayNoncachedVolume48DarkSvg = { id: "resAwsStorageGatewayNoncachedVolume48DarkSvg", name: "AWS Storage Gateway | Noncached Volume", icon: _resAwsStorageGatewayNoncachedVolume48DarkSvg };
export const resAwsStorageGatewayTapeGateway48DarkSvg = { id: "resAwsStorageGatewayTapeGateway48DarkSvg", name: "AWS Storage Gateway | Tape Gateway", icon: _resAwsStorageGatewayTapeGateway48DarkSvg };
export const resAwsStorageGatewayVirtualTapeLibrary48DarkSvg = { id: "resAwsStorageGatewayVirtualTapeLibrary48DarkSvg", name: "AWS Storage Gateway | Virtual Tape Library", icon: _resAwsStorageGatewayVirtualTapeLibrary48DarkSvg };
export const resAwsStorageGatewayVolumeGateway48DarkSvg = { id: "resAwsStorageGatewayVolumeGateway48DarkSvg", name: "AWS Storage Gateway | Volume Gateway", icon: _resAwsStorageGatewayVolumeGateway48DarkSvg };
export const resAmazonElasticBlockStoreAmazonDataLifecycleManager48DarkSvg = { id: "resAmazonElasticBlockStoreAmazonDataLifecycleManager48DarkSvg", name: "Amazon Elastic Block Store | Amazon Data Lifecycle Manager", icon: _resAmazonElasticBlockStoreAmazonDataLifecycleManager48DarkSvg };
export const resAmazonElasticBlockStoreMultipleVolumes48DarkSvg = { id: "resAmazonElasticBlockStoreMultipleVolumes48DarkSvg", name: "Amazon Elastic Block Store | Multiple Volumes", icon: _resAmazonElasticBlockStoreMultipleVolumes48DarkSvg };
export const resAmazonElasticBlockStoreSnapshot48DarkSvg = { id: "resAmazonElasticBlockStoreSnapshot48DarkSvg", name: "Amazon Elastic Block Store | Snapshot", icon: _resAmazonElasticBlockStoreSnapshot48DarkSvg };
export const resAmazonElasticBlockStoreVolumeGp348DarkSvg = { id: "resAmazonElasticBlockStoreVolumeGp348DarkSvg", name: "Amazon Elastic Block Store | Volume gp3", icon: _resAmazonElasticBlockStoreVolumeGp348DarkSvg };
export const resAmazonElasticBlockStoreVolume48DarkSvg = { id: "resAmazonElasticBlockStoreVolume48DarkSvg", name: "Amazon Elastic Block Store | Volume", icon: _resAmazonElasticBlockStoreVolume48DarkSvg };
export const resAmazonElasticFileSystemFileSystem48DarkSvg = { id: "resAmazonElasticFileSystemFileSystem48DarkSvg", name: "Amazon Elastic File System | File System", icon: _resAmazonElasticFileSystemFileSystem48DarkSvg };
export const resAmazonElasticFileSystemIntelligentTiering48DarkSvg = { id: "resAmazonElasticFileSystemIntelligentTiering48DarkSvg", name: "Amazon Elastic File System | Intelligent Tiering", icon: _resAmazonElasticFileSystemIntelligentTiering48DarkSvg };
export const resAmazonElasticFileSystemOneZoneInfrequentAccess48DarkSvg = { id: "resAmazonElasticFileSystemOneZoneInfrequentAccess48DarkSvg", name: "Amazon Elastic File System | One Zone Infrequent Access", icon: _resAmazonElasticFileSystemOneZoneInfrequentAccess48DarkSvg };
export const resAmazonElasticFileSystemOneZone48DarkSvg = { id: "resAmazonElasticFileSystemOneZone48DarkSvg", name: "Amazon Elastic File System | One Zone", icon: _resAmazonElasticFileSystemOneZone48DarkSvg };
export const resAmazonElasticFileSystemStandardInfrequentAccess48DarkSvg = { id: "resAmazonElasticFileSystemStandardInfrequentAccess48DarkSvg", name: "Amazon Elastic File System | Standard Infrequent Access", icon: _resAmazonElasticFileSystemStandardInfrequentAccess48DarkSvg };
export const resAmazonElasticFileSystemStandard48DarkSvg = { id: "resAmazonElasticFileSystemStandard48DarkSvg", name: "Amazon Elastic File System | Standard", icon: _resAmazonElasticFileSystemStandard48DarkSvg };
export const resAmazonSimpleStorageServiceGlacierArchive48DarkSvg = { id: "resAmazonSimpleStorageServiceGlacierArchive48DarkSvg", name: "Amazon Simple Storage Service Glacier | Archive", icon: _resAmazonSimpleStorageServiceGlacierArchive48DarkSvg };
export const resAmazonSimpleStorageServiceGlacierVault48DarkSvg = { id: "resAmazonSimpleStorageServiceGlacierVault48DarkSvg", name: "Amazon Simple Storage Service Glacier | Vault", icon: _resAmazonSimpleStorageServiceGlacierVault48DarkSvg };
export const resAmazonSimpleStorageServiceBucketWithObjects48DarkSvg = { id: "resAmazonSimpleStorageServiceBucketWithObjects48DarkSvg", name: "Amazon Simple Storage Service | Bucket With Objects", icon: _resAmazonSimpleStorageServiceBucketWithObjects48DarkSvg };
export const resAmazonSimpleStorageServiceBucket48DarkSvg = { id: "resAmazonSimpleStorageServiceBucket48DarkSvg", name: "Amazon Simple Storage Service | Bucket", icon: _resAmazonSimpleStorageServiceBucket48DarkSvg };
export const resAmazonSimpleStorageServiceGeneralAccessPoints48DarkSvg = { id: "resAmazonSimpleStorageServiceGeneralAccessPoints48DarkSvg", name: "Amazon Simple Storage Service | General Access Points", icon: _resAmazonSimpleStorageServiceGeneralAccessPoints48DarkSvg };
export const resAmazonSimpleStorageServiceObject48DarkSvg = { id: "resAmazonSimpleStorageServiceObject48DarkSvg", name: "Amazon Simple Storage Service | Object", icon: _resAmazonSimpleStorageServiceObject48DarkSvg };
export const resAmazonSimpleStorageServiceS3GlacierDeepArchive48DarkSvg = { id: "resAmazonSimpleStorageServiceS3GlacierDeepArchive48DarkSvg", name: "Amazon Simple Storage Service | S3 Glacier Deep Archive", icon: _resAmazonSimpleStorageServiceS3GlacierDeepArchive48DarkSvg };
export const resAmazonSimpleStorageServiceS3GlacierFlexibleRetrieval48DarkSvg = { id: "resAmazonSimpleStorageServiceS3GlacierFlexibleRetrieval48DarkSvg", name: "Amazon Simple Storage Service | S3 Glacier Flexible Retrieval", icon: _resAmazonSimpleStorageServiceS3GlacierFlexibleRetrieval48DarkSvg };
export const resAmazonSimpleStorageServiceS3GlacierInstantRetrieval48DarkSvg = { id: "resAmazonSimpleStorageServiceS3GlacierInstantRetrieval48DarkSvg", name: "Amazon Simple Storage Service | S3 Glacier Instant Retrieval", icon: _resAmazonSimpleStorageServiceS3GlacierInstantRetrieval48DarkSvg };
export const resAmazonSimpleStorageServiceS3IntelligentTiering48DarkSvg = { id: "resAmazonSimpleStorageServiceS3IntelligentTiering48DarkSvg", name: "Amazon Simple Storage Service | S3 Intelligent Tiering", icon: _resAmazonSimpleStorageServiceS3IntelligentTiering48DarkSvg };
export const resAmazonSimpleStorageServiceS3ObjectLambdaAccessPoints48DarkSvg = { id: "resAmazonSimpleStorageServiceS3ObjectLambdaAccessPoints48DarkSvg", name: "Amazon Simple Storage Service | S3 Object Lambda Access Points", icon: _resAmazonSimpleStorageServiceS3ObjectLambdaAccessPoints48DarkSvg };
export const resAmazonSimpleStorageServiceS3ObjectLambda48DarkSvg = { id: "resAmazonSimpleStorageServiceS3ObjectLambda48DarkSvg", name: "Amazon Simple Storage Service | S3 Object Lambda", icon: _resAmazonSimpleStorageServiceS3ObjectLambda48DarkSvg };
export const resAmazonSimpleStorageServiceS3OnOutposts48DarkSvg = { id: "resAmazonSimpleStorageServiceS3OnOutposts48DarkSvg", name: "Amazon Simple Storage Service | S3 On Outposts", icon: _resAmazonSimpleStorageServiceS3OnOutposts48DarkSvg };
export const resAmazonSimpleStorageServiceS3OneZoneIa48DarkSvg = { id: "resAmazonSimpleStorageServiceS3OneZoneIa48DarkSvg", name: "Amazon Simple Storage Service | S3 One Zone IA", icon: _resAmazonSimpleStorageServiceS3OneZoneIa48DarkSvg };
export const resAmazonSimpleStorageServiceS3ReplicationTimeControl48DarkSvg = { id: "resAmazonSimpleStorageServiceS3ReplicationTimeControl48DarkSvg", name: "Amazon Simple Storage Service | S3 Replication Time Control", icon: _resAmazonSimpleStorageServiceS3ReplicationTimeControl48DarkSvg };
export const resAmazonSimpleStorageServiceS3Replication48DarkSvg = { id: "resAmazonSimpleStorageServiceS3Replication48DarkSvg", name: "Amazon Simple Storage Service | S3 Replication", icon: _resAmazonSimpleStorageServiceS3Replication48DarkSvg };
export const resAmazonSimpleStorageServiceS3StandardIa48DarkSvg = { id: "resAmazonSimpleStorageServiceS3StandardIa48DarkSvg", name: "Amazon Simple Storage Service | S3 Standard IA", icon: _resAmazonSimpleStorageServiceS3StandardIa48DarkSvg };
export const resAmazonSimpleStorageServiceS3Standard48DarkSvg = { id: "resAmazonSimpleStorageServiceS3Standard48DarkSvg", name: "Amazon Simple Storage Service | S3 Standard", icon: _resAmazonSimpleStorageServiceS3Standard48DarkSvg };
export const resAmazonSimpleStorageServiceS3StorageLens48DarkSvg = { id: "resAmazonSimpleStorageServiceS3StorageLens48DarkSvg", name: "Amazon Simple Storage Service | S3 Storage Lens", icon: _resAmazonSimpleStorageServiceS3StorageLens48DarkSvg };
export const resAmazonSimpleStorageServiceVpcAccessPoints48DarkSvg = { id: "resAmazonSimpleStorageServiceVpcAccessPoints48DarkSvg", name: "Amazon Simple Storage Service | VPC Access Points", icon: _resAmazonSimpleStorageServiceVpcAccessPoints48DarkSvg };
