import _archAwsDataExchange32Svg from './Arch_AWS-Data-Exchange_32.svg';
import _archAwsDataPipeline32Svg from './Arch_AWS-Data-Pipeline_32.svg';
import _archAwsGlueDataBrew32Svg from './Arch_AWS-Glue-DataBrew_32.svg';
import _archAwsGlueElasticViews32Svg from './Arch_AWS-Glue-Elastic-Views_32.svg';
import _archAwsGlue32Svg from './Arch_AWS-Glue_32.svg';
import _archAwsLakeFormation32Svg from './Arch_AWS-Lake-Formation_32.svg';
import _archAmazonAthena32Svg from './Arch_Amazon-Athena_32.svg';
import _archAmazonCloudSearch32Svg from './Arch_Amazon-CloudSearch_32.svg';
import _archAmazonEmr32Svg from './Arch_Amazon-EMR_32.svg';
import _archAmazonFinSpace32Svg from './Arch_Amazon-FinSpace_32.svg';
import _archAmazonKinesisDataAnalytics32Svg from './Arch_Amazon-Kinesis-Data-Analytics_32.svg';
import _archAmazonKinesisDataStreams32Svg from './Arch_Amazon-Kinesis-Data-Streams_32.svg';
import _archAmazonKinesisFirehose32Svg from './Arch_Amazon-Kinesis-Firehose_32.svg';
import _archAmazonKinesisVideoStreams32Svg from './Arch_Amazon-Kinesis-Video-Streams_32.svg';
import _archAmazonKinesis32Svg from './Arch_Amazon-Kinesis_32.svg';
import _archAmazonManagedStreamingForApacheKafka32Svg from './Arch_Amazon-Managed-Streaming-for-Apache-Kafka_32.svg';
import _archAmazonOpenSearchService32Svg from './Arch_Amazon-OpenSearch-Service_32.svg';
import _archAmazonQuickSight32Svg from './Arch_Amazon-QuickSight_32.svg';
import _archAmazonRedshift32Svg from './Arch_Amazon-Redshift_32.svg';

export const archAwsDataExchange32Svg = { id: "archAwsDataExchange32Svg", name: "AWS Data Exchange", icon: _archAwsDataExchange32Svg };
export const archAwsDataPipeline32Svg = { id: "archAwsDataPipeline32Svg", name: "AWS Data Pipeline", icon: _archAwsDataPipeline32Svg };
export const archAwsGlueDataBrew32Svg = { id: "archAwsGlueDataBrew32Svg", name: "AWS Glue DataBrew", icon: _archAwsGlueDataBrew32Svg };
export const archAwsGlueElasticViews32Svg = { id: "archAwsGlueElasticViews32Svg", name: "AWS Glue Elastic Views", icon: _archAwsGlueElasticViews32Svg };
export const archAwsGlue32Svg = { id: "archAwsGlue32Svg", name: "AWS Glue", icon: _archAwsGlue32Svg };
export const archAwsLakeFormation32Svg = { id: "archAwsLakeFormation32Svg", name: "AWS Lake Formation", icon: _archAwsLakeFormation32Svg };
export const archAmazonAthena32Svg = { id: "archAmazonAthena32Svg", name: "Amazon Athena", icon: _archAmazonAthena32Svg };
export const archAmazonCloudSearch32Svg = { id: "archAmazonCloudSearch32Svg", name: "Amazon CloudSearch", icon: _archAmazonCloudSearch32Svg };
export const archAmazonEmr32Svg = { id: "archAmazonEmr32Svg", name: "Amazon EMR", icon: _archAmazonEmr32Svg };
export const archAmazonFinSpace32Svg = { id: "archAmazonFinSpace32Svg", name: "Amazon FinSpace", icon: _archAmazonFinSpace32Svg };
export const archAmazonKinesisDataAnalytics32Svg = { id: "archAmazonKinesisDataAnalytics32Svg", name: "Amazon Kinesis Data Analytics", icon: _archAmazonKinesisDataAnalytics32Svg };
export const archAmazonKinesisDataStreams32Svg = { id: "archAmazonKinesisDataStreams32Svg", name: "Amazon Kinesis Data Streams", icon: _archAmazonKinesisDataStreams32Svg };
export const archAmazonKinesisFirehose32Svg = { id: "archAmazonKinesisFirehose32Svg", name: "Amazon Kinesis Firehose", icon: _archAmazonKinesisFirehose32Svg };
export const archAmazonKinesisVideoStreams32Svg = { id: "archAmazonKinesisVideoStreams32Svg", name: "Amazon Kinesis Video Streams", icon: _archAmazonKinesisVideoStreams32Svg };
export const archAmazonKinesis32Svg = { id: "archAmazonKinesis32Svg", name: "Amazon Kinesis", icon: _archAmazonKinesis32Svg };
export const archAmazonManagedStreamingForApacheKafka32Svg = { id: "archAmazonManagedStreamingForApacheKafka32Svg", name: "Amazon Managed Streaming for Apache Kafka", icon: _archAmazonManagedStreamingForApacheKafka32Svg };
export const archAmazonOpenSearchService32Svg = { id: "archAmazonOpenSearchService32Svg", name: "Amazon OpenSearch Service", icon: _archAmazonOpenSearchService32Svg };
export const archAmazonQuickSight32Svg = { id: "archAmazonQuickSight32Svg", name: "Amazon QuickSight", icon: _archAmazonQuickSight32Svg };
export const archAmazonRedshift32Svg = { id: "archAmazonRedshift32Svg", name: "Amazon Redshift", icon: _archAmazonRedshift32Svg };
