import _resAwsElasticBeanstalkApplication48DarkSvg from './Res_AWS-Elastic-Beanstalk_Application_48_Dark.svg';
import _resAwsElasticBeanstalkDeployment48DarkSvg from './Res_AWS-Elastic-Beanstalk_Deployment_48_Dark.svg';
import _resAwsLambdaLambdaFunction48DarkSvg from './Res_AWS-Lambda_Lambda-Function_48_Dark.svg';
import _resAmazonEc2A1Instance48DarkSvg from './Res_Amazon-EC2_A1-Instance_48_Dark.svg';
import _resAmazonEc2Ami48DarkSvg from './Res_Amazon-EC2_AMI_48_Dark.svg';
import _resAmazonEc2AwsInferentia48DarkSvg from './Res_Amazon-EC2_AWS-Inferentia_48_Dark.svg';
import _resAmazonEc2AwsMicroserviceExtractorForNet48DarkSvg from './Res_Amazon-EC2_AWS-Microservice-Extractor-for-.NET_48_Dark.svg';
import _resAmazonEc2AutoScaling48DarkSvg from './Res_Amazon-EC2_Auto-Scaling_48_Dark.svg';
import _resAmazonEc2C4Instance48DarkSvg from './Res_Amazon-EC2_C4-Instance_48_Dark.svg';
import _resAmazonEc2C5Instance48DarkSvg from './Res_Amazon-EC2_C5-Instance_48_Dark.svg';
import _resAmazonEc2C5A48DarkSvg from './Res_Amazon-EC2_C5a_48_Dark.svg';
import _resAmazonEc2C5Ad48DarkSvg from './Res_Amazon-EC2_C5ad_48_Dark.svg';
import _resAmazonEc2C5D48DarkSvg from './Res_Amazon-EC2_C5d_48_Dark.svg';
import _resAmazonEc2C5NInstance48DarkSvg from './Res_Amazon-EC2_C5n-Instance_48_Dark.svg';
import _resAmazonEc2C6AInstance48DarkSvg from './Res_Amazon-EC2_C6a-Instance_48_Dark.svg';
import _resAmazonEc2C6GInstance48DarkSvg from './Res_Amazon-EC2_C6g-Instance_48_Dark.svg';
import _resAmazonEc2C6Gd48DarkSvg from './Res_Amazon-EC2_C6gd_48_Dark.svg';
import _resAmazonEc2C6GnInstance48DarkSvg from './Res_Amazon-EC2_C6gn-Instance_48_Dark.svg';
import _resAmazonEc2C6IInstance48DarkSvg from './Res_Amazon-EC2_C6i-Instance_48_Dark.svg';
import _resAmazonEc2C7GInstance48DarkSvg from './Res_Amazon-EC2_C7g-Instance_48_Dark.svg';
import _resAmazonEc2D2Instance48DarkSvg from './Res_Amazon-EC2_D2-Instance_48_Dark.svg';
import _resAmazonEc2D3Instance48DarkSvg from './Res_Amazon-EC2_D3-Instance_48_Dark.svg';
import _resAmazonEc2D3EnInstance48DarkSvg from './Res_Amazon-EC2_D3en-Instance_48_Dark.svg';
import _resAmazonEc2DbInstance48DarkSvg from './Res_Amazon-EC2_DB-Instance_48_Dark.svg';
import _resAmazonEc2Dl1Instance48DarkSvg from './Res_Amazon-EC2_DL1-Instance_48_Dark.svg';
import _resAmazonEc2ElasticIpAddress48DarkSvg from './Res_Amazon-EC2_Elastic-IP-Address_48_Dark.svg';
import _resAmazonEc2F1Instance48DarkSvg from './Res_Amazon-EC2_F1-Instance_48_Dark.svg';
import _resAmazonEc2G3Instance48DarkSvg from './Res_Amazon-EC2_G3-Instance_48_Dark.svg';
import _resAmazonEc2G4AdInstance48DarkSvg from './Res_Amazon-EC2_G4ad-Instance_48_Dark.svg';
import _resAmazonEc2G4Dn48DarkSvg from './Res_Amazon-EC2_G4dn_48_Dark.svg';
import _resAmazonEc2G5Instance48DarkSvg from './Res_Amazon-EC2_G5-Instance_48_Dark.svg';
import _resAmazonEc2G5GInstance48DarkSvg from './Res_Amazon-EC2_G5g-Instance_48_Dark.svg';
import _resAmazonEc2H1Instance48DarkSvg from './Res_Amazon-EC2_H1-Instance_48_Dark.svg';
import _resAmazonEc2HmiInstance48DarkSvg from './Res_Amazon-EC2_HMI-Instance_48_Dark.svg';
import _resAmazonEc2HabanaGaudi48DarkSvg from './Res_Amazon-EC2_Habana-Gaudi_48_Dark.svg';
import _resAmazonEc2Hpc6AInstance48DarkSvg from './Res_Amazon-EC2_Hpc6a-Instance_48_Dark.svg';
import _resAmazonEc2I248DarkSvg from './Res_Amazon-EC2_I2_48_Dark.svg';
import _resAmazonEc2I3Instance48DarkSvg from './Res_Amazon-EC2_I3-Instance_48_Dark.svg';
import _resAmazonEc2I3En48DarkSvg from './Res_Amazon-EC2_I3en_48_Dark.svg';
import _resAmazonEc2I4IInstance48DarkSvg from './Res_Amazon-EC2_I4i-Instance_48_Dark.svg';
import _resAmazonEc2Im4GnInstance48DarkSvg from './Res_Amazon-EC2_Im4gn-Instance_48_Dark.svg';
import _resAmazonEc2Inf148DarkSvg from './Res_Amazon-EC2_Inf1_48_Dark.svg';
import _resAmazonEc2InstanceWithCloudWatch48DarkSvg from './Res_Amazon-EC2_Instance-with-CloudWatch_48_Dark.svg';
import _resAmazonEc2Instance48DarkSvg from './Res_Amazon-EC2_Instance_48_Dark.svg';
import _resAmazonEc2Instances48DarkSvg from './Res_Amazon-EC2_Instances_48_Dark.svg';
import _resAmazonEc2Is4GenInstance48DarkSvg from './Res_Amazon-EC2_Is4gen-Instance_48_Dark.svg';
import _resAmazonEc2M1MacInstance48DarkSvg from './Res_Amazon-EC2_M1-Mac-Instance_48_Dark.svg';
import _resAmazonEc2M4Instance48DarkSvg from './Res_Amazon-EC2_M4-Instance_48_Dark.svg';
import _resAmazonEc2M5Instance48DarkSvg from './Res_Amazon-EC2_M5-Instance_48_Dark.svg';
import _resAmazonEc2M5AInstance48DarkSvg from './Res_Amazon-EC2_M5a-Instance_48_Dark.svg';
import _resAmazonEc2M5DInstance48DarkSvg from './Res_Amazon-EC2_M5d-Instance_48_Dark.svg';
import _resAmazonEc2M5DnInstance48DarkSvg from './Res_Amazon-EC2_M5dn-Instance_48_Dark.svg';
import _resAmazonEc2M5NInstance48DarkSvg from './Res_Amazon-EC2_M5n-Instance_48_Dark.svg';
import _resAmazonEc2M5ZnInstance48DarkSvg from './Res_Amazon-EC2_M5zn-Instance_48_Dark.svg';
import _resAmazonEc2M6AInstance48DarkSvg from './Res_Amazon-EC2_M6a-Instance_48_Dark.svg';
import _resAmazonEc2M6GInstance48DarkSvg from './Res_Amazon-EC2_M6g-Instance_48_Dark.svg';
import _resAmazonEc2M6GdInstance48DarkSvg from './Res_Amazon-EC2_M6gd-Instance_48_Dark.svg';
import _resAmazonEc2M6IInstance48DarkSvg from './Res_Amazon-EC2_M6i-Instance_48_Dark.svg';
import _resAmazonEc2MacInstance48DarkSvg from './Res_Amazon-EC2_Mac-Instance_48_Dark.svg';
import _resAmazonEc2P2Instance48DarkSvg from './Res_Amazon-EC2_P2-Instance_48_Dark.svg';
import _resAmazonEc2P3Instance48DarkSvg from './Res_Amazon-EC2_P3-Instance_48_Dark.svg';
import _resAmazonEc2P3DnInstance48DarkSvg from './Res_Amazon-EC2_P3dn-Instance_48_Dark.svg';
import _resAmazonEc2P4Instance48DarkSvg from './Res_Amazon-EC2_P4-Instance_48_Dark.svg';
import _resAmazonEc2P4DInstance48DarkSvg from './Res_Amazon-EC2_P4d-Instance_48_Dark.svg';
import _resAmazonEc2P4DeInstance48DarkSvg from './Res_Amazon-EC2_P4de-Instance_48_Dark.svg';
import _resAmazonEc2R4Instance48DarkSvg from './Res_Amazon-EC2_R4-Instance_48_Dark.svg';
import _resAmazonEc2R5Instance48DarkSvg from './Res_Amazon-EC2_R5-Instance_48_Dark.svg';
import _resAmazonEc2R5AInstance48DarkSvg from './Res_Amazon-EC2_R5a-Instance_48_Dark.svg';
import _resAmazonEc2R5AdInstance48DarkSvg from './Res_Amazon-EC2_R5ad-Instance_48_Dark.svg';
import _resAmazonEc2R5BInstance48DarkSvg from './Res_Amazon-EC2_R5b-Instance _48_Dark.svg';
import _resAmazonEc2R5DInstance48DarkSvg from './Res_Amazon-EC2_R5d-Instance_48_Dark.svg';
import _resAmazonEc2R5GdInstance48DarkSvg from './Res_Amazon-EC2_R5gd-Instance_48_Dark.svg';
import _resAmazonEc2R5NInstance48DarkSvg from './Res_Amazon-EC2_R5n-Instance_48_Dark.svg';
import _resAmazonEc2R6GInstance48DarkSvg from './Res_Amazon-EC2_R6g-Instance_48_Dark.svg';
import _resAmazonEc2R6IInstance48DarkSvg from './Res_Amazon-EC2_R6i-Instance_48_Dark.svg';
import _resAmazonEc2RdnInstance48DarkSvg from './Res_Amazon-EC2_Rdn-Instance_48_Dark.svg';
import _resAmazonEc2Rescue48DarkSvg from './Res_Amazon-EC2_Rescue_48_Dark.svg';
import _resAmazonEc2SpotInstance48DarkSvg from './Res_Amazon-EC2_Spot-Instance_48_Dark.svg';
import _resAmazonEc2T2Instance48DarkSvg from './Res_Amazon-EC2_T2-Instance_48_Dark.svg';
import _resAmazonEc2T3Instance48DarkSvg from './Res_Amazon-EC2_T3-Instance_48_Dark.svg';
import _resAmazonEc2T3AInstance48DarkSvg from './Res_Amazon-EC2_T3a-Instance_48_Dark.svg';
import _resAmazonEc2T4GInstance48DarkSvg from './Res_Amazon-EC2_T4g-Instance_48_Dark.svg';
import _resAmazonEc2TrainiumInstance48DarkSvg from './Res_Amazon-EC2_Trainium-Instance_48_Dark.svg';
import _resAmazonEc2Trn1Instance48DarkSvg from './Res_Amazon-EC2_Trn1-Instance_48_Dark.svg';
import _resAmazonEc2Vt1Instance48DarkSvg from './Res_Amazon-EC2_VT1-Instance_48_Dark.svg';
import _resAmazonEc2X1Instance48DarkSvg from './Res_Amazon-EC2_X1-Instance_48_Dark.svg';
import _resAmazonEc2X1EInstance48DarkSvg from './Res_Amazon-EC2_X1e-Instance_48_Dark.svg';
import _resAmazonEc2X2GdInstance48DarkSvg from './Res_Amazon-EC2_X2gd-Instance_48_Dark.svg';
import _resAmazonEc2X2IdnInstance48DarkSvg from './Res_Amazon-EC2_X2idn-Instance_48_Dark.svg';
import _resAmazonEc2X2IednInstance48DarkSvg from './Res_Amazon-EC2_X2iedn-Instance_48_Dark.svg';
import _resAmazonEc2X2IeznInstance48DarkSvg from './Res_Amazon-EC2_X2iezn-Instance_48_Dark.svg';
import _resAmazonEc2Z1DInstance48DarkSvg from './Res_Amazon-EC2_z1d-Instance_48_Dark.svg';

export const resAwsElasticBeanstalkApplication48DarkSvg = { id: "resAwsElasticBeanstalkApplication48DarkSvg", name: "AWS Elastic Beanstalk | Application", icon: _resAwsElasticBeanstalkApplication48DarkSvg };
export const resAwsElasticBeanstalkDeployment48DarkSvg = { id: "resAwsElasticBeanstalkDeployment48DarkSvg", name: "AWS Elastic Beanstalk | Deployment", icon: _resAwsElasticBeanstalkDeployment48DarkSvg };
export const resAwsLambdaLambdaFunction48DarkSvg = { id: "resAwsLambdaLambdaFunction48DarkSvg", name: "AWS Lambda | Lambda Function", icon: _resAwsLambdaLambdaFunction48DarkSvg };
export const resAmazonEc2A1Instance48DarkSvg = { id: "resAmazonEc2A1Instance48DarkSvg", name: "Amazon EC2 | A1 Instance", icon: _resAmazonEc2A1Instance48DarkSvg };
export const resAmazonEc2Ami48DarkSvg = { id: "resAmazonEc2Ami48DarkSvg", name: "Amazon EC2 | AMI", icon: _resAmazonEc2Ami48DarkSvg };
export const resAmazonEc2AwsInferentia48DarkSvg = { id: "resAmazonEc2AwsInferentia48DarkSvg", name: "Amazon EC2 | AWS Inferentia", icon: _resAmazonEc2AwsInferentia48DarkSvg };
export const resAmazonEc2AwsMicroserviceExtractorForNet48DarkSvg = { id: "resAmazonEc2AwsMicroserviceExtractorForNet48DarkSvg", name: "Amazon EC2 | AWS Microservice Extractor for .NET", icon: _resAmazonEc2AwsMicroserviceExtractorForNet48DarkSvg };
export const resAmazonEc2AutoScaling48DarkSvg = { id: "resAmazonEc2AutoScaling48DarkSvg", name: "Amazon EC2 | Auto Scaling", icon: _resAmazonEc2AutoScaling48DarkSvg };
export const resAmazonEc2C4Instance48DarkSvg = { id: "resAmazonEc2C4Instance48DarkSvg", name: "Amazon EC2 | C4 Instance", icon: _resAmazonEc2C4Instance48DarkSvg };
export const resAmazonEc2C5Instance48DarkSvg = { id: "resAmazonEc2C5Instance48DarkSvg", name: "Amazon EC2 | C5 Instance", icon: _resAmazonEc2C5Instance48DarkSvg };
export const resAmazonEc2C5A48DarkSvg = { id: "resAmazonEc2C5A48DarkSvg", name: "Amazon EC2 | C5a", icon: _resAmazonEc2C5A48DarkSvg };
export const resAmazonEc2C5Ad48DarkSvg = { id: "resAmazonEc2C5Ad48DarkSvg", name: "Amazon EC2 | C5ad", icon: _resAmazonEc2C5Ad48DarkSvg };
export const resAmazonEc2C5D48DarkSvg = { id: "resAmazonEc2C5D48DarkSvg", name: "Amazon EC2 | C5d", icon: _resAmazonEc2C5D48DarkSvg };
export const resAmazonEc2C5NInstance48DarkSvg = { id: "resAmazonEc2C5NInstance48DarkSvg", name: "Amazon EC2 | C5n Instance", icon: _resAmazonEc2C5NInstance48DarkSvg };
export const resAmazonEc2C6AInstance48DarkSvg = { id: "resAmazonEc2C6AInstance48DarkSvg", name: "Amazon EC2 | C6a Instance", icon: _resAmazonEc2C6AInstance48DarkSvg };
export const resAmazonEc2C6GInstance48DarkSvg = { id: "resAmazonEc2C6GInstance48DarkSvg", name: "Amazon EC2 | C6g Instance", icon: _resAmazonEc2C6GInstance48DarkSvg };
export const resAmazonEc2C6Gd48DarkSvg = { id: "resAmazonEc2C6Gd48DarkSvg", name: "Amazon EC2 | C6gd", icon: _resAmazonEc2C6Gd48DarkSvg };
export const resAmazonEc2C6GnInstance48DarkSvg = { id: "resAmazonEc2C6GnInstance48DarkSvg", name: "Amazon EC2 | C6gn Instance", icon: _resAmazonEc2C6GnInstance48DarkSvg };
export const resAmazonEc2C6IInstance48DarkSvg = { id: "resAmazonEc2C6IInstance48DarkSvg", name: "Amazon EC2 | C6i Instance", icon: _resAmazonEc2C6IInstance48DarkSvg };
export const resAmazonEc2C7GInstance48DarkSvg = { id: "resAmazonEc2C7GInstance48DarkSvg", name: "Amazon EC2 | C7g Instance", icon: _resAmazonEc2C7GInstance48DarkSvg };
export const resAmazonEc2D2Instance48DarkSvg = { id: "resAmazonEc2D2Instance48DarkSvg", name: "Amazon EC2 | D2 Instance", icon: _resAmazonEc2D2Instance48DarkSvg };
export const resAmazonEc2D3Instance48DarkSvg = { id: "resAmazonEc2D3Instance48DarkSvg", name: "Amazon EC2 | D3 Instance", icon: _resAmazonEc2D3Instance48DarkSvg };
export const resAmazonEc2D3EnInstance48DarkSvg = { id: "resAmazonEc2D3EnInstance48DarkSvg", name: "Amazon EC2 | D3en Instance", icon: _resAmazonEc2D3EnInstance48DarkSvg };
export const resAmazonEc2DbInstance48DarkSvg = { id: "resAmazonEc2DbInstance48DarkSvg", name: "Amazon EC2 | DB Instance", icon: _resAmazonEc2DbInstance48DarkSvg };
export const resAmazonEc2Dl1Instance48DarkSvg = { id: "resAmazonEc2Dl1Instance48DarkSvg", name: "Amazon EC2 | DL1 Instance", icon: _resAmazonEc2Dl1Instance48DarkSvg };
export const resAmazonEc2ElasticIpAddress48DarkSvg = { id: "resAmazonEc2ElasticIpAddress48DarkSvg", name: "Amazon EC2 | Elastic IP Address", icon: _resAmazonEc2ElasticIpAddress48DarkSvg };
export const resAmazonEc2F1Instance48DarkSvg = { id: "resAmazonEc2F1Instance48DarkSvg", name: "Amazon EC2 | F1 Instance", icon: _resAmazonEc2F1Instance48DarkSvg };
export const resAmazonEc2G3Instance48DarkSvg = { id: "resAmazonEc2G3Instance48DarkSvg", name: "Amazon EC2 | G3 Instance", icon: _resAmazonEc2G3Instance48DarkSvg };
export const resAmazonEc2G4AdInstance48DarkSvg = { id: "resAmazonEc2G4AdInstance48DarkSvg", name: "Amazon EC2 | G4ad Instance", icon: _resAmazonEc2G4AdInstance48DarkSvg };
export const resAmazonEc2G4Dn48DarkSvg = { id: "resAmazonEc2G4Dn48DarkSvg", name: "Amazon EC2 | G4dn", icon: _resAmazonEc2G4Dn48DarkSvg };
export const resAmazonEc2G5Instance48DarkSvg = { id: "resAmazonEc2G5Instance48DarkSvg", name: "Amazon EC2 | G5 Instance", icon: _resAmazonEc2G5Instance48DarkSvg };
export const resAmazonEc2G5GInstance48DarkSvg = { id: "resAmazonEc2G5GInstance48DarkSvg", name: "Amazon EC2 | G5g Instance", icon: _resAmazonEc2G5GInstance48DarkSvg };
export const resAmazonEc2H1Instance48DarkSvg = { id: "resAmazonEc2H1Instance48DarkSvg", name: "Amazon EC2 | H1 Instance", icon: _resAmazonEc2H1Instance48DarkSvg };
export const resAmazonEc2HmiInstance48DarkSvg = { id: "resAmazonEc2HmiInstance48DarkSvg", name: "Amazon EC2 | HMI Instance", icon: _resAmazonEc2HmiInstance48DarkSvg };
export const resAmazonEc2HabanaGaudi48DarkSvg = { id: "resAmazonEc2HabanaGaudi48DarkSvg", name: "Amazon EC2 | Habana Gaudi", icon: _resAmazonEc2HabanaGaudi48DarkSvg };
export const resAmazonEc2Hpc6AInstance48DarkSvg = { id: "resAmazonEc2Hpc6AInstance48DarkSvg", name: "Amazon EC2 | Hpc6a Instance", icon: _resAmazonEc2Hpc6AInstance48DarkSvg };
export const resAmazonEc2I248DarkSvg = { id: "resAmazonEc2I248DarkSvg", name: "Amazon EC2 | I2", icon: _resAmazonEc2I248DarkSvg };
export const resAmazonEc2I3Instance48DarkSvg = { id: "resAmazonEc2I3Instance48DarkSvg", name: "Amazon EC2 | I3 Instance", icon: _resAmazonEc2I3Instance48DarkSvg };
export const resAmazonEc2I3En48DarkSvg = { id: "resAmazonEc2I3En48DarkSvg", name: "Amazon EC2 | I3en", icon: _resAmazonEc2I3En48DarkSvg };
export const resAmazonEc2I4IInstance48DarkSvg = { id: "resAmazonEc2I4IInstance48DarkSvg", name: "Amazon EC2 | I4i Instance", icon: _resAmazonEc2I4IInstance48DarkSvg };
export const resAmazonEc2Im4GnInstance48DarkSvg = { id: "resAmazonEc2Im4GnInstance48DarkSvg", name: "Amazon EC2 | Im4gn Instance", icon: _resAmazonEc2Im4GnInstance48DarkSvg };
export const resAmazonEc2Inf148DarkSvg = { id: "resAmazonEc2Inf148DarkSvg", name: "Amazon EC2 | Inf1", icon: _resAmazonEc2Inf148DarkSvg };
export const resAmazonEc2InstanceWithCloudWatch48DarkSvg = { id: "resAmazonEc2InstanceWithCloudWatch48DarkSvg", name: "Amazon EC2 | Instance with CloudWatch", icon: _resAmazonEc2InstanceWithCloudWatch48DarkSvg };
export const resAmazonEc2Instance48DarkSvg = { id: "resAmazonEc2Instance48DarkSvg", name: "Amazon EC2 | Instance", icon: _resAmazonEc2Instance48DarkSvg };
export const resAmazonEc2Instances48DarkSvg = { id: "resAmazonEc2Instances48DarkSvg", name: "Amazon EC2 | Instances", icon: _resAmazonEc2Instances48DarkSvg };
export const resAmazonEc2Is4GenInstance48DarkSvg = { id: "resAmazonEc2Is4GenInstance48DarkSvg", name: "Amazon EC2 | Is4gen Instance", icon: _resAmazonEc2Is4GenInstance48DarkSvg };
export const resAmazonEc2M1MacInstance48DarkSvg = { id: "resAmazonEc2M1MacInstance48DarkSvg", name: "Amazon EC2 | M1 Mac Instance", icon: _resAmazonEc2M1MacInstance48DarkSvg };
export const resAmazonEc2M4Instance48DarkSvg = { id: "resAmazonEc2M4Instance48DarkSvg", name: "Amazon EC2 | M4 Instance", icon: _resAmazonEc2M4Instance48DarkSvg };
export const resAmazonEc2M5Instance48DarkSvg = { id: "resAmazonEc2M5Instance48DarkSvg", name: "Amazon EC2 | M5 Instance", icon: _resAmazonEc2M5Instance48DarkSvg };
export const resAmazonEc2M5AInstance48DarkSvg = { id: "resAmazonEc2M5AInstance48DarkSvg", name: "Amazon EC2 | M5a Instance", icon: _resAmazonEc2M5AInstance48DarkSvg };
export const resAmazonEc2M5DInstance48DarkSvg = { id: "resAmazonEc2M5DInstance48DarkSvg", name: "Amazon EC2 | M5d Instance", icon: _resAmazonEc2M5DInstance48DarkSvg };
export const resAmazonEc2M5DnInstance48DarkSvg = { id: "resAmazonEc2M5DnInstance48DarkSvg", name: "Amazon EC2 | M5dn Instance", icon: _resAmazonEc2M5DnInstance48DarkSvg };
export const resAmazonEc2M5NInstance48DarkSvg = { id: "resAmazonEc2M5NInstance48DarkSvg", name: "Amazon EC2 | M5n Instance", icon: _resAmazonEc2M5NInstance48DarkSvg };
export const resAmazonEc2M5ZnInstance48DarkSvg = { id: "resAmazonEc2M5ZnInstance48DarkSvg", name: "Amazon EC2 | M5zn Instance", icon: _resAmazonEc2M5ZnInstance48DarkSvg };
export const resAmazonEc2M6AInstance48DarkSvg = { id: "resAmazonEc2M6AInstance48DarkSvg", name: "Amazon EC2 | M6a Instance", icon: _resAmazonEc2M6AInstance48DarkSvg };
export const resAmazonEc2M6GInstance48DarkSvg = { id: "resAmazonEc2M6GInstance48DarkSvg", name: "Amazon EC2 | M6g Instance", icon: _resAmazonEc2M6GInstance48DarkSvg };
export const resAmazonEc2M6GdInstance48DarkSvg = { id: "resAmazonEc2M6GdInstance48DarkSvg", name: "Amazon EC2 | M6gd Instance", icon: _resAmazonEc2M6GdInstance48DarkSvg };
export const resAmazonEc2M6IInstance48DarkSvg = { id: "resAmazonEc2M6IInstance48DarkSvg", name: "Amazon EC2 | M6i Instance", icon: _resAmazonEc2M6IInstance48DarkSvg };
export const resAmazonEc2MacInstance48DarkSvg = { id: "resAmazonEc2MacInstance48DarkSvg", name: "Amazon EC2 | Mac Instance", icon: _resAmazonEc2MacInstance48DarkSvg };
export const resAmazonEc2P2Instance48DarkSvg = { id: "resAmazonEc2P2Instance48DarkSvg", name: "Amazon EC2 | P2 Instance", icon: _resAmazonEc2P2Instance48DarkSvg };
export const resAmazonEc2P3Instance48DarkSvg = { id: "resAmazonEc2P3Instance48DarkSvg", name: "Amazon EC2 | P3 Instance", icon: _resAmazonEc2P3Instance48DarkSvg };
export const resAmazonEc2P3DnInstance48DarkSvg = { id: "resAmazonEc2P3DnInstance48DarkSvg", name: "Amazon EC2 | P3dn Instance", icon: _resAmazonEc2P3DnInstance48DarkSvg };
export const resAmazonEc2P4Instance48DarkSvg = { id: "resAmazonEc2P4Instance48DarkSvg", name: "Amazon EC2 | P4 Instance", icon: _resAmazonEc2P4Instance48DarkSvg };
export const resAmazonEc2P4DInstance48DarkSvg = { id: "resAmazonEc2P4DInstance48DarkSvg", name: "Amazon EC2 | P4d Instance", icon: _resAmazonEc2P4DInstance48DarkSvg };
export const resAmazonEc2P4DeInstance48DarkSvg = { id: "resAmazonEc2P4DeInstance48DarkSvg", name: "Amazon EC2 | P4de Instance", icon: _resAmazonEc2P4DeInstance48DarkSvg };
export const resAmazonEc2R4Instance48DarkSvg = { id: "resAmazonEc2R4Instance48DarkSvg", name: "Amazon EC2 | R4 Instance", icon: _resAmazonEc2R4Instance48DarkSvg };
export const resAmazonEc2R5Instance48DarkSvg = { id: "resAmazonEc2R5Instance48DarkSvg", name: "Amazon EC2 | R5 Instance", icon: _resAmazonEc2R5Instance48DarkSvg };
export const resAmazonEc2R5AInstance48DarkSvg = { id: "resAmazonEc2R5AInstance48DarkSvg", name: "Amazon EC2 | R5a Instance", icon: _resAmazonEc2R5AInstance48DarkSvg };
export const resAmazonEc2R5AdInstance48DarkSvg = { id: "resAmazonEc2R5AdInstance48DarkSvg", name: "Amazon EC2 | R5ad Instance", icon: _resAmazonEc2R5AdInstance48DarkSvg };
export const resAmazonEc2R5BInstance48DarkSvg = { id: "resAmazonEc2R5BInstance48DarkSvg", name: "Amazon EC2 | R5b Instance ", icon: _resAmazonEc2R5BInstance48DarkSvg };
export const resAmazonEc2R5DInstance48DarkSvg = { id: "resAmazonEc2R5DInstance48DarkSvg", name: "Amazon EC2 | R5d Instance", icon: _resAmazonEc2R5DInstance48DarkSvg };
export const resAmazonEc2R5GdInstance48DarkSvg = { id: "resAmazonEc2R5GdInstance48DarkSvg", name: "Amazon EC2 | R5gd Instance", icon: _resAmazonEc2R5GdInstance48DarkSvg };
export const resAmazonEc2R5NInstance48DarkSvg = { id: "resAmazonEc2R5NInstance48DarkSvg", name: "Amazon EC2 | R5n Instance", icon: _resAmazonEc2R5NInstance48DarkSvg };
export const resAmazonEc2R6GInstance48DarkSvg = { id: "resAmazonEc2R6GInstance48DarkSvg", name: "Amazon EC2 | R6g Instance", icon: _resAmazonEc2R6GInstance48DarkSvg };
export const resAmazonEc2R6IInstance48DarkSvg = { id: "resAmazonEc2R6IInstance48DarkSvg", name: "Amazon EC2 | R6i Instance", icon: _resAmazonEc2R6IInstance48DarkSvg };
export const resAmazonEc2RdnInstance48DarkSvg = { id: "resAmazonEc2RdnInstance48DarkSvg", name: "Amazon EC2 | Rdn Instance", icon: _resAmazonEc2RdnInstance48DarkSvg };
export const resAmazonEc2Rescue48DarkSvg = { id: "resAmazonEc2Rescue48DarkSvg", name: "Amazon EC2 | Rescue", icon: _resAmazonEc2Rescue48DarkSvg };
export const resAmazonEc2SpotInstance48DarkSvg = { id: "resAmazonEc2SpotInstance48DarkSvg", name: "Amazon EC2 | Spot Instance", icon: _resAmazonEc2SpotInstance48DarkSvg };
export const resAmazonEc2T2Instance48DarkSvg = { id: "resAmazonEc2T2Instance48DarkSvg", name: "Amazon EC2 | T2 Instance", icon: _resAmazonEc2T2Instance48DarkSvg };
export const resAmazonEc2T3Instance48DarkSvg = { id: "resAmazonEc2T3Instance48DarkSvg", name: "Amazon EC2 | T3 Instance", icon: _resAmazonEc2T3Instance48DarkSvg };
export const resAmazonEc2T3AInstance48DarkSvg = { id: "resAmazonEc2T3AInstance48DarkSvg", name: "Amazon EC2 | T3a Instance", icon: _resAmazonEc2T3AInstance48DarkSvg };
export const resAmazonEc2T4GInstance48DarkSvg = { id: "resAmazonEc2T4GInstance48DarkSvg", name: "Amazon EC2 | T4g Instance", icon: _resAmazonEc2T4GInstance48DarkSvg };
export const resAmazonEc2TrainiumInstance48DarkSvg = { id: "resAmazonEc2TrainiumInstance48DarkSvg", name: "Amazon EC2 | Trainium Instance", icon: _resAmazonEc2TrainiumInstance48DarkSvg };
export const resAmazonEc2Trn1Instance48DarkSvg = { id: "resAmazonEc2Trn1Instance48DarkSvg", name: "Amazon EC2 | Trn1 Instance", icon: _resAmazonEc2Trn1Instance48DarkSvg };
export const resAmazonEc2Vt1Instance48DarkSvg = { id: "resAmazonEc2Vt1Instance48DarkSvg", name: "Amazon EC2 | VT1 Instance", icon: _resAmazonEc2Vt1Instance48DarkSvg };
export const resAmazonEc2X1Instance48DarkSvg = { id: "resAmazonEc2X1Instance48DarkSvg", name: "Amazon EC2 | X1 Instance", icon: _resAmazonEc2X1Instance48DarkSvg };
export const resAmazonEc2X1EInstance48DarkSvg = { id: "resAmazonEc2X1EInstance48DarkSvg", name: "Amazon EC2 | X1e Instance", icon: _resAmazonEc2X1EInstance48DarkSvg };
export const resAmazonEc2X2GdInstance48DarkSvg = { id: "resAmazonEc2X2GdInstance48DarkSvg", name: "Amazon EC2 | X2gd Instance", icon: _resAmazonEc2X2GdInstance48DarkSvg };
export const resAmazonEc2X2IdnInstance48DarkSvg = { id: "resAmazonEc2X2IdnInstance48DarkSvg", name: "Amazon EC2 | X2idn Instance", icon: _resAmazonEc2X2IdnInstance48DarkSvg };
export const resAmazonEc2X2IednInstance48DarkSvg = { id: "resAmazonEc2X2IednInstance48DarkSvg", name: "Amazon EC2 | X2iedn Instance", icon: _resAmazonEc2X2IednInstance48DarkSvg };
export const resAmazonEc2X2IeznInstance48DarkSvg = { id: "resAmazonEc2X2IeznInstance48DarkSvg", name: "Amazon EC2 | X2iezn Instance", icon: _resAmazonEc2X2IeznInstance48DarkSvg };
export const resAmazonEc2Z1DInstance48DarkSvg = { id: "resAmazonEc2Z1DInstance48DarkSvg", name: "Amazon EC2 | z1d Instance", icon: _resAmazonEc2Z1DInstance48DarkSvg };
