import _archAwsArtifact64Svg from './Arch_AWS-Artifact_64.svg';
import _archAwsAuditManager64Svg from './Arch_AWS-Audit-Manager_64.svg';
import _archAwsCertificateManager64Svg from './Arch_AWS-Certificate-Manager_64.svg';
import _archAwsCloudHsm64Svg from './Arch_AWS-CloudHSM_64.svg';
import _archAwsDirectoryService64Svg from './Arch_AWS-Directory-Service_64.svg';
import _archAwsFirewallManager64Svg from './Arch_AWS-Firewall-Manager_64.svg';
import _archAwsIamIdentityCenter64Svg from './Arch_AWS-IAM-Identity-Center_64.svg';
import _archAwsIdentityAndAccessManagement64Svg from './Arch_AWS-Identity-and-Access-Management_64.svg';
import _archAwsKeyManagementService64Svg from './Arch_AWS-Key-Management-Service_64.svg';
import _archAwsNetworkFirewall64Svg from './Arch_AWS-Network-Firewall_64.svg';
import _archAwsResourceAccessManager64Svg from './Arch_AWS-Resource-Access-Manager_64.svg';
import _archAwsSecretsManager64Svg from './Arch_AWS-Secrets-Manager_64.svg';
import _archAwsSecurityHub64Svg from './Arch_AWS-Security-Hub_64.svg';
import _archAwsShield64Svg from './Arch_AWS-Shield_64.svg';
import _archAwsSigner64Svg from './Arch_AWS-Signer_64.svg';
import _archAwsWaf64Svg from './Arch_AWS-WAF_64.svg';
import _archAmazonCloudDirectory64Svg from './Arch_Amazon-Cloud-Directory_64.svg';
import _archAmazonCognito64Svg from './Arch_Amazon-Cognito_64.svg';
import _archAmazonDetective64Svg from './Arch_Amazon-Detective_64.svg';
import _archAmazonGuardDuty64Svg from './Arch_Amazon-GuardDuty_64.svg';
import _archAmazonInspector64Svg from './Arch_Amazon-Inspector_64.svg';
import _archAmazonMacie64Svg from './Arch_Amazon-Macie_64.svg';

export const archAwsArtifact64Svg = { id: "archAwsArtifact64Svg", name: "AWS Artifact", icon: _archAwsArtifact64Svg };
export const archAwsAuditManager64Svg = { id: "archAwsAuditManager64Svg", name: "AWS Audit Manager", icon: _archAwsAuditManager64Svg };
export const archAwsCertificateManager64Svg = { id: "archAwsCertificateManager64Svg", name: "AWS Certificate Manager", icon: _archAwsCertificateManager64Svg };
export const archAwsCloudHsm64Svg = { id: "archAwsCloudHsm64Svg", name: "AWS CloudHSM", icon: _archAwsCloudHsm64Svg };
export const archAwsDirectoryService64Svg = { id: "archAwsDirectoryService64Svg", name: "AWS Directory Service", icon: _archAwsDirectoryService64Svg };
export const archAwsFirewallManager64Svg = { id: "archAwsFirewallManager64Svg", name: "AWS Firewall Manager", icon: _archAwsFirewallManager64Svg };
export const archAwsIamIdentityCenter64Svg = { id: "archAwsIamIdentityCenter64Svg", name: "AWS IAM Identity Center", icon: _archAwsIamIdentityCenter64Svg };
export const archAwsIdentityAndAccessManagement64Svg = { id: "archAwsIdentityAndAccessManagement64Svg", name: "AWS Identity and Access Management", icon: _archAwsIdentityAndAccessManagement64Svg };
export const archAwsKeyManagementService64Svg = { id: "archAwsKeyManagementService64Svg", name: "AWS Key Management Service", icon: _archAwsKeyManagementService64Svg };
export const archAwsNetworkFirewall64Svg = { id: "archAwsNetworkFirewall64Svg", name: "AWS Network Firewall", icon: _archAwsNetworkFirewall64Svg };
export const archAwsResourceAccessManager64Svg = { id: "archAwsResourceAccessManager64Svg", name: "AWS Resource Access Manager", icon: _archAwsResourceAccessManager64Svg };
export const archAwsSecretsManager64Svg = { id: "archAwsSecretsManager64Svg", name: "AWS Secrets Manager", icon: _archAwsSecretsManager64Svg };
export const archAwsSecurityHub64Svg = { id: "archAwsSecurityHub64Svg", name: "AWS Security Hub", icon: _archAwsSecurityHub64Svg };
export const archAwsShield64Svg = { id: "archAwsShield64Svg", name: "AWS Shield", icon: _archAwsShield64Svg };
export const archAwsSigner64Svg = { id: "archAwsSigner64Svg", name: "AWS Signer", icon: _archAwsSigner64Svg };
export const archAwsWaf64Svg = { id: "archAwsWaf64Svg", name: "AWS WAF", icon: _archAwsWaf64Svg };
export const archAmazonCloudDirectory64Svg = { id: "archAmazonCloudDirectory64Svg", name: "Amazon Cloud Directory", icon: _archAmazonCloudDirectory64Svg };
export const archAmazonCognito64Svg = { id: "archAmazonCognito64Svg", name: "Amazon Cognito", icon: _archAmazonCognito64Svg };
export const archAmazonDetective64Svg = { id: "archAmazonDetective64Svg", name: "Amazon Detective", icon: _archAmazonDetective64Svg };
export const archAmazonGuardDuty64Svg = { id: "archAmazonGuardDuty64Svg", name: "Amazon GuardDuty", icon: _archAmazonGuardDuty64Svg };
export const archAmazonInspector64Svg = { id: "archAmazonInspector64Svg", name: "Amazon Inspector", icon: _archAmazonInspector64Svg };
export const archAmazonMacie64Svg = { id: "archAmazonMacie64Svg", name: "Amazon Macie", icon: _archAmazonMacie64Svg };
