import _resAwsDatabaseMigrationServiceDatabaseMigrationWorkflowJob48LightSvg from './Res_AWS-Database-Migration-Service_Database-migration-workflow-job_48_Light.svg';
import _resAmazonAuroraInstance48LightSvg from './Res_Amazon-Aurora-Instance_48_Light.svg';
import _resAmazonAuroraMariaDbInstanceAlternate48LightSvg from './Res_Amazon-Aurora-MariaDB-Instance-Alternate_48_Light.svg';
import _resAmazonAuroraMariaDbInstance48LightSvg from './Res_Amazon-Aurora-MariaDB-Instance_48_Light.svg';
import _resAmazonAuroraMySqlInstanceAlternate48LightSvg from './Res_Amazon-Aurora-MySQL-Instance-Alternate_48_Light.svg';
import _resAmazonAuroraMySqlInstance48LightSvg from './Res_Amazon-Aurora-MySQL-Instance_48_Light.svg';
import _resAmazonAuroraOracleInstanceAlternate48LightSvg from './Res_Amazon-Aurora-Oracle-Instance-Alternate_48_Light.svg';
import _resAmazonAuroraOracleInstance48LightSvg from './Res_Amazon-Aurora-Oracle-Instance_48_Light.svg';
import _resAmazonAuroraPiopsInstance48LightSvg from './Res_Amazon-Aurora-PIOPS-Instance_48_Light.svg';
import _resAmazonAuroraPostgreSqlInstanceAlternate48LightSvg from './Res_Amazon-Aurora-PostgreSQL-Instance-Alternate_48_Light.svg';
import _resAmazonAuroraPostgreSqlInstance48LightSvg from './Res_Amazon-Aurora-PostgreSQL-Instance_48_Light.svg';
import _resAmazonAuroraSqlServerInstanceAlternate48LightSvg from './Res_Amazon-Aurora-SQL-Server-Instance-Alternate_48_Light.svg';
import _resAmazonAuroraSqlServerInstance48LightSvg from './Res_Amazon-Aurora-SQL-Server-Instance_48_Light.svg';
import _resAmazonAuroraAmazonAuroraInstanceAlternate48LightSvg from './Res_Amazon-Aurora_Amazon-Aurora-Instance-alternate_48_Light.svg';
import _resAmazonAuroraAmazonRdsInstanceAternate48LightSvg from './Res_Amazon-Aurora_Amazon-RDS-Instance-Aternate_48_Light.svg';
import _resAmazonAuroraAmazonRdsInstance48LightSvg from './Res_Amazon-Aurora_Amazon-RDS-Instance_48_Light.svg';
import _resAmazonDynamoDbAmazonDynamoDbAccelerator48LightSvg from './Res_Amazon-DynamoDB_Amazon-DynamoDB-Accelerator_48_Light.svg';
import _resAmazonDynamoDbAttribute48LightSvg from './Res_Amazon-DynamoDB_Attribute_48_Light.svg';
import _resAmazonDynamoDbAttributes48LightSvg from './Res_Amazon-DynamoDB_Attributes_48_Light.svg';
import _resAmazonDynamoDbGlobalSecondaryIndex48LightSvg from './Res_Amazon-DynamoDB_Global-secondary-index_48_Light.svg';
import _resAmazonDynamoDbItem48LightSvg from './Res_Amazon-DynamoDB_Item_48_Light.svg';
import _resAmazonDynamoDbItems48LightSvg from './Res_Amazon-DynamoDB_Items_48_Light.svg';
import _resAmazonDynamoDbStandardAccessTableClass48LightSvg from './Res_Amazon-DynamoDB_Standard-Access-Table-Class_48_Light.svg';
import _resAmazonDynamoDbStandardInfrequentAccessTableClass48LightSvg from './Res_Amazon-DynamoDB_Standard-Infrequent-Access-Table-Class_48_Light.svg';
import _resAmazonDynamoDbStream48LightSvg from './Res_Amazon-DynamoDB_Stream_48_Light.svg';
import _resAmazonDynamoDbTable48LightSvg from './Res_Amazon-DynamoDB_Table_48_Light.svg';
import _resAmazonElastiCacheCacheNode48LightSvg from './Res_Amazon-ElastiCache_Cache-Node_48_Light.svg';
import _resAmazonElastiCacheElastiCacheForMemcached48LightSvg from './Res_Amazon-ElastiCache_ElastiCache-for-Memcached_48_Light.svg';
import _resAmazonElastiCacheElastiCacheForRedis48LightSvg from './Res_Amazon-ElastiCache_ElastiCache-for-Redis_48_Light.svg';
import _resAmazonRdsProxyInstanceAlternate48LightSvg from './Res_Amazon-RDS-Proxy-Instance-Alternate_48_Light.svg';
import _resAmazonRdsProxyInstance48LightSvg from './Res_Amazon-RDS-Proxy-Instance_48_Light.svg';
import _resAmazonRdsMultiAzDbCluster48LightSvg from './Res_Amazon-RDS_Multi-AZ-DB-Cluster_48_Light.svg';
import _resAmazonRdsMultiAz48LightSvg from './Res_Amazon-RDS_Multi-AZ_48_Light.svg';

export const resAwsDatabaseMigrationServiceDatabaseMigrationWorkflowJob48LightSvg = { id: "resAwsDatabaseMigrationServiceDatabaseMigrationWorkflowJob48LightSvg", name: "AWS Database Migration Service / Database migration workflow job", icon: _resAwsDatabaseMigrationServiceDatabaseMigrationWorkflowJob48LightSvg };
export const resAmazonAuroraInstance48LightSvg = { id: "resAmazonAuroraInstance48LightSvg", name: "Amazon Aurora Instance", icon: _resAmazonAuroraInstance48LightSvg };
export const resAmazonAuroraMariaDbInstanceAlternate48LightSvg = { id: "resAmazonAuroraMariaDbInstanceAlternate48LightSvg", name: "Amazon Aurora MariaDB Instance Alternate", icon: _resAmazonAuroraMariaDbInstanceAlternate48LightSvg };
export const resAmazonAuroraMariaDbInstance48LightSvg = { id: "resAmazonAuroraMariaDbInstance48LightSvg", name: "Amazon Aurora MariaDB Instance", icon: _resAmazonAuroraMariaDbInstance48LightSvg };
export const resAmazonAuroraMySqlInstanceAlternate48LightSvg = { id: "resAmazonAuroraMySqlInstanceAlternate48LightSvg", name: "Amazon Aurora MySQL Instance Alternate", icon: _resAmazonAuroraMySqlInstanceAlternate48LightSvg };
export const resAmazonAuroraMySqlInstance48LightSvg = { id: "resAmazonAuroraMySqlInstance48LightSvg", name: "Amazon Aurora MySQL Instance", icon: _resAmazonAuroraMySqlInstance48LightSvg };
export const resAmazonAuroraOracleInstanceAlternate48LightSvg = { id: "resAmazonAuroraOracleInstanceAlternate48LightSvg", name: "Amazon Aurora Oracle Instance Alternate", icon: _resAmazonAuroraOracleInstanceAlternate48LightSvg };
export const resAmazonAuroraOracleInstance48LightSvg = { id: "resAmazonAuroraOracleInstance48LightSvg", name: "Amazon Aurora Oracle Instance", icon: _resAmazonAuroraOracleInstance48LightSvg };
export const resAmazonAuroraPiopsInstance48LightSvg = { id: "resAmazonAuroraPiopsInstance48LightSvg", name: "Amazon Aurora PIOPS Instance", icon: _resAmazonAuroraPiopsInstance48LightSvg };
export const resAmazonAuroraPostgreSqlInstanceAlternate48LightSvg = { id: "resAmazonAuroraPostgreSqlInstanceAlternate48LightSvg", name: "Amazon Aurora PostgreSQL Instance Alternate", icon: _resAmazonAuroraPostgreSqlInstanceAlternate48LightSvg };
export const resAmazonAuroraPostgreSqlInstance48LightSvg = { id: "resAmazonAuroraPostgreSqlInstance48LightSvg", name: "Amazon Aurora PostgreSQL Instance", icon: _resAmazonAuroraPostgreSqlInstance48LightSvg };
export const resAmazonAuroraSqlServerInstanceAlternate48LightSvg = { id: "resAmazonAuroraSqlServerInstanceAlternate48LightSvg", name: "Amazon Aurora SQL Server Instance Alternate", icon: _resAmazonAuroraSqlServerInstanceAlternate48LightSvg };
export const resAmazonAuroraSqlServerInstance48LightSvg = { id: "resAmazonAuroraSqlServerInstance48LightSvg", name: "Amazon Aurora SQL Server Instance", icon: _resAmazonAuroraSqlServerInstance48LightSvg };
export const resAmazonAuroraAmazonAuroraInstanceAlternate48LightSvg = { id: "resAmazonAuroraAmazonAuroraInstanceAlternate48LightSvg", name: "Amazon Aurora / Amazon Aurora Instance alternate", icon: _resAmazonAuroraAmazonAuroraInstanceAlternate48LightSvg };
export const resAmazonAuroraAmazonRdsInstanceAternate48LightSvg = { id: "resAmazonAuroraAmazonRdsInstanceAternate48LightSvg", name: "Amazon Aurora / Amazon RDS Instance Aternate", icon: _resAmazonAuroraAmazonRdsInstanceAternate48LightSvg };
export const resAmazonAuroraAmazonRdsInstance48LightSvg = { id: "resAmazonAuroraAmazonRdsInstance48LightSvg", name: "Amazon Aurora / Amazon RDS Instance", icon: _resAmazonAuroraAmazonRdsInstance48LightSvg };
export const resAmazonDynamoDbAmazonDynamoDbAccelerator48LightSvg = { id: "resAmazonDynamoDbAmazonDynamoDbAccelerator48LightSvg", name: "Amazon DynamoDB / Amazon DynamoDB Accelerator", icon: _resAmazonDynamoDbAmazonDynamoDbAccelerator48LightSvg };
export const resAmazonDynamoDbAttribute48LightSvg = { id: "resAmazonDynamoDbAttribute48LightSvg", name: "Amazon DynamoDB / Attribute", icon: _resAmazonDynamoDbAttribute48LightSvg };
export const resAmazonDynamoDbAttributes48LightSvg = { id: "resAmazonDynamoDbAttributes48LightSvg", name: "Amazon DynamoDB / Attributes", icon: _resAmazonDynamoDbAttributes48LightSvg };
export const resAmazonDynamoDbGlobalSecondaryIndex48LightSvg = { id: "resAmazonDynamoDbGlobalSecondaryIndex48LightSvg", name: "Amazon DynamoDB / Global secondary index", icon: _resAmazonDynamoDbGlobalSecondaryIndex48LightSvg };
export const resAmazonDynamoDbItem48LightSvg = { id: "resAmazonDynamoDbItem48LightSvg", name: "Amazon DynamoDB / Item", icon: _resAmazonDynamoDbItem48LightSvg };
export const resAmazonDynamoDbItems48LightSvg = { id: "resAmazonDynamoDbItems48LightSvg", name: "Amazon DynamoDB / Items", icon: _resAmazonDynamoDbItems48LightSvg };
export const resAmazonDynamoDbStandardAccessTableClass48LightSvg = { id: "resAmazonDynamoDbStandardAccessTableClass48LightSvg", name: "Amazon DynamoDB / Standard Access Table Class", icon: _resAmazonDynamoDbStandardAccessTableClass48LightSvg };
export const resAmazonDynamoDbStandardInfrequentAccessTableClass48LightSvg = { id: "resAmazonDynamoDbStandardInfrequentAccessTableClass48LightSvg", name: "Amazon DynamoDB / Standard Infrequent Access Table Class", icon: _resAmazonDynamoDbStandardInfrequentAccessTableClass48LightSvg };
export const resAmazonDynamoDbStream48LightSvg = { id: "resAmazonDynamoDbStream48LightSvg", name: "Amazon DynamoDB / Stream", icon: _resAmazonDynamoDbStream48LightSvg };
export const resAmazonDynamoDbTable48LightSvg = { id: "resAmazonDynamoDbTable48LightSvg", name: "Amazon DynamoDB / Table", icon: _resAmazonDynamoDbTable48LightSvg };
export const resAmazonElastiCacheCacheNode48LightSvg = { id: "resAmazonElastiCacheCacheNode48LightSvg", name: "Amazon ElastiCache / Cache Node", icon: _resAmazonElastiCacheCacheNode48LightSvg };
export const resAmazonElastiCacheElastiCacheForMemcached48LightSvg = { id: "resAmazonElastiCacheElastiCacheForMemcached48LightSvg", name: "Amazon ElastiCache / ElastiCache for Memcached", icon: _resAmazonElastiCacheElastiCacheForMemcached48LightSvg };
export const resAmazonElastiCacheElastiCacheForRedis48LightSvg = { id: "resAmazonElastiCacheElastiCacheForRedis48LightSvg", name: "Amazon ElastiCache / ElastiCache for Redis", icon: _resAmazonElastiCacheElastiCacheForRedis48LightSvg };
export const resAmazonRdsProxyInstanceAlternate48LightSvg = { id: "resAmazonRdsProxyInstanceAlternate48LightSvg", name: "Amazon RDS Proxy Instance Alternate", icon: _resAmazonRdsProxyInstanceAlternate48LightSvg };
export const resAmazonRdsProxyInstance48LightSvg = { id: "resAmazonRdsProxyInstance48LightSvg", name: "Amazon RDS Proxy Instance", icon: _resAmazonRdsProxyInstance48LightSvg };
export const resAmazonRdsMultiAzDbCluster48LightSvg = { id: "resAmazonRdsMultiAzDbCluster48LightSvg", name: "Amazon RDS / Multi AZ DB Cluster", icon: _resAmazonRdsMultiAzDbCluster48LightSvg };
export const resAmazonRdsMultiAz48LightSvg = { id: "resAmazonRdsMultiAz48LightSvg", name: "Amazon RDS / Multi AZ", icon: _resAmazonRdsMultiAz48LightSvg };
