import _archAwsCloudControlApi32Svg from './Arch_AWS-Cloud-Control-API_32.svg';
import _archAwsCloudDevelopmentKit32Svg from './Arch_AWS-Cloud-Development-Kit_32.svg';
import _archAwsCloud932Svg from './Arch_AWS-Cloud9_32.svg';
import _archAwsCloudShell32Svg from './Arch_AWS-CloudShell_32.svg';
import _archAwsCodeArtifact32Svg from './Arch_AWS-CodeArtifact_32.svg';
import _archAwsCodeBuild32Svg from './Arch_AWS-CodeBuild_32.svg';
import _archAwsCodeCommit32Svg from './Arch_AWS-CodeCommit_32.svg';
import _archAwsCodeDeploy32Svg from './Arch_AWS-CodeDeploy_32.svg';
import _archAwsCodePipeline32Svg from './Arch_AWS-CodePipeline_32.svg';
import _archAwsCodeStar32Svg from './Arch_AWS-CodeStar_32.svg';
import _archAwsCommandLineInterface32Svg from './Arch_AWS-Command-Line-Interface_32.svg';
import _archAwsToolsAndSdKs32Svg from './Arch_AWS-Tools-and-SDKs_32.svg';
import _archAwsXRay32Svg from './Arch_AWS-X-Ray_32.svg';
import _archAmazonCorretto32Svg from './Arch_Amazon-Corretto_32.svg';

export const archAwsCloudControlApi32Svg = { id: "archAwsCloudControlApi32Svg", name: "AWS Cloud Control API", icon: _archAwsCloudControlApi32Svg };
export const archAwsCloudDevelopmentKit32Svg = { id: "archAwsCloudDevelopmentKit32Svg", name: "AWS Cloud Development Kit", icon: _archAwsCloudDevelopmentKit32Svg };
export const archAwsCloud932Svg = { id: "archAwsCloud932Svg", name: "AWS Cloud9", icon: _archAwsCloud932Svg };
export const archAwsCloudShell32Svg = { id: "archAwsCloudShell32Svg", name: "AWS CloudShell", icon: _archAwsCloudShell32Svg };
export const archAwsCodeArtifact32Svg = { id: "archAwsCodeArtifact32Svg", name: "AWS CodeArtifact", icon: _archAwsCodeArtifact32Svg };
export const archAwsCodeBuild32Svg = { id: "archAwsCodeBuild32Svg", name: "AWS CodeBuild", icon: _archAwsCodeBuild32Svg };
export const archAwsCodeCommit32Svg = { id: "archAwsCodeCommit32Svg", name: "AWS CodeCommit", icon: _archAwsCodeCommit32Svg };
export const archAwsCodeDeploy32Svg = { id: "archAwsCodeDeploy32Svg", name: "AWS CodeDeploy", icon: _archAwsCodeDeploy32Svg };
export const archAwsCodePipeline32Svg = { id: "archAwsCodePipeline32Svg", name: "AWS CodePipeline", icon: _archAwsCodePipeline32Svg };
export const archAwsCodeStar32Svg = { id: "archAwsCodeStar32Svg", name: "AWS CodeStar", icon: _archAwsCodeStar32Svg };
export const archAwsCommandLineInterface32Svg = { id: "archAwsCommandLineInterface32Svg", name: "AWS Command Line Interface", icon: _archAwsCommandLineInterface32Svg };
export const archAwsToolsAndSdKs32Svg = { id: "archAwsToolsAndSdKs32Svg", name: "AWS Tools and SDKs", icon: _archAwsToolsAndSdKs32Svg };
export const archAwsXRay32Svg = { id: "archAwsXRay32Svg", name: "AWS X Ray", icon: _archAwsXRay32Svg };
export const archAmazonCorretto32Svg = { id: "archAmazonCorretto32Svg", name: "Amazon Corretto", icon: _archAmazonCorretto32Svg };
