import _archAwsCloudControlApi16Svg from './Arch_AWS-Cloud-Control-API_16.svg';
import _archAwsCloudDevelopmentKit16Svg from './Arch_AWS-Cloud-Development-Kit_16.svg';
import _archAwsCloud916Svg from './Arch_AWS-Cloud9_16.svg';
import _archAwsCloudShell16Svg from './Arch_AWS-CloudShell_16.svg';
import _archAwsCodeArtifact16Svg from './Arch_AWS-CodeArtifact_16.svg';
import _archAwsCodeBuild16Svg from './Arch_AWS-CodeBuild_16.svg';
import _archAwsCodeCommit16Svg from './Arch_AWS-CodeCommit_16.svg';
import _archAwsCodeDeploy16Svg from './Arch_AWS-CodeDeploy_16.svg';
import _archAwsCodePipeline16Svg from './Arch_AWS-CodePipeline_16.svg';
import _archAwsCodeStar16Svg from './Arch_AWS-CodeStar_16.svg';
import _archAwsCommandLineInterface16Svg from './Arch_AWS-Command-Line-Interface_16.svg';
import _archAwsToolsAndSdKs16Svg from './Arch_AWS-Tools-and-SDKs_16.svg';
import _archAwsXRay16Svg from './Arch_AWS-X-Ray_16.svg';
import _archAmazonCorretto16Svg from './Arch_Amazon-Corretto_16.svg';

export const archAwsCloudControlApi16Svg = { id: "archAwsCloudControlApi16Svg", name: "AWS Cloud Control API", icon: _archAwsCloudControlApi16Svg };
export const archAwsCloudDevelopmentKit16Svg = { id: "archAwsCloudDevelopmentKit16Svg", name: "AWS Cloud Development Kit", icon: _archAwsCloudDevelopmentKit16Svg };
export const archAwsCloud916Svg = { id: "archAwsCloud916Svg", name: "AWS Cloud9", icon: _archAwsCloud916Svg };
export const archAwsCloudShell16Svg = { id: "archAwsCloudShell16Svg", name: "AWS CloudShell", icon: _archAwsCloudShell16Svg };
export const archAwsCodeArtifact16Svg = { id: "archAwsCodeArtifact16Svg", name: "AWS CodeArtifact", icon: _archAwsCodeArtifact16Svg };
export const archAwsCodeBuild16Svg = { id: "archAwsCodeBuild16Svg", name: "AWS CodeBuild", icon: _archAwsCodeBuild16Svg };
export const archAwsCodeCommit16Svg = { id: "archAwsCodeCommit16Svg", name: "AWS CodeCommit", icon: _archAwsCodeCommit16Svg };
export const archAwsCodeDeploy16Svg = { id: "archAwsCodeDeploy16Svg", name: "AWS CodeDeploy", icon: _archAwsCodeDeploy16Svg };
export const archAwsCodePipeline16Svg = { id: "archAwsCodePipeline16Svg", name: "AWS CodePipeline", icon: _archAwsCodePipeline16Svg };
export const archAwsCodeStar16Svg = { id: "archAwsCodeStar16Svg", name: "AWS CodeStar", icon: _archAwsCodeStar16Svg };
export const archAwsCommandLineInterface16Svg = { id: "archAwsCommandLineInterface16Svg", name: "AWS Command Line Interface", icon: _archAwsCommandLineInterface16Svg };
export const archAwsToolsAndSdKs16Svg = { id: "archAwsToolsAndSdKs16Svg", name: "AWS Tools and SDKs", icon: _archAwsToolsAndSdKs16Svg };
export const archAwsXRay16Svg = { id: "archAwsXRay16Svg", name: "AWS X Ray", icon: _archAwsXRay16Svg };
export const archAmazonCorretto16Svg = { id: "archAmazonCorretto16Svg", name: "Amazon Corretto", icon: _archAmazonCorretto16Svg };
