import _archAwsIoT1Click32Svg from './Arch_AWS-IoT-1-Click_32.svg';
import _archAwsIoTAnalytics32Svg from './Arch_AWS-IoT-Analytics_32.svg';
import _archAwsIoTButton32Svg from './Arch_AWS-IoT-Button_32.svg';
import _archAwsIoTCore32Svg from './Arch_AWS-IoT-Core_32.svg';
import _archAwsIoTDeviceDefender32Svg from './Arch_AWS-IoT-Device-Defender_32.svg';
import _archAwsIoTDeviceManagement32Svg from './Arch_AWS-IoT-Device-Management_32.svg';
import _archAwsIoTEduKit32Svg from './Arch_AWS-IoT-EduKit_32.svg';
import _archAwsIoTEvents32Svg from './Arch_AWS-IoT-Events_32.svg';
import _archAwsIoTExpressLink32Svg from './Arch_AWS-IoT-ExpressLink_32.svg';
import _archAwsIoTFleetWise32Svg from './Arch_AWS-IoT-FleetWise_32.svg';
import _archAwsIoTGreengrass32Svg from './Arch_AWS-IoT-Greengrass_32.svg';
import _archAwsIoTRoboRunner32Svg from './Arch_AWS-IoT-RoboRunner_32.svg';
import _archAwsIoTSiteWise32Svg from './Arch_AWS-IoT-SiteWise_32.svg';
import _archAwsIoTThingsGraph32Svg from './Arch_AWS-IoT-Things-Graph_32.svg';
import _archAwsIoTTwinMaker32Svg from './Arch_AWS-IoT-TwinMaker_32.svg';
import _archFreeRtos32Svg from './Arch_FreeRTOS_32.svg';

export const archAwsIoT1Click32Svg = { id: "archAwsIoT1Click32Svg", name: "AWS IoT 1 Click", icon: _archAwsIoT1Click32Svg };
export const archAwsIoTAnalytics32Svg = { id: "archAwsIoTAnalytics32Svg", name: "AWS IoT Analytics", icon: _archAwsIoTAnalytics32Svg };
export const archAwsIoTButton32Svg = { id: "archAwsIoTButton32Svg", name: "AWS IoT Button", icon: _archAwsIoTButton32Svg };
export const archAwsIoTCore32Svg = { id: "archAwsIoTCore32Svg", name: "AWS IoT Core", icon: _archAwsIoTCore32Svg };
export const archAwsIoTDeviceDefender32Svg = { id: "archAwsIoTDeviceDefender32Svg", name: "AWS IoT Device Defender", icon: _archAwsIoTDeviceDefender32Svg };
export const archAwsIoTDeviceManagement32Svg = { id: "archAwsIoTDeviceManagement32Svg", name: "AWS IoT Device Management", icon: _archAwsIoTDeviceManagement32Svg };
export const archAwsIoTEduKit32Svg = { id: "archAwsIoTEduKit32Svg", name: "AWS IoT EduKit", icon: _archAwsIoTEduKit32Svg };
export const archAwsIoTEvents32Svg = { id: "archAwsIoTEvents32Svg", name: "AWS IoT Events", icon: _archAwsIoTEvents32Svg };
export const archAwsIoTExpressLink32Svg = { id: "archAwsIoTExpressLink32Svg", name: "AWS IoT ExpressLink", icon: _archAwsIoTExpressLink32Svg };
export const archAwsIoTFleetWise32Svg = { id: "archAwsIoTFleetWise32Svg", name: "AWS IoT FleetWise", icon: _archAwsIoTFleetWise32Svg };
export const archAwsIoTGreengrass32Svg = { id: "archAwsIoTGreengrass32Svg", name: "AWS IoT Greengrass", icon: _archAwsIoTGreengrass32Svg };
export const archAwsIoTRoboRunner32Svg = { id: "archAwsIoTRoboRunner32Svg", name: "AWS IoT RoboRunner", icon: _archAwsIoTRoboRunner32Svg };
export const archAwsIoTSiteWise32Svg = { id: "archAwsIoTSiteWise32Svg", name: "AWS IoT SiteWise", icon: _archAwsIoTSiteWise32Svg };
export const archAwsIoTThingsGraph32Svg = { id: "archAwsIoTThingsGraph32Svg", name: "AWS IoT Things Graph", icon: _archAwsIoTThingsGraph32Svg };
export const archAwsIoTTwinMaker32Svg = { id: "archAwsIoTTwinMaker32Svg", name: "AWS IoT TwinMaker", icon: _archAwsIoTTwinMaker32Svg };
export const archFreeRtos32Svg = { id: "archFreeRtos32Svg", name: "FreeRTOS", icon: _archFreeRtos32Svg };
