import _archAwsArtifact48Svg from './Arch_AWS-Artifact_48.svg';
import _archAwsAuditManager48Svg from './Arch_AWS-Audit-Manager_48.svg';
import _archAwsCertificateManager48Svg from './Arch_AWS-Certificate-Manager_48.svg';
import _archAwsCloudHsm48Svg from './Arch_AWS-CloudHSM_48.svg';
import _archAwsDirectoryService48Svg from './Arch_AWS-Directory-Service_48.svg';
import _archAwsFirewallManager48Svg from './Arch_AWS-Firewall-Manager_48.svg';
import _archAwsIamIdentityCenter48Svg from './Arch_AWS-IAM-Identity-Center_48.svg';
import _archAwsIdentityAndAccessManagement48Svg from './Arch_AWS-Identity-and-Access-Management_48.svg';
import _archAwsKeyManagementService48Svg from './Arch_AWS-Key-Management-Service_48.svg';
import _archAwsNetworkFirewall48Svg from './Arch_AWS-Network-Firewall_48.svg';
import _archAwsResourceAccessManager48Svg from './Arch_AWS-Resource-Access-Manager_48.svg';
import _archAwsSecretsManager48Svg from './Arch_AWS-Secrets-Manager_48.svg';
import _archAwsSecurityHub48Svg from './Arch_AWS-Security-Hub_48.svg';
import _archAwsShield48Svg from './Arch_AWS-Shield_48.svg';
import _archAwsSigner48Svg from './Arch_AWS-Signer_48.svg';
import _archAwsWaf48Svg from './Arch_AWS-WAF_48.svg';
import _archAmazonCloudDirectory48Svg from './Arch_Amazon-Cloud-Directory_48.svg';
import _archAmazonCognito48Svg from './Arch_Amazon-Cognito_48.svg';
import _archAmazonDetective48Svg from './Arch_Amazon-Detective_48.svg';
import _archAmazonGuardDuty48Svg from './Arch_Amazon-GuardDuty_48.svg';
import _archAmazonInspector48Svg from './Arch_Amazon-Inspector_48.svg';
import _archAmazonMacie48Svg from './Arch_Amazon-Macie_48.svg';

export const archAwsArtifact48Svg = { id: "archAwsArtifact48Svg", name: "AWS Artifact", icon: _archAwsArtifact48Svg };
export const archAwsAuditManager48Svg = { id: "archAwsAuditManager48Svg", name: "AWS Audit Manager", icon: _archAwsAuditManager48Svg };
export const archAwsCertificateManager48Svg = { id: "archAwsCertificateManager48Svg", name: "AWS Certificate Manager", icon: _archAwsCertificateManager48Svg };
export const archAwsCloudHsm48Svg = { id: "archAwsCloudHsm48Svg", name: "AWS CloudHSM", icon: _archAwsCloudHsm48Svg };
export const archAwsDirectoryService48Svg = { id: "archAwsDirectoryService48Svg", name: "AWS Directory Service", icon: _archAwsDirectoryService48Svg };
export const archAwsFirewallManager48Svg = { id: "archAwsFirewallManager48Svg", name: "AWS Firewall Manager", icon: _archAwsFirewallManager48Svg };
export const archAwsIamIdentityCenter48Svg = { id: "archAwsIamIdentityCenter48Svg", name: "AWS IAM Identity Center", icon: _archAwsIamIdentityCenter48Svg };
export const archAwsIdentityAndAccessManagement48Svg = { id: "archAwsIdentityAndAccessManagement48Svg", name: "AWS Identity and Access Management", icon: _archAwsIdentityAndAccessManagement48Svg };
export const archAwsKeyManagementService48Svg = { id: "archAwsKeyManagementService48Svg", name: "AWS Key Management Service", icon: _archAwsKeyManagementService48Svg };
export const archAwsNetworkFirewall48Svg = { id: "archAwsNetworkFirewall48Svg", name: "AWS Network Firewall", icon: _archAwsNetworkFirewall48Svg };
export const archAwsResourceAccessManager48Svg = { id: "archAwsResourceAccessManager48Svg", name: "AWS Resource Access Manager", icon: _archAwsResourceAccessManager48Svg };
export const archAwsSecretsManager48Svg = { id: "archAwsSecretsManager48Svg", name: "AWS Secrets Manager", icon: _archAwsSecretsManager48Svg };
export const archAwsSecurityHub48Svg = { id: "archAwsSecurityHub48Svg", name: "AWS Security Hub", icon: _archAwsSecurityHub48Svg };
export const archAwsShield48Svg = { id: "archAwsShield48Svg", name: "AWS Shield", icon: _archAwsShield48Svg };
export const archAwsSigner48Svg = { id: "archAwsSigner48Svg", name: "AWS Signer", icon: _archAwsSigner48Svg };
export const archAwsWaf48Svg = { id: "archAwsWaf48Svg", name: "AWS WAF", icon: _archAwsWaf48Svg };
export const archAmazonCloudDirectory48Svg = { id: "archAmazonCloudDirectory48Svg", name: "Amazon Cloud Directory", icon: _archAmazonCloudDirectory48Svg };
export const archAmazonCognito48Svg = { id: "archAmazonCognito48Svg", name: "Amazon Cognito", icon: _archAmazonCognito48Svg };
export const archAmazonDetective48Svg = { id: "archAmazonDetective48Svg", name: "Amazon Detective", icon: _archAmazonDetective48Svg };
export const archAmazonGuardDuty48Svg = { id: "archAmazonGuardDuty48Svg", name: "Amazon GuardDuty", icon: _archAmazonGuardDuty48Svg };
export const archAmazonInspector48Svg = { id: "archAmazonInspector48Svg", name: "Amazon Inspector", icon: _archAmazonInspector48Svg };
export const archAmazonMacie48Svg = { id: "archAmazonMacie48Svg", name: "Amazon Macie", icon: _archAmazonMacie48Svg };
