import _resAwsDatasyncAgent48LightSvg from './Res_AWS-Datasync_Agent_48_Light.svg';
import _resAwsMainframeModernizationAnalyzer48LightSvg from './Res_AWS-Mainframe-Modernization_Analyzer_48_Light.svg';
import _resAwsMainframeModernizationCompiler48LightSvg from './Res_AWS-Mainframe-Modernization_Compiler_48_Light.svg';
import _resAwsMainframeModernizationConverter48LightSvg from './Res_AWS-Mainframe-Modernization_Converter_48_Light.svg';
import _resAwsMainframeModernizationDeveloper48LightSvg from './Res_AWS-Mainframe-Modernization_Developer_48_Light.svg';
import _resAwsMainframeModernizationRuntime48LightSvg from './Res_AWS-Mainframe-Modernization_Runtime_48_Light.svg';
import _resAwsMigrationHubRefactorSpacesApplications48LightSvg from './Res_AWS-Migration-Hub_Refactor-Spaces-Applications_48_Light.svg';
import _resAwsMigrationHubRefactorSpacesEnvironments48LightSvg from './Res_AWS-Migration-Hub_Refactor-Spaces-Environments_48_Light.svg';
import _resAwsMigrationHubRefactorSpacesServices48LightSvg from './Res_AWS-Migration-Hub_Refactor-Spaces-Services_48_Light.svg';
import _resAwsTransferFamilyAwsFtps48LightSvg from './Res_AWS-Transfer-Family_AWS-FTPS_48_Light.svg';
import _resAwsTransferFamilyAwsFtp48LightSvg from './Res_AWS-Transfer-Family_AWS-FTP_48_Light.svg';
import _resAwsTransferFamilyAwsSftp48LightSvg from './Res_AWS-Transfer-Family_AWS-SFTP_48_Light.svg';

export const resAwsDatasyncAgent48LightSvg = { id: "resAwsDatasyncAgent48LightSvg", name: "AWS Datasync / Agent", icon: _resAwsDatasyncAgent48LightSvg };
export const resAwsMainframeModernizationAnalyzer48LightSvg = { id: "resAwsMainframeModernizationAnalyzer48LightSvg", name: "AWS Mainframe Modernization / Analyzer", icon: _resAwsMainframeModernizationAnalyzer48LightSvg };
export const resAwsMainframeModernizationCompiler48LightSvg = { id: "resAwsMainframeModernizationCompiler48LightSvg", name: "AWS Mainframe Modernization / Compiler", icon: _resAwsMainframeModernizationCompiler48LightSvg };
export const resAwsMainframeModernizationConverter48LightSvg = { id: "resAwsMainframeModernizationConverter48LightSvg", name: "AWS Mainframe Modernization / Converter", icon: _resAwsMainframeModernizationConverter48LightSvg };
export const resAwsMainframeModernizationDeveloper48LightSvg = { id: "resAwsMainframeModernizationDeveloper48LightSvg", name: "AWS Mainframe Modernization / Developer", icon: _resAwsMainframeModernizationDeveloper48LightSvg };
export const resAwsMainframeModernizationRuntime48LightSvg = { id: "resAwsMainframeModernizationRuntime48LightSvg", name: "AWS Mainframe Modernization / Runtime", icon: _resAwsMainframeModernizationRuntime48LightSvg };
export const resAwsMigrationHubRefactorSpacesApplications48LightSvg = { id: "resAwsMigrationHubRefactorSpacesApplications48LightSvg", name: "AWS Migration Hub / Refactor Spaces Applications", icon: _resAwsMigrationHubRefactorSpacesApplications48LightSvg };
export const resAwsMigrationHubRefactorSpacesEnvironments48LightSvg = { id: "resAwsMigrationHubRefactorSpacesEnvironments48LightSvg", name: "AWS Migration Hub / Refactor Spaces Environments", icon: _resAwsMigrationHubRefactorSpacesEnvironments48LightSvg };
export const resAwsMigrationHubRefactorSpacesServices48LightSvg = { id: "resAwsMigrationHubRefactorSpacesServices48LightSvg", name: "AWS Migration Hub / Refactor Spaces Services", icon: _resAwsMigrationHubRefactorSpacesServices48LightSvg };
export const resAwsTransferFamilyAwsFtps48LightSvg = { id: "resAwsTransferFamilyAwsFtps48LightSvg", name: "AWS Transfer Family / AWS FTPS", icon: _resAwsTransferFamilyAwsFtps48LightSvg };
export const resAwsTransferFamilyAwsFtp48LightSvg = { id: "resAwsTransferFamilyAwsFtp48LightSvg", name: "AWS Transfer Family / AWS FTP", icon: _resAwsTransferFamilyAwsFtp48LightSvg };
export const resAwsTransferFamilyAwsSftp48LightSvg = { id: "resAwsTransferFamilyAwsSftp48LightSvg", name: "AWS Transfer Family / AWS SFTP", icon: _resAwsTransferFamilyAwsSftp48LightSvg };
