export { ReactComponent as resAmazonElasticContainerRegistryImage48LightSvg } from './Res_Amazon-Elastic-Container-Registry_Image_48_Light.svg';
export { ReactComponent as resAmazonElasticContainerRegistryRegistry48LightSvg } from './Res_Amazon-Elastic-Container-Registry_Registry_48_Light.svg';
export { ReactComponent as resAmazonElasticContainerServiceContainer148LightSvg } from './Res_Amazon-Elastic-Container-Service_Container-1_48_Light.svg';
export { ReactComponent as resAmazonElasticContainerServiceContainer248LightSvg } from './Res_Amazon-Elastic-Container-Service_Container-2_48_Light.svg';
export { ReactComponent as resAmazonElasticContainerServiceContainer348LightSvg } from './Res_Amazon-Elastic-Container-Service_Container-3_48_Light.svg';
export { ReactComponent as resAmazonElasticContainerServiceCopilotCli48LightSvg } from './Res_Amazon-Elastic-Container-Service_Copilot-CLI_48_Light.svg';
export { ReactComponent as resAmazonElasticContainerServiceEcsAnywhere48LightSvg } from './Res_Amazon-Elastic-Container-Service_ECS-Anywhere_48_Light.svg';
export { ReactComponent as resAmazonElasticContainerServiceService48LightSvg } from './Res_Amazon-Elastic-Container-Service_Service_48_Light.svg';
export { ReactComponent as resAmazonElasticContainerServiceTask48LightSvg } from './Res_Amazon-Elastic-Container-Service_Task_48_Light.svg';