import _resAwsIoTAnalyticsChannel48DarkSvg from './Res_AWS-IoT-Analytics_Channel_48_Dark.svg';
import _resAwsIoTAnalyticsDataStore48DarkSvg from './Res_AWS-IoT-Analytics_Data-Store_48_Dark.svg';
import _resAwsIoTAnalyticsDataset48DarkSvg from './Res_AWS-IoT-Analytics_Dataset_48_Dark.svg';
import _resAwsIoTAnalyticsNotebook48DarkSvg from './Res_AWS-IoT-Analytics_Notebook_48_Dark.svg';
import _resAwsIoTAnalyticsPipeline48DarkSvg from './Res_AWS-IoT-Analytics_Pipeline_48_Dark.svg';
import _resAwsIoTDeviceDefenderIoTDeviceJobs48DarkSvg from './Res_AWS-IoT-Device-Defender_IoT-Device-Jobs_48_Dark.svg';
import _resAwsIoTDeviceManagementFleetHub48DarkSvg from './Res_AWS-IoT-Device-Management_Fleet-Hub_48_Dark.svg';
import _resAwsIoTGreengrassArtifact48DarkSvg from './Res_AWS-IoT-Greengrass_Artifact_48_Dark.svg';
import _resAwsIoTGreengrassComponentMachineLearning48DarkSvg from './Res_AWS-IoT-Greengrass_Component-Machine-Learning_48_Dark.svg';
import _resAwsIoTGreengrassComponentNucleus48DarkSvg from './Res_AWS-IoT-Greengrass_Component-Nucleus_48_Dark.svg';
import _resAwsIoTGreengrassComponentPrivate48DarkSvg from './Res_AWS-IoT-Greengrass_Component-Private_48_Dark.svg';
import _resAwsIoTGreengrassComponentPublic48DarkSvg from './Res_AWS-IoT-Greengrass_Component-Public_48_Dark.svg';
import _resAwsIoTGreengrassComponent48DarkSvg from './Res_AWS-IoT-Greengrass_Component_48_Dark.svg';
import _resAwsIoTGreengrassInterprocessCommunication48DarkSvg from './Res_AWS-IoT-Greengrass_Interprocess-Communication_48_Dark.svg';
import _resAwsIoTGreengrassProtocol48DarkSvg from './Res_AWS-IoT-Greengrass_Protocol_48_Dark.svg';
import _resAwsIoTGreengrassRecipe48DarkSvg from './Res_AWS-IoT-Greengrass_Recipe_48_Dark.svg';
import _resAwsIoTGreengrassStreamManager48DarkSvg from './Res_AWS-IoT-Greengrass_Stream-Manager_48_Dark.svg';
import _resAwsIoTHardwareBoard48DarkSvg from './Res_AWS-IoT-Hardware-Board_48_Dark.svg';
import _resAwsIoTRule48DarkSvg from './Res_AWS-IoT-Rule_48_Dark.svg';
import _resAwsIoTSiteWiseAssetHierarchy48DarkSvg from './Res_AWS-IoT-SiteWise_Asset-Hierarchy_48_Dark.svg';
import _resAwsIoTSiteWiseAssetModel48DarkSvg from './Res_AWS-IoT-SiteWise_Asset-Model_48_Dark.svg';
import _resAwsIoTSiteWiseAssetProperties48DarkSvg from './Res_AWS-IoT-SiteWise_Asset-Properties_48_Dark.svg';
import _resAwsIoTSiteWiseAsset48DarkSvg from './Res_AWS-IoT-SiteWise_Asset_48_Dark.svg';
import _resAwsIoTSiteWiseDataStreams48DarkSvg from './Res_AWS-IoT-SiteWise_Data-Streams_48_Dark.svg';
import _resAwsIoTAction48DarkSvg from './Res_AWS-IoT_Action_48_Dark.svg';
import _resAwsIoTActuator48DarkSvg from './Res_AWS-IoT_Actuator_48_Dark.svg';
import _resAwsIoTAlexaEnabledDevice48DarkSvg from './Res_AWS-IoT_Alexa_Enabled-Device_48_Dark.svg';
import _resAwsIoTAlexaSkill48DarkSvg from './Res_AWS-IoT_Alexa_Skill_48_Dark.svg';
import _resAwsIoTAlexaVoiceService48DarkSvg from './Res_AWS-IoT_Alexa_Voice-Service_48_Dark.svg';
import _resAwsIoTCertificate48DarkSvg from './Res_AWS-IoT_Certificate_48_Dark.svg';
import _resAwsIoTDesiredState48DarkSvg from './Res_AWS-IoT_Desired-State_48_Dark.svg';
import _resAwsIoTDeviceGateway48DarkSvg from './Res_AWS-IoT_Device-Gateway_48_Dark.svg';
import _resAwsIoTEcho48DarkSvg from './Res_AWS-IoT_Echo_48_Dark.svg';
import _resAwsIoTFireTvStick48DarkSvg from './Res_AWS-IoT_Fire-TV_Stick_48_Dark.svg';
import _resAwsIoTFireTv48DarkSvg from './Res_AWS-IoT_Fire_TV_48_Dark.svg';
import _resAwsIoTGreengrassConnector48DarkSvg from './Res_AWS-IoT_Greengrass_Connector_48_Dark.svg';
import _resAwsIoTHttp2Protocol48DarkSvg from './Res_AWS-IoT_HTTP2-Protocol_48_Dark.svg';
import _resAwsIoTHttpProtocol48DarkSvg from './Res_AWS-IoT_HTTP_Protocol_48_Dark.svg';
import _resAwsIoTLambdaFunction48DarkSvg from './Res_AWS-IoT_Lambda_Function_48_Dark.svg';
import _resAwsIoTLoRaWanProtocol48DarkSvg from './Res_AWS-IoT_LoRaWAN-Protocol _48_Dark.svg';
import _resAwsIoTMqttProtocol48DarkSvg from './Res_AWS-IoT_MQTT_Protocol_48_Dark.svg';
import _resAwsIoTOverAirUpdate48DarkSvg from './Res_AWS-IoT_Over-Air-Update_48_Dark.svg';
import _resAwsIoTPolicy48DarkSvg from './Res_AWS-IoT_Policy_48_Dark.svg';
import _resAwsIoTReportedState48DarkSvg from './Res_AWS-IoT_Reported-State_48_Dark.svg';
import _resAwsIoTSailboat48DarkSvg from './Res_AWS-IoT_Sailboat _48_Dark.svg';
import _resAwsIoTSensor48DarkSvg from './Res_AWS-IoT_Sensor_48_Dark.svg';
import _resAwsIoTServo48DarkSvg from './Res_AWS-IoT_Servo_48_Dark.svg';
import _resAwsIoTShadow48DarkSvg from './Res_AWS-IoT_Shadow_48_Dark.svg';
import _resAwsIoTSimulator48DarkSvg from './Res_AWS-IoT_Simulator_48_Dark.svg';
import _resAwsIoTThingBank48DarkSvg from './Res_AWS-IoT_Thing_Bank_48_Dark.svg';
import _resAwsIoTThingBicycle48DarkSvg from './Res_AWS-IoT_Thing_Bicycle_48_Dark.svg';
import _resAwsIoTThingCamera48DarkSvg from './Res_AWS-IoT_Thing_Camera_48_Dark.svg';
import _resAwsIoTThingCar48DarkSvg from './Res_AWS-IoT_Thing_Car_48_Dark.svg';
import _resAwsIoTThingCart48DarkSvg from './Res_AWS-IoT_Thing_Cart_48_Dark.svg';
import _resAwsIoTThingCoffeePot48DarkSvg from './Res_AWS-IoT_Thing_Coffee-Pot_48_Dark.svg';
import _resAwsIoTThingDoorLock48DarkSvg from './Res_AWS-IoT_Thing_Door-Lock_48_Dark.svg';
import _resAwsIoTThingFactory48DarkSvg from './Res_AWS-IoT_Thing_Factory_48_Dark.svg';
import _resAwsIoTThingFreeRtosDevice48DarkSvg from './Res_AWS-IoT_Thing_FreeRTOS-Device_48_Dark.svg';
import _resAwsIoTThingGeneric48DarkSvg from './Res_AWS-IoT_Thing_Generic_48_Dark.svg';
import _resAwsIoTThingHouse48DarkSvg from './Res_AWS-IoT_Thing_House_48_Dark.svg';
import _resAwsIoTThingHumiditySensor48DarkSvg from './Res_AWS-IoT_Thing_Humidity-Sensor_48_Dark.svg';
import _resAwsIoTThingIndustrialPc48DarkSvg from './Res_AWS-IoT_Thing_Industrial-PC_48_Dark.svg';
import _resAwsIoTThingLightbulb48DarkSvg from './Res_AWS-IoT_Thing_Lightbulb_48_Dark.svg';
import _resAwsIoTThingMedicalEmergency48DarkSvg from './Res_AWS-IoT_Thing_Medical-Emergency_48_Dark.svg';
import _resAwsIoTThingPlc48DarkSvg from './Res_AWS-IoT_Thing_PLC_48_Dark.svg';
import _resAwsIoTThingPoliceEmergency48DarkSvg from './Res_AWS-IoT_Thing_Police-Emergency_48_Dark.svg';
import _resAwsIoTThingRelay48DarkSvg from './Res_AWS-IoT_Thing_Relay_48_Dark.svg';
import _resAwsIoTThingStacklight48DarkSvg from './Res_AWS-IoT_Thing_Stacklight_48_Dark.svg';
import _resAwsIoTThingTemperatureHumiditySensor48DarkSvg from './Res_AWS-IoT_Thing_Temperature-Humidity-Sensor_48_Dark.svg';
import _resAwsIoTThingTemperatureSensor48DarkSvg from './Res_AWS-IoT_Thing_Temperature-Sensor_48_Dark.svg';
import _resAwsIoTThingTemperatureVibrationSensor48DarkSvg from './Res_AWS-IoT_Thing_Temperature-Vibration-Sensor_48_Dark.svg';
import _resAwsIoTThingThermostat48DarkSvg from './Res_AWS-IoT_Thing_Thermostat_48_Dark.svg';
import _resAwsIoTThingTravel48DarkSvg from './Res_AWS-IoT_Thing_Travel_48_Dark.svg';
import _resAwsIoTThingUtility48DarkSvg from './Res_AWS-IoT_Thing_Utility_48_Dark.svg';
import _resAwsIoTThingVibrationSensor48DarkSvg from './Res_AWS-IoT_Thing_Vibration-Sensor_48_Dark.svg';
import _resAwsIoTThingWindfarm48DarkSvg from './Res_AWS-IoT_Thing_Windfarm_48_Dark.svg';
import _resAwsIoTTopic48DarkSvg from './Res_AWS-IoT_Topic_48_Dark.svg';

export const resAwsIoTAnalyticsChannel48DarkSvg = { id: "resAwsIoTAnalyticsChannel48DarkSvg", name: "AWS IoT Analytics | Channel", icon: _resAwsIoTAnalyticsChannel48DarkSvg };
export const resAwsIoTAnalyticsDataStore48DarkSvg = { id: "resAwsIoTAnalyticsDataStore48DarkSvg", name: "AWS IoT Analytics | Data Store", icon: _resAwsIoTAnalyticsDataStore48DarkSvg };
export const resAwsIoTAnalyticsDataset48DarkSvg = { id: "resAwsIoTAnalyticsDataset48DarkSvg", name: "AWS IoT Analytics | Dataset", icon: _resAwsIoTAnalyticsDataset48DarkSvg };
export const resAwsIoTAnalyticsNotebook48DarkSvg = { id: "resAwsIoTAnalyticsNotebook48DarkSvg", name: "AWS IoT Analytics | Notebook", icon: _resAwsIoTAnalyticsNotebook48DarkSvg };
export const resAwsIoTAnalyticsPipeline48DarkSvg = { id: "resAwsIoTAnalyticsPipeline48DarkSvg", name: "AWS IoT Analytics | Pipeline", icon: _resAwsIoTAnalyticsPipeline48DarkSvg };
export const resAwsIoTDeviceDefenderIoTDeviceJobs48DarkSvg = { id: "resAwsIoTDeviceDefenderIoTDeviceJobs48DarkSvg", name: "AWS IoT Device Defender | IoT Device Jobs", icon: _resAwsIoTDeviceDefenderIoTDeviceJobs48DarkSvg };
export const resAwsIoTDeviceManagementFleetHub48DarkSvg = { id: "resAwsIoTDeviceManagementFleetHub48DarkSvg", name: "AWS IoT Device Management | Fleet Hub", icon: _resAwsIoTDeviceManagementFleetHub48DarkSvg };
export const resAwsIoTGreengrassArtifact48DarkSvg = { id: "resAwsIoTGreengrassArtifact48DarkSvg", name: "AWS IoT Greengrass | Artifact", icon: _resAwsIoTGreengrassArtifact48DarkSvg };
export const resAwsIoTGreengrassComponentMachineLearning48DarkSvg = { id: "resAwsIoTGreengrassComponentMachineLearning48DarkSvg", name: "AWS IoT Greengrass | Component Machine Learning", icon: _resAwsIoTGreengrassComponentMachineLearning48DarkSvg };
export const resAwsIoTGreengrassComponentNucleus48DarkSvg = { id: "resAwsIoTGreengrassComponentNucleus48DarkSvg", name: "AWS IoT Greengrass | Component Nucleus", icon: _resAwsIoTGreengrassComponentNucleus48DarkSvg };
export const resAwsIoTGreengrassComponentPrivate48DarkSvg = { id: "resAwsIoTGreengrassComponentPrivate48DarkSvg", name: "AWS IoT Greengrass | Component Private", icon: _resAwsIoTGreengrassComponentPrivate48DarkSvg };
export const resAwsIoTGreengrassComponentPublic48DarkSvg = { id: "resAwsIoTGreengrassComponentPublic48DarkSvg", name: "AWS IoT Greengrass | Component Public", icon: _resAwsIoTGreengrassComponentPublic48DarkSvg };
export const resAwsIoTGreengrassComponent48DarkSvg = { id: "resAwsIoTGreengrassComponent48DarkSvg", name: "AWS IoT Greengrass | Component", icon: _resAwsIoTGreengrassComponent48DarkSvg };
export const resAwsIoTGreengrassInterprocessCommunication48DarkSvg = { id: "resAwsIoTGreengrassInterprocessCommunication48DarkSvg", name: "AWS IoT Greengrass | Interprocess Communication", icon: _resAwsIoTGreengrassInterprocessCommunication48DarkSvg };
export const resAwsIoTGreengrassProtocol48DarkSvg = { id: "resAwsIoTGreengrassProtocol48DarkSvg", name: "AWS IoT Greengrass | Protocol", icon: _resAwsIoTGreengrassProtocol48DarkSvg };
export const resAwsIoTGreengrassRecipe48DarkSvg = { id: "resAwsIoTGreengrassRecipe48DarkSvg", name: "AWS IoT Greengrass | Recipe", icon: _resAwsIoTGreengrassRecipe48DarkSvg };
export const resAwsIoTGreengrassStreamManager48DarkSvg = { id: "resAwsIoTGreengrassStreamManager48DarkSvg", name: "AWS IoT Greengrass | Stream Manager", icon: _resAwsIoTGreengrassStreamManager48DarkSvg };
export const resAwsIoTHardwareBoard48DarkSvg = { id: "resAwsIoTHardwareBoard48DarkSvg", name: "AWS IoT Hardware Board", icon: _resAwsIoTHardwareBoard48DarkSvg };
export const resAwsIoTRule48DarkSvg = { id: "resAwsIoTRule48DarkSvg", name: "AWS IoT Rule", icon: _resAwsIoTRule48DarkSvg };
export const resAwsIoTSiteWiseAssetHierarchy48DarkSvg = { id: "resAwsIoTSiteWiseAssetHierarchy48DarkSvg", name: "AWS IoT SiteWise | Asset Hierarchy", icon: _resAwsIoTSiteWiseAssetHierarchy48DarkSvg };
export const resAwsIoTSiteWiseAssetModel48DarkSvg = { id: "resAwsIoTSiteWiseAssetModel48DarkSvg", name: "AWS IoT SiteWise | Asset Model", icon: _resAwsIoTSiteWiseAssetModel48DarkSvg };
export const resAwsIoTSiteWiseAssetProperties48DarkSvg = { id: "resAwsIoTSiteWiseAssetProperties48DarkSvg", name: "AWS IoT SiteWise | Asset Properties", icon: _resAwsIoTSiteWiseAssetProperties48DarkSvg };
export const resAwsIoTSiteWiseAsset48DarkSvg = { id: "resAwsIoTSiteWiseAsset48DarkSvg", name: "AWS IoT SiteWise | Asset", icon: _resAwsIoTSiteWiseAsset48DarkSvg };
export const resAwsIoTSiteWiseDataStreams48DarkSvg = { id: "resAwsIoTSiteWiseDataStreams48DarkSvg", name: "AWS IoT SiteWise | Data Streams", icon: _resAwsIoTSiteWiseDataStreams48DarkSvg };
export const resAwsIoTAction48DarkSvg = { id: "resAwsIoTAction48DarkSvg", name: "AWS IoT | Action", icon: _resAwsIoTAction48DarkSvg };
export const resAwsIoTActuator48DarkSvg = { id: "resAwsIoTActuator48DarkSvg", name: "AWS IoT | Actuator", icon: _resAwsIoTActuator48DarkSvg };
export const resAwsIoTAlexaEnabledDevice48DarkSvg = { id: "resAwsIoTAlexaEnabledDevice48DarkSvg", name: "AWS IoT | Alexa | Enabled Device", icon: _resAwsIoTAlexaEnabledDevice48DarkSvg };
export const resAwsIoTAlexaSkill48DarkSvg = { id: "resAwsIoTAlexaSkill48DarkSvg", name: "AWS IoT | Alexa | Skill", icon: _resAwsIoTAlexaSkill48DarkSvg };
export const resAwsIoTAlexaVoiceService48DarkSvg = { id: "resAwsIoTAlexaVoiceService48DarkSvg", name: "AWS IoT | Alexa | Voice Service", icon: _resAwsIoTAlexaVoiceService48DarkSvg };
export const resAwsIoTCertificate48DarkSvg = { id: "resAwsIoTCertificate48DarkSvg", name: "AWS IoT | Certificate", icon: _resAwsIoTCertificate48DarkSvg };
export const resAwsIoTDesiredState48DarkSvg = { id: "resAwsIoTDesiredState48DarkSvg", name: "AWS IoT | Desired State", icon: _resAwsIoTDesiredState48DarkSvg };
export const resAwsIoTDeviceGateway48DarkSvg = { id: "resAwsIoTDeviceGateway48DarkSvg", name: "AWS IoT | Device Gateway", icon: _resAwsIoTDeviceGateway48DarkSvg };
export const resAwsIoTEcho48DarkSvg = { id: "resAwsIoTEcho48DarkSvg", name: "AWS IoT | Echo", icon: _resAwsIoTEcho48DarkSvg };
export const resAwsIoTFireTvStick48DarkSvg = { id: "resAwsIoTFireTvStick48DarkSvg", name: "AWS IoT | Fire TV | Stick", icon: _resAwsIoTFireTvStick48DarkSvg };
export const resAwsIoTFireTv48DarkSvg = { id: "resAwsIoTFireTv48DarkSvg", name: "AWS IoT | Fire | TV", icon: _resAwsIoTFireTv48DarkSvg };
export const resAwsIoTGreengrassConnector48DarkSvg = { id: "resAwsIoTGreengrassConnector48DarkSvg", name: "AWS IoT | Greengrass | Connector", icon: _resAwsIoTGreengrassConnector48DarkSvg };
export const resAwsIoTHttp2Protocol48DarkSvg = { id: "resAwsIoTHttp2Protocol48DarkSvg", name: "AWS IoT | HTTP2 Protocol", icon: _resAwsIoTHttp2Protocol48DarkSvg };
export const resAwsIoTHttpProtocol48DarkSvg = { id: "resAwsIoTHttpProtocol48DarkSvg", name: "AWS IoT | HTTP | Protocol", icon: _resAwsIoTHttpProtocol48DarkSvg };
export const resAwsIoTLambdaFunction48DarkSvg = { id: "resAwsIoTLambdaFunction48DarkSvg", name: "AWS IoT | Lambda | Function", icon: _resAwsIoTLambdaFunction48DarkSvg };
export const resAwsIoTLoRaWanProtocol48DarkSvg = { id: "resAwsIoTLoRaWanProtocol48DarkSvg", name: "AWS IoT | LoRaWAN Protocol ", icon: _resAwsIoTLoRaWanProtocol48DarkSvg };
export const resAwsIoTMqttProtocol48DarkSvg = { id: "resAwsIoTMqttProtocol48DarkSvg", name: "AWS IoT | MQTT | Protocol", icon: _resAwsIoTMqttProtocol48DarkSvg };
export const resAwsIoTOverAirUpdate48DarkSvg = { id: "resAwsIoTOverAirUpdate48DarkSvg", name: "AWS IoT | Over Air Update", icon: _resAwsIoTOverAirUpdate48DarkSvg };
export const resAwsIoTPolicy48DarkSvg = { id: "resAwsIoTPolicy48DarkSvg", name: "AWS IoT | Policy", icon: _resAwsIoTPolicy48DarkSvg };
export const resAwsIoTReportedState48DarkSvg = { id: "resAwsIoTReportedState48DarkSvg", name: "AWS IoT | Reported State", icon: _resAwsIoTReportedState48DarkSvg };
export const resAwsIoTSailboat48DarkSvg = { id: "resAwsIoTSailboat48DarkSvg", name: "AWS IoT | Sailboat ", icon: _resAwsIoTSailboat48DarkSvg };
export const resAwsIoTSensor48DarkSvg = { id: "resAwsIoTSensor48DarkSvg", name: "AWS IoT | Sensor", icon: _resAwsIoTSensor48DarkSvg };
export const resAwsIoTServo48DarkSvg = { id: "resAwsIoTServo48DarkSvg", name: "AWS IoT | Servo", icon: _resAwsIoTServo48DarkSvg };
export const resAwsIoTShadow48DarkSvg = { id: "resAwsIoTShadow48DarkSvg", name: "AWS IoT | Shadow", icon: _resAwsIoTShadow48DarkSvg };
export const resAwsIoTSimulator48DarkSvg = { id: "resAwsIoTSimulator48DarkSvg", name: "AWS IoT | Simulator", icon: _resAwsIoTSimulator48DarkSvg };
export const resAwsIoTThingBank48DarkSvg = { id: "resAwsIoTThingBank48DarkSvg", name: "AWS IoT | Thing | Bank", icon: _resAwsIoTThingBank48DarkSvg };
export const resAwsIoTThingBicycle48DarkSvg = { id: "resAwsIoTThingBicycle48DarkSvg", name: "AWS IoT | Thing | Bicycle", icon: _resAwsIoTThingBicycle48DarkSvg };
export const resAwsIoTThingCamera48DarkSvg = { id: "resAwsIoTThingCamera48DarkSvg", name: "AWS IoT | Thing | Camera", icon: _resAwsIoTThingCamera48DarkSvg };
export const resAwsIoTThingCar48DarkSvg = { id: "resAwsIoTThingCar48DarkSvg", name: "AWS IoT | Thing | Car", icon: _resAwsIoTThingCar48DarkSvg };
export const resAwsIoTThingCart48DarkSvg = { id: "resAwsIoTThingCart48DarkSvg", name: "AWS IoT | Thing | Cart", icon: _resAwsIoTThingCart48DarkSvg };
export const resAwsIoTThingCoffeePot48DarkSvg = { id: "resAwsIoTThingCoffeePot48DarkSvg", name: "AWS IoT | Thing | Coffee Pot", icon: _resAwsIoTThingCoffeePot48DarkSvg };
export const resAwsIoTThingDoorLock48DarkSvg = { id: "resAwsIoTThingDoorLock48DarkSvg", name: "AWS IoT | Thing | Door Lock", icon: _resAwsIoTThingDoorLock48DarkSvg };
export const resAwsIoTThingFactory48DarkSvg = { id: "resAwsIoTThingFactory48DarkSvg", name: "AWS IoT | Thing | Factory", icon: _resAwsIoTThingFactory48DarkSvg };
export const resAwsIoTThingFreeRtosDevice48DarkSvg = { id: "resAwsIoTThingFreeRtosDevice48DarkSvg", name: "AWS IoT | Thing | FreeRTOS Device", icon: _resAwsIoTThingFreeRtosDevice48DarkSvg };
export const resAwsIoTThingGeneric48DarkSvg = { id: "resAwsIoTThingGeneric48DarkSvg", name: "AWS IoT | Thing | Generic", icon: _resAwsIoTThingGeneric48DarkSvg };
export const resAwsIoTThingHouse48DarkSvg = { id: "resAwsIoTThingHouse48DarkSvg", name: "AWS IoT | Thing | House", icon: _resAwsIoTThingHouse48DarkSvg };
export const resAwsIoTThingHumiditySensor48DarkSvg = { id: "resAwsIoTThingHumiditySensor48DarkSvg", name: "AWS IoT | Thing | Humidity Sensor", icon: _resAwsIoTThingHumiditySensor48DarkSvg };
export const resAwsIoTThingIndustrialPc48DarkSvg = { id: "resAwsIoTThingIndustrialPc48DarkSvg", name: "AWS IoT | Thing | Industrial PC", icon: _resAwsIoTThingIndustrialPc48DarkSvg };
export const resAwsIoTThingLightbulb48DarkSvg = { id: "resAwsIoTThingLightbulb48DarkSvg", name: "AWS IoT | Thing | Lightbulb", icon: _resAwsIoTThingLightbulb48DarkSvg };
export const resAwsIoTThingMedicalEmergency48DarkSvg = { id: "resAwsIoTThingMedicalEmergency48DarkSvg", name: "AWS IoT | Thing | Medical Emergency", icon: _resAwsIoTThingMedicalEmergency48DarkSvg };
export const resAwsIoTThingPlc48DarkSvg = { id: "resAwsIoTThingPlc48DarkSvg", name: "AWS IoT | Thing | PLC", icon: _resAwsIoTThingPlc48DarkSvg };
export const resAwsIoTThingPoliceEmergency48DarkSvg = { id: "resAwsIoTThingPoliceEmergency48DarkSvg", name: "AWS IoT | Thing | Police Emergency", icon: _resAwsIoTThingPoliceEmergency48DarkSvg };
export const resAwsIoTThingRelay48DarkSvg = { id: "resAwsIoTThingRelay48DarkSvg", name: "AWS IoT | Thing | Relay", icon: _resAwsIoTThingRelay48DarkSvg };
export const resAwsIoTThingStacklight48DarkSvg = { id: "resAwsIoTThingStacklight48DarkSvg", name: "AWS IoT | Thing | Stacklight", icon: _resAwsIoTThingStacklight48DarkSvg };
export const resAwsIoTThingTemperatureHumiditySensor48DarkSvg = { id: "resAwsIoTThingTemperatureHumiditySensor48DarkSvg", name: "AWS IoT | Thing | Temperature Humidity Sensor", icon: _resAwsIoTThingTemperatureHumiditySensor48DarkSvg };
export const resAwsIoTThingTemperatureSensor48DarkSvg = { id: "resAwsIoTThingTemperatureSensor48DarkSvg", name: "AWS IoT | Thing | Temperature Sensor", icon: _resAwsIoTThingTemperatureSensor48DarkSvg };
export const resAwsIoTThingTemperatureVibrationSensor48DarkSvg = { id: "resAwsIoTThingTemperatureVibrationSensor48DarkSvg", name: "AWS IoT | Thing | Temperature Vibration Sensor", icon: _resAwsIoTThingTemperatureVibrationSensor48DarkSvg };
export const resAwsIoTThingThermostat48DarkSvg = { id: "resAwsIoTThingThermostat48DarkSvg", name: "AWS IoT | Thing | Thermostat", icon: _resAwsIoTThingThermostat48DarkSvg };
export const resAwsIoTThingTravel48DarkSvg = { id: "resAwsIoTThingTravel48DarkSvg", name: "AWS IoT | Thing | Travel", icon: _resAwsIoTThingTravel48DarkSvg };
export const resAwsIoTThingUtility48DarkSvg = { id: "resAwsIoTThingUtility48DarkSvg", name: "AWS IoT | Thing | Utility", icon: _resAwsIoTThingUtility48DarkSvg };
export const resAwsIoTThingVibrationSensor48DarkSvg = { id: "resAwsIoTThingVibrationSensor48DarkSvg", name: "AWS IoT | Thing | Vibration Sensor", icon: _resAwsIoTThingVibrationSensor48DarkSvg };
export const resAwsIoTThingWindfarm48DarkSvg = { id: "resAwsIoTThingWindfarm48DarkSvg", name: "AWS IoT | Thing | Windfarm", icon: _resAwsIoTThingWindfarm48DarkSvg };
export const resAwsIoTTopic48DarkSvg = { id: "resAwsIoTTopic48DarkSvg", name: "AWS IoT | Topic", icon: _resAwsIoTTopic48DarkSvg };
