import _archAwsBackup48Svg from './Arch_AWS-Backup_48.svg';
import _archAwsSnowballEdge48Svg from './Arch_AWS-Snowball-Edge_48.svg';
import _archAwsSnowball48Svg from './Arch_AWS-Snowball_48.svg';
import _archAwsSnowcone48Svg from './Arch_AWS-Snowcone_48.svg';
import _archAwsSnowmobile48Svg from './Arch_AWS-Snowmobile_48.svg';
import _archAwsStorageGateway48Svg from './Arch_AWS-Storage-Gateway_48.svg';
import _archAmazonEfs48Svg from './Arch_Amazon-EFS_48.svg';
import _archAmazonElasticBlockStore48Svg from './Arch_Amazon-Elastic-Block-Store_48.svg';
import _archAmazonFsxForLustre48Svg from './Arch_Amazon-FSx-for-Lustre_48.svg';
import _archAmazonFsxForNetAppOntap48Svg from './Arch_Amazon-FSx-for-NetApp-ONTAP_48.svg';
import _archAmazonFsxForOpenZfs48Svg from './Arch_Amazon-FSx-for-OpenZFS_48.svg';
import _archAmazonFsxForWfs48Svg from './Arch_Amazon-FSx-for-WFS_48.svg';
import _archAmazonFsx48Svg from './Arch_Amazon-FSx_48.svg';
import _archAmazonS3OnOutposts48Svg from './Arch_Amazon-S3-on-Outposts_48.svg';
import _archAmazonSimpleStorageServiceGlacier48Svg from './Arch_Amazon-Simple-Storage-Service-Glacier_48.svg';
import _archAmazonSimpleStorageService48Svg from './Arch_Amazon-Simple-Storage-Service_48.svg';
import _archCloudEndureDisasterRecovery48Svg from './Arch_CloudEndure-Disaster-Recovery_48.svg';

export const archAwsBackup48Svg = { id: "archAwsBackup48Svg", name: "AWS Backup", icon: _archAwsBackup48Svg };
export const archAwsSnowballEdge48Svg = { id: "archAwsSnowballEdge48Svg", name: "AWS Snowball Edge", icon: _archAwsSnowballEdge48Svg };
export const archAwsSnowball48Svg = { id: "archAwsSnowball48Svg", name: "AWS Snowball", icon: _archAwsSnowball48Svg };
export const archAwsSnowcone48Svg = { id: "archAwsSnowcone48Svg", name: "AWS Snowcone", icon: _archAwsSnowcone48Svg };
export const archAwsSnowmobile48Svg = { id: "archAwsSnowmobile48Svg", name: "AWS Snowmobile", icon: _archAwsSnowmobile48Svg };
export const archAwsStorageGateway48Svg = { id: "archAwsStorageGateway48Svg", name: "AWS Storage Gateway", icon: _archAwsStorageGateway48Svg };
export const archAmazonEfs48Svg = { id: "archAmazonEfs48Svg", name: "Amazon EFS", icon: _archAmazonEfs48Svg };
export const archAmazonElasticBlockStore48Svg = { id: "archAmazonElasticBlockStore48Svg", name: "Amazon Elastic Block Store", icon: _archAmazonElasticBlockStore48Svg };
export const archAmazonFsxForLustre48Svg = { id: "archAmazonFsxForLustre48Svg", name: "Amazon FSx for Lustre", icon: _archAmazonFsxForLustre48Svg };
export const archAmazonFsxForNetAppOntap48Svg = { id: "archAmazonFsxForNetAppOntap48Svg", name: "Amazon FSx for NetApp ONTAP", icon: _archAmazonFsxForNetAppOntap48Svg };
export const archAmazonFsxForOpenZfs48Svg = { id: "archAmazonFsxForOpenZfs48Svg", name: "Amazon FSx for OpenZFS", icon: _archAmazonFsxForOpenZfs48Svg };
export const archAmazonFsxForWfs48Svg = { id: "archAmazonFsxForWfs48Svg", name: "Amazon FSx for WFS", icon: _archAmazonFsxForWfs48Svg };
export const archAmazonFsx48Svg = { id: "archAmazonFsx48Svg", name: "Amazon FSx", icon: _archAmazonFsx48Svg };
export const archAmazonS3OnOutposts48Svg = { id: "archAmazonS3OnOutposts48Svg", name: "Amazon S3 on Outposts", icon: _archAmazonS3OnOutposts48Svg };
export const archAmazonSimpleStorageServiceGlacier48Svg = { id: "archAmazonSimpleStorageServiceGlacier48Svg", name: "Amazon Simple Storage Service Glacier", icon: _archAmazonSimpleStorageServiceGlacier48Svg };
export const archAmazonSimpleStorageService48Svg = { id: "archAmazonSimpleStorageService48Svg", name: "Amazon Simple Storage Service", icon: _archAmazonSimpleStorageService48Svg };
export const archCloudEndureDisasterRecovery48Svg = { id: "archCloudEndureDisasterRecovery48Svg", name: "CloudEndure Disaster Recovery", icon: _archCloudEndureDisasterRecovery48Svg };
