import _resAwsCloudFormationChangeSet48LightSvg from './Res_AWS-CloudFormation_Change-Set_48_Light.svg';
import _resAwsCloudFormationStack48LightSvg from './Res_AWS-CloudFormation_Stack_48_Light.svg';
import _resAwsCloudFormationTemplate48LightSvg from './Res_AWS-CloudFormation_Template_48_Light.svg';
import _resAwsLicenseManagerApplicationDiscovery48LightSvg from './Res_AWS-License-Manager_Application-Discovery_48_Light.svg';
import _resAwsLicenseManagerLicenseBlending48LightSvg from './Res_AWS-License-Manager_License-Blending_48_Light.svg';
import _resAwsOpsWorksApps48LightSvg from './Res_AWS-OpsWorks_Apps_48_Light.svg';
import _resAwsOpsWorksDeployments48LightSvg from './Res_AWS-OpsWorks_Deployments_48_Light.svg';
import _resAwsOpsWorksInstances48LightSvg from './Res_AWS-OpsWorks_Instances_48_Light.svg';
import _resAwsOpsWorksLayers48LightSvg from './Res_AWS-OpsWorks_Layers_48_Light.svg';
import _resAwsOpsWorksMonitoring48LightSvg from './Res_AWS-OpsWorks_Monitoring_48_Light.svg';
import _resAwsOpsWorksPermissions48LightSvg from './Res_AWS-OpsWorks_Permissions_48_Light.svg';
import _resAwsOpsWorksResources48LightSvg from './Res_AWS-OpsWorks_Resources_48_Light.svg';
import _resAwsOpsWorksStack248LightSvg from './Res_AWS-OpsWorks_Stack2_48_Light.svg';
import _resAwsOrganizationsAccount48LightSvg from './Res_AWS-Organizations_Account_48_Light.svg';
import _resAwsOrganizationsManagementAccount48LightSvg from './Res_AWS-Organizations_Management-Account_48_Light.svg';
import _resAwsOrganizationsOrganizationalUnit48LightSvg from './Res_AWS-Organizations_Organizational-Unit_48_Light.svg';
import _resAwsSystemsManagerAutomation48LightSvg from './Res_AWS-Systems-Manager_Automation_48_Light.svg';
import _resAwsSystemsManagerChangeCalendar48LightSvg from './Res_AWS-Systems-Manager_Change-Calendar_48_Light.svg';
import _resAwsSystemsManagerChangeManager48LightSvg from './Res_AWS-Systems-Manager_Change-Manager_48_Light.svg';
import _resAwsSystemsManagerCompliance48LightSvg from './Res_AWS-Systems-Manager_Compliance_48_Light.svg';
import _resAwsSystemsManagerDocuments48LightSvg from './Res_AWS-Systems-Manager_Documents_48_Light.svg';
import _resAwsSystemsManagerInventory48LightSvg from './Res_AWS-Systems-Manager_Inventory_48_Light.svg';
import _resAwsSystemsManagerMaintenanceWindows48LightSvg from './Res_AWS-Systems-Manager_Maintenance-Windows_48_Light.svg';
import _resAwsSystemsManagerOpsCenter48LightSvg from './Res_AWS-Systems-Manager_OpsCenter_48_Light.svg';
import _resAwsSystemsManagerParameterStore48LightSvg from './Res_AWS-Systems-Manager_Parameter-Store_48_Light.svg';
import _resAwsSystemsManagerPatchManager48LightSvg from './Res_AWS-Systems-Manager_Patch-Manager_48_Light.svg';
import _resAwsSystemsManagerRunCommand48LightSvg from './Res_AWS-Systems-Manager_Run-Command_48_Light.svg';
import _resAwsSystemsManagerSessionManager48LightSvg from './Res_AWS-Systems-Manager_Session-Manager_48_Light.svg';
import _resAwsSystemsManagerStateManager48LightSvg from './Res_AWS-Systems-Manager_State-Manager_48_Light.svg';
import _resAwsTrustedAdvisorChecklistCost48LightSvg from './Res_AWS-Trusted-Advisor_Checklist-Cost_48_Light.svg';
import _resAwsTrustedAdvisorChecklistFaultTolerant48LightSvg from './Res_AWS-Trusted-Advisor_Checklist-Fault-Tolerant_48_Light.svg';
import _resAwsTrustedAdvisorChecklistPerformance48LightSvg from './Res_AWS-Trusted-Advisor_Checklist-Performance_48_Light.svg';
import _resAwsTrustedAdvisorChecklistSecurity48LightSvg from './Res_AWS-Trusted-Advisor_Checklist-Security_48_Light.svg';
import _resAwsTrustedAdvisorChecklist48LightSvg from './Res_AWS-Trusted-Advisor_Checklist_48_Light.svg';
import _resAmazonCloudWatchAlarm48LightSvg from './Res_Amazon-CloudWatch_Alarm_48_Light.svg';
import _resAmazonCloudWatchEventEventBased48LightSvg from './Res_Amazon-CloudWatch_Event-Event-Based_48_Light.svg';
import _resAmazonCloudWatchEventTimeBased48LightSvg from './Res_Amazon-CloudWatch_Event-Time-Based_48_Light.svg';
import _resAmazonCloudWatchEvidently48LightSvg from './Res_Amazon-CloudWatch_Evidently_48_Light.svg';
import _resAmazonCloudWatchLogs48LightSvg from './Res_Amazon-CloudWatch_Logs_48_Light.svg';
import _resAmazonCloudWatchMetricsInsights48LightSvg from './Res_Amazon-CloudWatch_Metrics-Insights_48_Light.svg';
import _resAmazonCloudWatchRum48LightSvg from './Res_Amazon-CloudWatch_RUM_48_Light.svg';
import _resAmazonCloudWatchRule48LightSvg from './Res_Amazon-CloudWatch_Rule_48_Light.svg';
import _resAmazonCloudWatchSynthetics48LightSvg from './Res_Amazon-CloudWatch_Synthetics_48_Light.svg';

export const resAwsCloudFormationChangeSet48LightSvg = { id: "resAwsCloudFormationChangeSet48LightSvg", name: "AWS CloudFormation / Change Set", icon: _resAwsCloudFormationChangeSet48LightSvg };
export const resAwsCloudFormationStack48LightSvg = { id: "resAwsCloudFormationStack48LightSvg", name: "AWS CloudFormation / Stack", icon: _resAwsCloudFormationStack48LightSvg };
export const resAwsCloudFormationTemplate48LightSvg = { id: "resAwsCloudFormationTemplate48LightSvg", name: "AWS CloudFormation / Template", icon: _resAwsCloudFormationTemplate48LightSvg };
export const resAwsLicenseManagerApplicationDiscovery48LightSvg = { id: "resAwsLicenseManagerApplicationDiscovery48LightSvg", name: "AWS License Manager / Application Discovery", icon: _resAwsLicenseManagerApplicationDiscovery48LightSvg };
export const resAwsLicenseManagerLicenseBlending48LightSvg = { id: "resAwsLicenseManagerLicenseBlending48LightSvg", name: "AWS License Manager / License Blending", icon: _resAwsLicenseManagerLicenseBlending48LightSvg };
export const resAwsOpsWorksApps48LightSvg = { id: "resAwsOpsWorksApps48LightSvg", name: "AWS OpsWorks / Apps", icon: _resAwsOpsWorksApps48LightSvg };
export const resAwsOpsWorksDeployments48LightSvg = { id: "resAwsOpsWorksDeployments48LightSvg", name: "AWS OpsWorks / Deployments", icon: _resAwsOpsWorksDeployments48LightSvg };
export const resAwsOpsWorksInstances48LightSvg = { id: "resAwsOpsWorksInstances48LightSvg", name: "AWS OpsWorks / Instances", icon: _resAwsOpsWorksInstances48LightSvg };
export const resAwsOpsWorksLayers48LightSvg = { id: "resAwsOpsWorksLayers48LightSvg", name: "AWS OpsWorks / Layers", icon: _resAwsOpsWorksLayers48LightSvg };
export const resAwsOpsWorksMonitoring48LightSvg = { id: "resAwsOpsWorksMonitoring48LightSvg", name: "AWS OpsWorks / Monitoring", icon: _resAwsOpsWorksMonitoring48LightSvg };
export const resAwsOpsWorksPermissions48LightSvg = { id: "resAwsOpsWorksPermissions48LightSvg", name: "AWS OpsWorks / Permissions", icon: _resAwsOpsWorksPermissions48LightSvg };
export const resAwsOpsWorksResources48LightSvg = { id: "resAwsOpsWorksResources48LightSvg", name: "AWS OpsWorks / Resources", icon: _resAwsOpsWorksResources48LightSvg };
export const resAwsOpsWorksStack248LightSvg = { id: "resAwsOpsWorksStack248LightSvg", name: "AWS OpsWorks / Stack2", icon: _resAwsOpsWorksStack248LightSvg };
export const resAwsOrganizationsAccount48LightSvg = { id: "resAwsOrganizationsAccount48LightSvg", name: "AWS Organizations / Account", icon: _resAwsOrganizationsAccount48LightSvg };
export const resAwsOrganizationsManagementAccount48LightSvg = { id: "resAwsOrganizationsManagementAccount48LightSvg", name: "AWS Organizations / Management Account", icon: _resAwsOrganizationsManagementAccount48LightSvg };
export const resAwsOrganizationsOrganizationalUnit48LightSvg = { id: "resAwsOrganizationsOrganizationalUnit48LightSvg", name: "AWS Organizations / Organizational Unit", icon: _resAwsOrganizationsOrganizationalUnit48LightSvg };
export const resAwsSystemsManagerAutomation48LightSvg = { id: "resAwsSystemsManagerAutomation48LightSvg", name: "AWS Systems Manager / Automation", icon: _resAwsSystemsManagerAutomation48LightSvg };
export const resAwsSystemsManagerChangeCalendar48LightSvg = { id: "resAwsSystemsManagerChangeCalendar48LightSvg", name: "AWS Systems Manager / Change Calendar", icon: _resAwsSystemsManagerChangeCalendar48LightSvg };
export const resAwsSystemsManagerChangeManager48LightSvg = { id: "resAwsSystemsManagerChangeManager48LightSvg", name: "AWS Systems Manager / Change Manager", icon: _resAwsSystemsManagerChangeManager48LightSvg };
export const resAwsSystemsManagerCompliance48LightSvg = { id: "resAwsSystemsManagerCompliance48LightSvg", name: "AWS Systems Manager / Compliance", icon: _resAwsSystemsManagerCompliance48LightSvg };
export const resAwsSystemsManagerDocuments48LightSvg = { id: "resAwsSystemsManagerDocuments48LightSvg", name: "AWS Systems Manager / Documents", icon: _resAwsSystemsManagerDocuments48LightSvg };
export const resAwsSystemsManagerInventory48LightSvg = { id: "resAwsSystemsManagerInventory48LightSvg", name: "AWS Systems Manager / Inventory", icon: _resAwsSystemsManagerInventory48LightSvg };
export const resAwsSystemsManagerMaintenanceWindows48LightSvg = { id: "resAwsSystemsManagerMaintenanceWindows48LightSvg", name: "AWS Systems Manager / Maintenance Windows", icon: _resAwsSystemsManagerMaintenanceWindows48LightSvg };
export const resAwsSystemsManagerOpsCenter48LightSvg = { id: "resAwsSystemsManagerOpsCenter48LightSvg", name: "AWS Systems Manager / OpsCenter", icon: _resAwsSystemsManagerOpsCenter48LightSvg };
export const resAwsSystemsManagerParameterStore48LightSvg = { id: "resAwsSystemsManagerParameterStore48LightSvg", name: "AWS Systems Manager / Parameter Store", icon: _resAwsSystemsManagerParameterStore48LightSvg };
export const resAwsSystemsManagerPatchManager48LightSvg = { id: "resAwsSystemsManagerPatchManager48LightSvg", name: "AWS Systems Manager / Patch Manager", icon: _resAwsSystemsManagerPatchManager48LightSvg };
export const resAwsSystemsManagerRunCommand48LightSvg = { id: "resAwsSystemsManagerRunCommand48LightSvg", name: "AWS Systems Manager / Run Command", icon: _resAwsSystemsManagerRunCommand48LightSvg };
export const resAwsSystemsManagerSessionManager48LightSvg = { id: "resAwsSystemsManagerSessionManager48LightSvg", name: "AWS Systems Manager / Session Manager", icon: _resAwsSystemsManagerSessionManager48LightSvg };
export const resAwsSystemsManagerStateManager48LightSvg = { id: "resAwsSystemsManagerStateManager48LightSvg", name: "AWS Systems Manager / State Manager", icon: _resAwsSystemsManagerStateManager48LightSvg };
export const resAwsTrustedAdvisorChecklistCost48LightSvg = { id: "resAwsTrustedAdvisorChecklistCost48LightSvg", name: "AWS Trusted Advisor / Checklist Cost", icon: _resAwsTrustedAdvisorChecklistCost48LightSvg };
export const resAwsTrustedAdvisorChecklistFaultTolerant48LightSvg = { id: "resAwsTrustedAdvisorChecklistFaultTolerant48LightSvg", name: "AWS Trusted Advisor / Checklist Fault Tolerant", icon: _resAwsTrustedAdvisorChecklistFaultTolerant48LightSvg };
export const resAwsTrustedAdvisorChecklistPerformance48LightSvg = { id: "resAwsTrustedAdvisorChecklistPerformance48LightSvg", name: "AWS Trusted Advisor / Checklist Performance", icon: _resAwsTrustedAdvisorChecklistPerformance48LightSvg };
export const resAwsTrustedAdvisorChecklistSecurity48LightSvg = { id: "resAwsTrustedAdvisorChecklistSecurity48LightSvg", name: "AWS Trusted Advisor / Checklist Security", icon: _resAwsTrustedAdvisorChecklistSecurity48LightSvg };
export const resAwsTrustedAdvisorChecklist48LightSvg = { id: "resAwsTrustedAdvisorChecklist48LightSvg", name: "AWS Trusted Advisor / Checklist", icon: _resAwsTrustedAdvisorChecklist48LightSvg };
export const resAmazonCloudWatchAlarm48LightSvg = { id: "resAmazonCloudWatchAlarm48LightSvg", name: "Amazon CloudWatch / Alarm", icon: _resAmazonCloudWatchAlarm48LightSvg };
export const resAmazonCloudWatchEventEventBased48LightSvg = { id: "resAmazonCloudWatchEventEventBased48LightSvg", name: "Amazon CloudWatch / Event Event Based", icon: _resAmazonCloudWatchEventEventBased48LightSvg };
export const resAmazonCloudWatchEventTimeBased48LightSvg = { id: "resAmazonCloudWatchEventTimeBased48LightSvg", name: "Amazon CloudWatch / Event Time Based", icon: _resAmazonCloudWatchEventTimeBased48LightSvg };
export const resAmazonCloudWatchEvidently48LightSvg = { id: "resAmazonCloudWatchEvidently48LightSvg", name: "Amazon CloudWatch / Evidently", icon: _resAmazonCloudWatchEvidently48LightSvg };
export const resAmazonCloudWatchLogs48LightSvg = { id: "resAmazonCloudWatchLogs48LightSvg", name: "Amazon CloudWatch / Logs", icon: _resAmazonCloudWatchLogs48LightSvg };
export const resAmazonCloudWatchMetricsInsights48LightSvg = { id: "resAmazonCloudWatchMetricsInsights48LightSvg", name: "Amazon CloudWatch / Metrics Insights", icon: _resAmazonCloudWatchMetricsInsights48LightSvg };
export const resAmazonCloudWatchRum48LightSvg = { id: "resAmazonCloudWatchRum48LightSvg", name: "Amazon CloudWatch / RUM", icon: _resAmazonCloudWatchRum48LightSvg };
export const resAmazonCloudWatchRule48LightSvg = { id: "resAmazonCloudWatchRule48LightSvg", name: "Amazon CloudWatch / Rule", icon: _resAmazonCloudWatchRule48LightSvg };
export const resAmazonCloudWatchSynthetics48LightSvg = { id: "resAmazonCloudWatchSynthetics48LightSvg", name: "Amazon CloudWatch / Synthetics", icon: _resAmazonCloudWatchSynthetics48LightSvg };
