import _archAwsElementalAppliancesSoftware32Svg from './Arch_AWS-Elemental-Appliances-&-Software_32.svg';
import _archAwsElementalConductor32Svg from './Arch_AWS-Elemental-Conductor_32.svg';
import _archAwsElementalDelta32Svg from './Arch_AWS-Elemental-Delta_32.svg';
import _archAwsElementalLink32Svg from './Arch_AWS-Elemental-Link_32.svg';
import _archAwsElementalLive32Svg from './Arch_AWS-Elemental-Live_32.svg';
import _archAwsElementalMediaConnect32Svg from './Arch_AWS-Elemental-MediaConnect_32.svg';
import _archAwsElementalMediaConvert32Svg from './Arch_AWS-Elemental-MediaConvert_32.svg';
import _archAwsElementalMediaLive32Svg from './Arch_AWS-Elemental-MediaLive_32.svg';
import _archAwsElementalMediaPackage32Svg from './Arch_AWS-Elemental-MediaPackage_32.svg';
import _archAwsElementalMediaStore32Svg from './Arch_AWS-Elemental-MediaStore_32.svg';
import _archAwsElementalMediaTailor32Svg from './Arch_AWS-Elemental-MediaTailor_32.svg';
import _archAwsElementalServer32Svg from './Arch_AWS-Elemental-Server_32.svg';
import _archAmazonElasticTranscoder32Svg from './Arch_Amazon-Elastic-Transcoder_32.svg';
import _archAmazonInteractiveVideoService32Svg from './Arch_Amazon-Interactive-Video-Service_32.svg';
import _archAmazonKinesisVideoStreams32Svg from './Arch_Amazon-Kinesis-Video-Streams_32.svg';
import _archAmazonNimbleStudio32Svg from './Arch_Amazon-Nimble-Studio_32.svg';

export const archAwsElementalAppliancesSoftware32Svg = { id: "archAwsElementalAppliancesSoftware32Svg", name: "AWS Elemental Appliances & Software", icon: _archAwsElementalAppliancesSoftware32Svg };
export const archAwsElementalConductor32Svg = { id: "archAwsElementalConductor32Svg", name: "AWS Elemental Conductor", icon: _archAwsElementalConductor32Svg };
export const archAwsElementalDelta32Svg = { id: "archAwsElementalDelta32Svg", name: "AWS Elemental Delta", icon: _archAwsElementalDelta32Svg };
export const archAwsElementalLink32Svg = { id: "archAwsElementalLink32Svg", name: "AWS Elemental Link", icon: _archAwsElementalLink32Svg };
export const archAwsElementalLive32Svg = { id: "archAwsElementalLive32Svg", name: "AWS Elemental Live", icon: _archAwsElementalLive32Svg };
export const archAwsElementalMediaConnect32Svg = { id: "archAwsElementalMediaConnect32Svg", name: "AWS Elemental MediaConnect", icon: _archAwsElementalMediaConnect32Svg };
export const archAwsElementalMediaConvert32Svg = { id: "archAwsElementalMediaConvert32Svg", name: "AWS Elemental MediaConvert", icon: _archAwsElementalMediaConvert32Svg };
export const archAwsElementalMediaLive32Svg = { id: "archAwsElementalMediaLive32Svg", name: "AWS Elemental MediaLive", icon: _archAwsElementalMediaLive32Svg };
export const archAwsElementalMediaPackage32Svg = { id: "archAwsElementalMediaPackage32Svg", name: "AWS Elemental MediaPackage", icon: _archAwsElementalMediaPackage32Svg };
export const archAwsElementalMediaStore32Svg = { id: "archAwsElementalMediaStore32Svg", name: "AWS Elemental MediaStore", icon: _archAwsElementalMediaStore32Svg };
export const archAwsElementalMediaTailor32Svg = { id: "archAwsElementalMediaTailor32Svg", name: "AWS Elemental MediaTailor", icon: _archAwsElementalMediaTailor32Svg };
export const archAwsElementalServer32Svg = { id: "archAwsElementalServer32Svg", name: "AWS Elemental Server", icon: _archAwsElementalServer32Svg };
export const archAmazonElasticTranscoder32Svg = { id: "archAmazonElasticTranscoder32Svg", name: "Amazon Elastic Transcoder", icon: _archAmazonElasticTranscoder32Svg };
export const archAmazonInteractiveVideoService32Svg = { id: "archAmazonInteractiveVideoService32Svg", name: "Amazon Interactive Video Service", icon: _archAmazonInteractiveVideoService32Svg };
export const archAmazonKinesisVideoStreams32Svg = { id: "archAmazonKinesisVideoStreams32Svg", name: "Amazon Kinesis Video Streams", icon: _archAmazonKinesisVideoStreams32Svg };
export const archAmazonNimbleStudio32Svg = { id: "archAmazonNimbleStudio32Svg", name: "Amazon Nimble Studio", icon: _archAmazonNimbleStudio32Svg };
