import _archAwsAppRunner48Svg from './Arch_AWS-App-Runner_48.svg';
import _archAwsBatch48Svg from './Arch_AWS-Batch_48.svg';
import _archAwsComputeOptimizer48Svg from './Arch_AWS-Compute-Optimizer_48.svg';
import _archAwsElasticBeanstalk48Svg from './Arch_AWS-Elastic-Beanstalk_48.svg';
import _archAwsFargate48Svg from './Arch_AWS-Fargate_48.svg';
import _archAwsLambda48Svg from './Arch_AWS-Lambda_48.svg';
import _archAwsLocalZones48Svg from './Arch_AWS-Local-Zones_48.svg';
import _archAwsNitroEnclaves48Svg from './Arch_AWS-Nitro-Enclaves_48.svg';
import _archAwsOutpostsFamily48Svg from './Arch_AWS-Outposts-family_48.svg';
import _archAwsOutpostsRack48Svg from './Arch_AWS-Outposts-rack_48.svg';
import _archAwsOutpostsServers48Svg from './Arch_AWS-Outposts-servers_48.svg';
import _archAwsParallelCluster48Svg from './Arch_AWS-ParallelCluster_48.svg';
import _archAwsServerlessApplicationRepository48Svg from './Arch_AWS-Serverless-Application-Repository_48.svg';
import _archAwsThinkboxDeadline48Svg from './Arch_AWS-Thinkbox-Deadline_48.svg';
import _archAwsThinkboxFrost48Svg from './Arch_AWS-Thinkbox-Frost_48.svg';
import _archAwsThinkboxKrakatoa48Svg from './Arch_AWS-Thinkbox-Krakatoa_48.svg';
import _archAwsThinkboxSequoia48Svg from './Arch_AWS-Thinkbox-Sequoia_48.svg';
import _archAwsThinkboxStoke48Svg from './Arch_AWS-Thinkbox-Stoke_48.svg';
import _archAwsThinkboxXmesh48Svg from './Arch_AWS-Thinkbox-XMesh_48.svg';
import _archAwsWavelength48Svg from './Arch_AWS-Wavelength_48.svg';
import _archAmazonEc2AutoScaling48Svg from './Arch_Amazon-EC2-Auto-Scaling_48.svg';
import _archAmazonEc2ImageBuilder48Svg from './Arch_Amazon-EC2-Image-Builder_48.svg';
import _archAmazonEc2M5N48Svg from './Arch_Amazon-EC2-M5n_48.svg';
import _archAmazonEc2R5N48Svg from './Arch_Amazon-EC2-R5n_48.svg';
import _archAmazonEc248Svg from './Arch_Amazon-EC2_48.svg';
import _archAmazonElasticContainerKubernetes48Svg from './Arch_Amazon-Elastic-Container-Kubernetes_48.svg';
import _archAmazonElasticContainerRegistry48Svg from './Arch_Amazon-Elastic-Container-Registry_48.svg';
import _archAmazonElasticContainerService48Svg from './Arch_Amazon-Elastic-Container-Service_48.svg';
import _archAmazonGenomicsCli48Svg from './Arch_Amazon-Genomics-CLI_48.svg';
import _archAmazonLightsail48Svg from './Arch_Amazon-Lightsail_48.svg';
import _archBottlerocket48Svg from './Arch_Bottlerocket_48.svg';
import _archElasticFabricAdapter48Svg from './Arch_Elastic-Fabric-Adapter_48.svg';
import _archNiceDcv48Svg from './Arch_NICE-DCV_48.svg';
import _archNiceEnginFrame48Svg from './Arch_NICE-EnginFrame_48.svg';
import _archVMwareCloudOnAws48Svg from './Arch_VMware-Cloud-on-AWS_48.svg';

export const archAwsAppRunner48Svg = { id: "archAwsAppRunner48Svg", name: "AWS App Runner", icon: _archAwsAppRunner48Svg };
export const archAwsBatch48Svg = { id: "archAwsBatch48Svg", name: "AWS Batch", icon: _archAwsBatch48Svg };
export const archAwsComputeOptimizer48Svg = { id: "archAwsComputeOptimizer48Svg", name: "AWS Compute Optimizer", icon: _archAwsComputeOptimizer48Svg };
export const archAwsElasticBeanstalk48Svg = { id: "archAwsElasticBeanstalk48Svg", name: "AWS Elastic Beanstalk", icon: _archAwsElasticBeanstalk48Svg };
export const archAwsFargate48Svg = { id: "archAwsFargate48Svg", name: "AWS Fargate", icon: _archAwsFargate48Svg };
export const archAwsLambda48Svg = { id: "archAwsLambda48Svg", name: "AWS Lambda", icon: _archAwsLambda48Svg };
export const archAwsLocalZones48Svg = { id: "archAwsLocalZones48Svg", name: "AWS Local Zones", icon: _archAwsLocalZones48Svg };
export const archAwsNitroEnclaves48Svg = { id: "archAwsNitroEnclaves48Svg", name: "AWS Nitro Enclaves", icon: _archAwsNitroEnclaves48Svg };
export const archAwsOutpostsFamily48Svg = { id: "archAwsOutpostsFamily48Svg", name: "AWS Outposts family", icon: _archAwsOutpostsFamily48Svg };
export const archAwsOutpostsRack48Svg = { id: "archAwsOutpostsRack48Svg", name: "AWS Outposts rack", icon: _archAwsOutpostsRack48Svg };
export const archAwsOutpostsServers48Svg = { id: "archAwsOutpostsServers48Svg", name: "AWS Outposts servers", icon: _archAwsOutpostsServers48Svg };
export const archAwsParallelCluster48Svg = { id: "archAwsParallelCluster48Svg", name: "AWS ParallelCluster", icon: _archAwsParallelCluster48Svg };
export const archAwsServerlessApplicationRepository48Svg = { id: "archAwsServerlessApplicationRepository48Svg", name: "AWS Serverless Application Repository", icon: _archAwsServerlessApplicationRepository48Svg };
export const archAwsThinkboxDeadline48Svg = { id: "archAwsThinkboxDeadline48Svg", name: "AWS Thinkbox Deadline", icon: _archAwsThinkboxDeadline48Svg };
export const archAwsThinkboxFrost48Svg = { id: "archAwsThinkboxFrost48Svg", name: "AWS Thinkbox Frost", icon: _archAwsThinkboxFrost48Svg };
export const archAwsThinkboxKrakatoa48Svg = { id: "archAwsThinkboxKrakatoa48Svg", name: "AWS Thinkbox Krakatoa", icon: _archAwsThinkboxKrakatoa48Svg };
export const archAwsThinkboxSequoia48Svg = { id: "archAwsThinkboxSequoia48Svg", name: "AWS Thinkbox Sequoia", icon: _archAwsThinkboxSequoia48Svg };
export const archAwsThinkboxStoke48Svg = { id: "archAwsThinkboxStoke48Svg", name: "AWS Thinkbox Stoke", icon: _archAwsThinkboxStoke48Svg };
export const archAwsThinkboxXmesh48Svg = { id: "archAwsThinkboxXmesh48Svg", name: "AWS Thinkbox XMesh", icon: _archAwsThinkboxXmesh48Svg };
export const archAwsWavelength48Svg = { id: "archAwsWavelength48Svg", name: "AWS Wavelength", icon: _archAwsWavelength48Svg };
export const archAmazonEc2AutoScaling48Svg = { id: "archAmazonEc2AutoScaling48Svg", name: "Amazon EC2 Auto Scaling", icon: _archAmazonEc2AutoScaling48Svg };
export const archAmazonEc2ImageBuilder48Svg = { id: "archAmazonEc2ImageBuilder48Svg", name: "Amazon EC2 Image Builder", icon: _archAmazonEc2ImageBuilder48Svg };
export const archAmazonEc2M5N48Svg = { id: "archAmazonEc2M5N48Svg", name: "Amazon EC2 M5n", icon: _archAmazonEc2M5N48Svg };
export const archAmazonEc2R5N48Svg = { id: "archAmazonEc2R5N48Svg", name: "Amazon EC2 R5n", icon: _archAmazonEc2R5N48Svg };
export const archAmazonEc248Svg = { id: "archAmazonEc248Svg", name: "Amazon EC2", icon: _archAmazonEc248Svg };
export const archAmazonElasticContainerKubernetes48Svg = { id: "archAmazonElasticContainerKubernetes48Svg", name: "Amazon Elastic Container Kubernetes", icon: _archAmazonElasticContainerKubernetes48Svg };
export const archAmazonElasticContainerRegistry48Svg = { id: "archAmazonElasticContainerRegistry48Svg", name: "Amazon Elastic Container Registry", icon: _archAmazonElasticContainerRegistry48Svg };
export const archAmazonElasticContainerService48Svg = { id: "archAmazonElasticContainerService48Svg", name: "Amazon Elastic Container Service", icon: _archAmazonElasticContainerService48Svg };
export const archAmazonGenomicsCli48Svg = { id: "archAmazonGenomicsCli48Svg", name: "Amazon Genomics CLI", icon: _archAmazonGenomicsCli48Svg };
export const archAmazonLightsail48Svg = { id: "archAmazonLightsail48Svg", name: "Amazon Lightsail", icon: _archAmazonLightsail48Svg };
export const archBottlerocket48Svg = { id: "archBottlerocket48Svg", name: "Bottlerocket", icon: _archBottlerocket48Svg };
export const archElasticFabricAdapter48Svg = { id: "archElasticFabricAdapter48Svg", name: "Elastic Fabric Adapter", icon: _archElasticFabricAdapter48Svg };
export const archNiceDcv48Svg = { id: "archNiceDcv48Svg", name: "NICE DCV", icon: _archNiceDcv48Svg };
export const archNiceEnginFrame48Svg = { id: "archNiceEnginFrame48Svg", name: "NICE EnginFrame", icon: _archNiceEnginFrame48Svg };
export const archVMwareCloudOnAws48Svg = { id: "archVMwareCloudOnAws48Svg", name: "VMware Cloud on AWS", icon: _archVMwareCloudOnAws48Svg };
