import _resAwsDataExchangeForApIs48DarkSvg from './Res_AWS-Data-Exchange-for-APIs_48_Dark.svg';
import _resAwsGlueCrawler48DarkSvg from './Res_AWS-Glue_Crawler_48_Dark.svg';
import _resAwsGlueDataCatalog48DarkSvg from './Res_AWS-Glue_Data-Catalog_48_Dark.svg';
import _resAwsLakeFormationDataLake48DarkSvg from './Res_AWS-Lake-Formation_Data-Lake_48_Dark.svg';
import _resAmazonCloudSearchSearchDocuments48DarkSvg from './Res_Amazon-CloudSearch_Search-Documents_48_Dark.svg';
import _resAmazonEmrCluster48DarkSvg from './Res_Amazon-EMR_Cluster_48_Dark.svg';
import _resAmazonEmrEmrEngine48DarkSvg from './Res_Amazon-EMR_EMR-Engine_48_Dark.svg';
import _resAmazonEmrHdfsCluster48DarkSvg from './Res_Amazon-EMR_HDFS-Cluster_48_Dark.svg';
import _resAmazonMskAmazonMskConnect48DarkSvg from './Res_Amazon-MSK_Amazon-MSK-Connect_48_Dark.svg';
import _resAmazonRedshiftDenseComputeNode48DarkSvg from './Res_Amazon-Redshift_Dense-Compute-Node_48_Dark.svg';
import _resAmazonRedshiftDenseStorageNode48DarkSvg from './Res_Amazon-Redshift_Dense-Storage-Node_48_Dark.svg';
import _resAmazonRedshiftMl48DarkSvg from './Res_Amazon-Redshift_ML_48_Dark.svg';
import _resAmazonRedshiftRa348DarkSvg from './Res_Amazon-Redshift_RA3_48_Dark.svg';

export const resAwsDataExchangeForApIs48DarkSvg = { id: "resAwsDataExchangeForApIs48DarkSvg", name: "AWS Data Exchange for APIs", icon: _resAwsDataExchangeForApIs48DarkSvg };
export const resAwsGlueCrawler48DarkSvg = { id: "resAwsGlueCrawler48DarkSvg", name: "AWS Glue | Crawler", icon: _resAwsGlueCrawler48DarkSvg };
export const resAwsGlueDataCatalog48DarkSvg = { id: "resAwsGlueDataCatalog48DarkSvg", name: "AWS Glue | Data Catalog", icon: _resAwsGlueDataCatalog48DarkSvg };
export const resAwsLakeFormationDataLake48DarkSvg = { id: "resAwsLakeFormationDataLake48DarkSvg", name: "AWS Lake Formation | Data Lake", icon: _resAwsLakeFormationDataLake48DarkSvg };
export const resAmazonCloudSearchSearchDocuments48DarkSvg = { id: "resAmazonCloudSearchSearchDocuments48DarkSvg", name: "Amazon CloudSearch | Search Documents", icon: _resAmazonCloudSearchSearchDocuments48DarkSvg };
export const resAmazonEmrCluster48DarkSvg = { id: "resAmazonEmrCluster48DarkSvg", name: "Amazon EMR | Cluster", icon: _resAmazonEmrCluster48DarkSvg };
export const resAmazonEmrEmrEngine48DarkSvg = { id: "resAmazonEmrEmrEngine48DarkSvg", name: "Amazon EMR | EMR Engine", icon: _resAmazonEmrEmrEngine48DarkSvg };
export const resAmazonEmrHdfsCluster48DarkSvg = { id: "resAmazonEmrHdfsCluster48DarkSvg", name: "Amazon EMR | HDFS Cluster", icon: _resAmazonEmrHdfsCluster48DarkSvg };
export const resAmazonMskAmazonMskConnect48DarkSvg = { id: "resAmazonMskAmazonMskConnect48DarkSvg", name: "Amazon MSK | Amazon MSK Connect", icon: _resAmazonMskAmazonMskConnect48DarkSvg };
export const resAmazonRedshiftDenseComputeNode48DarkSvg = { id: "resAmazonRedshiftDenseComputeNode48DarkSvg", name: "Amazon Redshift | Dense Compute Node", icon: _resAmazonRedshiftDenseComputeNode48DarkSvg };
export const resAmazonRedshiftDenseStorageNode48DarkSvg = { id: "resAmazonRedshiftDenseStorageNode48DarkSvg", name: "Amazon Redshift | Dense Storage Node", icon: _resAmazonRedshiftDenseStorageNode48DarkSvg };
export const resAmazonRedshiftMl48DarkSvg = { id: "resAmazonRedshiftMl48DarkSvg", name: "Amazon Redshift | ML", icon: _resAmazonRedshiftMl48DarkSvg };
export const resAmazonRedshiftRa348DarkSvg = { id: "resAmazonRedshiftRa348DarkSvg", name: "Amazon Redshift | RA3", icon: _resAmazonRedshiftRa348DarkSvg };
