import _archAwsAppConfig48Svg from './Arch_AWS-AppConfig_48.svg';
import _archAwsApplicationAutoScaling48Svg from './Arch_AWS-Application-Auto-Scaling_48.svg';
import _archAwsAutoScaling48Svg from './Arch_AWS-Auto-Scaling_48.svg';
import _archAwsBackintAgent48Svg from './Arch_AWS-Backint-Agent_48.svg';
import _archAwsChatbot48Svg from './Arch_AWS-Chatbot_48.svg';
import _archAwsCloudFormation48Svg from './Arch_AWS-CloudFormation_48.svg';
import _archAwsCloudTrail48Svg from './Arch_AWS-CloudTrail_48.svg';
import _archAwsConfig48Svg from './Arch_AWS-Config_48.svg';
import _archAwsControlTower48Svg from './Arch_AWS-Control-Tower_48.svg';
import _archAwsDistroForOpenTelemetry48Svg from './Arch_AWS-Distro-for-OpenTelemetry_48.svg';
import _archAwsFaultInjectionSimulator48Svg from './Arch_AWS-Fault-Injection-Simulator_48.svg';
import _archAwsLaunchWizard48Svg from './Arch_AWS-Launch-Wizard_48.svg';
import _archAwsLicenseManager48Svg from './Arch_AWS-License-Manager_48.svg';
import _archAwsManagementConsole48Svg from './Arch_AWS-Management-Console_48.svg';
import _archAwsOpsWorks48Svg from './Arch_AWS-OpsWorks_48.svg';
import _archAwsOrganizations48Svg from './Arch_AWS-Organizations_48.svg';
import _archAwsPersonalHealthDashboard48Svg from './Arch_AWS-Personal-Health-Dashboard_48.svg';
import _archAwsProton48Svg from './Arch_AWS-Proton_48.svg';
import _archAwsResilienceHub48Svg from './Arch_AWS-Resilience-Hub_48.svg';
import _archAwsServiceCatalog48Svg from './Arch_AWS-Service-Catalog_48.svg';
import _archAwsSystemsManagerIncidentManager48Svg from './Arch_AWS-Systems-Manager-Incident-Manager_48.svg';
import _archAwsSystemsManager48Svg from './Arch_AWS-Systems-Manager_48.svg';
import _archAwsTrustedAdvisor48Svg from './Arch_AWS-Trusted-Advisor_48.svg';
import _archAwsWellArchitectedTool48Svg from './Arch_AWS-Well-Architected-Tool_48.svg';
import _archAmazonCloudWatch48Svg from './Arch_Amazon-CloudWatch_48.svg';
import _archAmazonManagedGrafana48Svg from './Arch_Amazon-Managed-Grafana_48.svg';
import _archAmazonManagedServiceForPrometheus48Svg from './Arch_Amazon-Managed-Service-for-Prometheus_48.svg';

export const archAwsAppConfig48Svg = { id: "archAwsAppConfig48Svg", name: "AWS AppConfig", icon: _archAwsAppConfig48Svg };
export const archAwsApplicationAutoScaling48Svg = { id: "archAwsApplicationAutoScaling48Svg", name: "AWS Application Auto Scaling", icon: _archAwsApplicationAutoScaling48Svg };
export const archAwsAutoScaling48Svg = { id: "archAwsAutoScaling48Svg", name: "AWS Auto Scaling", icon: _archAwsAutoScaling48Svg };
export const archAwsBackintAgent48Svg = { id: "archAwsBackintAgent48Svg", name: "AWS Backint Agent", icon: _archAwsBackintAgent48Svg };
export const archAwsChatbot48Svg = { id: "archAwsChatbot48Svg", name: "AWS Chatbot", icon: _archAwsChatbot48Svg };
export const archAwsCloudFormation48Svg = { id: "archAwsCloudFormation48Svg", name: "AWS CloudFormation", icon: _archAwsCloudFormation48Svg };
export const archAwsCloudTrail48Svg = { id: "archAwsCloudTrail48Svg", name: "AWS CloudTrail", icon: _archAwsCloudTrail48Svg };
export const archAwsConfig48Svg = { id: "archAwsConfig48Svg", name: "AWS Config", icon: _archAwsConfig48Svg };
export const archAwsControlTower48Svg = { id: "archAwsControlTower48Svg", name: "AWS Control Tower", icon: _archAwsControlTower48Svg };
export const archAwsDistroForOpenTelemetry48Svg = { id: "archAwsDistroForOpenTelemetry48Svg", name: "AWS Distro for OpenTelemetry", icon: _archAwsDistroForOpenTelemetry48Svg };
export const archAwsFaultInjectionSimulator48Svg = { id: "archAwsFaultInjectionSimulator48Svg", name: "AWS Fault Injection Simulator", icon: _archAwsFaultInjectionSimulator48Svg };
export const archAwsLaunchWizard48Svg = { id: "archAwsLaunchWizard48Svg", name: "AWS Launch Wizard", icon: _archAwsLaunchWizard48Svg };
export const archAwsLicenseManager48Svg = { id: "archAwsLicenseManager48Svg", name: "AWS License Manager", icon: _archAwsLicenseManager48Svg };
export const archAwsManagementConsole48Svg = { id: "archAwsManagementConsole48Svg", name: "AWS Management Console", icon: _archAwsManagementConsole48Svg };
export const archAwsOpsWorks48Svg = { id: "archAwsOpsWorks48Svg", name: "AWS OpsWorks", icon: _archAwsOpsWorks48Svg };
export const archAwsOrganizations48Svg = { id: "archAwsOrganizations48Svg", name: "AWS Organizations", icon: _archAwsOrganizations48Svg };
export const archAwsPersonalHealthDashboard48Svg = { id: "archAwsPersonalHealthDashboard48Svg", name: "AWS Personal Health Dashboard", icon: _archAwsPersonalHealthDashboard48Svg };
export const archAwsProton48Svg = { id: "archAwsProton48Svg", name: "AWS Proton", icon: _archAwsProton48Svg };
export const archAwsResilienceHub48Svg = { id: "archAwsResilienceHub48Svg", name: "AWS Resilience Hub", icon: _archAwsResilienceHub48Svg };
export const archAwsServiceCatalog48Svg = { id: "archAwsServiceCatalog48Svg", name: "AWS Service Catalog", icon: _archAwsServiceCatalog48Svg };
export const archAwsSystemsManagerIncidentManager48Svg = { id: "archAwsSystemsManagerIncidentManager48Svg", name: "AWS Systems Manager Incident Manager", icon: _archAwsSystemsManagerIncidentManager48Svg };
export const archAwsSystemsManager48Svg = { id: "archAwsSystemsManager48Svg", name: "AWS Systems Manager", icon: _archAwsSystemsManager48Svg };
export const archAwsTrustedAdvisor48Svg = { id: "archAwsTrustedAdvisor48Svg", name: "AWS Trusted Advisor", icon: _archAwsTrustedAdvisor48Svg };
export const archAwsWellArchitectedTool48Svg = { id: "archAwsWellArchitectedTool48Svg", name: "AWS Well Architected Tool", icon: _archAwsWellArchitectedTool48Svg };
export const archAmazonCloudWatch48Svg = { id: "archAmazonCloudWatch48Svg", name: "Amazon CloudWatch", icon: _archAmazonCloudWatch48Svg };
export const archAmazonManagedGrafana48Svg = { id: "archAmazonManagedGrafana48Svg", name: "Amazon Managed Grafana", icon: _archAmazonManagedGrafana48Svg };
export const archAmazonManagedServiceForPrometheus48Svg = { id: "archAmazonManagedServiceForPrometheus48Svg", name: "Amazon Managed Service for Prometheus", icon: _archAmazonManagedServiceForPrometheus48Svg };
