import _archAwsCloudControlApi64Svg from './Arch_AWS-Cloud-Control-API_64.svg';
import _archAwsCloudDevelopmentKit64Svg from './Arch_AWS-Cloud-Development-Kit_64.svg';
import _archAwsCloud964Svg from './Arch_AWS-Cloud9_64.svg';
import _archAwsCloudShell64Svg from './Arch_AWS-CloudShell_64.svg';
import _archAwsCodeArtifact64Svg from './Arch_AWS-CodeArtifact_64.svg';
import _archAwsCodeBuild64Svg from './Arch_AWS-CodeBuild_64.svg';
import _archAwsCodeCommit64Svg from './Arch_AWS-CodeCommit_64.svg';
import _archAwsCodeDeploy64Svg from './Arch_AWS-CodeDeploy_64.svg';
import _archAwsCodePipeline64Svg from './Arch_AWS-CodePipeline_64.svg';
import _archAwsCodeStar64Svg from './Arch_AWS-CodeStar_64.svg';
import _archAwsCommandLineInterface64Svg from './Arch_AWS-Command-Line-Interface_64.svg';
import _archAwsToolsAndSdKs64Svg from './Arch_AWS-Tools-and-SDKs_64.svg';
import _archAwsXRay64Svg from './Arch_AWS-X-Ray_64.svg';
import _archAmazonCorretto64Svg from './Arch_Amazon-Corretto_64.svg';

export const archAwsCloudControlApi64Svg = { id: "archAwsCloudControlApi64Svg", name: "AWS Cloud Control API", icon: _archAwsCloudControlApi64Svg };
export const archAwsCloudDevelopmentKit64Svg = { id: "archAwsCloudDevelopmentKit64Svg", name: "AWS Cloud Development Kit", icon: _archAwsCloudDevelopmentKit64Svg };
export const archAwsCloud964Svg = { id: "archAwsCloud964Svg", name: "AWS Cloud9", icon: _archAwsCloud964Svg };
export const archAwsCloudShell64Svg = { id: "archAwsCloudShell64Svg", name: "AWS CloudShell", icon: _archAwsCloudShell64Svg };
export const archAwsCodeArtifact64Svg = { id: "archAwsCodeArtifact64Svg", name: "AWS CodeArtifact", icon: _archAwsCodeArtifact64Svg };
export const archAwsCodeBuild64Svg = { id: "archAwsCodeBuild64Svg", name: "AWS CodeBuild", icon: _archAwsCodeBuild64Svg };
export const archAwsCodeCommit64Svg = { id: "archAwsCodeCommit64Svg", name: "AWS CodeCommit", icon: _archAwsCodeCommit64Svg };
export const archAwsCodeDeploy64Svg = { id: "archAwsCodeDeploy64Svg", name: "AWS CodeDeploy", icon: _archAwsCodeDeploy64Svg };
export const archAwsCodePipeline64Svg = { id: "archAwsCodePipeline64Svg", name: "AWS CodePipeline", icon: _archAwsCodePipeline64Svg };
export const archAwsCodeStar64Svg = { id: "archAwsCodeStar64Svg", name: "AWS CodeStar", icon: _archAwsCodeStar64Svg };
export const archAwsCommandLineInterface64Svg = { id: "archAwsCommandLineInterface64Svg", name: "AWS Command Line Interface", icon: _archAwsCommandLineInterface64Svg };
export const archAwsToolsAndSdKs64Svg = { id: "archAwsToolsAndSdKs64Svg", name: "AWS Tools and SDKs", icon: _archAwsToolsAndSdKs64Svg };
export const archAwsXRay64Svg = { id: "archAwsXRay64Svg", name: "AWS X Ray", icon: _archAwsXRay64Svg };
export const archAmazonCorretto64Svg = { id: "archAmazonCorretto64Svg", name: "Amazon Corretto", icon: _archAmazonCorretto64Svg };
