import _archAmazonApiGateway48Svg from './Arch_ Amazon-API-Gateway_48.svg';
import _archAwsAppSync48Svg from './Arch_AWS-AppSync_48.svg';
import _archAwsConsoleMobileApplication48Svg from './Arch_AWS-Console-Mobile-Application _48.svg';
import _archAwsExpressWorkflows48Svg from './Arch_AWS-Express-Workflows_48.svg';
import _archAwsStepFunctions48Svg from './Arch_AWS-Step-Functions_48.svg';
import _archAmazonAppFlow48Svg from './Arch_Amazon-AppFlow_48.svg';
import _archAmazonEventBridge48Svg from './Arch_Amazon-EventBridge_48.svg';
import _archAmazonMq48Svg from './Arch_Amazon-MQ_48.svg';
import _archAmazonManagedWorkflowsForApacheAirflow48Svg from './Arch_Amazon-Managed-Workflows-for-Apache-Airflow_48.svg';
import _archAmazonSimpleNotificationService48Svg from './Arch_Amazon-Simple-Notification-Service_48.svg';
import _archAmazonSimpleQueueService48Svg from './Arch_Amazon-Simple-Queue-Service_48.svg';

export const archAmazonApiGateway48Svg = { id: "archAmazonApiGateway48Svg", name: " Amazon API Gateway", icon: _archAmazonApiGateway48Svg };
export const archAwsAppSync48Svg = { id: "archAwsAppSync48Svg", name: "AWS AppSync", icon: _archAwsAppSync48Svg };
export const archAwsConsoleMobileApplication48Svg = { id: "archAwsConsoleMobileApplication48Svg", name: "AWS Console Mobile Application ", icon: _archAwsConsoleMobileApplication48Svg };
export const archAwsExpressWorkflows48Svg = { id: "archAwsExpressWorkflows48Svg", name: "AWS Express Workflows", icon: _archAwsExpressWorkflows48Svg };
export const archAwsStepFunctions48Svg = { id: "archAwsStepFunctions48Svg", name: "AWS Step Functions", icon: _archAwsStepFunctions48Svg };
export const archAmazonAppFlow48Svg = { id: "archAmazonAppFlow48Svg", name: "Amazon AppFlow", icon: _archAmazonAppFlow48Svg };
export const archAmazonEventBridge48Svg = { id: "archAmazonEventBridge48Svg", name: "Amazon EventBridge", icon: _archAmazonEventBridge48Svg };
export const archAmazonMq48Svg = { id: "archAmazonMq48Svg", name: "Amazon MQ", icon: _archAmazonMq48Svg };
export const archAmazonManagedWorkflowsForApacheAirflow48Svg = { id: "archAmazonManagedWorkflowsForApacheAirflow48Svg", name: "Amazon Managed Workflows for Apache Airflow", icon: _archAmazonManagedWorkflowsForApacheAirflow48Svg };
export const archAmazonSimpleNotificationService48Svg = { id: "archAmazonSimpleNotificationService48Svg", name: "Amazon Simple Notification Service", icon: _archAmazonSimpleNotificationService48Svg };
export const archAmazonSimpleQueueService48Svg = { id: "archAmazonSimpleQueueService48Svg", name: "Amazon Simple Queue Service", icon: _archAmazonSimpleQueueService48Svg };
