import _archAwsElementalAppliancesSoftware64Svg from './Arch_AWS-Elemental-Appliances-&-Software_64.svg';
import _archAwsElementalConductor64Svg from './Arch_AWS-Elemental-Conductor_64.svg';
import _archAwsElementalDelta64Svg from './Arch_AWS-Elemental-Delta_64.svg';
import _archAwsElementalLink64Svg from './Arch_AWS-Elemental-Link_64.svg';
import _archAwsElementalLive64Svg from './Arch_AWS-Elemental-Live_64.svg';
import _archAwsElementalMediaConnect64Svg from './Arch_AWS-Elemental-MediaConnect_64.svg';
import _archAwsElementalMediaConvert64Svg from './Arch_AWS-Elemental-MediaConvert_64.svg';
import _archAwsElementalMediaLive64Svg from './Arch_AWS-Elemental-MediaLive_64.svg';
import _archAwsElementalMediaPackage64Svg from './Arch_AWS-Elemental-MediaPackage_64.svg';
import _archAwsElementalMediaStore64Svg from './Arch_AWS-Elemental-MediaStore_64.svg';
import _archAwsElementalMediaTailor64Svg from './Arch_AWS-Elemental-MediaTailor_64.svg';
import _archAwsElementalServer64Svg from './Arch_AWS-Elemental-Server_64.svg';
import _archAmazonElasticTranscoder64Svg from './Arch_Amazon-Elastic-Transcoder_64.svg';
import _archAmazonInteractiveVideoService64Svg from './Arch_Amazon-Interactive-Video-Service_64.svg';
import _archAmazonKinesisVideoStreams64Svg from './Arch_Amazon-Kinesis-Video-Streams_64.svg';
import _archAmazonNimbleStudio64Svg from './Arch_Amazon-Nimble-Studio_64.svg';

export const archAwsElementalAppliancesSoftware64Svg = { id: "archAwsElementalAppliancesSoftware64Svg", name: "AWS Elemental Appliances & Software", icon: _archAwsElementalAppliancesSoftware64Svg };
export const archAwsElementalConductor64Svg = { id: "archAwsElementalConductor64Svg", name: "AWS Elemental Conductor", icon: _archAwsElementalConductor64Svg };
export const archAwsElementalDelta64Svg = { id: "archAwsElementalDelta64Svg", name: "AWS Elemental Delta", icon: _archAwsElementalDelta64Svg };
export const archAwsElementalLink64Svg = { id: "archAwsElementalLink64Svg", name: "AWS Elemental Link", icon: _archAwsElementalLink64Svg };
export const archAwsElementalLive64Svg = { id: "archAwsElementalLive64Svg", name: "AWS Elemental Live", icon: _archAwsElementalLive64Svg };
export const archAwsElementalMediaConnect64Svg = { id: "archAwsElementalMediaConnect64Svg", name: "AWS Elemental MediaConnect", icon: _archAwsElementalMediaConnect64Svg };
export const archAwsElementalMediaConvert64Svg = { id: "archAwsElementalMediaConvert64Svg", name: "AWS Elemental MediaConvert", icon: _archAwsElementalMediaConvert64Svg };
export const archAwsElementalMediaLive64Svg = { id: "archAwsElementalMediaLive64Svg", name: "AWS Elemental MediaLive", icon: _archAwsElementalMediaLive64Svg };
export const archAwsElementalMediaPackage64Svg = { id: "archAwsElementalMediaPackage64Svg", name: "AWS Elemental MediaPackage", icon: _archAwsElementalMediaPackage64Svg };
export const archAwsElementalMediaStore64Svg = { id: "archAwsElementalMediaStore64Svg", name: "AWS Elemental MediaStore", icon: _archAwsElementalMediaStore64Svg };
export const archAwsElementalMediaTailor64Svg = { id: "archAwsElementalMediaTailor64Svg", name: "AWS Elemental MediaTailor", icon: _archAwsElementalMediaTailor64Svg };
export const archAwsElementalServer64Svg = { id: "archAwsElementalServer64Svg", name: "AWS Elemental Server", icon: _archAwsElementalServer64Svg };
export const archAmazonElasticTranscoder64Svg = { id: "archAmazonElasticTranscoder64Svg", name: "Amazon Elastic Transcoder", icon: _archAmazonElasticTranscoder64Svg };
export const archAmazonInteractiveVideoService64Svg = { id: "archAmazonInteractiveVideoService64Svg", name: "Amazon Interactive Video Service", icon: _archAmazonInteractiveVideoService64Svg };
export const archAmazonKinesisVideoStreams64Svg = { id: "archAmazonKinesisVideoStreams64Svg", name: "Amazon Kinesis Video Streams", icon: _archAmazonKinesisVideoStreams64Svg };
export const archAmazonNimbleStudio64Svg = { id: "archAmazonNimbleStudio64Svg", name: "Amazon Nimble Studio", icon: _archAmazonNimbleStudio64Svg };
