import _resAwsCloudFormationChangeSet48DarkSvg from './Res_AWS-CloudFormation_Change-Set_48_Dark.svg';
import _resAwsCloudFormationStack48DarkSvg from './Res_AWS-CloudFormation_Stack_48_Dark.svg';
import _resAwsCloudFormationTemplate48DarkSvg from './Res_AWS-CloudFormation_Template_48_Dark.svg';
import _resAwsLicenseManagerApplicationDiscovery48DarkSvg from './Res_AWS-License-Manager_Application-Discovery_48_Dark.svg';
import _resAwsLicenseManagerLicenseBlending48DarkSvg from './Res_AWS-License-Manager_License-Blending_48_Dark.svg';
import _resAwsOpsWorksApps48DarkSvg from './Res_AWS-OpsWorks_Apps_48_Dark.svg';
import _resAwsOpsWorksDeployments48DarkSvg from './Res_AWS-OpsWorks_Deployments_48_Dark.svg';
import _resAwsOpsWorksInstances48DarkSvg from './Res_AWS-OpsWorks_Instances_48_Dark.svg';
import _resAwsOpsWorksLayers48DarkSvg from './Res_AWS-OpsWorks_Layers_48_Dark.svg';
import _resAwsOpsWorksMonitoring48DarkSvg from './Res_AWS-OpsWorks_Monitoring_48_Dark.svg';
import _resAwsOpsWorksPermissions48DarkSvg from './Res_AWS-OpsWorks_Permissions_48_Dark.svg';
import _resAwsOpsWorksResources48DarkSvg from './Res_AWS-OpsWorks_Resources_48_Dark.svg';
import _resAwsOpsWorksStack248DarkSvg from './Res_AWS-OpsWorks_Stack2_48_Dark.svg';
import _resAwsOrganizationsAccount48DarkSvg from './Res_AWS-Organizations_Account_48_Dark.svg';
import _resAwsOrganizationsManagementAccount48DarkSvg from './Res_AWS-Organizations_Management-Account_48_Dark.svg';
import _resAwsOrganizationsOrganizationalUnit48DarkSvg from './Res_AWS-Organizations_Organizational-Unit_48_Dark.svg';
import _resAwsSystemsManagerAutomation48DarkSvg from './Res_AWS-Systems-Manager_Automation_48_Dark.svg';
import _resAwsSystemsManagerChangeCalendar48DarkSvg from './Res_AWS-Systems-Manager_Change-Calendar_48_Dark.svg';
import _resAwsSystemsManagerChangeManager48DarkSvg from './Res_AWS-Systems-Manager_Change-Manager_48_Dark.svg';
import _resAwsSystemsManagerCompliance48DarkSvg from './Res_AWS-Systems-Manager_Compliance_48_Dark.svg';
import _resAwsSystemsManagerDocuments48DarkSvg from './Res_AWS-Systems-Manager_Documents_48_Dark.svg';
import _resAwsSystemsManagerInventory48DarkSvg from './Res_AWS-Systems-Manager_Inventory_48_Dark.svg';
import _resAwsSystemsManagerMaintenanceWindows48DarkSvg from './Res_AWS-Systems-Manager_Maintenance-Windows_48_Dark.svg';
import _resAwsSystemsManagerOpsCenter48DarkSvg from './Res_AWS-Systems-Manager_OpsCenter_48_Dark.svg';
import _resAwsSystemsManagerParameterStore48DarkSvg from './Res_AWS-Systems-Manager_Parameter-Store_48_Dark.svg';
import _resAwsSystemsManagerPatchManager48DarkSvg from './Res_AWS-Systems-Manager_Patch-Manager_48_Dark.svg';
import _resAwsSystemsManagerRunCommand48DarkSvg from './Res_AWS-Systems-Manager_Run-Command_48_Dark.svg';
import _resAwsSystemsManagerSessionManager48DarkSvg from './Res_AWS-Systems-Manager_Session-Manager_48_Dark.svg';
import _resAwsSystemsManagerStateManager48DarkSvg from './Res_AWS-Systems-Manager_State-Manager_48_Dark.svg';
import _resAwsTrustedAdvisorChecklistCost48DarkSvg from './Res_AWS-Trusted-Advisor_Checklist-Cost_48_Dark.svg';
import _resAwsTrustedAdvisorChecklistFaultTolerant48DarkSvg from './Res_AWS-Trusted-Advisor_Checklist-Fault-Tolerant_48_Dark.svg';
import _resAwsTrustedAdvisorChecklistPerformance48DarkSvg from './Res_AWS-Trusted-Advisor_Checklist-Performance_48_Dark.svg';
import _resAwsTrustedAdvisorChecklistSecurity48DarkSvg from './Res_AWS-Trusted-Advisor_Checklist-Security_48_Dark.svg';
import _resAwsTrustedAdvisorChecklist48DarkSvg from './Res_AWS-Trusted-Advisor_Checklist_48_Dark.svg';
import _resAmazonCloudWatchAlarm48DarkSvg from './Res_Amazon-CloudWatch_Alarm_48_Dark.svg';
import _resAmazonCloudWatchEventEventBased48DarkSvg from './Res_Amazon-CloudWatch_Event-Event-Based_48_Dark.svg';
import _resAmazonCloudWatchEventTimeBased48DarkSvg from './Res_Amazon-CloudWatch_Event-Time-Based_48_Dark.svg';
import _resAmazonCloudWatchEvidently48DarkSvg from './Res_Amazon-CloudWatch_Evidently_48_Dark.svg';
import _resAmazonCloudWatchLogs48DarkSvg from './Res_Amazon-CloudWatch_Logs_48_Dark.svg';
import _resAmazonCloudWatchMetricsInsights48DarkSvg from './Res_Amazon-CloudWatch_Metrics-Insights_48_Dark.svg';
import _resAmazonCloudWatchRum48DarkSvg from './Res_Amazon-CloudWatch_RUM_48_Dark.svg';
import _resAmazonCloudWatchRule48DarkSvg from './Res_Amazon-CloudWatch_Rule_48_Dark.svg';
import _resAmazonCloudWatchSynthetics48DarkSvg from './Res_Amazon-CloudWatch_Synthetics_48_Dark.svg';

export const resAwsCloudFormationChangeSet48DarkSvg = { id: "resAwsCloudFormationChangeSet48DarkSvg", name: "AWS CloudFormation / Change Set", icon: _resAwsCloudFormationChangeSet48DarkSvg };
export const resAwsCloudFormationStack48DarkSvg = { id: "resAwsCloudFormationStack48DarkSvg", name: "AWS CloudFormation / Stack", icon: _resAwsCloudFormationStack48DarkSvg };
export const resAwsCloudFormationTemplate48DarkSvg = { id: "resAwsCloudFormationTemplate48DarkSvg", name: "AWS CloudFormation / Template", icon: _resAwsCloudFormationTemplate48DarkSvg };
export const resAwsLicenseManagerApplicationDiscovery48DarkSvg = { id: "resAwsLicenseManagerApplicationDiscovery48DarkSvg", name: "AWS License Manager / Application Discovery", icon: _resAwsLicenseManagerApplicationDiscovery48DarkSvg };
export const resAwsLicenseManagerLicenseBlending48DarkSvg = { id: "resAwsLicenseManagerLicenseBlending48DarkSvg", name: "AWS License Manager / License Blending", icon: _resAwsLicenseManagerLicenseBlending48DarkSvg };
export const resAwsOpsWorksApps48DarkSvg = { id: "resAwsOpsWorksApps48DarkSvg", name: "AWS OpsWorks / Apps", icon: _resAwsOpsWorksApps48DarkSvg };
export const resAwsOpsWorksDeployments48DarkSvg = { id: "resAwsOpsWorksDeployments48DarkSvg", name: "AWS OpsWorks / Deployments", icon: _resAwsOpsWorksDeployments48DarkSvg };
export const resAwsOpsWorksInstances48DarkSvg = { id: "resAwsOpsWorksInstances48DarkSvg", name: "AWS OpsWorks / Instances", icon: _resAwsOpsWorksInstances48DarkSvg };
export const resAwsOpsWorksLayers48DarkSvg = { id: "resAwsOpsWorksLayers48DarkSvg", name: "AWS OpsWorks / Layers", icon: _resAwsOpsWorksLayers48DarkSvg };
export const resAwsOpsWorksMonitoring48DarkSvg = { id: "resAwsOpsWorksMonitoring48DarkSvg", name: "AWS OpsWorks / Monitoring", icon: _resAwsOpsWorksMonitoring48DarkSvg };
export const resAwsOpsWorksPermissions48DarkSvg = { id: "resAwsOpsWorksPermissions48DarkSvg", name: "AWS OpsWorks / Permissions", icon: _resAwsOpsWorksPermissions48DarkSvg };
export const resAwsOpsWorksResources48DarkSvg = { id: "resAwsOpsWorksResources48DarkSvg", name: "AWS OpsWorks / Resources", icon: _resAwsOpsWorksResources48DarkSvg };
export const resAwsOpsWorksStack248DarkSvg = { id: "resAwsOpsWorksStack248DarkSvg", name: "AWS OpsWorks / Stack2", icon: _resAwsOpsWorksStack248DarkSvg };
export const resAwsOrganizationsAccount48DarkSvg = { id: "resAwsOrganizationsAccount48DarkSvg", name: "AWS Organizations / Account", icon: _resAwsOrganizationsAccount48DarkSvg };
export const resAwsOrganizationsManagementAccount48DarkSvg = { id: "resAwsOrganizationsManagementAccount48DarkSvg", name: "AWS Organizations / Management Account", icon: _resAwsOrganizationsManagementAccount48DarkSvg };
export const resAwsOrganizationsOrganizationalUnit48DarkSvg = { id: "resAwsOrganizationsOrganizationalUnit48DarkSvg", name: "AWS Organizations / Organizational Unit", icon: _resAwsOrganizationsOrganizationalUnit48DarkSvg };
export const resAwsSystemsManagerAutomation48DarkSvg = { id: "resAwsSystemsManagerAutomation48DarkSvg", name: "AWS Systems Manager / Automation", icon: _resAwsSystemsManagerAutomation48DarkSvg };
export const resAwsSystemsManagerChangeCalendar48DarkSvg = { id: "resAwsSystemsManagerChangeCalendar48DarkSvg", name: "AWS Systems Manager / Change Calendar", icon: _resAwsSystemsManagerChangeCalendar48DarkSvg };
export const resAwsSystemsManagerChangeManager48DarkSvg = { id: "resAwsSystemsManagerChangeManager48DarkSvg", name: "AWS Systems Manager / Change Manager", icon: _resAwsSystemsManagerChangeManager48DarkSvg };
export const resAwsSystemsManagerCompliance48DarkSvg = { id: "resAwsSystemsManagerCompliance48DarkSvg", name: "AWS Systems Manager / Compliance", icon: _resAwsSystemsManagerCompliance48DarkSvg };
export const resAwsSystemsManagerDocuments48DarkSvg = { id: "resAwsSystemsManagerDocuments48DarkSvg", name: "AWS Systems Manager / Documents", icon: _resAwsSystemsManagerDocuments48DarkSvg };
export const resAwsSystemsManagerInventory48DarkSvg = { id: "resAwsSystemsManagerInventory48DarkSvg", name: "AWS Systems Manager / Inventory", icon: _resAwsSystemsManagerInventory48DarkSvg };
export const resAwsSystemsManagerMaintenanceWindows48DarkSvg = { id: "resAwsSystemsManagerMaintenanceWindows48DarkSvg", name: "AWS Systems Manager / Maintenance Windows", icon: _resAwsSystemsManagerMaintenanceWindows48DarkSvg };
export const resAwsSystemsManagerOpsCenter48DarkSvg = { id: "resAwsSystemsManagerOpsCenter48DarkSvg", name: "AWS Systems Manager / OpsCenter", icon: _resAwsSystemsManagerOpsCenter48DarkSvg };
export const resAwsSystemsManagerParameterStore48DarkSvg = { id: "resAwsSystemsManagerParameterStore48DarkSvg", name: "AWS Systems Manager / Parameter Store", icon: _resAwsSystemsManagerParameterStore48DarkSvg };
export const resAwsSystemsManagerPatchManager48DarkSvg = { id: "resAwsSystemsManagerPatchManager48DarkSvg", name: "AWS Systems Manager / Patch Manager", icon: _resAwsSystemsManagerPatchManager48DarkSvg };
export const resAwsSystemsManagerRunCommand48DarkSvg = { id: "resAwsSystemsManagerRunCommand48DarkSvg", name: "AWS Systems Manager / Run Command", icon: _resAwsSystemsManagerRunCommand48DarkSvg };
export const resAwsSystemsManagerSessionManager48DarkSvg = { id: "resAwsSystemsManagerSessionManager48DarkSvg", name: "AWS Systems Manager / Session Manager", icon: _resAwsSystemsManagerSessionManager48DarkSvg };
export const resAwsSystemsManagerStateManager48DarkSvg = { id: "resAwsSystemsManagerStateManager48DarkSvg", name: "AWS Systems Manager / State Manager", icon: _resAwsSystemsManagerStateManager48DarkSvg };
export const resAwsTrustedAdvisorChecklistCost48DarkSvg = { id: "resAwsTrustedAdvisorChecklistCost48DarkSvg", name: "AWS Trusted Advisor / Checklist Cost", icon: _resAwsTrustedAdvisorChecklistCost48DarkSvg };
export const resAwsTrustedAdvisorChecklistFaultTolerant48DarkSvg = { id: "resAwsTrustedAdvisorChecklistFaultTolerant48DarkSvg", name: "AWS Trusted Advisor / Checklist Fault Tolerant", icon: _resAwsTrustedAdvisorChecklistFaultTolerant48DarkSvg };
export const resAwsTrustedAdvisorChecklistPerformance48DarkSvg = { id: "resAwsTrustedAdvisorChecklistPerformance48DarkSvg", name: "AWS Trusted Advisor / Checklist Performance", icon: _resAwsTrustedAdvisorChecklistPerformance48DarkSvg };
export const resAwsTrustedAdvisorChecklistSecurity48DarkSvg = { id: "resAwsTrustedAdvisorChecklistSecurity48DarkSvg", name: "AWS Trusted Advisor / Checklist Security", icon: _resAwsTrustedAdvisorChecklistSecurity48DarkSvg };
export const resAwsTrustedAdvisorChecklist48DarkSvg = { id: "resAwsTrustedAdvisorChecklist48DarkSvg", name: "AWS Trusted Advisor / Checklist", icon: _resAwsTrustedAdvisorChecklist48DarkSvg };
export const resAmazonCloudWatchAlarm48DarkSvg = { id: "resAmazonCloudWatchAlarm48DarkSvg", name: "Amazon CloudWatch / Alarm", icon: _resAmazonCloudWatchAlarm48DarkSvg };
export const resAmazonCloudWatchEventEventBased48DarkSvg = { id: "resAmazonCloudWatchEventEventBased48DarkSvg", name: "Amazon CloudWatch / Event Event Based", icon: _resAmazonCloudWatchEventEventBased48DarkSvg };
export const resAmazonCloudWatchEventTimeBased48DarkSvg = { id: "resAmazonCloudWatchEventTimeBased48DarkSvg", name: "Amazon CloudWatch / Event Time Based", icon: _resAmazonCloudWatchEventTimeBased48DarkSvg };
export const resAmazonCloudWatchEvidently48DarkSvg = { id: "resAmazonCloudWatchEvidently48DarkSvg", name: "Amazon CloudWatch / Evidently", icon: _resAmazonCloudWatchEvidently48DarkSvg };
export const resAmazonCloudWatchLogs48DarkSvg = { id: "resAmazonCloudWatchLogs48DarkSvg", name: "Amazon CloudWatch / Logs", icon: _resAmazonCloudWatchLogs48DarkSvg };
export const resAmazonCloudWatchMetricsInsights48DarkSvg = { id: "resAmazonCloudWatchMetricsInsights48DarkSvg", name: "Amazon CloudWatch / Metrics Insights", icon: _resAmazonCloudWatchMetricsInsights48DarkSvg };
export const resAmazonCloudWatchRum48DarkSvg = { id: "resAmazonCloudWatchRum48DarkSvg", name: "Amazon CloudWatch / RUM", icon: _resAmazonCloudWatchRum48DarkSvg };
export const resAmazonCloudWatchRule48DarkSvg = { id: "resAmazonCloudWatchRule48DarkSvg", name: "Amazon CloudWatch / Rule", icon: _resAmazonCloudWatchRule48DarkSvg };
export const resAmazonCloudWatchSynthetics48DarkSvg = { id: "resAmazonCloudWatchSynthetics48DarkSvg", name: "Amazon CloudWatch / Synthetics", icon: _resAmazonCloudWatchSynthetics48DarkSvg };
