import _resAmazonApiGatewayEndpoint48DarkSvg from './Res_Amazon-API-Gateway_Endpoint_48_Dark.svg';
import _resAmazonEventBridgeCustomEventBus48DarkSvg from './Res_Amazon-EventBridge_Custom-Event-Bus_48_Dark.svg';
import _resAmazonEventBridgeDefaultEventBus48DarkSvg from './Res_Amazon-EventBridge_Default-Event-Bus_48_Dark.svg';
import _resAmazonEventBridgeEvent48DarkSvg from './Res_Amazon-EventBridge_Event_48_Dark.svg';
import _resAmazonEventBridgeRule48DarkSvg from './Res_Amazon-EventBridge_Rule_48_Dark.svg';
import _resAmazonEventBridgeSaasPartnerEvent48DarkSvg from './Res_Amazon-EventBridge_Saas-Partner-Event_48_Dark.svg';
import _resAmazonEventBridgeSchemaRegistry48DarkSvg from './Res_Amazon-EventBridge_Schema-Registry_48_Dark.svg';
import _resAmazonEventBridgeSchema48DarkSvg from './Res_Amazon-EventBridge_Schema_48_Dark.svg';
import _resAmazonMqBroker48DarkSvg from './Res_Amazon-MQ_Broker_48_Dark.svg';
import _resAmazonSimpleNotificationServiceEmailNotification48DarkSvg from './Res_Amazon-Simple-Notification-Service_Email-Notification_48_Dark.svg';
import _resAmazonSimpleNotificationServiceHttpNotification48DarkSvg from './Res_Amazon-Simple-Notification-Service_HTTP-Notification_48_Dark.svg';
import _resAmazonSimpleNotificationServiceTopic48DarkSvg from './Res_Amazon-Simple-Notification-Service_Topic_48_Dark.svg';
import _resAmazonSimpleQueueServiceMessage48DarkSvg from './Res_Amazon-Simple-Queue-Service_Message_48_Dark.svg';
import _resAmazonSimpleQueueServiceQueue48DarkSvg from './Res_Amazon-Simple-Queue-Service_Queue_48_Dark.svg';

export const resAmazonApiGatewayEndpoint48DarkSvg = { id: "resAmazonApiGatewayEndpoint48DarkSvg", name: "Amazon API Gateway / Endpoint", icon: _resAmazonApiGatewayEndpoint48DarkSvg };
export const resAmazonEventBridgeCustomEventBus48DarkSvg = { id: "resAmazonEventBridgeCustomEventBus48DarkSvg", name: "Amazon EventBridge / Custom Event Bus", icon: _resAmazonEventBridgeCustomEventBus48DarkSvg };
export const resAmazonEventBridgeDefaultEventBus48DarkSvg = { id: "resAmazonEventBridgeDefaultEventBus48DarkSvg", name: "Amazon EventBridge / Default Event Bus", icon: _resAmazonEventBridgeDefaultEventBus48DarkSvg };
export const resAmazonEventBridgeEvent48DarkSvg = { id: "resAmazonEventBridgeEvent48DarkSvg", name: "Amazon EventBridge / Event", icon: _resAmazonEventBridgeEvent48DarkSvg };
export const resAmazonEventBridgeRule48DarkSvg = { id: "resAmazonEventBridgeRule48DarkSvg", name: "Amazon EventBridge / Rule", icon: _resAmazonEventBridgeRule48DarkSvg };
export const resAmazonEventBridgeSaasPartnerEvent48DarkSvg = { id: "resAmazonEventBridgeSaasPartnerEvent48DarkSvg", name: "Amazon EventBridge / Saas Partner Event", icon: _resAmazonEventBridgeSaasPartnerEvent48DarkSvg };
export const resAmazonEventBridgeSchemaRegistry48DarkSvg = { id: "resAmazonEventBridgeSchemaRegistry48DarkSvg", name: "Amazon EventBridge / Schema Registry", icon: _resAmazonEventBridgeSchemaRegistry48DarkSvg };
export const resAmazonEventBridgeSchema48DarkSvg = { id: "resAmazonEventBridgeSchema48DarkSvg", name: "Amazon EventBridge / Schema", icon: _resAmazonEventBridgeSchema48DarkSvg };
export const resAmazonMqBroker48DarkSvg = { id: "resAmazonMqBroker48DarkSvg", name: "Amazon MQ / Broker", icon: _resAmazonMqBroker48DarkSvg };
export const resAmazonSimpleNotificationServiceEmailNotification48DarkSvg = { id: "resAmazonSimpleNotificationServiceEmailNotification48DarkSvg", name: "Amazon Simple Notification Service / Email Notification", icon: _resAmazonSimpleNotificationServiceEmailNotification48DarkSvg };
export const resAmazonSimpleNotificationServiceHttpNotification48DarkSvg = { id: "resAmazonSimpleNotificationServiceHttpNotification48DarkSvg", name: "Amazon Simple Notification Service / HTTP Notification", icon: _resAmazonSimpleNotificationServiceHttpNotification48DarkSvg };
export const resAmazonSimpleNotificationServiceTopic48DarkSvg = { id: "resAmazonSimpleNotificationServiceTopic48DarkSvg", name: "Amazon Simple Notification Service / Topic", icon: _resAmazonSimpleNotificationServiceTopic48DarkSvg };
export const resAmazonSimpleQueueServiceMessage48DarkSvg = { id: "resAmazonSimpleQueueServiceMessage48DarkSvg", name: "Amazon Simple Queue Service / Message", icon: _resAmazonSimpleQueueServiceMessage48DarkSvg };
export const resAmazonSimpleQueueServiceQueue48DarkSvg = { id: "resAmazonSimpleQueueServiceQueue48DarkSvg", name: "Amazon Simple Queue Service / Queue", icon: _resAmazonSimpleQueueServiceQueue48DarkSvg };
