import _resAmazonBraketChandelier48LightSvg from './Res_Amazon-Braket_Chandelier_48_Light.svg';
import _resAmazonBraketChip48LightSvg from './Res_Amazon-Braket_Chip_48_Light.svg';
import _resAmazonBraketEmbeddedSimulator48LightSvg from './Res_Amazon-Braket_Embedded-Simulator_48_Light.svg';
import _resAmazonBraketManagedSimulator48LightSvg from './Res_Amazon-Braket_Managed-Simulator_48_Light.svg';
import _resAmazonBraketNoiseSimulator48LightSvg from './Res_Amazon-Braket_Noise-Simulator_48_Light.svg';
import _resAmazonBraketQpu48LightSvg from './Res_Amazon-Braket_QPU_48_Light.svg';
import _resAmazonBraketSimulator148LightSvg from './Res_Amazon-Braket_Simulator-1_48_Light.svg';
import _resAmazonBraketSimulator248LightSvg from './Res_Amazon-Braket_Simulator-2_48_Light.svg';
import _resAmazonBraketSimulator348LightSvg from './Res_Amazon-Braket_Simulator-3_48_Light.svg';
import _resAmazonBraketSimulator448LightSvg from './Res_Amazon-Braket_Simulator-4_48_Light.svg';
import _resAmazonBraketSimulator48LightSvg from './Res_Amazon-Braket_Simulator_48_Light.svg';
import _resAmazonBraketStateVector48LightSvg from './Res_Amazon-Braket_State-Vector_48_Light.svg';
import _resAmazonBraketTensorNetwork48LightSvg from './Res_Amazon-Braket_Tensor-Network_48_Light.svg';

export const resAmazonBraketChandelier48LightSvg = { id: "resAmazonBraketChandelier48LightSvg", name: "Amazon Braket | Chandelier", icon: _resAmazonBraketChandelier48LightSvg };
export const resAmazonBraketChip48LightSvg = { id: "resAmazonBraketChip48LightSvg", name: "Amazon Braket | Chip", icon: _resAmazonBraketChip48LightSvg };
export const resAmazonBraketEmbeddedSimulator48LightSvg = { id: "resAmazonBraketEmbeddedSimulator48LightSvg", name: "Amazon Braket | Embedded Simulator", icon: _resAmazonBraketEmbeddedSimulator48LightSvg };
export const resAmazonBraketManagedSimulator48LightSvg = { id: "resAmazonBraketManagedSimulator48LightSvg", name: "Amazon Braket | Managed Simulator", icon: _resAmazonBraketManagedSimulator48LightSvg };
export const resAmazonBraketNoiseSimulator48LightSvg = { id: "resAmazonBraketNoiseSimulator48LightSvg", name: "Amazon Braket | Noise Simulator", icon: _resAmazonBraketNoiseSimulator48LightSvg };
export const resAmazonBraketQpu48LightSvg = { id: "resAmazonBraketQpu48LightSvg", name: "Amazon Braket | QPU", icon: _resAmazonBraketQpu48LightSvg };
export const resAmazonBraketSimulator148LightSvg = { id: "resAmazonBraketSimulator148LightSvg", name: "Amazon Braket | Simulator 1", icon: _resAmazonBraketSimulator148LightSvg };
export const resAmazonBraketSimulator248LightSvg = { id: "resAmazonBraketSimulator248LightSvg", name: "Amazon Braket | Simulator 2", icon: _resAmazonBraketSimulator248LightSvg };
export const resAmazonBraketSimulator348LightSvg = { id: "resAmazonBraketSimulator348LightSvg", name: "Amazon Braket | Simulator 3", icon: _resAmazonBraketSimulator348LightSvg };
export const resAmazonBraketSimulator448LightSvg = { id: "resAmazonBraketSimulator448LightSvg", name: "Amazon Braket | Simulator 4", icon: _resAmazonBraketSimulator448LightSvg };
export const resAmazonBraketSimulator48LightSvg = { id: "resAmazonBraketSimulator48LightSvg", name: "Amazon Braket | Simulator", icon: _resAmazonBraketSimulator48LightSvg };
export const resAmazonBraketStateVector48LightSvg = { id: "resAmazonBraketStateVector48LightSvg", name: "Amazon Braket | State Vector", icon: _resAmazonBraketStateVector48LightSvg };
export const resAmazonBraketTensorNetwork48LightSvg = { id: "resAmazonBraketTensorNetwork48LightSvg", name: "Amazon Braket | Tensor Network", icon: _resAmazonBraketTensorNetwork48LightSvg };
