import _archAwsIoT1Click64Svg from './Arch_AWS-IoT-1-Click_64.svg';
import _archAwsIoTAnalytics64Svg from './Arch_AWS-IoT-Analytics_64.svg';
import _archAwsIoTButton64Svg from './Arch_AWS-IoT-Button_64.svg';
import _archAwsIoTCore64Svg from './Arch_AWS-IoT-Core_64.svg';
import _archAwsIoTDeviceDefender64Svg from './Arch_AWS-IoT-Device-Defender_64.svg';
import _archAwsIoTDeviceManagement64Svg from './Arch_AWS-IoT-Device-Management_64.svg';
import _archAwsIoTEduKit64Svg from './Arch_AWS-IoT-EduKit_64.svg';
import _archAwsIoTEvents64Svg from './Arch_AWS-IoT-Events_64.svg';
import _archAwsIoTExpressLink64Svg from './Arch_AWS-IoT-ExpressLink_64.svg';
import _archAwsIoTFleetWise64Svg from './Arch_AWS-IoT-FleetWise_64.svg';
import _archAwsIoTGreengrass64Svg from './Arch_AWS-IoT-Greengrass_64.svg';
import _archAwsIoTRoboRunner64Svg from './Arch_AWS-IoT-RoboRunner_64.svg';
import _archAwsIoTSiteWise64Svg from './Arch_AWS-IoT-SiteWise_64.svg';
import _archAwsIoTThingsGraph64Svg from './Arch_AWS-IoT-Things-Graph_64.svg';
import _archAwsIoTTwinMaker64Svg from './Arch_AWS-IoT-TwinMaker_64.svg';
import _archFreeRtos64Svg from './Arch_FreeRTOS_64.svg';

export const archAwsIoT1Click64Svg = { id: "archAwsIoT1Click64Svg", name: "AWS IoT 1 Click", icon: _archAwsIoT1Click64Svg };
export const archAwsIoTAnalytics64Svg = { id: "archAwsIoTAnalytics64Svg", name: "AWS IoT Analytics", icon: _archAwsIoTAnalytics64Svg };
export const archAwsIoTButton64Svg = { id: "archAwsIoTButton64Svg", name: "AWS IoT Button", icon: _archAwsIoTButton64Svg };
export const archAwsIoTCore64Svg = { id: "archAwsIoTCore64Svg", name: "AWS IoT Core", icon: _archAwsIoTCore64Svg };
export const archAwsIoTDeviceDefender64Svg = { id: "archAwsIoTDeviceDefender64Svg", name: "AWS IoT Device Defender", icon: _archAwsIoTDeviceDefender64Svg };
export const archAwsIoTDeviceManagement64Svg = { id: "archAwsIoTDeviceManagement64Svg", name: "AWS IoT Device Management", icon: _archAwsIoTDeviceManagement64Svg };
export const archAwsIoTEduKit64Svg = { id: "archAwsIoTEduKit64Svg", name: "AWS IoT EduKit", icon: _archAwsIoTEduKit64Svg };
export const archAwsIoTEvents64Svg = { id: "archAwsIoTEvents64Svg", name: "AWS IoT Events", icon: _archAwsIoTEvents64Svg };
export const archAwsIoTExpressLink64Svg = { id: "archAwsIoTExpressLink64Svg", name: "AWS IoT ExpressLink", icon: _archAwsIoTExpressLink64Svg };
export const archAwsIoTFleetWise64Svg = { id: "archAwsIoTFleetWise64Svg", name: "AWS IoT FleetWise", icon: _archAwsIoTFleetWise64Svg };
export const archAwsIoTGreengrass64Svg = { id: "archAwsIoTGreengrass64Svg", name: "AWS IoT Greengrass", icon: _archAwsIoTGreengrass64Svg };
export const archAwsIoTRoboRunner64Svg = { id: "archAwsIoTRoboRunner64Svg", name: "AWS IoT RoboRunner", icon: _archAwsIoTRoboRunner64Svg };
export const archAwsIoTSiteWise64Svg = { id: "archAwsIoTSiteWise64Svg", name: "AWS IoT SiteWise", icon: _archAwsIoTSiteWise64Svg };
export const archAwsIoTThingsGraph64Svg = { id: "archAwsIoTThingsGraph64Svg", name: "AWS IoT Things Graph", icon: _archAwsIoTThingsGraph64Svg };
export const archAwsIoTTwinMaker64Svg = { id: "archAwsIoTTwinMaker64Svg", name: "AWS IoT TwinMaker", icon: _archAwsIoTTwinMaker64Svg };
export const archFreeRtos64Svg = { id: "archFreeRtos64Svg", name: "FreeRTOS", icon: _archFreeRtos64Svg };
