import _archAwsAppRunner16Svg from './Arch_AWS-App-Runner_16.svg';
import _archAwsBatch16Svg from './Arch_AWS-Batch_16.svg';
import _archAwsComputeOptimizer16Svg from './Arch_AWS-Compute-Optimizer_16.svg';
import _archAwsElasticBeanstalk16Svg from './Arch_AWS-Elastic-Beanstalk_16.svg';
import _archAwsFargate16Svg from './Arch_AWS-Fargate_16.svg';
import _archAwsLambda16Svg from './Arch_AWS-Lambda_16.svg';
import _archAwsLocalZones16Svg from './Arch_AWS-Local-Zones_16.svg';
import _archAwsNitroEnclaves16Svg from './Arch_AWS-Nitro-Enclaves_16.svg';
import _archAwsOutpostsFamily16Svg from './Arch_AWS-Outposts-family_16.svg';
import _archAwsOutpostsRack16Svg from './Arch_AWS-Outposts-rack_16.svg';
import _archAwsOutpostsServers16Svg from './Arch_AWS-Outposts-servers_16.svg';
import _archAwsParallelCluster16Svg from './Arch_AWS-ParallelCluster_16.svg';
import _archAwsServerlessApplicationRepository16Svg from './Arch_AWS-Serverless-Application-Repository_16.svg';
import _archAwsThinkboxDeadline16Svg from './Arch_AWS-Thinkbox-Deadline_16.svg';
import _archAwsThinkboxFrost16Svg from './Arch_AWS-Thinkbox-Frost_16.svg';
import _archAwsThinkboxKrakatoa16Svg from './Arch_AWS-Thinkbox-Krakatoa_16.svg';
import _archAwsThinkboxSequoia16Svg from './Arch_AWS-Thinkbox-Sequoia_16.svg';
import _archAwsThinkboxStoke16Svg from './Arch_AWS-Thinkbox-Stoke_16.svg';
import _archAwsThinkboxXmesh16Svg from './Arch_AWS-Thinkbox-XMesh_16.svg';
import _archAwsWavelength16Svg from './Arch_AWS-Wavelength_16.svg';
import _archAmazonEc2AutoScaling16Svg from './Arch_Amazon-EC2-Auto-Scaling_16.svg';
import _archAmazonEc2ImageBuilder16Svg from './Arch_Amazon-EC2-Image-Builder_16.svg';
import _archAmazonEc2M5N16Svg from './Arch_Amazon-EC2-M5n_16.svg';
import _archAmazonEc2R5N16Svg from './Arch_Amazon-EC2-R5n_16.svg';
import _archAmazonEc216Svg from './Arch_Amazon-EC2_16.svg';
import _archAmazonElasticContainerKubernetes16Svg from './Arch_Amazon-Elastic-Container-Kubernetes_16.svg';
import _archAmazonElasticContainerRegistry16Svg from './Arch_Amazon-Elastic-Container-Registry_16.svg';
import _archAmazonElasticContainerService16Svg from './Arch_Amazon-Elastic-Container-Service_16.svg';
import _archAmazonGenomicsCli16Svg from './Arch_Amazon-Genomics-CLI_16.svg';
import _archAmazonLightsail16Svg from './Arch_Amazon-Lightsail_16.svg';
import _archBottlerocket16Svg from './Arch_Bottlerocket_16.svg';
import _archElasticFabricAdapter16Svg from './Arch_Elastic-Fabric-Adapter_16.svg';
import _archNiceDcv16Svg from './Arch_NICE-DCV_16.svg';
import _archNiceEnginFrame16Svg from './Arch_NICE-EnginFrame_16.svg';
import _archVMwareCloudOnAws16Svg from './Arch_VMware-Cloud-on-AWS_16.svg';

export const archAwsAppRunner16Svg = { id: "archAwsAppRunner16Svg", name: "AWS App Runner", icon: _archAwsAppRunner16Svg };
export const archAwsBatch16Svg = { id: "archAwsBatch16Svg", name: "AWS Batch", icon: _archAwsBatch16Svg };
export const archAwsComputeOptimizer16Svg = { id: "archAwsComputeOptimizer16Svg", name: "AWS Compute Optimizer", icon: _archAwsComputeOptimizer16Svg };
export const archAwsElasticBeanstalk16Svg = { id: "archAwsElasticBeanstalk16Svg", name: "AWS Elastic Beanstalk", icon: _archAwsElasticBeanstalk16Svg };
export const archAwsFargate16Svg = { id: "archAwsFargate16Svg", name: "AWS Fargate", icon: _archAwsFargate16Svg };
export const archAwsLambda16Svg = { id: "archAwsLambda16Svg", name: "AWS Lambda", icon: _archAwsLambda16Svg };
export const archAwsLocalZones16Svg = { id: "archAwsLocalZones16Svg", name: "AWS Local Zones", icon: _archAwsLocalZones16Svg };
export const archAwsNitroEnclaves16Svg = { id: "archAwsNitroEnclaves16Svg", name: "AWS Nitro Enclaves", icon: _archAwsNitroEnclaves16Svg };
export const archAwsOutpostsFamily16Svg = { id: "archAwsOutpostsFamily16Svg", name: "AWS Outposts family", icon: _archAwsOutpostsFamily16Svg };
export const archAwsOutpostsRack16Svg = { id: "archAwsOutpostsRack16Svg", name: "AWS Outposts rack", icon: _archAwsOutpostsRack16Svg };
export const archAwsOutpostsServers16Svg = { id: "archAwsOutpostsServers16Svg", name: "AWS Outposts servers", icon: _archAwsOutpostsServers16Svg };
export const archAwsParallelCluster16Svg = { id: "archAwsParallelCluster16Svg", name: "AWS ParallelCluster", icon: _archAwsParallelCluster16Svg };
export const archAwsServerlessApplicationRepository16Svg = { id: "archAwsServerlessApplicationRepository16Svg", name: "AWS Serverless Application Repository", icon: _archAwsServerlessApplicationRepository16Svg };
export const archAwsThinkboxDeadline16Svg = { id: "archAwsThinkboxDeadline16Svg", name: "AWS Thinkbox Deadline", icon: _archAwsThinkboxDeadline16Svg };
export const archAwsThinkboxFrost16Svg = { id: "archAwsThinkboxFrost16Svg", name: "AWS Thinkbox Frost", icon: _archAwsThinkboxFrost16Svg };
export const archAwsThinkboxKrakatoa16Svg = { id: "archAwsThinkboxKrakatoa16Svg", name: "AWS Thinkbox Krakatoa", icon: _archAwsThinkboxKrakatoa16Svg };
export const archAwsThinkboxSequoia16Svg = { id: "archAwsThinkboxSequoia16Svg", name: "AWS Thinkbox Sequoia", icon: _archAwsThinkboxSequoia16Svg };
export const archAwsThinkboxStoke16Svg = { id: "archAwsThinkboxStoke16Svg", name: "AWS Thinkbox Stoke", icon: _archAwsThinkboxStoke16Svg };
export const archAwsThinkboxXmesh16Svg = { id: "archAwsThinkboxXmesh16Svg", name: "AWS Thinkbox XMesh", icon: _archAwsThinkboxXmesh16Svg };
export const archAwsWavelength16Svg = { id: "archAwsWavelength16Svg", name: "AWS Wavelength", icon: _archAwsWavelength16Svg };
export const archAmazonEc2AutoScaling16Svg = { id: "archAmazonEc2AutoScaling16Svg", name: "Amazon EC2 Auto Scaling", icon: _archAmazonEc2AutoScaling16Svg };
export const archAmazonEc2ImageBuilder16Svg = { id: "archAmazonEc2ImageBuilder16Svg", name: "Amazon EC2 Image Builder", icon: _archAmazonEc2ImageBuilder16Svg };
export const archAmazonEc2M5N16Svg = { id: "archAmazonEc2M5N16Svg", name: "Amazon EC2 M5n", icon: _archAmazonEc2M5N16Svg };
export const archAmazonEc2R5N16Svg = { id: "archAmazonEc2R5N16Svg", name: "Amazon EC2 R5n", icon: _archAmazonEc2R5N16Svg };
export const archAmazonEc216Svg = { id: "archAmazonEc216Svg", name: "Amazon EC2", icon: _archAmazonEc216Svg };
export const archAmazonElasticContainerKubernetes16Svg = { id: "archAmazonElasticContainerKubernetes16Svg", name: "Amazon Elastic Container Kubernetes", icon: _archAmazonElasticContainerKubernetes16Svg };
export const archAmazonElasticContainerRegistry16Svg = { id: "archAmazonElasticContainerRegistry16Svg", name: "Amazon Elastic Container Registry", icon: _archAmazonElasticContainerRegistry16Svg };
export const archAmazonElasticContainerService16Svg = { id: "archAmazonElasticContainerService16Svg", name: "Amazon Elastic Container Service", icon: _archAmazonElasticContainerService16Svg };
export const archAmazonGenomicsCli16Svg = { id: "archAmazonGenomicsCli16Svg", name: "Amazon Genomics CLI", icon: _archAmazonGenomicsCli16Svg };
export const archAmazonLightsail16Svg = { id: "archAmazonLightsail16Svg", name: "Amazon Lightsail", icon: _archAmazonLightsail16Svg };
export const archBottlerocket16Svg = { id: "archBottlerocket16Svg", name: "Bottlerocket", icon: _archBottlerocket16Svg };
export const archElasticFabricAdapter16Svg = { id: "archElasticFabricAdapter16Svg", name: "Elastic Fabric Adapter", icon: _archElasticFabricAdapter16Svg };
export const archNiceDcv16Svg = { id: "archNiceDcv16Svg", name: "NICE DCV", icon: _archNiceDcv16Svg };
export const archNiceEnginFrame16Svg = { id: "archNiceEnginFrame16Svg", name: "NICE EnginFrame", icon: _archNiceEnginFrame16Svg };
export const archVMwareCloudOnAws16Svg = { id: "archVMwareCloudOnAws16Svg", name: "VMware Cloud on AWS", icon: _archVMwareCloudOnAws16Svg };
