import _resAmazonApiGatewayEndpoint48LightSvg from './Res_Amazon-API-Gateway_Endpoint_48_Light.svg';
import _resAmazonEventBridgeCustomEventBus48LightSvg from './Res_Amazon-EventBridge_Custom-Event-Bus_48_Light.svg';
import _resAmazonEventBridgeDefaultEventBus48LightSvg from './Res_Amazon-EventBridge_Default-Event-Bus_48_Light.svg';
import _resAmazonEventBridgeEvent48LightSvg from './Res_Amazon-EventBridge_Event_48_Light.svg';
import _resAmazonEventBridgeRule48LightSvg from './Res_Amazon-EventBridge_Rule_48_Light.svg';
import _resAmazonEventBridgeSaasPartnerEvent48LightSvg from './Res_Amazon-EventBridge_Saas-Partner-Event_48_Light.svg';
import _resAmazonEventBridgeSchemaRegistry48LightSvg from './Res_Amazon-EventBridge_Schema-Registry_48_Light.svg';
import _resAmazonEventBridgeSchema48LightSvg from './Res_Amazon-EventBridge_Schema_48_Light.svg';
import _resAmazonMqBroker48LightSvg from './Res_Amazon-MQ_Broker_48_Light.svg';
import _resAmazonSimpleNotificationServiceEmailNotification48LightSvg from './Res_Amazon-Simple-Notification-Service_Email-Notification_48_Light.svg';
import _resAmazonSimpleNotificationServiceHttpNotification48LightSvg from './Res_Amazon-Simple-Notification-Service_HTTP-Notification_48_Light.svg';
import _resAmazonSimpleNotificationServiceTopic48LightSvg from './Res_Amazon-Simple-Notification-Service_Topic_48_Light.svg';
import _resAmazonSimpleQueueServiceMessage48LightSvg from './Res_Amazon-Simple-Queue-Service_Message_48_Light.svg';
import _resAmazonSimpleQueueServiceQueue48LightSvg from './Res_Amazon-Simple-Queue-Service_Queue_48_Light.svg';

export const resAmazonApiGatewayEndpoint48LightSvg = { id: "resAmazonApiGatewayEndpoint48LightSvg", name: "Amazon API Gateway | Endpoint", icon: _resAmazonApiGatewayEndpoint48LightSvg };
export const resAmazonEventBridgeCustomEventBus48LightSvg = { id: "resAmazonEventBridgeCustomEventBus48LightSvg", name: "Amazon EventBridge | Custom Event Bus", icon: _resAmazonEventBridgeCustomEventBus48LightSvg };
export const resAmazonEventBridgeDefaultEventBus48LightSvg = { id: "resAmazonEventBridgeDefaultEventBus48LightSvg", name: "Amazon EventBridge | Default Event Bus", icon: _resAmazonEventBridgeDefaultEventBus48LightSvg };
export const resAmazonEventBridgeEvent48LightSvg = { id: "resAmazonEventBridgeEvent48LightSvg", name: "Amazon EventBridge | Event", icon: _resAmazonEventBridgeEvent48LightSvg };
export const resAmazonEventBridgeRule48LightSvg = { id: "resAmazonEventBridgeRule48LightSvg", name: "Amazon EventBridge | Rule", icon: _resAmazonEventBridgeRule48LightSvg };
export const resAmazonEventBridgeSaasPartnerEvent48LightSvg = { id: "resAmazonEventBridgeSaasPartnerEvent48LightSvg", name: "Amazon EventBridge | Saas Partner Event", icon: _resAmazonEventBridgeSaasPartnerEvent48LightSvg };
export const resAmazonEventBridgeSchemaRegistry48LightSvg = { id: "resAmazonEventBridgeSchemaRegistry48LightSvg", name: "Amazon EventBridge | Schema Registry", icon: _resAmazonEventBridgeSchemaRegistry48LightSvg };
export const resAmazonEventBridgeSchema48LightSvg = { id: "resAmazonEventBridgeSchema48LightSvg", name: "Amazon EventBridge | Schema", icon: _resAmazonEventBridgeSchema48LightSvg };
export const resAmazonMqBroker48LightSvg = { id: "resAmazonMqBroker48LightSvg", name: "Amazon MQ | Broker", icon: _resAmazonMqBroker48LightSvg };
export const resAmazonSimpleNotificationServiceEmailNotification48LightSvg = { id: "resAmazonSimpleNotificationServiceEmailNotification48LightSvg", name: "Amazon Simple Notification Service | Email Notification", icon: _resAmazonSimpleNotificationServiceEmailNotification48LightSvg };
export const resAmazonSimpleNotificationServiceHttpNotification48LightSvg = { id: "resAmazonSimpleNotificationServiceHttpNotification48LightSvg", name: "Amazon Simple Notification Service | HTTP Notification", icon: _resAmazonSimpleNotificationServiceHttpNotification48LightSvg };
export const resAmazonSimpleNotificationServiceTopic48LightSvg = { id: "resAmazonSimpleNotificationServiceTopic48LightSvg", name: "Amazon Simple Notification Service | Topic", icon: _resAmazonSimpleNotificationServiceTopic48LightSvg };
export const resAmazonSimpleQueueServiceMessage48LightSvg = { id: "resAmazonSimpleQueueServiceMessage48LightSvg", name: "Amazon Simple Queue Service | Message", icon: _resAmazonSimpleQueueServiceMessage48LightSvg };
export const resAmazonSimpleQueueServiceQueue48LightSvg = { id: "resAmazonSimpleQueueServiceQueue48LightSvg", name: "Amazon Simple Queue Service | Queue", icon: _resAmazonSimpleQueueServiceQueue48LightSvg };
