import _archAlexaForBusiness48Svg from './Arch_Alexa-For-Business_48.svg';
import _archAmazonChimeSdk48Svg from './Arch_Amazon-Chime-SDK_48.svg';
import _archAmazonChimeVoiceConnector48Svg from './Arch_Amazon-Chime-Voice-Connector_48.svg';
import _archAmazonChime48Svg from './Arch_Amazon-Chime_48.svg';
import _archAmazonConnect48Svg from './Arch_Amazon-Connect_48.svg';
import _archAmazonHoneycode48Svg from './Arch_Amazon-Honeycode_48.svg';
import _archAmazonPinpointApIs48Svg from './Arch_Amazon-Pinpoint-APIs_48.svg';
import _archAmazonPinpoint48Svg from './Arch_Amazon-Pinpoint_48.svg';
import _archAmazonSimpleEmailService48Svg from './Arch_Amazon-Simple-Email-Service_48.svg';
import _archAmazonWorkDocsSdk48Svg from './Arch_Amazon-WorkDocs-SDK_48.svg';
import _archAmazonWorkDocs48Svg from './Arch_Amazon-WorkDocs_48.svg';
import _archAmazonWorkMail48Svg from './Arch_Amazon-WorkMail_48.svg';

export const archAlexaForBusiness48Svg = { id: "archAlexaForBusiness48Svg", name: "Alexa For Business", icon: _archAlexaForBusiness48Svg };
export const archAmazonChimeSdk48Svg = { id: "archAmazonChimeSdk48Svg", name: "Amazon Chime SDK", icon: _archAmazonChimeSdk48Svg };
export const archAmazonChimeVoiceConnector48Svg = { id: "archAmazonChimeVoiceConnector48Svg", name: "Amazon Chime Voice Connector", icon: _archAmazonChimeVoiceConnector48Svg };
export const archAmazonChime48Svg = { id: "archAmazonChime48Svg", name: "Amazon Chime", icon: _archAmazonChime48Svg };
export const archAmazonConnect48Svg = { id: "archAmazonConnect48Svg", name: "Amazon Connect", icon: _archAmazonConnect48Svg };
export const archAmazonHoneycode48Svg = { id: "archAmazonHoneycode48Svg", name: "Amazon Honeycode", icon: _archAmazonHoneycode48Svg };
export const archAmazonPinpointApIs48Svg = { id: "archAmazonPinpointApIs48Svg", name: "Amazon Pinpoint APIs", icon: _archAmazonPinpointApIs48Svg };
export const archAmazonPinpoint48Svg = { id: "archAmazonPinpoint48Svg", name: "Amazon Pinpoint", icon: _archAmazonPinpoint48Svg };
export const archAmazonSimpleEmailService48Svg = { id: "archAmazonSimpleEmailService48Svg", name: "Amazon Simple Email Service", icon: _archAmazonSimpleEmailService48Svg };
export const archAmazonWorkDocsSdk48Svg = { id: "archAmazonWorkDocsSdk48Svg", name: "Amazon WorkDocs SDK", icon: _archAmazonWorkDocsSdk48Svg };
export const archAmazonWorkDocs48Svg = { id: "archAmazonWorkDocs48Svg", name: "Amazon WorkDocs", icon: _archAmazonWorkDocs48Svg };
export const archAmazonWorkMail48Svg = { id: "archAmazonWorkMail48Svg", name: "Amazon WorkMail", icon: _archAmazonWorkMail48Svg };
