import _resAwsAppMeshMesh48DarkSvg from './Res_AWS-App-Mesh_Mesh_48_Dark.svg';
import _resAwsAppMeshVirtualGateway48DarkSvg from './Res_AWS-App-Mesh_Virtual-Gateway_48_Dark.svg';
import _resAwsAppMeshVirtualNode48DarkSvg from './Res_AWS-App-Mesh_Virtual-Node_48_Dark.svg';
import _resAwsAppMeshVirtualRouter48DarkSvg from './Res_AWS-App-Mesh_Virtual-Router_48_Dark.svg';
import _resAwsAppMeshVirtualService48DarkSvg from './Res_AWS-App-Mesh_Virtual-Service_48_Dark.svg';
import _resAwsCloudMapNamespace48DarkSvg from './Res_AWS-Cloud-Map_Namespace_48_Dark.svg';
import _resAwsCloudMapResource48DarkSvg from './Res_AWS-Cloud-Map_Resource_48_Dark.svg';
import _resAwsCloudMapService48DarkSvg from './Res_AWS-Cloud-Map_Service_48_Dark.svg';
import _resAwsCloudWanCoreNetworkEdge48DarkSvg from './Res_AWS-Cloud-WAN_Core-Network-Edge_48_Dark.svg';
import _resAwsCloudWanSegmentNetwork48DarkSvg from './Res_AWS-Cloud-WAN_Segment-Network_48_Dark.svg';
import _resAwsCloudWanVirtualPoP48DarkSvg from './Res_AWS-Cloud-WAN_Virtual-PoP_48_Dark.svg';
import _resAwsDirectConnectGateway48DarkSvg from './Res_AWS-Direct-Connect_Gateway_48_Dark.svg';
import _resAwsTransitGatewayAttachment48DarkSvg from './Res_AWS-Transit-Gateway_Attachment_48_Dark.svg';
import _resAmazonCloudFrontDownloadDistribution48DarkSvg from './Res_Amazon-CloudFront_Download-Distribution_48_Dark.svg';
import _resAmazonCloudFrontEdgeLocation48DarkSvg from './Res_Amazon-CloudFront_Edge-Location_48_Dark.svg';
import _resAmazonCloudFrontFunctions48DarkSvg from './Res_Amazon-CloudFront_Functions_48_Dark.svg';
import _resAmazonCloudFrontStreamingDistribution48DarkSvg from './Res_Amazon-CloudFront_Streaming-Distribution_48_Dark.svg';
import _resAmazonRoute53HostedZone48DarkSvg from './Res_Amazon-Route-53-Hosted-Zone_48_Dark.svg';
import _resAmazonRoute53ApplicationRecoveryController48DarkSvg from './Res_Amazon-Route-53_Application-Recovery-Controller_48_Dark.svg';
import _resAmazonRoute53ReadinessChecks48DarkSvg from './Res_Amazon-Route-53_Readiness-Checks_48_Dark.svg';
import _resAmazonRoute53ResolverDnsFirewall48DarkSvg from './Res_Amazon-Route-53_Resolver-DNS-Firewall_48_Dark.svg';
import _resAmazonRoute53ResolverQueryLogging48DarkSvg from './Res_Amazon-Route-53_Resolver-Query-Logging_48_Dark.svg';
import _resAmazonRoute53Resolver48DarkSvg from './Res_Amazon-Route-53_Resolver_48_Dark.svg';
import _resAmazonRoute53RouteTable48DarkSvg from './Res_Amazon-Route-53_Route-Table_48_Dark.svg';
import _resAmazonRoute53RoutingControls48DarkSvg from './Res_Amazon-Route-53_Routing-Controls_48_Dark.svg';
import _resAmazonVpcCarrierGateway48DarkSvg from './Res_Amazon-VPC_Carrier-Gateway_48_Dark.svg';
import _resAmazonVpcCustomerGateway48DarkSvg from './Res_Amazon-VPC_Customer-Gateway_48_Dark.svg';
import _resAmazonVpcElasticNetworkAdapter48DarkSvg from './Res_Amazon-VPC_Elastic-Network-Adapter_48_Dark.svg';
import _resAmazonVpcElasticNetworkInterface48DarkSvg from './Res_Amazon-VPC_Elastic-Network-Interface_48_Dark.svg';
import _resAmazonVpcEndpoints48DarkSvg from './Res_Amazon-VPC_Endpoints_48_Dark.svg';
import _resAmazonVpcFlowLogs48DarkSvg from './Res_Amazon-VPC_Flow-Logs_48_Dark.svg';
import _resAmazonVpcInternetGateway48DarkSvg from './Res_Amazon-VPC_Internet-Gateway_48_Dark.svg';
import _resAmazonVpcNatGateway48DarkSvg from './Res_Amazon-VPC_NAT-Gateway_48_Dark.svg';
import _resAmazonVpcNetworkAccessAnalyzer48DarkSvg from './Res_Amazon-VPC_Network-Access-Analyzer_48_Dark.svg';
import _resAmazonVpcNetworkAccessControlList48DarkSvg from './Res_Amazon-VPC_Network-Access-Control-List_48_Dark.svg';
import _resAmazonVpcPeeringConnection48DarkSvg from './Res_Amazon-VPC_Peering-Connection_48_Dark.svg';
import _resAmazonVpcReachabilityAnalyzer48DarkSvg from './Res_Amazon-VPC_Reachability-Analyzer_48_Dark.svg';
import _resAmazonVpcRouter48DarkSvg from './Res_Amazon-VPC_Router_48_Dark.svg';
import _resAmazonVpcTrafficMirroring48DarkSvg from './Res_Amazon-VPC_Traffic-Mirroring_48_Dark.svg';
import _resAmazonVpcVpnConnection48DarkSvg from './Res_Amazon-VPC_VPN-Connection_48_Dark.svg';
import _resAmazonVpcVpnGateway48DarkSvg from './Res_Amazon-VPC_VPN-Gateway_48_Dark.svg';
import _resElasticLoadBalancingApplicationLoadBalancer48DarkSvg from './Res_Elastic-Load-Balancing_Application-Load-Balancer_48_Dark.svg';
import _resElasticLoadBalancingClassicLoadBalancer48DarkSvg from './Res_Elastic-Load-Balancing_Classic-Load-Balancer_48_Dark.svg';
import _resElasticLoadBalancingGatewayLoadBalancer48DarkSvg from './Res_Elastic-Load-Balancing_Gateway-Load-Balancer_48_Dark.svg';
import _resElasticLoadBalancingNetworkLoadBalancer48DarkSvg from './Res_Elastic-Load-Balancing_Network-Load-Balancer_48_Dark.svg';

export const resAwsAppMeshMesh48DarkSvg = { id: "resAwsAppMeshMesh48DarkSvg", name: "AWS App Mesh / Mesh", icon: _resAwsAppMeshMesh48DarkSvg };
export const resAwsAppMeshVirtualGateway48DarkSvg = { id: "resAwsAppMeshVirtualGateway48DarkSvg", name: "AWS App Mesh / Virtual Gateway", icon: _resAwsAppMeshVirtualGateway48DarkSvg };
export const resAwsAppMeshVirtualNode48DarkSvg = { id: "resAwsAppMeshVirtualNode48DarkSvg", name: "AWS App Mesh / Virtual Node", icon: _resAwsAppMeshVirtualNode48DarkSvg };
export const resAwsAppMeshVirtualRouter48DarkSvg = { id: "resAwsAppMeshVirtualRouter48DarkSvg", name: "AWS App Mesh / Virtual Router", icon: _resAwsAppMeshVirtualRouter48DarkSvg };
export const resAwsAppMeshVirtualService48DarkSvg = { id: "resAwsAppMeshVirtualService48DarkSvg", name: "AWS App Mesh / Virtual Service", icon: _resAwsAppMeshVirtualService48DarkSvg };
export const resAwsCloudMapNamespace48DarkSvg = { id: "resAwsCloudMapNamespace48DarkSvg", name: "AWS Cloud Map / Namespace", icon: _resAwsCloudMapNamespace48DarkSvg };
export const resAwsCloudMapResource48DarkSvg = { id: "resAwsCloudMapResource48DarkSvg", name: "AWS Cloud Map / Resource", icon: _resAwsCloudMapResource48DarkSvg };
export const resAwsCloudMapService48DarkSvg = { id: "resAwsCloudMapService48DarkSvg", name: "AWS Cloud Map / Service", icon: _resAwsCloudMapService48DarkSvg };
export const resAwsCloudWanCoreNetworkEdge48DarkSvg = { id: "resAwsCloudWanCoreNetworkEdge48DarkSvg", name: "AWS Cloud WAN / Core Network Edge", icon: _resAwsCloudWanCoreNetworkEdge48DarkSvg };
export const resAwsCloudWanSegmentNetwork48DarkSvg = { id: "resAwsCloudWanSegmentNetwork48DarkSvg", name: "AWS Cloud WAN / Segment Network", icon: _resAwsCloudWanSegmentNetwork48DarkSvg };
export const resAwsCloudWanVirtualPoP48DarkSvg = { id: "resAwsCloudWanVirtualPoP48DarkSvg", name: "AWS Cloud WAN / Virtual PoP", icon: _resAwsCloudWanVirtualPoP48DarkSvg };
export const resAwsDirectConnectGateway48DarkSvg = { id: "resAwsDirectConnectGateway48DarkSvg", name: "AWS Direct Connect / Gateway", icon: _resAwsDirectConnectGateway48DarkSvg };
export const resAwsTransitGatewayAttachment48DarkSvg = { id: "resAwsTransitGatewayAttachment48DarkSvg", name: "AWS Transit Gateway / Attachment", icon: _resAwsTransitGatewayAttachment48DarkSvg };
export const resAmazonCloudFrontDownloadDistribution48DarkSvg = { id: "resAmazonCloudFrontDownloadDistribution48DarkSvg", name: "Amazon CloudFront / Download Distribution", icon: _resAmazonCloudFrontDownloadDistribution48DarkSvg };
export const resAmazonCloudFrontEdgeLocation48DarkSvg = { id: "resAmazonCloudFrontEdgeLocation48DarkSvg", name: "Amazon CloudFront / Edge Location", icon: _resAmazonCloudFrontEdgeLocation48DarkSvg };
export const resAmazonCloudFrontFunctions48DarkSvg = { id: "resAmazonCloudFrontFunctions48DarkSvg", name: "Amazon CloudFront / Functions", icon: _resAmazonCloudFrontFunctions48DarkSvg };
export const resAmazonCloudFrontStreamingDistribution48DarkSvg = { id: "resAmazonCloudFrontStreamingDistribution48DarkSvg", name: "Amazon CloudFront / Streaming Distribution", icon: _resAmazonCloudFrontStreamingDistribution48DarkSvg };
export const resAmazonRoute53HostedZone48DarkSvg = { id: "resAmazonRoute53HostedZone48DarkSvg", name: "Amazon Route 53 Hosted Zone", icon: _resAmazonRoute53HostedZone48DarkSvg };
export const resAmazonRoute53ApplicationRecoveryController48DarkSvg = { id: "resAmazonRoute53ApplicationRecoveryController48DarkSvg", name: "Amazon Route 53 / Application Recovery Controller", icon: _resAmazonRoute53ApplicationRecoveryController48DarkSvg };
export const resAmazonRoute53ReadinessChecks48DarkSvg = { id: "resAmazonRoute53ReadinessChecks48DarkSvg", name: "Amazon Route 53 / Readiness Checks", icon: _resAmazonRoute53ReadinessChecks48DarkSvg };
export const resAmazonRoute53ResolverDnsFirewall48DarkSvg = { id: "resAmazonRoute53ResolverDnsFirewall48DarkSvg", name: "Amazon Route 53 / Resolver DNS Firewall", icon: _resAmazonRoute53ResolverDnsFirewall48DarkSvg };
export const resAmazonRoute53ResolverQueryLogging48DarkSvg = { id: "resAmazonRoute53ResolverQueryLogging48DarkSvg", name: "Amazon Route 53 / Resolver Query Logging", icon: _resAmazonRoute53ResolverQueryLogging48DarkSvg };
export const resAmazonRoute53Resolver48DarkSvg = { id: "resAmazonRoute53Resolver48DarkSvg", name: "Amazon Route 53 / Resolver", icon: _resAmazonRoute53Resolver48DarkSvg };
export const resAmazonRoute53RouteTable48DarkSvg = { id: "resAmazonRoute53RouteTable48DarkSvg", name: "Amazon Route 53 / Route Table", icon: _resAmazonRoute53RouteTable48DarkSvg };
export const resAmazonRoute53RoutingControls48DarkSvg = { id: "resAmazonRoute53RoutingControls48DarkSvg", name: "Amazon Route 53 / Routing Controls", icon: _resAmazonRoute53RoutingControls48DarkSvg };
export const resAmazonVpcCarrierGateway48DarkSvg = { id: "resAmazonVpcCarrierGateway48DarkSvg", name: "Amazon VPC / Carrier Gateway", icon: _resAmazonVpcCarrierGateway48DarkSvg };
export const resAmazonVpcCustomerGateway48DarkSvg = { id: "resAmazonVpcCustomerGateway48DarkSvg", name: "Amazon VPC / Customer Gateway", icon: _resAmazonVpcCustomerGateway48DarkSvg };
export const resAmazonVpcElasticNetworkAdapter48DarkSvg = { id: "resAmazonVpcElasticNetworkAdapter48DarkSvg", name: "Amazon VPC / Elastic Network Adapter", icon: _resAmazonVpcElasticNetworkAdapter48DarkSvg };
export const resAmazonVpcElasticNetworkInterface48DarkSvg = { id: "resAmazonVpcElasticNetworkInterface48DarkSvg", name: "Amazon VPC / Elastic Network Interface", icon: _resAmazonVpcElasticNetworkInterface48DarkSvg };
export const resAmazonVpcEndpoints48DarkSvg = { id: "resAmazonVpcEndpoints48DarkSvg", name: "Amazon VPC / Endpoints", icon: _resAmazonVpcEndpoints48DarkSvg };
export const resAmazonVpcFlowLogs48DarkSvg = { id: "resAmazonVpcFlowLogs48DarkSvg", name: "Amazon VPC / Flow Logs", icon: _resAmazonVpcFlowLogs48DarkSvg };
export const resAmazonVpcInternetGateway48DarkSvg = { id: "resAmazonVpcInternetGateway48DarkSvg", name: "Amazon VPC / Internet Gateway", icon: _resAmazonVpcInternetGateway48DarkSvg };
export const resAmazonVpcNatGateway48DarkSvg = { id: "resAmazonVpcNatGateway48DarkSvg", name: "Amazon VPC / NAT Gateway", icon: _resAmazonVpcNatGateway48DarkSvg };
export const resAmazonVpcNetworkAccessAnalyzer48DarkSvg = { id: "resAmazonVpcNetworkAccessAnalyzer48DarkSvg", name: "Amazon VPC / Network Access Analyzer", icon: _resAmazonVpcNetworkAccessAnalyzer48DarkSvg };
export const resAmazonVpcNetworkAccessControlList48DarkSvg = { id: "resAmazonVpcNetworkAccessControlList48DarkSvg", name: "Amazon VPC / Network Access Control List", icon: _resAmazonVpcNetworkAccessControlList48DarkSvg };
export const resAmazonVpcPeeringConnection48DarkSvg = { id: "resAmazonVpcPeeringConnection48DarkSvg", name: "Amazon VPC / Peering Connection", icon: _resAmazonVpcPeeringConnection48DarkSvg };
export const resAmazonVpcReachabilityAnalyzer48DarkSvg = { id: "resAmazonVpcReachabilityAnalyzer48DarkSvg", name: "Amazon VPC / Reachability Analyzer", icon: _resAmazonVpcReachabilityAnalyzer48DarkSvg };
export const resAmazonVpcRouter48DarkSvg = { id: "resAmazonVpcRouter48DarkSvg", name: "Amazon VPC / Router", icon: _resAmazonVpcRouter48DarkSvg };
export const resAmazonVpcTrafficMirroring48DarkSvg = { id: "resAmazonVpcTrafficMirroring48DarkSvg", name: "Amazon VPC / Traffic Mirroring", icon: _resAmazonVpcTrafficMirroring48DarkSvg };
export const resAmazonVpcVpnConnection48DarkSvg = { id: "resAmazonVpcVpnConnection48DarkSvg", name: "Amazon VPC / VPN Connection", icon: _resAmazonVpcVpnConnection48DarkSvg };
export const resAmazonVpcVpnGateway48DarkSvg = { id: "resAmazonVpcVpnGateway48DarkSvg", name: "Amazon VPC / VPN Gateway", icon: _resAmazonVpcVpnGateway48DarkSvg };
export const resElasticLoadBalancingApplicationLoadBalancer48DarkSvg = { id: "resElasticLoadBalancingApplicationLoadBalancer48DarkSvg", name: "Elastic Load Balancing / Application Load Balancer", icon: _resElasticLoadBalancingApplicationLoadBalancer48DarkSvg };
export const resElasticLoadBalancingClassicLoadBalancer48DarkSvg = { id: "resElasticLoadBalancingClassicLoadBalancer48DarkSvg", name: "Elastic Load Balancing / Classic Load Balancer", icon: _resElasticLoadBalancingClassicLoadBalancer48DarkSvg };
export const resElasticLoadBalancingGatewayLoadBalancer48DarkSvg = { id: "resElasticLoadBalancingGatewayLoadBalancer48DarkSvg", name: "Elastic Load Balancing / Gateway Load Balancer", icon: _resElasticLoadBalancingGatewayLoadBalancer48DarkSvg };
export const resElasticLoadBalancingNetworkLoadBalancer48DarkSvg = { id: "resElasticLoadBalancingNetworkLoadBalancer48DarkSvg", name: "Elastic Load Balancing / Network Load Balancer", icon: _resElasticLoadBalancingNetworkLoadBalancer48DarkSvg };
