import _archAwsDataExchange16Svg from './Arch_AWS-Data-Exchange_16.svg';
import _archAwsDataPipeline16Svg from './Arch_AWS-Data-Pipeline_16.svg';
import _archAwsGlueDataBrew16Svg from './Arch_AWS-Glue-DataBrew_16.svg';
import _archAwsGlueElasticViews16Svg from './Arch_AWS-Glue-Elastic-Views_16.svg';
import _archAwsGlue16Svg from './Arch_AWS-Glue_16.svg';
import _archAwsLakeFormation16Svg from './Arch_AWS-Lake-Formation_16.svg';
import _archAmazonAthena16Svg from './Arch_Amazon-Athena_16.svg';
import _archAmazonCloudSearch16Svg from './Arch_Amazon-CloudSearch_16.svg';
import _archAmazonEmr16Svg from './Arch_Amazon-EMR_16.svg';
import _archAmazonFinSpace16Svg from './Arch_Amazon-FinSpace_16.svg';
import _archAmazonKinesisDataAnalytics16Svg from './Arch_Amazon-Kinesis-Data-Analytics_16.svg';
import _archAmazonKinesisDataStreams16Svg from './Arch_Amazon-Kinesis-Data-Streams_16.svg';
import _archAmazonKinesisFirehose16Svg from './Arch_Amazon-Kinesis-Firehose_16.svg';
import _archAmazonKinesisVideoStreams16Svg from './Arch_Amazon-Kinesis-Video-Streams_16.svg';
import _archAmazonKinesis16Svg from './Arch_Amazon-Kinesis_16.svg';
import _archAmazonManagedStreamingForApacheKafka16Svg from './Arch_Amazon-Managed-Streaming-for-Apache-Kafka_16.svg';
import _archAmazonOpenSearchService16Svg from './Arch_Amazon-OpenSearch-Service_16.svg';
import _archAmazonQuickSight16Svg from './Arch_Amazon-QuickSight_16.svg';
import _archAmazonRedshift16Svg from './Arch_Amazon-Redshift_16.svg';

export const archAwsDataExchange16Svg = { id: "archAwsDataExchange16Svg", name: "AWS Data Exchange", icon: _archAwsDataExchange16Svg };
export const archAwsDataPipeline16Svg = { id: "archAwsDataPipeline16Svg", name: "AWS Data Pipeline", icon: _archAwsDataPipeline16Svg };
export const archAwsGlueDataBrew16Svg = { id: "archAwsGlueDataBrew16Svg", name: "AWS Glue DataBrew", icon: _archAwsGlueDataBrew16Svg };
export const archAwsGlueElasticViews16Svg = { id: "archAwsGlueElasticViews16Svg", name: "AWS Glue Elastic Views", icon: _archAwsGlueElasticViews16Svg };
export const archAwsGlue16Svg = { id: "archAwsGlue16Svg", name: "AWS Glue", icon: _archAwsGlue16Svg };
export const archAwsLakeFormation16Svg = { id: "archAwsLakeFormation16Svg", name: "AWS Lake Formation", icon: _archAwsLakeFormation16Svg };
export const archAmazonAthena16Svg = { id: "archAmazonAthena16Svg", name: "Amazon Athena", icon: _archAmazonAthena16Svg };
export const archAmazonCloudSearch16Svg = { id: "archAmazonCloudSearch16Svg", name: "Amazon CloudSearch", icon: _archAmazonCloudSearch16Svg };
export const archAmazonEmr16Svg = { id: "archAmazonEmr16Svg", name: "Amazon EMR", icon: _archAmazonEmr16Svg };
export const archAmazonFinSpace16Svg = { id: "archAmazonFinSpace16Svg", name: "Amazon FinSpace", icon: _archAmazonFinSpace16Svg };
export const archAmazonKinesisDataAnalytics16Svg = { id: "archAmazonKinesisDataAnalytics16Svg", name: "Amazon Kinesis Data Analytics", icon: _archAmazonKinesisDataAnalytics16Svg };
export const archAmazonKinesisDataStreams16Svg = { id: "archAmazonKinesisDataStreams16Svg", name: "Amazon Kinesis Data Streams", icon: _archAmazonKinesisDataStreams16Svg };
export const archAmazonKinesisFirehose16Svg = { id: "archAmazonKinesisFirehose16Svg", name: "Amazon Kinesis Firehose", icon: _archAmazonKinesisFirehose16Svg };
export const archAmazonKinesisVideoStreams16Svg = { id: "archAmazonKinesisVideoStreams16Svg", name: "Amazon Kinesis Video Streams", icon: _archAmazonKinesisVideoStreams16Svg };
export const archAmazonKinesis16Svg = { id: "archAmazonKinesis16Svg", name: "Amazon Kinesis", icon: _archAmazonKinesis16Svg };
export const archAmazonManagedStreamingForApacheKafka16Svg = { id: "archAmazonManagedStreamingForApacheKafka16Svg", name: "Amazon Managed Streaming for Apache Kafka", icon: _archAmazonManagedStreamingForApacheKafka16Svg };
export const archAmazonOpenSearchService16Svg = { id: "archAmazonOpenSearchService16Svg", name: "Amazon OpenSearch Service", icon: _archAmazonOpenSearchService16Svg };
export const archAmazonQuickSight16Svg = { id: "archAmazonQuickSight16Svg", name: "Amazon QuickSight", icon: _archAmazonQuickSight16Svg };
export const archAmazonRedshift16Svg = { id: "archAmazonRedshift16Svg", name: "Amazon Redshift", icon: _archAmazonRedshift16Svg };
