import _archAwsDatabaseMigrationService64Svg from './Arch_AWS-Database-Migration-Service_64.svg';
import _archAmazonAurora64Svg from './Arch_Amazon-Aurora_64.svg';
import _archAmazonDocumentDb64Svg from './Arch_Amazon-DocumentDB_64.svg';
import _archAmazonDynamoDb64Svg from './Arch_Amazon-DynamoDB_64.svg';
import _archAmazonElastiCache64Svg from './Arch_Amazon-ElastiCache_64.svg';
import _archAmazonKeyspaces64Svg from './Arch_Amazon-Keyspaces_64.svg';
import _archAmazonMemoryDbForRedis64Svg from './Arch_Amazon-MemoryDB-for-Redis_64.svg';
import _archAmazonNeptune64Svg from './Arch_Amazon-Neptune_64.svg';
import _archAmazonQuantumLedgerDatabase64Svg from './Arch_Amazon-Quantum-Ledger-Database_64.svg';
import _archAmazonRdsOnVmware64Svg from './Arch_Amazon-RDS-on-VMware_64.svg';
import _archAmazonRds64Svg from './Arch_Amazon-RDS_64.svg';
import _archAmazonTimestream64Svg from './Arch_Amazon-Timestream_64.svg';

export const archAwsDatabaseMigrationService64Svg = { id: "archAwsDatabaseMigrationService64Svg", name: "AWS Database Migration Service", icon: _archAwsDatabaseMigrationService64Svg };
export const archAmazonAurora64Svg = { id: "archAmazonAurora64Svg", name: "Amazon Aurora", icon: _archAmazonAurora64Svg };
export const archAmazonDocumentDb64Svg = { id: "archAmazonDocumentDb64Svg", name: "Amazon DocumentDB", icon: _archAmazonDocumentDb64Svg };
export const archAmazonDynamoDb64Svg = { id: "archAmazonDynamoDb64Svg", name: "Amazon DynamoDB", icon: _archAmazonDynamoDb64Svg };
export const archAmazonElastiCache64Svg = { id: "archAmazonElastiCache64Svg", name: "Amazon ElastiCache", icon: _archAmazonElastiCache64Svg };
export const archAmazonKeyspaces64Svg = { id: "archAmazonKeyspaces64Svg", name: "Amazon Keyspaces", icon: _archAmazonKeyspaces64Svg };
export const archAmazonMemoryDbForRedis64Svg = { id: "archAmazonMemoryDbForRedis64Svg", name: "Amazon MemoryDB for Redis", icon: _archAmazonMemoryDbForRedis64Svg };
export const archAmazonNeptune64Svg = { id: "archAmazonNeptune64Svg", name: "Amazon Neptune", icon: _archAmazonNeptune64Svg };
export const archAmazonQuantumLedgerDatabase64Svg = { id: "archAmazonQuantumLedgerDatabase64Svg", name: "Amazon Quantum Ledger Database", icon: _archAmazonQuantumLedgerDatabase64Svg };
export const archAmazonRdsOnVmware64Svg = { id: "archAmazonRdsOnVmware64Svg", name: "Amazon RDS on VMware", icon: _archAmazonRdsOnVmware64Svg };
export const archAmazonRds64Svg = { id: "archAmazonRds64Svg", name: "Amazon RDS", icon: _archAmazonRds64Svg };
export const archAmazonTimestream64Svg = { id: "archAmazonTimestream64Svg", name: "Amazon Timestream", icon: _archAmazonTimestream64Svg };
