import _archAwsAppRunner32Svg from './Arch_AWS-App-Runner_32.svg';
import _archAwsBatch32Svg from './Arch_AWS-Batch_32.svg';
import _archAwsComputeOptimizer32Svg from './Arch_AWS-Compute-Optimizer_32.svg';
import _archAwsElasticBeanstalk32Svg from './Arch_AWS-Elastic-Beanstalk_32.svg';
import _archAwsFargate32Svg from './Arch_AWS-Fargate_32.svg';
import _archAwsLambda32Svg from './Arch_AWS-Lambda_32.svg';
import _archAwsLocalZones32Svg from './Arch_AWS-Local-Zones_32.svg';
import _archAwsNitroEnclaves32Svg from './Arch_AWS-Nitro-Enclaves_32.svg';
import _archAwsOutpostsFamily32Svg from './Arch_AWS-Outposts-family_32.svg';
import _archAwsOutpostsRack32Svg from './Arch_AWS-Outposts-rack_32.svg';
import _archAwsOutpostsServers32Svg from './Arch_AWS-Outposts-servers_32.svg';
import _archAwsParallelCluster32Svg from './Arch_AWS-ParallelCluster_32.svg';
import _archAwsServerlessApplicationRepository32Svg from './Arch_AWS-Serverless-Application-Repository_32.svg';
import _archAwsThinkboxDeadline32Svg from './Arch_AWS-Thinkbox-Deadline_32.svg';
import _archAwsThinkboxFrost32Svg from './Arch_AWS-Thinkbox-Frost_32.svg';
import _archAwsThinkboxKrakatoa32Svg from './Arch_AWS-Thinkbox-Krakatoa_32.svg';
import _archAwsThinkboxSequoia32Svg from './Arch_AWS-Thinkbox-Sequoia_32.svg';
import _archAwsThinkboxStoke32Svg from './Arch_AWS-Thinkbox-Stoke_32.svg';
import _archAwsThinkboxXmesh32Svg from './Arch_AWS-Thinkbox-XMesh_32.svg';
import _archAwsWavelength32Svg from './Arch_AWS-Wavelength_32.svg';
import _archAmazonEc2AutoScaling32Svg from './Arch_Amazon-EC2-Auto-Scaling_32.svg';
import _archAmazonEc2ImageBuilder32Svg from './Arch_Amazon-EC2-Image-Builder_32.svg';
import _archAmazonEc2M5N32Svg from './Arch_Amazon-EC2-M5n_32.svg';
import _archAmazonEc2R5N32Svg from './Arch_Amazon-EC2-R5n_32.svg';
import _archAmazonEc232Svg from './Arch_Amazon-EC2_32.svg';
import _archAmazonElasticContainerKubernetes32Svg from './Arch_Amazon-Elastic-Container-Kubernetes_32.svg';
import _archAmazonElasticContainerRegistry32Svg from './Arch_Amazon-Elastic-Container-Registry_32.svg';
import _archAmazonElasticContainerService32Svg from './Arch_Amazon-Elastic-Container-Service_32.svg';
import _archAmazonGenomicsCli32Svg from './Arch_Amazon-Genomics-CLI_32.svg';
import _archAmazonLightsail32Svg from './Arch_Amazon-Lightsail_32.svg';
import _archBottlerocket32Svg from './Arch_Bottlerocket_32.svg';
import _archElasticFabricAdapter32Svg from './Arch_Elastic-Fabric-Adapter_32.svg';
import _archNiceDcv32Svg from './Arch_NICE-DCV_32.svg';
import _archNiceEnginFrame32Svg from './Arch_NICE-EnginFrame_32.svg';
import _archVMwareCloudOnAws32Svg from './Arch_VMware-Cloud-on-AWS_32.svg';

export const archAwsAppRunner32Svg = { id: "archAwsAppRunner32Svg", name: "AWS App Runner", icon: _archAwsAppRunner32Svg };
export const archAwsBatch32Svg = { id: "archAwsBatch32Svg", name: "AWS Batch", icon: _archAwsBatch32Svg };
export const archAwsComputeOptimizer32Svg = { id: "archAwsComputeOptimizer32Svg", name: "AWS Compute Optimizer", icon: _archAwsComputeOptimizer32Svg };
export const archAwsElasticBeanstalk32Svg = { id: "archAwsElasticBeanstalk32Svg", name: "AWS Elastic Beanstalk", icon: _archAwsElasticBeanstalk32Svg };
export const archAwsFargate32Svg = { id: "archAwsFargate32Svg", name: "AWS Fargate", icon: _archAwsFargate32Svg };
export const archAwsLambda32Svg = { id: "archAwsLambda32Svg", name: "AWS Lambda", icon: _archAwsLambda32Svg };
export const archAwsLocalZones32Svg = { id: "archAwsLocalZones32Svg", name: "AWS Local Zones", icon: _archAwsLocalZones32Svg };
export const archAwsNitroEnclaves32Svg = { id: "archAwsNitroEnclaves32Svg", name: "AWS Nitro Enclaves", icon: _archAwsNitroEnclaves32Svg };
export const archAwsOutpostsFamily32Svg = { id: "archAwsOutpostsFamily32Svg", name: "AWS Outposts family", icon: _archAwsOutpostsFamily32Svg };
export const archAwsOutpostsRack32Svg = { id: "archAwsOutpostsRack32Svg", name: "AWS Outposts rack", icon: _archAwsOutpostsRack32Svg };
export const archAwsOutpostsServers32Svg = { id: "archAwsOutpostsServers32Svg", name: "AWS Outposts servers", icon: _archAwsOutpostsServers32Svg };
export const archAwsParallelCluster32Svg = { id: "archAwsParallelCluster32Svg", name: "AWS ParallelCluster", icon: _archAwsParallelCluster32Svg };
export const archAwsServerlessApplicationRepository32Svg = { id: "archAwsServerlessApplicationRepository32Svg", name: "AWS Serverless Application Repository", icon: _archAwsServerlessApplicationRepository32Svg };
export const archAwsThinkboxDeadline32Svg = { id: "archAwsThinkboxDeadline32Svg", name: "AWS Thinkbox Deadline", icon: _archAwsThinkboxDeadline32Svg };
export const archAwsThinkboxFrost32Svg = { id: "archAwsThinkboxFrost32Svg", name: "AWS Thinkbox Frost", icon: _archAwsThinkboxFrost32Svg };
export const archAwsThinkboxKrakatoa32Svg = { id: "archAwsThinkboxKrakatoa32Svg", name: "AWS Thinkbox Krakatoa", icon: _archAwsThinkboxKrakatoa32Svg };
export const archAwsThinkboxSequoia32Svg = { id: "archAwsThinkboxSequoia32Svg", name: "AWS Thinkbox Sequoia", icon: _archAwsThinkboxSequoia32Svg };
export const archAwsThinkboxStoke32Svg = { id: "archAwsThinkboxStoke32Svg", name: "AWS Thinkbox Stoke", icon: _archAwsThinkboxStoke32Svg };
export const archAwsThinkboxXmesh32Svg = { id: "archAwsThinkboxXmesh32Svg", name: "AWS Thinkbox XMesh", icon: _archAwsThinkboxXmesh32Svg };
export const archAwsWavelength32Svg = { id: "archAwsWavelength32Svg", name: "AWS Wavelength", icon: _archAwsWavelength32Svg };
export const archAmazonEc2AutoScaling32Svg = { id: "archAmazonEc2AutoScaling32Svg", name: "Amazon EC2 Auto Scaling", icon: _archAmazonEc2AutoScaling32Svg };
export const archAmazonEc2ImageBuilder32Svg = { id: "archAmazonEc2ImageBuilder32Svg", name: "Amazon EC2 Image Builder", icon: _archAmazonEc2ImageBuilder32Svg };
export const archAmazonEc2M5N32Svg = { id: "archAmazonEc2M5N32Svg", name: "Amazon EC2 M5n", icon: _archAmazonEc2M5N32Svg };
export const archAmazonEc2R5N32Svg = { id: "archAmazonEc2R5N32Svg", name: "Amazon EC2 R5n", icon: _archAmazonEc2R5N32Svg };
export const archAmazonEc232Svg = { id: "archAmazonEc232Svg", name: "Amazon EC2", icon: _archAmazonEc232Svg };
export const archAmazonElasticContainerKubernetes32Svg = { id: "archAmazonElasticContainerKubernetes32Svg", name: "Amazon Elastic Container Kubernetes", icon: _archAmazonElasticContainerKubernetes32Svg };
export const archAmazonElasticContainerRegistry32Svg = { id: "archAmazonElasticContainerRegistry32Svg", name: "Amazon Elastic Container Registry", icon: _archAmazonElasticContainerRegistry32Svg };
export const archAmazonElasticContainerService32Svg = { id: "archAmazonElasticContainerService32Svg", name: "Amazon Elastic Container Service", icon: _archAmazonElasticContainerService32Svg };
export const archAmazonGenomicsCli32Svg = { id: "archAmazonGenomicsCli32Svg", name: "Amazon Genomics CLI", icon: _archAmazonGenomicsCli32Svg };
export const archAmazonLightsail32Svg = { id: "archAmazonLightsail32Svg", name: "Amazon Lightsail", icon: _archAmazonLightsail32Svg };
export const archBottlerocket32Svg = { id: "archBottlerocket32Svg", name: "Bottlerocket", icon: _archBottlerocket32Svg };
export const archElasticFabricAdapter32Svg = { id: "archElasticFabricAdapter32Svg", name: "Elastic Fabric Adapter", icon: _archElasticFabricAdapter32Svg };
export const archNiceDcv32Svg = { id: "archNiceDcv32Svg", name: "NICE DCV", icon: _archNiceDcv32Svg };
export const archNiceEnginFrame32Svg = { id: "archNiceEnginFrame32Svg", name: "NICE EnginFrame", icon: _archNiceEnginFrame32Svg };
export const archVMwareCloudOnAws32Svg = { id: "archVMwareCloudOnAws32Svg", name: "VMware Cloud on AWS", icon: _archVMwareCloudOnAws32Svg };
