export { default as archAmazonApiGateway32Svg } from './Arch_ Amazon-API-Gateway_32.svg';
export { default as archAwsAppSync32Svg } from './Arch_AWS-AppSync_32.svg';
export { default as archAwsConsoleMobileApplication32Svg } from './Arch_AWS-Console-Mobile-Application _32.svg';
export { default as archAwsExpressWorkflows32Svg } from './Arch_AWS-Express-Workflows_32.svg';
export { default as archAwsStepFunctions32Svg } from './Arch_AWS-Step-Functions_32.svg';
export { default as archAmazonAppFlow32Svg } from './Arch_Amazon-AppFlow_32.svg';
export { default as archAmazonEventBridge32Svg } from './Arch_Amazon-EventBridge_32.svg';
export { default as archAmazonMq32Svg } from './Arch_Amazon-MQ_32.svg';
export { default as archAmazonManagedWorkflowsForApacheAirflow32Svg } from './Arch_Amazon-Managed-Workflows-for-Apache-Airflow_32.svg';
export { default as archAmazonSimpleNotificationService32Svg } from './Arch_Amazon-Simple-Notification-Service_32.svg';
export { default as archAmazonSimpleQueueService32Svg } from './Arch_Amazon-Simple-Queue-Service_32.svg';