import _archAwsArtifact16Svg from './Arch_AWS-Artifact_16.svg';
import _archAwsAuditManager16Svg from './Arch_AWS-Audit-Manager_16.svg';
import _archAwsCertificateManager16Svg from './Arch_AWS-Certificate-Manager_16.svg';
import _archAwsCloudHsm16Svg from './Arch_AWS-CloudHSM_16.svg';
import _archAwsDirectoryService16Svg from './Arch_AWS-Directory-Service_16.svg';
import _archAwsFirewallManager16Svg from './Arch_AWS-Firewall-Manager_16.svg';
import _archAwsIamIdentityCenter16Svg from './Arch_AWS-IAM-Identity-Center_16.svg';
import _archAwsIdentityAndAccessManagement16Svg from './Arch_AWS-Identity-and-Access-Management_16.svg';
import _archAwsKeyManagementService16Svg from './Arch_AWS-Key-Management-Service_16.svg';
import _archAwsNetworkFirewall16Svg from './Arch_AWS-Network-Firewall_16.svg';
import _archAwsResourceAccessManager16Svg from './Arch_AWS-Resource-Access-Manager_16.svg';
import _archAwsSecretsManager16Svg from './Arch_AWS-Secrets-Manager_16.svg';
import _archAwsSecurityHub16Svg from './Arch_AWS-Security-Hub_16.svg';
import _archAwsShield16Svg from './Arch_AWS-Shield_16.svg';
import _archAwsSigner16Svg from './Arch_AWS-Signer_16.svg';
import _archAwsWaf16Svg from './Arch_AWS-WAF_16.svg';
import _archAmazonCloudDirectory16Svg from './Arch_Amazon-Cloud-Directory_16.svg';
import _archAmazonCognito16Svg from './Arch_Amazon-Cognito_16.svg';
import _archAmazonDetective16Svg from './Arch_Amazon-Detective_16.svg';
import _archAmazonGuardDuty16Svg from './Arch_Amazon-GuardDuty_16.svg';
import _archAmazonInspector16Svg from './Arch_Amazon-Inspector_16.svg';
import _archAmazonMacie16Svg from './Arch_Amazon-Macie_16.svg';

export const archAwsArtifact16Svg = { id: "archAwsArtifact16Svg", name: "AWS Artifact", icon: _archAwsArtifact16Svg };
export const archAwsAuditManager16Svg = { id: "archAwsAuditManager16Svg", name: "AWS Audit Manager", icon: _archAwsAuditManager16Svg };
export const archAwsCertificateManager16Svg = { id: "archAwsCertificateManager16Svg", name: "AWS Certificate Manager", icon: _archAwsCertificateManager16Svg };
export const archAwsCloudHsm16Svg = { id: "archAwsCloudHsm16Svg", name: "AWS CloudHSM", icon: _archAwsCloudHsm16Svg };
export const archAwsDirectoryService16Svg = { id: "archAwsDirectoryService16Svg", name: "AWS Directory Service", icon: _archAwsDirectoryService16Svg };
export const archAwsFirewallManager16Svg = { id: "archAwsFirewallManager16Svg", name: "AWS Firewall Manager", icon: _archAwsFirewallManager16Svg };
export const archAwsIamIdentityCenter16Svg = { id: "archAwsIamIdentityCenter16Svg", name: "AWS IAM Identity Center", icon: _archAwsIamIdentityCenter16Svg };
export const archAwsIdentityAndAccessManagement16Svg = { id: "archAwsIdentityAndAccessManagement16Svg", name: "AWS Identity and Access Management", icon: _archAwsIdentityAndAccessManagement16Svg };
export const archAwsKeyManagementService16Svg = { id: "archAwsKeyManagementService16Svg", name: "AWS Key Management Service", icon: _archAwsKeyManagementService16Svg };
export const archAwsNetworkFirewall16Svg = { id: "archAwsNetworkFirewall16Svg", name: "AWS Network Firewall", icon: _archAwsNetworkFirewall16Svg };
export const archAwsResourceAccessManager16Svg = { id: "archAwsResourceAccessManager16Svg", name: "AWS Resource Access Manager", icon: _archAwsResourceAccessManager16Svg };
export const archAwsSecretsManager16Svg = { id: "archAwsSecretsManager16Svg", name: "AWS Secrets Manager", icon: _archAwsSecretsManager16Svg };
export const archAwsSecurityHub16Svg = { id: "archAwsSecurityHub16Svg", name: "AWS Security Hub", icon: _archAwsSecurityHub16Svg };
export const archAwsShield16Svg = { id: "archAwsShield16Svg", name: "AWS Shield", icon: _archAwsShield16Svg };
export const archAwsSigner16Svg = { id: "archAwsSigner16Svg", name: "AWS Signer", icon: _archAwsSigner16Svg };
export const archAwsWaf16Svg = { id: "archAwsWaf16Svg", name: "AWS WAF", icon: _archAwsWaf16Svg };
export const archAmazonCloudDirectory16Svg = { id: "archAmazonCloudDirectory16Svg", name: "Amazon Cloud Directory", icon: _archAmazonCloudDirectory16Svg };
export const archAmazonCognito16Svg = { id: "archAmazonCognito16Svg", name: "Amazon Cognito", icon: _archAmazonCognito16Svg };
export const archAmazonDetective16Svg = { id: "archAmazonDetective16Svg", name: "Amazon Detective", icon: _archAmazonDetective16Svg };
export const archAmazonGuardDuty16Svg = { id: "archAmazonGuardDuty16Svg", name: "Amazon GuardDuty", icon: _archAmazonGuardDuty16Svg };
export const archAmazonInspector16Svg = { id: "archAmazonInspector16Svg", name: "Amazon Inspector", icon: _archAmazonInspector16Svg };
export const archAmazonMacie16Svg = { id: "archAmazonMacie16Svg", name: "Amazon Macie", icon: _archAmazonMacie16Svg };
