import _archAwsDataExchange64Svg from './Arch_AWS-Data-Exchange_64.svg';
import _archAwsDataPipeline64Svg from './Arch_AWS-Data-Pipeline_64.svg';
import _archAwsGlueDataBrew64Svg from './Arch_AWS-Glue-DataBrew_64.svg';
import _archAwsGlueElasticViews64Svg from './Arch_AWS-Glue-Elastic-Views_64.svg';
import _archAwsGlue64Svg from './Arch_AWS-Glue_64.svg';
import _archAwsLakeFormation64Svg from './Arch_AWS-Lake-Formation_64.svg';
import _archAmazonAthena64Svg from './Arch_Amazon-Athena_64.svg';
import _archAmazonCloudSearch64Svg from './Arch_Amazon-CloudSearch_64.svg';
import _archAmazonEmr64Svg from './Arch_Amazon-EMR_64.svg';
import _archAmazonFinSpace64Svg from './Arch_Amazon-FinSpace_64.svg';
import _archAmazonKinesisDataAnalytics64Svg from './Arch_Amazon-Kinesis-Data-Analytics_64.svg';
import _archAmazonKinesisDataStreams64Svg from './Arch_Amazon-Kinesis-Data-Streams_64.svg';
import _archAmazonKinesisFirehose64Svg from './Arch_Amazon-Kinesis-Firehose_64.svg';
import _archAmazonKinesisVideoStreams64Svg from './Arch_Amazon-Kinesis-Video-Streams_64.svg';
import _archAmazonKinesis64Svg from './Arch_Amazon-Kinesis_64.svg';
import _archAmazonManagedStreamingForApacheKafka64Svg from './Arch_Amazon-Managed-Streaming-for-Apache-Kafka_64.svg';
import _archAmazonOpenSearchService64Svg from './Arch_Amazon-OpenSearch-Service_64.svg';
import _archAmazonQuickSight64Svg from './Arch_Amazon-QuickSight_64.svg';
import _archAmazonRedshift64Svg from './Arch_Amazon-Redshift_64.svg';

export const archAwsDataExchange64Svg = { id: "archAwsDataExchange64Svg", name: "AWS Data Exchange", icon: _archAwsDataExchange64Svg };
export const archAwsDataPipeline64Svg = { id: "archAwsDataPipeline64Svg", name: "AWS Data Pipeline", icon: _archAwsDataPipeline64Svg };
export const archAwsGlueDataBrew64Svg = { id: "archAwsGlueDataBrew64Svg", name: "AWS Glue DataBrew", icon: _archAwsGlueDataBrew64Svg };
export const archAwsGlueElasticViews64Svg = { id: "archAwsGlueElasticViews64Svg", name: "AWS Glue Elastic Views", icon: _archAwsGlueElasticViews64Svg };
export const archAwsGlue64Svg = { id: "archAwsGlue64Svg", name: "AWS Glue", icon: _archAwsGlue64Svg };
export const archAwsLakeFormation64Svg = { id: "archAwsLakeFormation64Svg", name: "AWS Lake Formation", icon: _archAwsLakeFormation64Svg };
export const archAmazonAthena64Svg = { id: "archAmazonAthena64Svg", name: "Amazon Athena", icon: _archAmazonAthena64Svg };
export const archAmazonCloudSearch64Svg = { id: "archAmazonCloudSearch64Svg", name: "Amazon CloudSearch", icon: _archAmazonCloudSearch64Svg };
export const archAmazonEmr64Svg = { id: "archAmazonEmr64Svg", name: "Amazon EMR", icon: _archAmazonEmr64Svg };
export const archAmazonFinSpace64Svg = { id: "archAmazonFinSpace64Svg", name: "Amazon FinSpace", icon: _archAmazonFinSpace64Svg };
export const archAmazonKinesisDataAnalytics64Svg = { id: "archAmazonKinesisDataAnalytics64Svg", name: "Amazon Kinesis Data Analytics", icon: _archAmazonKinesisDataAnalytics64Svg };
export const archAmazonKinesisDataStreams64Svg = { id: "archAmazonKinesisDataStreams64Svg", name: "Amazon Kinesis Data Streams", icon: _archAmazonKinesisDataStreams64Svg };
export const archAmazonKinesisFirehose64Svg = { id: "archAmazonKinesisFirehose64Svg", name: "Amazon Kinesis Firehose", icon: _archAmazonKinesisFirehose64Svg };
export const archAmazonKinesisVideoStreams64Svg = { id: "archAmazonKinesisVideoStreams64Svg", name: "Amazon Kinesis Video Streams", icon: _archAmazonKinesisVideoStreams64Svg };
export const archAmazonKinesis64Svg = { id: "archAmazonKinesis64Svg", name: "Amazon Kinesis", icon: _archAmazonKinesis64Svg };
export const archAmazonManagedStreamingForApacheKafka64Svg = { id: "archAmazonManagedStreamingForApacheKafka64Svg", name: "Amazon Managed Streaming for Apache Kafka", icon: _archAmazonManagedStreamingForApacheKafka64Svg };
export const archAmazonOpenSearchService64Svg = { id: "archAmazonOpenSearchService64Svg", name: "Amazon OpenSearch Service", icon: _archAmazonOpenSearchService64Svg };
export const archAmazonQuickSight64Svg = { id: "archAmazonQuickSight64Svg", name: "Amazon QuickSight", icon: _archAmazonQuickSight64Svg };
export const archAmazonRedshift64Svg = { id: "archAmazonRedshift64Svg", name: "Amazon Redshift", icon: _archAmazonRedshift64Svg };
