import _archCategoryAnalytics48Svg from './Arch-Category_Analytics_48.svg';
import _archCategoryApplicationIntegration48Svg from './Arch-Category_Application-Integration_48.svg';
import _archCategoryBlockchain48Svg from './Arch-Category_Blockchain_48.svg';
import _archCategoryBusinessApplications48Svg from './Arch-Category_Business-Applications_48.svg';
import _archCategoryCloudFinancialManagement48Svg from './Arch-Category_Cloud-Financial-Management_48.svg';
import _archCategoryCompute48Svg from './Arch-Category_Compute_48.svg';
import _archCategoryContainers48Svg from './Arch-Category_Containers_48.svg';
import _archCategoryCustomerEnablement48Svg from './Arch-Category_Customer-Enablement_48.svg';
import _archCategoryDatabase48Svg from './Arch-Category_Database_48.svg';
import _archCategoryDeveloperTools48Svg from './Arch-Category_Developer-Tools_48.svg';
import _archCategoryEndUserComputing48Svg from './Arch-Category_End-User-Computing_48.svg';
import _archCategoryFrontEndWebMobile48Svg from './Arch-Category_Front-End-Web-Mobile_48.svg';
import _archCategoryGameTech48Svg from './Arch-Category_Game-Tech_48.svg';
import _archCategoryInternetOfThings48Svg from './Arch-Category_Internet-of-Things_48.svg';
import _archCategoryMachineLearning48Svg from './Arch-Category_Machine-Learning_48.svg';
import _archCategoryManagementGovernance48Svg from './Arch-Category_Management-Governance_48.svg';
import _archCategoryMediaServices48Svg from './Arch-Category_Media-Services_48.svg';
import _archCategoryMigrationTransfer48Svg from './Arch-Category_Migration-Transfer_48.svg';
import _archCategoryNetworkingContentDelivery48Svg from './Arch-Category_Networking-Content-Delivery_48.svg';
import _archCategoryQuantumTechnologies48Svg from './Arch-Category_Quantum-Technologies_48.svg';
import _archCategoryRobotics48Svg from './Arch-Category_Robotics_48.svg';
import _archCategorySatellite48Svg from './Arch-Category_Satellite_48.svg';
import _archCategorySecurityIdentityCompliance48Svg from './Arch-Category_Security-Identity-Compliance_48.svg';
import _archCategoryServerless48Svg from './Arch-Category_Serverless_48.svg';
import _archCategoryStorage48Svg from './Arch-Category_Storage_48.svg';
import _archCategoryVrAr48Svg from './Arch-Category_VR-AR_48.svg';

export const archCategoryAnalytics48Svg = { id: "archCategoryAnalytics48Svg", name: "Analytics", icon: _archCategoryAnalytics48Svg };
export const archCategoryApplicationIntegration48Svg = { id: "archCategoryApplicationIntegration48Svg", name: "Application Integration", icon: _archCategoryApplicationIntegration48Svg };
export const archCategoryBlockchain48Svg = { id: "archCategoryBlockchain48Svg", name: "Blockchain", icon: _archCategoryBlockchain48Svg };
export const archCategoryBusinessApplications48Svg = { id: "archCategoryBusinessApplications48Svg", name: "Business Applications", icon: _archCategoryBusinessApplications48Svg };
export const archCategoryCloudFinancialManagement48Svg = { id: "archCategoryCloudFinancialManagement48Svg", name: "Cloud Financial Management", icon: _archCategoryCloudFinancialManagement48Svg };
export const archCategoryCompute48Svg = { id: "archCategoryCompute48Svg", name: "Compute", icon: _archCategoryCompute48Svg };
export const archCategoryContainers48Svg = { id: "archCategoryContainers48Svg", name: "Containers", icon: _archCategoryContainers48Svg };
export const archCategoryCustomerEnablement48Svg = { id: "archCategoryCustomerEnablement48Svg", name: "Customer Enablement", icon: _archCategoryCustomerEnablement48Svg };
export const archCategoryDatabase48Svg = { id: "archCategoryDatabase48Svg", name: "Database", icon: _archCategoryDatabase48Svg };
export const archCategoryDeveloperTools48Svg = { id: "archCategoryDeveloperTools48Svg", name: "Developer Tools", icon: _archCategoryDeveloperTools48Svg };
export const archCategoryEndUserComputing48Svg = { id: "archCategoryEndUserComputing48Svg", name: "End User Computing", icon: _archCategoryEndUserComputing48Svg };
export const archCategoryFrontEndWebMobile48Svg = { id: "archCategoryFrontEndWebMobile48Svg", name: "Front End Web Mobile", icon: _archCategoryFrontEndWebMobile48Svg };
export const archCategoryGameTech48Svg = { id: "archCategoryGameTech48Svg", name: "Game Tech", icon: _archCategoryGameTech48Svg };
export const archCategoryInternetOfThings48Svg = { id: "archCategoryInternetOfThings48Svg", name: "Internet of Things", icon: _archCategoryInternetOfThings48Svg };
export const archCategoryMachineLearning48Svg = { id: "archCategoryMachineLearning48Svg", name: "Machine Learning", icon: _archCategoryMachineLearning48Svg };
export const archCategoryManagementGovernance48Svg = { id: "archCategoryManagementGovernance48Svg", name: "Management Governance", icon: _archCategoryManagementGovernance48Svg };
export const archCategoryMediaServices48Svg = { id: "archCategoryMediaServices48Svg", name: "Media Services", icon: _archCategoryMediaServices48Svg };
export const archCategoryMigrationTransfer48Svg = { id: "archCategoryMigrationTransfer48Svg", name: "Migration Transfer", icon: _archCategoryMigrationTransfer48Svg };
export const archCategoryNetworkingContentDelivery48Svg = { id: "archCategoryNetworkingContentDelivery48Svg", name: "Networking Content Delivery", icon: _archCategoryNetworkingContentDelivery48Svg };
export const archCategoryQuantumTechnologies48Svg = { id: "archCategoryQuantumTechnologies48Svg", name: "Quantum Technologies", icon: _archCategoryQuantumTechnologies48Svg };
export const archCategoryRobotics48Svg = { id: "archCategoryRobotics48Svg", name: "Robotics", icon: _archCategoryRobotics48Svg };
export const archCategorySatellite48Svg = { id: "archCategorySatellite48Svg", name: "Satellite", icon: _archCategorySatellite48Svg };
export const archCategorySecurityIdentityCompliance48Svg = { id: "archCategorySecurityIdentityCompliance48Svg", name: "Security Identity Compliance", icon: _archCategorySecurityIdentityCompliance48Svg };
export const archCategoryServerless48Svg = { id: "archCategoryServerless48Svg", name: "Serverless", icon: _archCategoryServerless48Svg };
export const archCategoryStorage48Svg = { id: "archCategoryStorage48Svg", name: "Storage", icon: _archCategoryStorage48Svg };
export const archCategoryVrAr48Svg = { id: "archCategoryVrAr48Svg", name: "VR AR", icon: _archCategoryVrAr48Svg };
