import _archAlexaForBusiness32Svg from './Arch_Alexa-For-Business_32.svg';
import _archAmazonChimeSdk32Svg from './Arch_Amazon-Chime-SDK_32.svg';
import _archAmazonChimeVoiceConnector32Svg from './Arch_Amazon-Chime-Voice-Connector_32.svg';
import _archAmazonChime32Svg from './Arch_Amazon-Chime_32.svg';
import _archAmazonConnect32Svg from './Arch_Amazon-Connect_32.svg';
import _archAmazonHoneycode32Svg from './Arch_Amazon-Honeycode_32.svg';
import _archAmazonPinpointApIs32Svg from './Arch_Amazon-Pinpoint-APIs_32.svg';
import _archAmazonPinpoint32Svg from './Arch_Amazon-Pinpoint_32.svg';
import _archAmazonSimpleEmailService32Svg from './Arch_Amazon-Simple-Email-Service_32.svg';
import _archAmazonWorkDocsSdk32Svg from './Arch_Amazon-WorkDocs-SDK_32.svg';
import _archAmazonWorkDocs32Svg from './Arch_Amazon-WorkDocs_32.svg';
import _archAmazonWorkMail32Svg from './Arch_Amazon-WorkMail_32.svg';

export const archAlexaForBusiness32Svg = { id: "archAlexaForBusiness32Svg", name: "Alexa For Business", icon: _archAlexaForBusiness32Svg };
export const archAmazonChimeSdk32Svg = { id: "archAmazonChimeSdk32Svg", name: "Amazon Chime SDK", icon: _archAmazonChimeSdk32Svg };
export const archAmazonChimeVoiceConnector32Svg = { id: "archAmazonChimeVoiceConnector32Svg", name: "Amazon Chime Voice Connector", icon: _archAmazonChimeVoiceConnector32Svg };
export const archAmazonChime32Svg = { id: "archAmazonChime32Svg", name: "Amazon Chime", icon: _archAmazonChime32Svg };
export const archAmazonConnect32Svg = { id: "archAmazonConnect32Svg", name: "Amazon Connect", icon: _archAmazonConnect32Svg };
export const archAmazonHoneycode32Svg = { id: "archAmazonHoneycode32Svg", name: "Amazon Honeycode", icon: _archAmazonHoneycode32Svg };
export const archAmazonPinpointApIs32Svg = { id: "archAmazonPinpointApIs32Svg", name: "Amazon Pinpoint APIs", icon: _archAmazonPinpointApIs32Svg };
export const archAmazonPinpoint32Svg = { id: "archAmazonPinpoint32Svg", name: "Amazon Pinpoint", icon: _archAmazonPinpoint32Svg };
export const archAmazonSimpleEmailService32Svg = { id: "archAmazonSimpleEmailService32Svg", name: "Amazon Simple Email Service", icon: _archAmazonSimpleEmailService32Svg };
export const archAmazonWorkDocsSdk32Svg = { id: "archAmazonWorkDocsSdk32Svg", name: "Amazon WorkDocs SDK", icon: _archAmazonWorkDocsSdk32Svg };
export const archAmazonWorkDocs32Svg = { id: "archAmazonWorkDocs32Svg", name: "Amazon WorkDocs", icon: _archAmazonWorkDocs32Svg };
export const archAmazonWorkMail32Svg = { id: "archAmazonWorkMail32Svg", name: "Amazon WorkMail", icon: _archAmazonWorkMail32Svg };
