import _resAwsCertificateManagerCertificateAuthority48DarkSvg from './Res_AWS-Certificate-Manager_Certificate-Authority_48_Dark.svg';
import _resAwsDirectoryServiceAdConnector48DarkSvg from './Res_AWS-Directory-Service_AD-Connector_48_Dark.svg';
import _resAwsDirectoryServiceAwsManagedMicrosoftAd48DarkSvg from './Res_AWS-Directory-Service_AWS-Managed-Microsoft-AD_48_Dark.svg';
import _resAwsDirectoryServiceSimpleAd48DarkSvg from './Res_AWS-Directory-Service_Simple-AD_48_Dark.svg';
import _resAwsIdentityAccessManagementAwsStsAlternate48DarkSvg from './Res_AWS-Identity-Access-Management_AWS-STS-Alternate_48_Dark.svg';
import _resAwsIdentityAccessManagementAwsSts48DarkSvg from './Res_AWS-Identity-Access-Management_AWS-STS_48_Dark.svg';
import _resAwsIdentityAccessManagementAddOn48DarkSvg from './Res_AWS-Identity-Access-Management_Add-on_48_Dark.svg';
import _resAwsIdentityAccessManagementDataEncryptionKey48DarkSvg from './Res_AWS-Identity-Access-Management_Data-Encryption-Key_48_Dark.svg';
import _resAwsIdentityAccessManagementEncryptedData48DarkSvg from './Res_AWS-Identity-Access-Management_Encrypted-Data_48_Dark.svg';
import _resAwsIdentityAccessManagementIamAccessAnalyzer48DarkSvg from './Res_AWS-Identity-Access-Management_IAM-Access-Analyzer_48_Dark.svg';
import _resAwsIdentityAccessManagementIamRolesAnywhere48DarkSvg from './Res_AWS-Identity-Access-Management_IAM-Roles-Anywhere_48_Dark.svg';
import _resAwsIdentityAccessManagementLongTermSecurityCredential48DarkSvg from './Res_AWS-Identity-Access-Management_Long-Term-Security-Credential_48_Dark.svg';
import _resAwsIdentityAccessManagementMfaToken48DarkSvg from './Res_AWS-Identity-Access-Management_MFA-Token_48_Dark.svg';
import _resAwsIdentityAccessManagementPermissions48DarkSvg from './Res_AWS-Identity-Access-Management_Permissions_48_Dark.svg';
import _resAwsIdentityAccessManagementRole48DarkSvg from './Res_AWS-Identity-Access-Management_Role_48_Dark.svg';
import _resAwsIdentityAccessManagementTemporarySecurityCredential48DarkSvg from './Res_AWS-Identity-Access-Management_Temporary-Security-Credential_48_Dark.svg';
import _resAwsNetworkFirewallEndpoints48DarkSvg from './Res_AWS-Network-Firewall_Endpoints_48_Dark.svg';
import _resAwsSecurityHubFinding48DarkSvg from './Res_AWS-Security-Hub_Finding_48_Dark.svg';
import _resAwsShieldAwsShieldAdvanced48DarkSvg from './Res_AWS-Shield_AWS-Shield-Advanced_48_Dark.svg';
import _resAwsWafBadBot48DarkSvg from './Res_AWS-WAF_Bad-Bot_48_Dark.svg';
import _resAwsWafBotControl48DarkSvg from './Res_AWS-WAF_Bot-Control_48_Dark.svg';
import _resAwsWafBot48DarkSvg from './Res_AWS-WAF_Bot_48_Dark.svg';
import _resAwsWafFilteringRule48DarkSvg from './Res_AWS-WAF_Filtering-Rule_48_Dark.svg';
import _resAwsWafLabels48DarkSvg from './Res_AWS-WAF_Labels_48_Dark.svg';
import _resAwsWafManagedRule48DarkSvg from './Res_AWS-WAF_Managed-Rule_48_Dark.svg';
import _resAwsWafRule48DarkSvg from './Res_AWS-WAF_Rule_48_Dark.svg';
import _resAmazonInspectorAgent48DarkSvg from './Res_Amazon-Inspector_Agent_48_Dark.svg';

export const resAwsCertificateManagerCertificateAuthority48DarkSvg = { id: "resAwsCertificateManagerCertificateAuthority48DarkSvg", name: "AWS Certificate Manager | Certificate Authority", icon: _resAwsCertificateManagerCertificateAuthority48DarkSvg };
export const resAwsDirectoryServiceAdConnector48DarkSvg = { id: "resAwsDirectoryServiceAdConnector48DarkSvg", name: "AWS Directory Service | AD Connector", icon: _resAwsDirectoryServiceAdConnector48DarkSvg };
export const resAwsDirectoryServiceAwsManagedMicrosoftAd48DarkSvg = { id: "resAwsDirectoryServiceAwsManagedMicrosoftAd48DarkSvg", name: "AWS Directory Service | AWS Managed Microsoft AD", icon: _resAwsDirectoryServiceAwsManagedMicrosoftAd48DarkSvg };
export const resAwsDirectoryServiceSimpleAd48DarkSvg = { id: "resAwsDirectoryServiceSimpleAd48DarkSvg", name: "AWS Directory Service | Simple AD", icon: _resAwsDirectoryServiceSimpleAd48DarkSvg };
export const resAwsIdentityAccessManagementAwsStsAlternate48DarkSvg = { id: "resAwsIdentityAccessManagementAwsStsAlternate48DarkSvg", name: "AWS Identity Access Management | AWS STS Alternate", icon: _resAwsIdentityAccessManagementAwsStsAlternate48DarkSvg };
export const resAwsIdentityAccessManagementAwsSts48DarkSvg = { id: "resAwsIdentityAccessManagementAwsSts48DarkSvg", name: "AWS Identity Access Management | AWS STS", icon: _resAwsIdentityAccessManagementAwsSts48DarkSvg };
export const resAwsIdentityAccessManagementAddOn48DarkSvg = { id: "resAwsIdentityAccessManagementAddOn48DarkSvg", name: "AWS Identity Access Management | Add on", icon: _resAwsIdentityAccessManagementAddOn48DarkSvg };
export const resAwsIdentityAccessManagementDataEncryptionKey48DarkSvg = { id: "resAwsIdentityAccessManagementDataEncryptionKey48DarkSvg", name: "AWS Identity Access Management | Data Encryption Key", icon: _resAwsIdentityAccessManagementDataEncryptionKey48DarkSvg };
export const resAwsIdentityAccessManagementEncryptedData48DarkSvg = { id: "resAwsIdentityAccessManagementEncryptedData48DarkSvg", name: "AWS Identity Access Management | Encrypted Data", icon: _resAwsIdentityAccessManagementEncryptedData48DarkSvg };
export const resAwsIdentityAccessManagementIamAccessAnalyzer48DarkSvg = { id: "resAwsIdentityAccessManagementIamAccessAnalyzer48DarkSvg", name: "AWS Identity Access Management | IAM Access Analyzer", icon: _resAwsIdentityAccessManagementIamAccessAnalyzer48DarkSvg };
export const resAwsIdentityAccessManagementIamRolesAnywhere48DarkSvg = { id: "resAwsIdentityAccessManagementIamRolesAnywhere48DarkSvg", name: "AWS Identity Access Management | IAM Roles Anywhere", icon: _resAwsIdentityAccessManagementIamRolesAnywhere48DarkSvg };
export const resAwsIdentityAccessManagementLongTermSecurityCredential48DarkSvg = { id: "resAwsIdentityAccessManagementLongTermSecurityCredential48DarkSvg", name: "AWS Identity Access Management | Long Term Security Credential", icon: _resAwsIdentityAccessManagementLongTermSecurityCredential48DarkSvg };
export const resAwsIdentityAccessManagementMfaToken48DarkSvg = { id: "resAwsIdentityAccessManagementMfaToken48DarkSvg", name: "AWS Identity Access Management | MFA Token", icon: _resAwsIdentityAccessManagementMfaToken48DarkSvg };
export const resAwsIdentityAccessManagementPermissions48DarkSvg = { id: "resAwsIdentityAccessManagementPermissions48DarkSvg", name: "AWS Identity Access Management | Permissions", icon: _resAwsIdentityAccessManagementPermissions48DarkSvg };
export const resAwsIdentityAccessManagementRole48DarkSvg = { id: "resAwsIdentityAccessManagementRole48DarkSvg", name: "AWS Identity Access Management | Role", icon: _resAwsIdentityAccessManagementRole48DarkSvg };
export const resAwsIdentityAccessManagementTemporarySecurityCredential48DarkSvg = { id: "resAwsIdentityAccessManagementTemporarySecurityCredential48DarkSvg", name: "AWS Identity Access Management | Temporary Security Credential", icon: _resAwsIdentityAccessManagementTemporarySecurityCredential48DarkSvg };
export const resAwsNetworkFirewallEndpoints48DarkSvg = { id: "resAwsNetworkFirewallEndpoints48DarkSvg", name: "AWS Network Firewall | Endpoints", icon: _resAwsNetworkFirewallEndpoints48DarkSvg };
export const resAwsSecurityHubFinding48DarkSvg = { id: "resAwsSecurityHubFinding48DarkSvg", name: "AWS Security Hub | Finding", icon: _resAwsSecurityHubFinding48DarkSvg };
export const resAwsShieldAwsShieldAdvanced48DarkSvg = { id: "resAwsShieldAwsShieldAdvanced48DarkSvg", name: "AWS Shield | AWS Shield Advanced", icon: _resAwsShieldAwsShieldAdvanced48DarkSvg };
export const resAwsWafBadBot48DarkSvg = { id: "resAwsWafBadBot48DarkSvg", name: "AWS WAF | Bad Bot", icon: _resAwsWafBadBot48DarkSvg };
export const resAwsWafBotControl48DarkSvg = { id: "resAwsWafBotControl48DarkSvg", name: "AWS WAF | Bot Control", icon: _resAwsWafBotControl48DarkSvg };
export const resAwsWafBot48DarkSvg = { id: "resAwsWafBot48DarkSvg", name: "AWS WAF | Bot", icon: _resAwsWafBot48DarkSvg };
export const resAwsWafFilteringRule48DarkSvg = { id: "resAwsWafFilteringRule48DarkSvg", name: "AWS WAF | Filtering Rule", icon: _resAwsWafFilteringRule48DarkSvg };
export const resAwsWafLabels48DarkSvg = { id: "resAwsWafLabels48DarkSvg", name: "AWS WAF | Labels", icon: _resAwsWafLabels48DarkSvg };
export const resAwsWafManagedRule48DarkSvg = { id: "resAwsWafManagedRule48DarkSvg", name: "AWS WAF | Managed Rule", icon: _resAwsWafManagedRule48DarkSvg };
export const resAwsWafRule48DarkSvg = { id: "resAwsWafRule48DarkSvg", name: "AWS WAF | Rule", icon: _resAwsWafRule48DarkSvg };
export const resAmazonInspectorAgent48DarkSvg = { id: "resAmazonInspectorAgent48DarkSvg", name: "Amazon Inspector | Agent", icon: _resAmazonInspectorAgent48DarkSvg };
