export { ReactComponent as archAmazonApiGateway16Svg } from './Arch_ Amazon-API-Gateway_16.svg';
export { ReactComponent as archAwsAppSync16Svg } from './Arch_AWS-AppSync_16.svg';
export { ReactComponent as archAwsConsoleMobileApplication16Svg } from './Arch_AWS-Console-Mobile-Application _16.svg';
export { ReactComponent as archAwsExpressWorkflows16Svg } from './Arch_AWS-Express-Workflows_16.svg';
export { ReactComponent as archAwsStepFunctions16Svg } from './Arch_AWS-Step-Functions_16.svg';
export { ReactComponent as archAmazonAppFlow16Svg } from './Arch_Amazon-AppFlow_16.svg';
export { ReactComponent as archAmazonEventBridge16Svg } from './Arch_Amazon-EventBridge_16.svg';
export { ReactComponent as archAmazonMq16Svg } from './Arch_Amazon-MQ_16.svg';
export { ReactComponent as archAmazonManagedWorkflowsForApacheAirflow16Svg } from './Arch_Amazon-Managed-Workflows-for-Apache-Airflow_16.svg';
export { ReactComponent as archAmazonSimpleNotificationService16Svg } from './Arch_Amazon-Simple-Notification-Service_16.svg';
export { ReactComponent as archAmazonSimpleQueueService16Svg } from './Arch_Amazon-Simple-Queue-Service_16.svg';