import _archAmazonApiGateway16Svg from './Arch_ Amazon-API-Gateway_16.svg';
import _archAwsAppSync16Svg from './Arch_AWS-AppSync_16.svg';
import _archAwsConsoleMobileApplication16Svg from './Arch_AWS-Console-Mobile-Application _16.svg';
import _archAwsExpressWorkflows16Svg from './Arch_AWS-Express-Workflows_16.svg';
import _archAwsStepFunctions16Svg from './Arch_AWS-Step-Functions_16.svg';
import _archAmazonAppFlow16Svg from './Arch_Amazon-AppFlow_16.svg';
import _archAmazonEventBridge16Svg from './Arch_Amazon-EventBridge_16.svg';
import _archAmazonMq16Svg from './Arch_Amazon-MQ_16.svg';
import _archAmazonManagedWorkflowsForApacheAirflow16Svg from './Arch_Amazon-Managed-Workflows-for-Apache-Airflow_16.svg';
import _archAmazonSimpleNotificationService16Svg from './Arch_Amazon-Simple-Notification-Service_16.svg';
import _archAmazonSimpleQueueService16Svg from './Arch_Amazon-Simple-Queue-Service_16.svg';

export const archAmazonApiGateway16Svg = { id: "archAmazonApiGateway16Svg", name: " Amazon API Gateway", icon: _archAmazonApiGateway16Svg };
export const archAwsAppSync16Svg = { id: "archAwsAppSync16Svg", name: "AWS AppSync", icon: _archAwsAppSync16Svg };
export const archAwsConsoleMobileApplication16Svg = { id: "archAwsConsoleMobileApplication16Svg", name: "AWS Console Mobile Application ", icon: _archAwsConsoleMobileApplication16Svg };
export const archAwsExpressWorkflows16Svg = { id: "archAwsExpressWorkflows16Svg", name: "AWS Express Workflows", icon: _archAwsExpressWorkflows16Svg };
export const archAwsStepFunctions16Svg = { id: "archAwsStepFunctions16Svg", name: "AWS Step Functions", icon: _archAwsStepFunctions16Svg };
export const archAmazonAppFlow16Svg = { id: "archAmazonAppFlow16Svg", name: "Amazon AppFlow", icon: _archAmazonAppFlow16Svg };
export const archAmazonEventBridge16Svg = { id: "archAmazonEventBridge16Svg", name: "Amazon EventBridge", icon: _archAmazonEventBridge16Svg };
export const archAmazonMq16Svg = { id: "archAmazonMq16Svg", name: "Amazon MQ", icon: _archAmazonMq16Svg };
export const archAmazonManagedWorkflowsForApacheAirflow16Svg = { id: "archAmazonManagedWorkflowsForApacheAirflow16Svg", name: "Amazon Managed Workflows for Apache Airflow", icon: _archAmazonManagedWorkflowsForApacheAirflow16Svg };
export const archAmazonSimpleNotificationService16Svg = { id: "archAmazonSimpleNotificationService16Svg", name: "Amazon Simple Notification Service", icon: _archAmazonSimpleNotificationService16Svg };
export const archAmazonSimpleQueueService16Svg = { id: "archAmazonSimpleQueueService16Svg", name: "Amazon Simple Queue Service", icon: _archAmazonSimpleQueueService16Svg };
