export { default as archAmazonApiGateway16Svg } from './Arch_ Amazon-API-Gateway_16.svg';
export { default as archAwsAppSync16Svg } from './Arch_AWS-AppSync_16.svg';
export { default as archAwsConsoleMobileApplication16Svg } from './Arch_AWS-Console-Mobile-Application _16.svg';
export { default as archAwsExpressWorkflows16Svg } from './Arch_AWS-Express-Workflows_16.svg';
export { default as archAwsStepFunctions16Svg } from './Arch_AWS-Step-Functions_16.svg';
export { default as archAmazonAppFlow16Svg } from './Arch_Amazon-AppFlow_16.svg';
export { default as archAmazonEventBridge16Svg } from './Arch_Amazon-EventBridge_16.svg';
export { default as archAmazonMq16Svg } from './Arch_Amazon-MQ_16.svg';
export { default as archAmazonManagedWorkflowsForApacheAirflow16Svg } from './Arch_Amazon-Managed-Workflows-for-Apache-Airflow_16.svg';
export { default as archAmazonSimpleNotificationService16Svg } from './Arch_Amazon-Simple-Notification-Service_16.svg';
export { default as archAmazonSimpleQueueService16Svg } from './Arch_Amazon-Simple-Queue-Service_16.svg';