import _archAwsAppConfig32Svg from './Arch_AWS-AppConfig_32.svg';
import _archAwsApplicationAutoScaling32Svg from './Arch_AWS-Application-Auto-Scaling_32.svg';
import _archAwsAutoScaling32Svg from './Arch_AWS-Auto-Scaling_32.svg';
import _archAwsBackintAgent32Svg from './Arch_AWS-Backint-Agent_32.svg';
import _archAwsChatbot32Svg from './Arch_AWS-Chatbot_32.svg';
import _archAwsCloudFormation32Svg from './Arch_AWS-CloudFormation_32.svg';
import _archAwsCloudTrail32Svg from './Arch_AWS-CloudTrail_32.svg';
import _archAwsConfig32Svg from './Arch_AWS-Config_32.svg';
import _archAwsControlTower32Svg from './Arch_AWS-Control-Tower_32.svg';
import _archAwsDistroForOpenTelemetry32Svg from './Arch_AWS-Distro-for-OpenTelemetry_32.svg';
import _archAwsFaultInjectionSimulator32Svg from './Arch_AWS-Fault-Injection-Simulator_32.svg';
import _archAwsLaunchWizard32Svg from './Arch_AWS-Launch-Wizard_32.svg';
import _archAwsLicenseManager32Svg from './Arch_AWS-License-Manager_32.svg';
import _archAwsManagementConsole32Svg from './Arch_AWS-Management-Console_32.svg';
import _archAwsOpsWorks32Svg from './Arch_AWS-OpsWorks_32.svg';
import _archAwsOrganizations32Svg from './Arch_AWS-Organizations_32.svg';
import _archAwsPersonalHealthDashboard32Svg from './Arch_AWS-Personal-Health-Dashboard_32.svg';
import _archAwsProton32Svg from './Arch_AWS-Proton_32.svg';
import _archAwsResilienceHub32Svg from './Arch_AWS-Resilience-Hub_32.svg';
import _archAwsServiceCatalog32Svg from './Arch_AWS-Service-Catalog_32.svg';
import _archAwsSystemsManagerIncidentManager32Svg from './Arch_AWS-Systems-Manager-Incident-Manager_32.svg';
import _archAwsSystemsManager32Svg from './Arch_AWS-Systems-Manager_32.svg';
import _archAwsTrustedAdvisor32Svg from './Arch_AWS-Trusted-Advisor_32.svg';
import _archAwsWellArchitectedTool32Svg from './Arch_AWS-Well-Architected-Tool_32.svg';
import _archAmazonCloudWatch32Svg from './Arch_Amazon-CloudWatch_32.svg';
import _archAmazonManagedGrafana32Svg from './Arch_Amazon-Managed-Grafana_32.svg';
import _archAmazonManagedServiceForPrometheus32Svg from './Arch_Amazon-Managed-Service-for-Prometheus_32.svg';

export const archAwsAppConfig32Svg = { id: "archAwsAppConfig32Svg", name: "AWS AppConfig", icon: _archAwsAppConfig32Svg };
export const archAwsApplicationAutoScaling32Svg = { id: "archAwsApplicationAutoScaling32Svg", name: "AWS Application Auto Scaling", icon: _archAwsApplicationAutoScaling32Svg };
export const archAwsAutoScaling32Svg = { id: "archAwsAutoScaling32Svg", name: "AWS Auto Scaling", icon: _archAwsAutoScaling32Svg };
export const archAwsBackintAgent32Svg = { id: "archAwsBackintAgent32Svg", name: "AWS Backint Agent", icon: _archAwsBackintAgent32Svg };
export const archAwsChatbot32Svg = { id: "archAwsChatbot32Svg", name: "AWS Chatbot", icon: _archAwsChatbot32Svg };
export const archAwsCloudFormation32Svg = { id: "archAwsCloudFormation32Svg", name: "AWS CloudFormation", icon: _archAwsCloudFormation32Svg };
export const archAwsCloudTrail32Svg = { id: "archAwsCloudTrail32Svg", name: "AWS CloudTrail", icon: _archAwsCloudTrail32Svg };
export const archAwsConfig32Svg = { id: "archAwsConfig32Svg", name: "AWS Config", icon: _archAwsConfig32Svg };
export const archAwsControlTower32Svg = { id: "archAwsControlTower32Svg", name: "AWS Control Tower", icon: _archAwsControlTower32Svg };
export const archAwsDistroForOpenTelemetry32Svg = { id: "archAwsDistroForOpenTelemetry32Svg", name: "AWS Distro for OpenTelemetry", icon: _archAwsDistroForOpenTelemetry32Svg };
export const archAwsFaultInjectionSimulator32Svg = { id: "archAwsFaultInjectionSimulator32Svg", name: "AWS Fault Injection Simulator", icon: _archAwsFaultInjectionSimulator32Svg };
export const archAwsLaunchWizard32Svg = { id: "archAwsLaunchWizard32Svg", name: "AWS Launch Wizard", icon: _archAwsLaunchWizard32Svg };
export const archAwsLicenseManager32Svg = { id: "archAwsLicenseManager32Svg", name: "AWS License Manager", icon: _archAwsLicenseManager32Svg };
export const archAwsManagementConsole32Svg = { id: "archAwsManagementConsole32Svg", name: "AWS Management Console", icon: _archAwsManagementConsole32Svg };
export const archAwsOpsWorks32Svg = { id: "archAwsOpsWorks32Svg", name: "AWS OpsWorks", icon: _archAwsOpsWorks32Svg };
export const archAwsOrganizations32Svg = { id: "archAwsOrganizations32Svg", name: "AWS Organizations", icon: _archAwsOrganizations32Svg };
export const archAwsPersonalHealthDashboard32Svg = { id: "archAwsPersonalHealthDashboard32Svg", name: "AWS Personal Health Dashboard", icon: _archAwsPersonalHealthDashboard32Svg };
export const archAwsProton32Svg = { id: "archAwsProton32Svg", name: "AWS Proton", icon: _archAwsProton32Svg };
export const archAwsResilienceHub32Svg = { id: "archAwsResilienceHub32Svg", name: "AWS Resilience Hub", icon: _archAwsResilienceHub32Svg };
export const archAwsServiceCatalog32Svg = { id: "archAwsServiceCatalog32Svg", name: "AWS Service Catalog", icon: _archAwsServiceCatalog32Svg };
export const archAwsSystemsManagerIncidentManager32Svg = { id: "archAwsSystemsManagerIncidentManager32Svg", name: "AWS Systems Manager Incident Manager", icon: _archAwsSystemsManagerIncidentManager32Svg };
export const archAwsSystemsManager32Svg = { id: "archAwsSystemsManager32Svg", name: "AWS Systems Manager", icon: _archAwsSystemsManager32Svg };
export const archAwsTrustedAdvisor32Svg = { id: "archAwsTrustedAdvisor32Svg", name: "AWS Trusted Advisor", icon: _archAwsTrustedAdvisor32Svg };
export const archAwsWellArchitectedTool32Svg = { id: "archAwsWellArchitectedTool32Svg", name: "AWS Well Architected Tool", icon: _archAwsWellArchitectedTool32Svg };
export const archAmazonCloudWatch32Svg = { id: "archAmazonCloudWatch32Svg", name: "Amazon CloudWatch", icon: _archAmazonCloudWatch32Svg };
export const archAmazonManagedGrafana32Svg = { id: "archAmazonManagedGrafana32Svg", name: "Amazon Managed Grafana", icon: _archAmazonManagedGrafana32Svg };
export const archAmazonManagedServiceForPrometheus32Svg = { id: "archAmazonManagedServiceForPrometheus32Svg", name: "Amazon Managed Service for Prometheus", icon: _archAmazonManagedServiceForPrometheus32Svg };
