import _resAwsDatabaseMigrationServiceDatabaseMigrationWorkflowJob48DarkSvg from './Res_AWS-Database-Migration-Service_Database-migration-workflow-job_48_Dark.svg';
import _resAmazonAuroraInstance48DarkSvg from './Res_Amazon-Aurora-Instance_48_Dark.svg';
import _resAmazonAuroraMariaDbInstanceAlternate48DarkSvg from './Res_Amazon-Aurora-MariaDB-Instance-Alternate_48_Dark.svg';
import _resAmazonAuroraMariaDbInstance48DarkSvg from './Res_Amazon-Aurora-MariaDB-Instance_48_Dark.svg';
import _resAmazonAuroraMySqlInstanceAlternate48DarkSvg from './Res_Amazon-Aurora-MySQL-Instance-Alternate_48_Dark.svg';
import _resAmazonAuroraMySqlInstance48DarkSvg from './Res_Amazon-Aurora-MySQL-Instance_48_Dark.svg';
import _resAmazonAuroraOracleInstanceAlternate48DarkSvg from './Res_Amazon-Aurora-Oracle-Instance-Alternate_48_Dark.svg';
import _resAmazonAuroraOracleInstance48DarkSvg from './Res_Amazon-Aurora-Oracle-Instance_48_Dark.svg';
import _resAmazonAuroraPiopsInstance48DarkSvg from './Res_Amazon-Aurora-PIOPS-Instance_48_Dark.svg';
import _resAmazonAuroraPostgreSqlInstanceAlternate48DarkSvg from './Res_Amazon-Aurora-PostgreSQL-Instance-Alternate_48_Dark.svg';
import _resAmazonAuroraPostgreSqlInstance48DarkSvg from './Res_Amazon-Aurora-PostgreSQL-Instance_48_Dark.svg';
import _resAmazonAuroraSqlServerInstanceAlternate48DarkSvg from './Res_Amazon-Aurora-SQL-Server-Instance-Alternate_48_Dark.svg';
import _resAmazonAuroraSqlServerInstance48DarkSvg from './Res_Amazon-Aurora-SQL-Server-Instance_48_Dark.svg';
import _resAmazonAuroraAmazonAuroraInstanceAlternate48DarkSvg from './Res_Amazon-Aurora_Amazon-Aurora-Instance-alternate_48_Dark.svg';
import _resAmazonAuroraAmazonRdsInstanceAternate48DarkSvg from './Res_Amazon-Aurora_Amazon-RDS-Instance-Aternate_48_Dark.svg';
import _resAmazonAuroraAmazonRdsInstance48DarkSvg from './Res_Amazon-Aurora_Amazon-RDS-Instance_48_Dark.svg';
import _resAmazonDatabaseAmazonRdsProxyInstanceAlternate48DarkSvg from './Res_Amazon-Database_Amazon-RDS-Proxy-Instance-Alternate_48_Dark.svg';
import _resAmazonDatabaseAmazonRdsProxyInstance48DarkSvg from './Res_Amazon-Database_Amazon-RDS-Proxy-Instance_48_Dark.svg';
import _resAmazonDynamoDbAmazonDynamoDbAccelerator48DarkSvg from './Res_Amazon-DynamoDB_Amazon-DynamoDB-Accelerator_48_Dark.svg';
import _resAmazonDynamoDbAttribute48DarkSvg from './Res_Amazon-DynamoDB_Attribute_48_Dark.svg';
import _resAmazonDynamoDbAttributes48DarkSvg from './Res_Amazon-DynamoDB_Attributes_48_Dark.svg';
import _resAmazonDynamoDbGlobalSecondaryIndex48DarkSvg from './Res_Amazon-DynamoDB_Global-secondary-index_48_Dark.svg';
import _resAmazonDynamoDbItem48DarkSvg from './Res_Amazon-DynamoDB_Item_48_Dark.svg';
import _resAmazonDynamoDbItems48DarkSvg from './Res_Amazon-DynamoDB_Items_48_Dark.svg';
import _resAmazonDynamoDbStandardAccessTableClass48DarkSvg from './Res_Amazon-DynamoDB_Standard-Access-Table-Class_48_Dark.svg';
import _resAmazonDynamoDbStandardInfrequentAccessTableClass48DarkSvg from './Res_Amazon-DynamoDB_Standard-Infrequent-Access-Table-Class_48_Dark.svg';
import _resAmazonDynamoDbStream48DarkSvg from './Res_Amazon-DynamoDB_Stream_48_Dark.svg';
import _resAmazonDynamoDbTable48DarkSvg from './Res_Amazon-DynamoDB_Table_48_Dark.svg';
import _resAmazonElastiCacheCacheNode48DarkSvg from './Res_Amazon-ElastiCache_Cache-Node_48_Dark.svg';
import _resAmazonElastiCacheElastiCacheForMemcached48DarkSvg from './Res_Amazon-ElastiCache_ElastiCache-for-Memcached_48_Dark.svg';
import _resAmazonElastiCacheElastiCacheForRedis48DarkSvg from './Res_Amazon-ElastiCache_ElastiCache-for-Redis_48_Dark.svg';
import _resAmazonRdsMultiAzDbCluster48DarkSvg from './Res_Amazon-RDS_Multi-AZ-DB-Cluster_48_Dark.svg';
import _resAmazonRdsMultiAz48DarkSvg from './Res_Amazon-RDS_Multi-AZ_48_Dark.svg';

export const resAwsDatabaseMigrationServiceDatabaseMigrationWorkflowJob48DarkSvg = { id: "resAwsDatabaseMigrationServiceDatabaseMigrationWorkflowJob48DarkSvg", name: "AWS Database Migration Service / Database migration workflow job", icon: _resAwsDatabaseMigrationServiceDatabaseMigrationWorkflowJob48DarkSvg };
export const resAmazonAuroraInstance48DarkSvg = { id: "resAmazonAuroraInstance48DarkSvg", name: "Amazon Aurora Instance", icon: _resAmazonAuroraInstance48DarkSvg };
export const resAmazonAuroraMariaDbInstanceAlternate48DarkSvg = { id: "resAmazonAuroraMariaDbInstanceAlternate48DarkSvg", name: "Amazon Aurora MariaDB Instance Alternate", icon: _resAmazonAuroraMariaDbInstanceAlternate48DarkSvg };
export const resAmazonAuroraMariaDbInstance48DarkSvg = { id: "resAmazonAuroraMariaDbInstance48DarkSvg", name: "Amazon Aurora MariaDB Instance", icon: _resAmazonAuroraMariaDbInstance48DarkSvg };
export const resAmazonAuroraMySqlInstanceAlternate48DarkSvg = { id: "resAmazonAuroraMySqlInstanceAlternate48DarkSvg", name: "Amazon Aurora MySQL Instance Alternate", icon: _resAmazonAuroraMySqlInstanceAlternate48DarkSvg };
export const resAmazonAuroraMySqlInstance48DarkSvg = { id: "resAmazonAuroraMySqlInstance48DarkSvg", name: "Amazon Aurora MySQL Instance", icon: _resAmazonAuroraMySqlInstance48DarkSvg };
export const resAmazonAuroraOracleInstanceAlternate48DarkSvg = { id: "resAmazonAuroraOracleInstanceAlternate48DarkSvg", name: "Amazon Aurora Oracle Instance Alternate", icon: _resAmazonAuroraOracleInstanceAlternate48DarkSvg };
export const resAmazonAuroraOracleInstance48DarkSvg = { id: "resAmazonAuroraOracleInstance48DarkSvg", name: "Amazon Aurora Oracle Instance", icon: _resAmazonAuroraOracleInstance48DarkSvg };
export const resAmazonAuroraPiopsInstance48DarkSvg = { id: "resAmazonAuroraPiopsInstance48DarkSvg", name: "Amazon Aurora PIOPS Instance", icon: _resAmazonAuroraPiopsInstance48DarkSvg };
export const resAmazonAuroraPostgreSqlInstanceAlternate48DarkSvg = { id: "resAmazonAuroraPostgreSqlInstanceAlternate48DarkSvg", name: "Amazon Aurora PostgreSQL Instance Alternate", icon: _resAmazonAuroraPostgreSqlInstanceAlternate48DarkSvg };
export const resAmazonAuroraPostgreSqlInstance48DarkSvg = { id: "resAmazonAuroraPostgreSqlInstance48DarkSvg", name: "Amazon Aurora PostgreSQL Instance", icon: _resAmazonAuroraPostgreSqlInstance48DarkSvg };
export const resAmazonAuroraSqlServerInstanceAlternate48DarkSvg = { id: "resAmazonAuroraSqlServerInstanceAlternate48DarkSvg", name: "Amazon Aurora SQL Server Instance Alternate", icon: _resAmazonAuroraSqlServerInstanceAlternate48DarkSvg };
export const resAmazonAuroraSqlServerInstance48DarkSvg = { id: "resAmazonAuroraSqlServerInstance48DarkSvg", name: "Amazon Aurora SQL Server Instance", icon: _resAmazonAuroraSqlServerInstance48DarkSvg };
export const resAmazonAuroraAmazonAuroraInstanceAlternate48DarkSvg = { id: "resAmazonAuroraAmazonAuroraInstanceAlternate48DarkSvg", name: "Amazon Aurora / Amazon Aurora Instance alternate", icon: _resAmazonAuroraAmazonAuroraInstanceAlternate48DarkSvg };
export const resAmazonAuroraAmazonRdsInstanceAternate48DarkSvg = { id: "resAmazonAuroraAmazonRdsInstanceAternate48DarkSvg", name: "Amazon Aurora / Amazon RDS Instance Aternate", icon: _resAmazonAuroraAmazonRdsInstanceAternate48DarkSvg };
export const resAmazonAuroraAmazonRdsInstance48DarkSvg = { id: "resAmazonAuroraAmazonRdsInstance48DarkSvg", name: "Amazon Aurora / Amazon RDS Instance", icon: _resAmazonAuroraAmazonRdsInstance48DarkSvg };
export const resAmazonDatabaseAmazonRdsProxyInstanceAlternate48DarkSvg = { id: "resAmazonDatabaseAmazonRdsProxyInstanceAlternate48DarkSvg", name: "Amazon Database / Amazon RDS Proxy Instance Alternate", icon: _resAmazonDatabaseAmazonRdsProxyInstanceAlternate48DarkSvg };
export const resAmazonDatabaseAmazonRdsProxyInstance48DarkSvg = { id: "resAmazonDatabaseAmazonRdsProxyInstance48DarkSvg", name: "Amazon Database / Amazon RDS Proxy Instance", icon: _resAmazonDatabaseAmazonRdsProxyInstance48DarkSvg };
export const resAmazonDynamoDbAmazonDynamoDbAccelerator48DarkSvg = { id: "resAmazonDynamoDbAmazonDynamoDbAccelerator48DarkSvg", name: "Amazon DynamoDB / Amazon DynamoDB Accelerator", icon: _resAmazonDynamoDbAmazonDynamoDbAccelerator48DarkSvg };
export const resAmazonDynamoDbAttribute48DarkSvg = { id: "resAmazonDynamoDbAttribute48DarkSvg", name: "Amazon DynamoDB / Attribute", icon: _resAmazonDynamoDbAttribute48DarkSvg };
export const resAmazonDynamoDbAttributes48DarkSvg = { id: "resAmazonDynamoDbAttributes48DarkSvg", name: "Amazon DynamoDB / Attributes", icon: _resAmazonDynamoDbAttributes48DarkSvg };
export const resAmazonDynamoDbGlobalSecondaryIndex48DarkSvg = { id: "resAmazonDynamoDbGlobalSecondaryIndex48DarkSvg", name: "Amazon DynamoDB / Global secondary index", icon: _resAmazonDynamoDbGlobalSecondaryIndex48DarkSvg };
export const resAmazonDynamoDbItem48DarkSvg = { id: "resAmazonDynamoDbItem48DarkSvg", name: "Amazon DynamoDB / Item", icon: _resAmazonDynamoDbItem48DarkSvg };
export const resAmazonDynamoDbItems48DarkSvg = { id: "resAmazonDynamoDbItems48DarkSvg", name: "Amazon DynamoDB / Items", icon: _resAmazonDynamoDbItems48DarkSvg };
export const resAmazonDynamoDbStandardAccessTableClass48DarkSvg = { id: "resAmazonDynamoDbStandardAccessTableClass48DarkSvg", name: "Amazon DynamoDB / Standard Access Table Class", icon: _resAmazonDynamoDbStandardAccessTableClass48DarkSvg };
export const resAmazonDynamoDbStandardInfrequentAccessTableClass48DarkSvg = { id: "resAmazonDynamoDbStandardInfrequentAccessTableClass48DarkSvg", name: "Amazon DynamoDB / Standard Infrequent Access Table Class", icon: _resAmazonDynamoDbStandardInfrequentAccessTableClass48DarkSvg };
export const resAmazonDynamoDbStream48DarkSvg = { id: "resAmazonDynamoDbStream48DarkSvg", name: "Amazon DynamoDB / Stream", icon: _resAmazonDynamoDbStream48DarkSvg };
export const resAmazonDynamoDbTable48DarkSvg = { id: "resAmazonDynamoDbTable48DarkSvg", name: "Amazon DynamoDB / Table", icon: _resAmazonDynamoDbTable48DarkSvg };
export const resAmazonElastiCacheCacheNode48DarkSvg = { id: "resAmazonElastiCacheCacheNode48DarkSvg", name: "Amazon ElastiCache / Cache Node", icon: _resAmazonElastiCacheCacheNode48DarkSvg };
export const resAmazonElastiCacheElastiCacheForMemcached48DarkSvg = { id: "resAmazonElastiCacheElastiCacheForMemcached48DarkSvg", name: "Amazon ElastiCache / ElastiCache for Memcached", icon: _resAmazonElastiCacheElastiCacheForMemcached48DarkSvg };
export const resAmazonElastiCacheElastiCacheForRedis48DarkSvg = { id: "resAmazonElastiCacheElastiCacheForRedis48DarkSvg", name: "Amazon ElastiCache / ElastiCache for Redis", icon: _resAmazonElastiCacheElastiCacheForRedis48DarkSvg };
export const resAmazonRdsMultiAzDbCluster48DarkSvg = { id: "resAmazonRdsMultiAzDbCluster48DarkSvg", name: "Amazon RDS / Multi AZ DB Cluster", icon: _resAmazonRdsMultiAzDbCluster48DarkSvg };
export const resAmazonRdsMultiAz48DarkSvg = { id: "resAmazonRdsMultiAz48DarkSvg", name: "Amazon RDS / Multi AZ", icon: _resAmazonRdsMultiAz48DarkSvg };
