import _archAwsDeepLearningAmIs64Svg from './Arch_AWS-Deep-Learning-AMIs_64.svg';
import _archAwsDeepLearningContainers64Svg from './Arch_AWS-Deep-Learning-Containers_64.svg';
import _archAwsDeepComposer64Svg from './Arch_AWS-DeepComposer_64.svg';
import _archAwsDeepLens64Svg from './Arch_AWS-DeepLens_64.svg';
import _archAwsDeepRacer64Svg from './Arch_AWS-DeepRacer_64.svg';
import _archAwsNeuron64Svg from './Arch_AWS-Neuron_64.svg';
import _archAwsPanorama64Svg from './Arch_AWS-Panorama_64.svg';
import _archAmazonAugmentedAiA2I64Svg from './Arch_Amazon-Augmented-AI-A2I_64.svg';
import _archAmazonCodeGuru64Svg from './Arch_Amazon-CodeGuru_64.svg';
import _archAmazonCodeWhisperer64Svg from './Arch_Amazon-CodeWhisperer_64.svg';
import _archAmazonComprehendMedical64Svg from './Arch_Amazon-Comprehend-Medical_64.svg';
import _archAmazonComprehend64Svg from './Arch_Amazon-Comprehend_64.svg';
import _archAmazonDevOpsGuru64Svg from './Arch_Amazon-DevOps-Guru_64.svg';
import _archAmazonElasticInference64Svg from './Arch_Amazon-Elastic-Inference_64.svg';
import _archAmazonForecast64Svg from './Arch_Amazon-Forecast_64.svg';
import _archAmazonFraudDetector64Svg from './Arch_Amazon-Fraud-Detector_64.svg';
import _archAmazonHealthLake64Svg from './Arch_Amazon-HealthLake_64.svg';
import _archAmazonKendra64Svg from './Arch_Amazon-Kendra_64.svg';
import _archAmazonLex64Svg from './Arch_Amazon-Lex_64.svg';
import _archAmazonLookoutForEquipment64Svg from './Arch_Amazon-Lookout-for-Equipment_64.svg';
import _archAmazonLookoutForMetrics64Svg from './Arch_Amazon-Lookout-for-Metrics_64.svg';
import _archAmazonLookoutForVision64Svg from './Arch_Amazon-Lookout-for-Vision_64.svg';
import _archAmazonMonitron64Svg from './Arch_Amazon-Monitron_64.svg';
import _archAmazonPersonalize64Svg from './Arch_Amazon-Personalize_64.svg';
import _archAmazonPolly64Svg from './Arch_Amazon-Polly_64.svg';
import _archAmazonRekognition64Svg from './Arch_Amazon-Rekognition_64.svg';
import _archAmazonSageMakerGroundTruth64Svg from './Arch_Amazon-SageMaker-Ground-Truth_64.svg';
import _archAmazonSageMakerStudioLab64Svg from './Arch_Amazon-SageMaker-Studio-Lab_64.svg';
import _archAmazonSageMaker64Svg from './Arch_Amazon-SageMaker_64.svg';
import _archAmazonTextract64Svg from './Arch_Amazon-Textract_64.svg';
import _archAmazonTranscribe64Svg from './Arch_Amazon-Transcribe_64.svg';
import _archAmazonTranslate64Svg from './Arch_Amazon-Translate_64.svg';
import _archApacheMxNetOnAws64Svg from './Arch_Apache-MXNet-on-AWS_64.svg';
import _archTensorFlowOnAws64Svg from './Arch_TensorFlow-on-AWS_64.svg';
import _archTorchServe64Svg from './Arch_TorchServe_64.svg';

export const archAwsDeepLearningAmIs64Svg = { id: "archAwsDeepLearningAmIs64Svg", name: "AWS Deep Learning AMIs", icon: _archAwsDeepLearningAmIs64Svg };
export const archAwsDeepLearningContainers64Svg = { id: "archAwsDeepLearningContainers64Svg", name: "AWS Deep Learning Containers", icon: _archAwsDeepLearningContainers64Svg };
export const archAwsDeepComposer64Svg = { id: "archAwsDeepComposer64Svg", name: "AWS DeepComposer", icon: _archAwsDeepComposer64Svg };
export const archAwsDeepLens64Svg = { id: "archAwsDeepLens64Svg", name: "AWS DeepLens", icon: _archAwsDeepLens64Svg };
export const archAwsDeepRacer64Svg = { id: "archAwsDeepRacer64Svg", name: "AWS DeepRacer", icon: _archAwsDeepRacer64Svg };
export const archAwsNeuron64Svg = { id: "archAwsNeuron64Svg", name: "AWS Neuron", icon: _archAwsNeuron64Svg };
export const archAwsPanorama64Svg = { id: "archAwsPanorama64Svg", name: "AWS Panorama", icon: _archAwsPanorama64Svg };
export const archAmazonAugmentedAiA2I64Svg = { id: "archAmazonAugmentedAiA2I64Svg", name: "Amazon Augmented AI A2I", icon: _archAmazonAugmentedAiA2I64Svg };
export const archAmazonCodeGuru64Svg = { id: "archAmazonCodeGuru64Svg", name: "Amazon CodeGuru", icon: _archAmazonCodeGuru64Svg };
export const archAmazonCodeWhisperer64Svg = { id: "archAmazonCodeWhisperer64Svg", name: "Amazon CodeWhisperer", icon: _archAmazonCodeWhisperer64Svg };
export const archAmazonComprehendMedical64Svg = { id: "archAmazonComprehendMedical64Svg", name: "Amazon Comprehend Medical", icon: _archAmazonComprehendMedical64Svg };
export const archAmazonComprehend64Svg = { id: "archAmazonComprehend64Svg", name: "Amazon Comprehend", icon: _archAmazonComprehend64Svg };
export const archAmazonDevOpsGuru64Svg = { id: "archAmazonDevOpsGuru64Svg", name: "Amazon DevOps Guru", icon: _archAmazonDevOpsGuru64Svg };
export const archAmazonElasticInference64Svg = { id: "archAmazonElasticInference64Svg", name: "Amazon Elastic Inference", icon: _archAmazonElasticInference64Svg };
export const archAmazonForecast64Svg = { id: "archAmazonForecast64Svg", name: "Amazon Forecast", icon: _archAmazonForecast64Svg };
export const archAmazonFraudDetector64Svg = { id: "archAmazonFraudDetector64Svg", name: "Amazon Fraud Detector", icon: _archAmazonFraudDetector64Svg };
export const archAmazonHealthLake64Svg = { id: "archAmazonHealthLake64Svg", name: "Amazon HealthLake", icon: _archAmazonHealthLake64Svg };
export const archAmazonKendra64Svg = { id: "archAmazonKendra64Svg", name: "Amazon Kendra", icon: _archAmazonKendra64Svg };
export const archAmazonLex64Svg = { id: "archAmazonLex64Svg", name: "Amazon Lex", icon: _archAmazonLex64Svg };
export const archAmazonLookoutForEquipment64Svg = { id: "archAmazonLookoutForEquipment64Svg", name: "Amazon Lookout for Equipment", icon: _archAmazonLookoutForEquipment64Svg };
export const archAmazonLookoutForMetrics64Svg = { id: "archAmazonLookoutForMetrics64Svg", name: "Amazon Lookout for Metrics", icon: _archAmazonLookoutForMetrics64Svg };
export const archAmazonLookoutForVision64Svg = { id: "archAmazonLookoutForVision64Svg", name: "Amazon Lookout for Vision", icon: _archAmazonLookoutForVision64Svg };
export const archAmazonMonitron64Svg = { id: "archAmazonMonitron64Svg", name: "Amazon Monitron", icon: _archAmazonMonitron64Svg };
export const archAmazonPersonalize64Svg = { id: "archAmazonPersonalize64Svg", name: "Amazon Personalize", icon: _archAmazonPersonalize64Svg };
export const archAmazonPolly64Svg = { id: "archAmazonPolly64Svg", name: "Amazon Polly", icon: _archAmazonPolly64Svg };
export const archAmazonRekognition64Svg = { id: "archAmazonRekognition64Svg", name: "Amazon Rekognition", icon: _archAmazonRekognition64Svg };
export const archAmazonSageMakerGroundTruth64Svg = { id: "archAmazonSageMakerGroundTruth64Svg", name: "Amazon SageMaker Ground Truth", icon: _archAmazonSageMakerGroundTruth64Svg };
export const archAmazonSageMakerStudioLab64Svg = { id: "archAmazonSageMakerStudioLab64Svg", name: "Amazon SageMaker Studio Lab", icon: _archAmazonSageMakerStudioLab64Svg };
export const archAmazonSageMaker64Svg = { id: "archAmazonSageMaker64Svg", name: "Amazon SageMaker", icon: _archAmazonSageMaker64Svg };
export const archAmazonTextract64Svg = { id: "archAmazonTextract64Svg", name: "Amazon Textract", icon: _archAmazonTextract64Svg };
export const archAmazonTranscribe64Svg = { id: "archAmazonTranscribe64Svg", name: "Amazon Transcribe", icon: _archAmazonTranscribe64Svg };
export const archAmazonTranslate64Svg = { id: "archAmazonTranslate64Svg", name: "Amazon Translate", icon: _archAmazonTranslate64Svg };
export const archApacheMxNetOnAws64Svg = { id: "archApacheMxNetOnAws64Svg", name: "Apache MXNet on AWS", icon: _archApacheMxNetOnAws64Svg };
export const archTensorFlowOnAws64Svg = { id: "archTensorFlowOnAws64Svg", name: "TensorFlow on AWS", icon: _archTensorFlowOnAws64Svg };
export const archTorchServe64Svg = { id: "archTorchServe64Svg", name: "TorchServe", icon: _archTorchServe64Svg };
