import _archAwsAppMesh64Svg from './Arch_AWS-App-Mesh_64.svg';
import _archAwsClientVpn64Svg from './Arch_AWS-Client-VPN_64.svg';
import _archAwsCloudMap64Svg from './Arch_AWS-Cloud-Map_64.svg';
import _archAwsCloudWan64Svg from './Arch_AWS-Cloud-WAN_64.svg';
import _archAwsDirectConnect64Svg from './Arch_AWS-Direct-Connect_64.svg';
import _archAwsGlobalAccelerator64Svg from './Arch_AWS-Global-Accelerator_64.svg';
import _archAwsPrivate5G64Svg from './Arch_AWS-Private-5G_64.svg';
import _archAwsPrivateLink64Svg from './Arch_AWS-PrivateLink_64.svg';
import _archAwsSiteToSiteVpn64Svg from './Arch_AWS-Site-to-Site-VPN_64.svg';
import _archAwsTransitGateway64Svg from './Arch_AWS-Transit-Gateway_64.svg';
import _archAmazonCloudDirectory64Svg from './Arch_Amazon-Cloud-Directory_64.svg';
import _archAmazonCloudFront64Svg from './Arch_Amazon-CloudFront_64.svg';
import _archAmazonRoute5364Svg from './Arch_Amazon-Route-53_64.svg';
import _archAmazonVirtualPrivateCloud64Svg from './Arch_Amazon-Virtual-Private-Cloud_64.svg';
import _archElasticLoadBalancing64Svg from './Arch_Elastic-Load-Balancing_64.svg';

export const archAwsAppMesh64Svg = { id: "archAwsAppMesh64Svg", name: "AWS App Mesh", icon: _archAwsAppMesh64Svg };
export const archAwsClientVpn64Svg = { id: "archAwsClientVpn64Svg", name: "AWS Client VPN", icon: _archAwsClientVpn64Svg };
export const archAwsCloudMap64Svg = { id: "archAwsCloudMap64Svg", name: "AWS Cloud Map", icon: _archAwsCloudMap64Svg };
export const archAwsCloudWan64Svg = { id: "archAwsCloudWan64Svg", name: "AWS Cloud WAN", icon: _archAwsCloudWan64Svg };
export const archAwsDirectConnect64Svg = { id: "archAwsDirectConnect64Svg", name: "AWS Direct Connect", icon: _archAwsDirectConnect64Svg };
export const archAwsGlobalAccelerator64Svg = { id: "archAwsGlobalAccelerator64Svg", name: "AWS Global Accelerator", icon: _archAwsGlobalAccelerator64Svg };
export const archAwsPrivate5G64Svg = { id: "archAwsPrivate5G64Svg", name: "AWS Private 5G", icon: _archAwsPrivate5G64Svg };
export const archAwsPrivateLink64Svg = { id: "archAwsPrivateLink64Svg", name: "AWS PrivateLink", icon: _archAwsPrivateLink64Svg };
export const archAwsSiteToSiteVpn64Svg = { id: "archAwsSiteToSiteVpn64Svg", name: "AWS Site to Site VPN", icon: _archAwsSiteToSiteVpn64Svg };
export const archAwsTransitGateway64Svg = { id: "archAwsTransitGateway64Svg", name: "AWS Transit Gateway", icon: _archAwsTransitGateway64Svg };
export const archAmazonCloudDirectory64Svg = { id: "archAmazonCloudDirectory64Svg", name: "Amazon Cloud Directory", icon: _archAmazonCloudDirectory64Svg };
export const archAmazonCloudFront64Svg = { id: "archAmazonCloudFront64Svg", name: "Amazon CloudFront", icon: _archAmazonCloudFront64Svg };
export const archAmazonRoute5364Svg = { id: "archAmazonRoute5364Svg", name: "Amazon Route 53", icon: _archAmazonRoute5364Svg };
export const archAmazonVirtualPrivateCloud64Svg = { id: "archAmazonVirtualPrivateCloud64Svg", name: "Amazon Virtual Private Cloud", icon: _archAmazonVirtualPrivateCloud64Svg };
export const archElasticLoadBalancing64Svg = { id: "archElasticLoadBalancing64Svg", name: "Elastic Load Balancing", icon: _archElasticLoadBalancing64Svg };
