import _archAwsDeepLearningAmIs16Svg from './Arch_AWS-Deep-Learning-AMIs_16.svg';
import _archAwsDeepLearningContainers16Svg from './Arch_AWS-Deep-Learning-Containers_16.svg';
import _archAwsDeepComposer16Svg from './Arch_AWS-DeepComposer_16.svg';
import _archAwsDeepLens16Svg from './Arch_AWS-DeepLens_16.svg';
import _archAwsDeepRacer16Svg from './Arch_AWS-DeepRacer_16.svg';
import _archAwsNeuron16Svg from './Arch_AWS-Neuron_16.svg';
import _archAwsPanorama16Svg from './Arch_AWS-Panorama_16.svg';
import _archAmazonAugmentedAiA2I16Svg from './Arch_Amazon-Augmented-AI-A2I_16.svg';
import _archAmazonCodeGuru16Svg from './Arch_Amazon-CodeGuru_16.svg';
import _archAmazonCodeWhisperer16Svg from './Arch_Amazon-CodeWhisperer_16.svg';
import _archAmazonComprehendMedical16Svg from './Arch_Amazon-Comprehend-Medical_16.svg';
import _archAmazonComprehend16Svg from './Arch_Amazon-Comprehend_16.svg';
import _archAmazonDevOpsGuru16Svg from './Arch_Amazon-DevOps-Guru_16.svg';
import _archAmazonElasticInference16Svg from './Arch_Amazon-Elastic-Inference_16.svg';
import _archAmazonForecast16Svg from './Arch_Amazon-Forecast_16.svg';
import _archAmazonFraudDetector16Svg from './Arch_Amazon-Fraud-Detector_16.svg';
import _archAmazonHealthLake16Svg from './Arch_Amazon-HealthLake_16.svg';
import _archAmazonKendra16Svg from './Arch_Amazon-Kendra_16.svg';
import _archAmazonLex16Svg from './Arch_Amazon-Lex_16.svg';
import _archAmazonLookoutForEquipment16Svg from './Arch_Amazon-Lookout-for-Equipment_16.svg';
import _archAmazonLookoutForMetrics16Svg from './Arch_Amazon-Lookout-for-Metrics_16.svg';
import _archAmazonLookoutForVision16Svg from './Arch_Amazon-Lookout-for-Vision_16.svg';
import _archAmazonMonitron16Svg from './Arch_Amazon-Monitron_16.svg';
import _archAmazonPersonalize16Svg from './Arch_Amazon-Personalize_16.svg';
import _archAmazonPolly16Svg from './Arch_Amazon-Polly_16.svg';
import _archAmazonRekognition16Svg from './Arch_Amazon-Rekognition_16.svg';
import _archAmazonSageMakerGroundTruth16Svg from './Arch_Amazon-SageMaker-Ground-Truth_16.svg';
import _archAmazonSageMakerStudioLab16Svg from './Arch_Amazon-SageMaker-Studio-Lab_16.svg';
import _archAmazonSageMaker16Svg from './Arch_Amazon-SageMaker_16.svg';
import _archAmazonTextract16Svg from './Arch_Amazon-Textract_16.svg';
import _archAmazonTranscribe16Svg from './Arch_Amazon-Transcribe_16.svg';
import _archAmazonTranslate16Svg from './Arch_Amazon-Translate_16.svg';
import _archApacheMxNetOnAws16Svg from './Arch_Apache-MXNet-on-AWS_16.svg';
import _archTensorFlowOnAws16Svg from './Arch_TensorFlow-on-AWS_16.svg';
import _archTorchServe16Svg from './Arch_TorchServe_16.svg';

export const archAwsDeepLearningAmIs16Svg = { id: "archAwsDeepLearningAmIs16Svg", name: "AWS Deep Learning AMIs", icon: _archAwsDeepLearningAmIs16Svg };
export const archAwsDeepLearningContainers16Svg = { id: "archAwsDeepLearningContainers16Svg", name: "AWS Deep Learning Containers", icon: _archAwsDeepLearningContainers16Svg };
export const archAwsDeepComposer16Svg = { id: "archAwsDeepComposer16Svg", name: "AWS DeepComposer", icon: _archAwsDeepComposer16Svg };
export const archAwsDeepLens16Svg = { id: "archAwsDeepLens16Svg", name: "AWS DeepLens", icon: _archAwsDeepLens16Svg };
export const archAwsDeepRacer16Svg = { id: "archAwsDeepRacer16Svg", name: "AWS DeepRacer", icon: _archAwsDeepRacer16Svg };
export const archAwsNeuron16Svg = { id: "archAwsNeuron16Svg", name: "AWS Neuron", icon: _archAwsNeuron16Svg };
export const archAwsPanorama16Svg = { id: "archAwsPanorama16Svg", name: "AWS Panorama", icon: _archAwsPanorama16Svg };
export const archAmazonAugmentedAiA2I16Svg = { id: "archAmazonAugmentedAiA2I16Svg", name: "Amazon Augmented AI A2I", icon: _archAmazonAugmentedAiA2I16Svg };
export const archAmazonCodeGuru16Svg = { id: "archAmazonCodeGuru16Svg", name: "Amazon CodeGuru", icon: _archAmazonCodeGuru16Svg };
export const archAmazonCodeWhisperer16Svg = { id: "archAmazonCodeWhisperer16Svg", name: "Amazon CodeWhisperer", icon: _archAmazonCodeWhisperer16Svg };
export const archAmazonComprehendMedical16Svg = { id: "archAmazonComprehendMedical16Svg", name: "Amazon Comprehend Medical", icon: _archAmazonComprehendMedical16Svg };
export const archAmazonComprehend16Svg = { id: "archAmazonComprehend16Svg", name: "Amazon Comprehend", icon: _archAmazonComprehend16Svg };
export const archAmazonDevOpsGuru16Svg = { id: "archAmazonDevOpsGuru16Svg", name: "Amazon DevOps Guru", icon: _archAmazonDevOpsGuru16Svg };
export const archAmazonElasticInference16Svg = { id: "archAmazonElasticInference16Svg", name: "Amazon Elastic Inference", icon: _archAmazonElasticInference16Svg };
export const archAmazonForecast16Svg = { id: "archAmazonForecast16Svg", name: "Amazon Forecast", icon: _archAmazonForecast16Svg };
export const archAmazonFraudDetector16Svg = { id: "archAmazonFraudDetector16Svg", name: "Amazon Fraud Detector", icon: _archAmazonFraudDetector16Svg };
export const archAmazonHealthLake16Svg = { id: "archAmazonHealthLake16Svg", name: "Amazon HealthLake", icon: _archAmazonHealthLake16Svg };
export const archAmazonKendra16Svg = { id: "archAmazonKendra16Svg", name: "Amazon Kendra", icon: _archAmazonKendra16Svg };
export const archAmazonLex16Svg = { id: "archAmazonLex16Svg", name: "Amazon Lex", icon: _archAmazonLex16Svg };
export const archAmazonLookoutForEquipment16Svg = { id: "archAmazonLookoutForEquipment16Svg", name: "Amazon Lookout for Equipment", icon: _archAmazonLookoutForEquipment16Svg };
export const archAmazonLookoutForMetrics16Svg = { id: "archAmazonLookoutForMetrics16Svg", name: "Amazon Lookout for Metrics", icon: _archAmazonLookoutForMetrics16Svg };
export const archAmazonLookoutForVision16Svg = { id: "archAmazonLookoutForVision16Svg", name: "Amazon Lookout for Vision", icon: _archAmazonLookoutForVision16Svg };
export const archAmazonMonitron16Svg = { id: "archAmazonMonitron16Svg", name: "Amazon Monitron", icon: _archAmazonMonitron16Svg };
export const archAmazonPersonalize16Svg = { id: "archAmazonPersonalize16Svg", name: "Amazon Personalize", icon: _archAmazonPersonalize16Svg };
export const archAmazonPolly16Svg = { id: "archAmazonPolly16Svg", name: "Amazon Polly", icon: _archAmazonPolly16Svg };
export const archAmazonRekognition16Svg = { id: "archAmazonRekognition16Svg", name: "Amazon Rekognition", icon: _archAmazonRekognition16Svg };
export const archAmazonSageMakerGroundTruth16Svg = { id: "archAmazonSageMakerGroundTruth16Svg", name: "Amazon SageMaker Ground Truth", icon: _archAmazonSageMakerGroundTruth16Svg };
export const archAmazonSageMakerStudioLab16Svg = { id: "archAmazonSageMakerStudioLab16Svg", name: "Amazon SageMaker Studio Lab", icon: _archAmazonSageMakerStudioLab16Svg };
export const archAmazonSageMaker16Svg = { id: "archAmazonSageMaker16Svg", name: "Amazon SageMaker", icon: _archAmazonSageMaker16Svg };
export const archAmazonTextract16Svg = { id: "archAmazonTextract16Svg", name: "Amazon Textract", icon: _archAmazonTextract16Svg };
export const archAmazonTranscribe16Svg = { id: "archAmazonTranscribe16Svg", name: "Amazon Transcribe", icon: _archAmazonTranscribe16Svg };
export const archAmazonTranslate16Svg = { id: "archAmazonTranslate16Svg", name: "Amazon Translate", icon: _archAmazonTranslate16Svg };
export const archApacheMxNetOnAws16Svg = { id: "archApacheMxNetOnAws16Svg", name: "Apache MXNet on AWS", icon: _archApacheMxNetOnAws16Svg };
export const archTensorFlowOnAws16Svg = { id: "archTensorFlowOnAws16Svg", name: "TensorFlow on AWS", icon: _archTensorFlowOnAws16Svg };
export const archTorchServe16Svg = { id: "archTorchServe16Svg", name: "TorchServe", icon: _archTorchServe16Svg };
