import _archAwsIoT1Click16Svg from './Arch_AWS-IoT-1-Click_16.svg';
import _archAwsIoTAnalytics16Svg from './Arch_AWS-IoT-Analytics_16.svg';
import _archAwsIoTButton16Svg from './Arch_AWS-IoT-Button_16.svg';
import _archAwsIoTCore16Svg from './Arch_AWS-IoT-Core_16.svg';
import _archAwsIoTDeviceDefender16Svg from './Arch_AWS-IoT-Device-Defender_16.svg';
import _archAwsIoTDeviceManagement16Svg from './Arch_AWS-IoT-Device-Management_16.svg';
import _archAwsIoTEduKit16Svg from './Arch_AWS-IoT-EduKit_16.svg';
import _archAwsIoTEvents16Svg from './Arch_AWS-IoT-Events_16.svg';
import _archAwsIoTExpressLink16Svg from './Arch_AWS-IoT-ExpressLink_16.svg';
import _archAwsIoTFleetWise16Svg from './Arch_AWS-IoT-FleetWise_16.svg';
import _archAwsIoTGreengrass16Svg from './Arch_AWS-IoT-Greengrass_16.svg';
import _archAwsIoTRoboRunner16Svg from './Arch_AWS-IoT-RoboRunner_16.svg';
import _archAwsIoTSiteWise16Svg from './Arch_AWS-IoT-SiteWise_16.svg';
import _archAwsIoTThingsGraph16Svg from './Arch_AWS-IoT-Things-Graph_16.svg';
import _archAwsIoTTwinMaker16Svg from './Arch_AWS-IoT-TwinMaker_16.svg';
import _archFreeRtos16Svg from './Arch_FreeRTOS_16.svg';

export const archAwsIoT1Click16Svg = { id: "archAwsIoT1Click16Svg", name: "AWS IoT 1 Click", icon: _archAwsIoT1Click16Svg };
export const archAwsIoTAnalytics16Svg = { id: "archAwsIoTAnalytics16Svg", name: "AWS IoT Analytics", icon: _archAwsIoTAnalytics16Svg };
export const archAwsIoTButton16Svg = { id: "archAwsIoTButton16Svg", name: "AWS IoT Button", icon: _archAwsIoTButton16Svg };
export const archAwsIoTCore16Svg = { id: "archAwsIoTCore16Svg", name: "AWS IoT Core", icon: _archAwsIoTCore16Svg };
export const archAwsIoTDeviceDefender16Svg = { id: "archAwsIoTDeviceDefender16Svg", name: "AWS IoT Device Defender", icon: _archAwsIoTDeviceDefender16Svg };
export const archAwsIoTDeviceManagement16Svg = { id: "archAwsIoTDeviceManagement16Svg", name: "AWS IoT Device Management", icon: _archAwsIoTDeviceManagement16Svg };
export const archAwsIoTEduKit16Svg = { id: "archAwsIoTEduKit16Svg", name: "AWS IoT EduKit", icon: _archAwsIoTEduKit16Svg };
export const archAwsIoTEvents16Svg = { id: "archAwsIoTEvents16Svg", name: "AWS IoT Events", icon: _archAwsIoTEvents16Svg };
export const archAwsIoTExpressLink16Svg = { id: "archAwsIoTExpressLink16Svg", name: "AWS IoT ExpressLink", icon: _archAwsIoTExpressLink16Svg };
export const archAwsIoTFleetWise16Svg = { id: "archAwsIoTFleetWise16Svg", name: "AWS IoT FleetWise", icon: _archAwsIoTFleetWise16Svg };
export const archAwsIoTGreengrass16Svg = { id: "archAwsIoTGreengrass16Svg", name: "AWS IoT Greengrass", icon: _archAwsIoTGreengrass16Svg };
export const archAwsIoTRoboRunner16Svg = { id: "archAwsIoTRoboRunner16Svg", name: "AWS IoT RoboRunner", icon: _archAwsIoTRoboRunner16Svg };
export const archAwsIoTSiteWise16Svg = { id: "archAwsIoTSiteWise16Svg", name: "AWS IoT SiteWise", icon: _archAwsIoTSiteWise16Svg };
export const archAwsIoTThingsGraph16Svg = { id: "archAwsIoTThingsGraph16Svg", name: "AWS IoT Things Graph", icon: _archAwsIoTThingsGraph16Svg };
export const archAwsIoTTwinMaker16Svg = { id: "archAwsIoTTwinMaker16Svg", name: "AWS IoT TwinMaker", icon: _archAwsIoTTwinMaker16Svg };
export const archFreeRtos16Svg = { id: "archFreeRtos16Svg", name: "FreeRTOS", icon: _archFreeRtos16Svg };
