import _archAwsDatabaseMigrationService32Svg from './Arch_AWS-Database-Migration-Service_32.svg';
import _archAmazonAurora32Svg from './Arch_Amazon-Aurora_32.svg';
import _archAmazonDocumentDb32Svg from './Arch_Amazon-DocumentDB_32.svg';
import _archAmazonDynamoDb32Svg from './Arch_Amazon-DynamoDB_32.svg';
import _archAmazonElastiCache32Svg from './Arch_Amazon-ElastiCache_32.svg';
import _archAmazonKeyspaces32Svg from './Arch_Amazon-Keyspaces_32.svg';
import _archAmazonMemoryDbForRedis32Svg from './Arch_Amazon-MemoryDB-for-Redis_32.svg';
import _archAmazonNeptune32Svg from './Arch_Amazon-Neptune_32.svg';
import _archAmazonQuantumLedgerDatabase32Svg from './Arch_Amazon-Quantum-Ledger-Database_32.svg';
import _archAmazonRdsOnVmware32Svg from './Arch_Amazon-RDS-on-VMware_32.svg';
import _archAmazonRds32Svg from './Arch_Amazon-RDS_32.svg';
import _archAmazonTimestream32Svg from './Arch_Amazon-Timestream_32.svg';

export const archAwsDatabaseMigrationService32Svg = { id: "archAwsDatabaseMigrationService32Svg", name: "AWS Database Migration Service", icon: _archAwsDatabaseMigrationService32Svg };
export const archAmazonAurora32Svg = { id: "archAmazonAurora32Svg", name: "Amazon Aurora", icon: _archAmazonAurora32Svg };
export const archAmazonDocumentDb32Svg = { id: "archAmazonDocumentDb32Svg", name: "Amazon DocumentDB", icon: _archAmazonDocumentDb32Svg };
export const archAmazonDynamoDb32Svg = { id: "archAmazonDynamoDb32Svg", name: "Amazon DynamoDB", icon: _archAmazonDynamoDb32Svg };
export const archAmazonElastiCache32Svg = { id: "archAmazonElastiCache32Svg", name: "Amazon ElastiCache", icon: _archAmazonElastiCache32Svg };
export const archAmazonKeyspaces32Svg = { id: "archAmazonKeyspaces32Svg", name: "Amazon Keyspaces", icon: _archAmazonKeyspaces32Svg };
export const archAmazonMemoryDbForRedis32Svg = { id: "archAmazonMemoryDbForRedis32Svg", name: "Amazon MemoryDB for Redis", icon: _archAmazonMemoryDbForRedis32Svg };
export const archAmazonNeptune32Svg = { id: "archAmazonNeptune32Svg", name: "Amazon Neptune", icon: _archAmazonNeptune32Svg };
export const archAmazonQuantumLedgerDatabase32Svg = { id: "archAmazonQuantumLedgerDatabase32Svg", name: "Amazon Quantum Ledger Database", icon: _archAmazonQuantumLedgerDatabase32Svg };
export const archAmazonRdsOnVmware32Svg = { id: "archAmazonRdsOnVmware32Svg", name: "Amazon RDS on VMware", icon: _archAmazonRdsOnVmware32Svg };
export const archAmazonRds32Svg = { id: "archAmazonRds32Svg", name: "Amazon RDS", icon: _archAmazonRds32Svg };
export const archAmazonTimestream32Svg = { id: "archAmazonTimestream32Svg", name: "Amazon Timestream", icon: _archAmazonTimestream32Svg };
