import _resAwsCertificateManagerCertificateAuthority48LightSvg from './Res_AWS-Certificate-Manager_Certificate-Authority_48_Light.svg';
import _resAwsDirectoryServiceAdConnector48LightSvg from './Res_AWS-Directory-Service_AD-Connector_48_Light.svg';
import _resAwsDirectoryServiceAwsManagedMicrosoftAd48LightSvg from './Res_AWS-Directory-Service_AWS-Managed-Microsoft-AD_48_Light.svg';
import _resAwsDirectoryServiceSimpleAd48LightSvg from './Res_AWS-Directory-Service_Simple-AD_48_Light.svg';
import _resAwsIdentityAccessManagementAwsStsAlternate48LightSvg from './Res_AWS-Identity-Access-Management_AWS-STS-Alternate_48_Light.svg';
import _resAwsIdentityAccessManagementAwsSts48LightSvg from './Res_AWS-Identity-Access-Management_AWS-STS_48_Light.svg';
import _resAwsIdentityAccessManagementAddOn48LightSvg from './Res_AWS-Identity-Access-Management_Add-on_48_Light.svg';
import _resAwsIdentityAccessManagementDataEncryptionKey48LightSvg from './Res_AWS-Identity-Access-Management_Data-Encryption-Key_48_Light.svg';
import _resAwsIdentityAccessManagementEncryptedData48LightSvg from './Res_AWS-Identity-Access-Management_Encrypted-Data_48_Light.svg';
import _resAwsIdentityAccessManagementIamAccessAnalyzer48LightSvg from './Res_AWS-Identity-Access-Management_IAM-Access-Analyzer_48_Light.svg';
import _resAwsIdentityAccessManagementIamRolesAnywhere48LightSvg from './Res_AWS-Identity-Access-Management_IAM-Roles-Anywhere_48_Light.svg';
import _resAwsIdentityAccessManagementLongTermSecurityCredential48LightSvg from './Res_AWS-Identity-Access-Management_Long-Term-Security-Credential_48_Light.svg';
import _resAwsIdentityAccessManagementMfaToken48LightSvg from './Res_AWS-Identity-Access-Management_MFA-Token_48_Light.svg';
import _resAwsIdentityAccessManagementPermissions48LightSvg from './Res_AWS-Identity-Access-Management_Permissions_48_Light.svg';
import _resAwsIdentityAccessManagementRole48LightSvg from './Res_AWS-Identity-Access-Management_Role_48_Light.svg';
import _resAwsIdentityAccessManagementTemporarySecurityCredential48LightSvg from './Res_AWS-Identity-Access-Management_Temporary-Security-Credential_48_Light.svg';
import _resAwsNetworkFirewallEndpoints48LightSvg from './Res_AWS-Network-Firewall_Endpoints_48_Light.svg';
import _resAwsSecurityHubFinding48LightSvg from './Res_AWS-Security-Hub_Finding_48_Light.svg';
import _resAwsShieldAwsShieldAdvanced48LightSvg from './Res_AWS-Shield_AWS-Shield-Advanced_48_Light.svg';
import _resAwsWafBadBot48LightSvg from './Res_AWS-WAF_Bad-Bot_48_Light.svg';
import _resAwsWafBotControl48LightSvg from './Res_AWS-WAF_Bot-Control_48_Light.svg';
import _resAwsWafBot48LightSvg from './Res_AWS-WAF_Bot_48_Light.svg';
import _resAwsWafFilteringRule48LightSvg from './Res_AWS-WAF_Filtering-Rule_48_Light.svg';
import _resAwsWafLabels48LightSvg from './Res_AWS-WAF_Labels_48_Light.svg';
import _resAwsWafManagedRule48LightSvg from './Res_AWS-WAF_Managed-Rule_48_Light.svg';
import _resAwsWafRule48LightSvg from './Res_AWS-WAF_Rule_48_Light.svg';
import _resAmazonInspectorAgent48LightSvg from './Res_Amazon-Inspector_Agent_48_Light.svg';

export const resAwsCertificateManagerCertificateAuthority48LightSvg = { id: "resAwsCertificateManagerCertificateAuthority48LightSvg", name: "AWS Certificate Manager | Certificate Authority", icon: _resAwsCertificateManagerCertificateAuthority48LightSvg };
export const resAwsDirectoryServiceAdConnector48LightSvg = { id: "resAwsDirectoryServiceAdConnector48LightSvg", name: "AWS Directory Service | AD Connector", icon: _resAwsDirectoryServiceAdConnector48LightSvg };
export const resAwsDirectoryServiceAwsManagedMicrosoftAd48LightSvg = { id: "resAwsDirectoryServiceAwsManagedMicrosoftAd48LightSvg", name: "AWS Directory Service | AWS Managed Microsoft AD", icon: _resAwsDirectoryServiceAwsManagedMicrosoftAd48LightSvg };
export const resAwsDirectoryServiceSimpleAd48LightSvg = { id: "resAwsDirectoryServiceSimpleAd48LightSvg", name: "AWS Directory Service | Simple AD", icon: _resAwsDirectoryServiceSimpleAd48LightSvg };
export const resAwsIdentityAccessManagementAwsStsAlternate48LightSvg = { id: "resAwsIdentityAccessManagementAwsStsAlternate48LightSvg", name: "AWS Identity Access Management | AWS STS Alternate", icon: _resAwsIdentityAccessManagementAwsStsAlternate48LightSvg };
export const resAwsIdentityAccessManagementAwsSts48LightSvg = { id: "resAwsIdentityAccessManagementAwsSts48LightSvg", name: "AWS Identity Access Management | AWS STS", icon: _resAwsIdentityAccessManagementAwsSts48LightSvg };
export const resAwsIdentityAccessManagementAddOn48LightSvg = { id: "resAwsIdentityAccessManagementAddOn48LightSvg", name: "AWS Identity Access Management | Add on", icon: _resAwsIdentityAccessManagementAddOn48LightSvg };
export const resAwsIdentityAccessManagementDataEncryptionKey48LightSvg = { id: "resAwsIdentityAccessManagementDataEncryptionKey48LightSvg", name: "AWS Identity Access Management | Data Encryption Key", icon: _resAwsIdentityAccessManagementDataEncryptionKey48LightSvg };
export const resAwsIdentityAccessManagementEncryptedData48LightSvg = { id: "resAwsIdentityAccessManagementEncryptedData48LightSvg", name: "AWS Identity Access Management | Encrypted Data", icon: _resAwsIdentityAccessManagementEncryptedData48LightSvg };
export const resAwsIdentityAccessManagementIamAccessAnalyzer48LightSvg = { id: "resAwsIdentityAccessManagementIamAccessAnalyzer48LightSvg", name: "AWS Identity Access Management | IAM Access Analyzer", icon: _resAwsIdentityAccessManagementIamAccessAnalyzer48LightSvg };
export const resAwsIdentityAccessManagementIamRolesAnywhere48LightSvg = { id: "resAwsIdentityAccessManagementIamRolesAnywhere48LightSvg", name: "AWS Identity Access Management | IAM Roles Anywhere", icon: _resAwsIdentityAccessManagementIamRolesAnywhere48LightSvg };
export const resAwsIdentityAccessManagementLongTermSecurityCredential48LightSvg = { id: "resAwsIdentityAccessManagementLongTermSecurityCredential48LightSvg", name: "AWS Identity Access Management | Long Term Security Credential", icon: _resAwsIdentityAccessManagementLongTermSecurityCredential48LightSvg };
export const resAwsIdentityAccessManagementMfaToken48LightSvg = { id: "resAwsIdentityAccessManagementMfaToken48LightSvg", name: "AWS Identity Access Management | MFA Token", icon: _resAwsIdentityAccessManagementMfaToken48LightSvg };
export const resAwsIdentityAccessManagementPermissions48LightSvg = { id: "resAwsIdentityAccessManagementPermissions48LightSvg", name: "AWS Identity Access Management | Permissions", icon: _resAwsIdentityAccessManagementPermissions48LightSvg };
export const resAwsIdentityAccessManagementRole48LightSvg = { id: "resAwsIdentityAccessManagementRole48LightSvg", name: "AWS Identity Access Management | Role", icon: _resAwsIdentityAccessManagementRole48LightSvg };
export const resAwsIdentityAccessManagementTemporarySecurityCredential48LightSvg = { id: "resAwsIdentityAccessManagementTemporarySecurityCredential48LightSvg", name: "AWS Identity Access Management | Temporary Security Credential", icon: _resAwsIdentityAccessManagementTemporarySecurityCredential48LightSvg };
export const resAwsNetworkFirewallEndpoints48LightSvg = { id: "resAwsNetworkFirewallEndpoints48LightSvg", name: "AWS Network Firewall | Endpoints", icon: _resAwsNetworkFirewallEndpoints48LightSvg };
export const resAwsSecurityHubFinding48LightSvg = { id: "resAwsSecurityHubFinding48LightSvg", name: "AWS Security Hub | Finding", icon: _resAwsSecurityHubFinding48LightSvg };
export const resAwsShieldAwsShieldAdvanced48LightSvg = { id: "resAwsShieldAwsShieldAdvanced48LightSvg", name: "AWS Shield | AWS Shield Advanced", icon: _resAwsShieldAwsShieldAdvanced48LightSvg };
export const resAwsWafBadBot48LightSvg = { id: "resAwsWafBadBot48LightSvg", name: "AWS WAF | Bad Bot", icon: _resAwsWafBadBot48LightSvg };
export const resAwsWafBotControl48LightSvg = { id: "resAwsWafBotControl48LightSvg", name: "AWS WAF | Bot Control", icon: _resAwsWafBotControl48LightSvg };
export const resAwsWafBot48LightSvg = { id: "resAwsWafBot48LightSvg", name: "AWS WAF | Bot", icon: _resAwsWafBot48LightSvg };
export const resAwsWafFilteringRule48LightSvg = { id: "resAwsWafFilteringRule48LightSvg", name: "AWS WAF | Filtering Rule", icon: _resAwsWafFilteringRule48LightSvg };
export const resAwsWafLabels48LightSvg = { id: "resAwsWafLabels48LightSvg", name: "AWS WAF | Labels", icon: _resAwsWafLabels48LightSvg };
export const resAwsWafManagedRule48LightSvg = { id: "resAwsWafManagedRule48LightSvg", name: "AWS WAF | Managed Rule", icon: _resAwsWafManagedRule48LightSvg };
export const resAwsWafRule48LightSvg = { id: "resAwsWafRule48LightSvg", name: "AWS WAF | Rule", icon: _resAwsWafRule48LightSvg };
export const resAmazonInspectorAgent48LightSvg = { id: "resAmazonInspectorAgent48LightSvg", name: "Amazon Inspector | Agent", icon: _resAmazonInspectorAgent48LightSvg };
