import _archAlexaForBusiness16Svg from './Arch_Alexa-For-Business_16.svg';
import _archAmazonChimeSdk16Svg from './Arch_Amazon-Chime-SDK_16.svg';
import _archAmazonChimeVoiceConnector16Svg from './Arch_Amazon-Chime-Voice-Connector_16.svg';
import _archAmazonChime16Svg from './Arch_Amazon-Chime_16.svg';
import _archAmazonConnect16Svg from './Arch_Amazon-Connect_16.svg';
import _archAmazonHoneycode16Svg from './Arch_Amazon-Honeycode_16.svg';
import _archAmazonPinpointApIs16Svg from './Arch_Amazon-Pinpoint-APIs_16.svg';
import _archAmazonPinpoint16Svg from './Arch_Amazon-Pinpoint_16.svg';
import _archAmazonSimpleEmailService16Svg from './Arch_Amazon-Simple-Email-Service_16.svg';
import _archAmazonWorkDocsSdk16Svg from './Arch_Amazon-WorkDocs-SDK_16.svg';
import _archAmazonWorkDocs16Svg from './Arch_Amazon-WorkDocs_16.svg';
import _archAmazonWorkMail16Svg from './Arch_Amazon-WorkMail_16.svg';

export const archAlexaForBusiness16Svg = { id: "archAlexaForBusiness16Svg", name: "Alexa For Business", icon: _archAlexaForBusiness16Svg };
export const archAmazonChimeSdk16Svg = { id: "archAmazonChimeSdk16Svg", name: "Amazon Chime SDK", icon: _archAmazonChimeSdk16Svg };
export const archAmazonChimeVoiceConnector16Svg = { id: "archAmazonChimeVoiceConnector16Svg", name: "Amazon Chime Voice Connector", icon: _archAmazonChimeVoiceConnector16Svg };
export const archAmazonChime16Svg = { id: "archAmazonChime16Svg", name: "Amazon Chime", icon: _archAmazonChime16Svg };
export const archAmazonConnect16Svg = { id: "archAmazonConnect16Svg", name: "Amazon Connect", icon: _archAmazonConnect16Svg };
export const archAmazonHoneycode16Svg = { id: "archAmazonHoneycode16Svg", name: "Amazon Honeycode", icon: _archAmazonHoneycode16Svg };
export const archAmazonPinpointApIs16Svg = { id: "archAmazonPinpointApIs16Svg", name: "Amazon Pinpoint APIs", icon: _archAmazonPinpointApIs16Svg };
export const archAmazonPinpoint16Svg = { id: "archAmazonPinpoint16Svg", name: "Amazon Pinpoint", icon: _archAmazonPinpoint16Svg };
export const archAmazonSimpleEmailService16Svg = { id: "archAmazonSimpleEmailService16Svg", name: "Amazon Simple Email Service", icon: _archAmazonSimpleEmailService16Svg };
export const archAmazonWorkDocsSdk16Svg = { id: "archAmazonWorkDocsSdk16Svg", name: "Amazon WorkDocs SDK", icon: _archAmazonWorkDocsSdk16Svg };
export const archAmazonWorkDocs16Svg = { id: "archAmazonWorkDocs16Svg", name: "Amazon WorkDocs", icon: _archAmazonWorkDocs16Svg };
export const archAmazonWorkMail16Svg = { id: "archAmazonWorkMail16Svg", name: "Amazon WorkMail", icon: _archAmazonWorkMail16Svg };
