export { default as archAwsFargate32Svg } from './Arch_AWS-Fargate_32.svg';
export { default as archAmazonEcsAnywhere32Svg } from './Arch_Amazon-ECS-Anywhere_32.svg';
export { default as archAmazonEksAnywhere32Svg } from './Arch_Amazon-EKS-Anywhere_32.svg';
export { default as archAmazonEksCloud32Svg } from './Arch_Amazon-EKS-Cloud_32.svg';
export { default as archAmazonEksDistro32Svg } from './Arch_Amazon-EKS-Distro_32.svg';
export { default as archAmazonElasticContainerRegistry32Svg } from './Arch_Amazon-Elastic-Container-Registry_32.svg';
export { default as archAmazonElasticContainerService32Svg } from './Arch_Amazon-Elastic-Container-Service_32.svg';
export { default as archAmazonElasticKubernetesService32Svg } from './Arch_Amazon-Elastic-Kubernetes-Service_32.svg';
export { default as archRedHatOpenShift32Svg } from './Arch_Red-Hat-OpenShift_32.svg';