import _archAwsElementalAppliancesSoftware48Svg from './Arch_AWS-Elemental-Appliances-&-Software_48.svg';
import _archAwsElementalConductor48Svg from './Arch_AWS-Elemental-Conductor_48.svg';
import _archAwsElementalDelta48Svg from './Arch_AWS-Elemental-Delta_48.svg';
import _archAwsElementalLink48Svg from './Arch_AWS-Elemental-Link_48.svg';
import _archAwsElementalLive48Svg from './Arch_AWS-Elemental-Live_48.svg';
import _archAwsElementalMediaConnect48Svg from './Arch_AWS-Elemental-MediaConnect_48.svg';
import _archAwsElementalMediaConvert48Svg from './Arch_AWS-Elemental-MediaConvert_48.svg';
import _archAwsElementalMediaLive48Svg from './Arch_AWS-Elemental-MediaLive_48.svg';
import _archAwsElementalMediaPackage48Svg from './Arch_AWS-Elemental-MediaPackage_48.svg';
import _archAwsElementalMediaStore48Svg from './Arch_AWS-Elemental-MediaStore_48.svg';
import _archAwsElementalMediaTailor48Svg from './Arch_AWS-Elemental-MediaTailor_48.svg';
import _archAwsElementalServer48Svg from './Arch_AWS-Elemental-Server_48.svg';
import _archAmazonElasticTranscoder48Svg from './Arch_Amazon-Elastic-Transcoder_48.svg';
import _archAmazonInteractiveVideoService48Svg from './Arch_Amazon-Interactive-Video-Service_48.svg';
import _archAmazonKinesisVideoStreams48Svg from './Arch_Amazon-Kinesis-Video-Streams_48.svg';
import _archAmazonNimbleStudio48Svg from './Arch_Amazon-Nimble-Studio_48.svg';

export const archAwsElementalAppliancesSoftware48Svg = { id: "archAwsElementalAppliancesSoftware48Svg", name: "AWS Elemental Appliances & Software", icon: _archAwsElementalAppliancesSoftware48Svg };
export const archAwsElementalConductor48Svg = { id: "archAwsElementalConductor48Svg", name: "AWS Elemental Conductor", icon: _archAwsElementalConductor48Svg };
export const archAwsElementalDelta48Svg = { id: "archAwsElementalDelta48Svg", name: "AWS Elemental Delta", icon: _archAwsElementalDelta48Svg };
export const archAwsElementalLink48Svg = { id: "archAwsElementalLink48Svg", name: "AWS Elemental Link", icon: _archAwsElementalLink48Svg };
export const archAwsElementalLive48Svg = { id: "archAwsElementalLive48Svg", name: "AWS Elemental Live", icon: _archAwsElementalLive48Svg };
export const archAwsElementalMediaConnect48Svg = { id: "archAwsElementalMediaConnect48Svg", name: "AWS Elemental MediaConnect", icon: _archAwsElementalMediaConnect48Svg };
export const archAwsElementalMediaConvert48Svg = { id: "archAwsElementalMediaConvert48Svg", name: "AWS Elemental MediaConvert", icon: _archAwsElementalMediaConvert48Svg };
export const archAwsElementalMediaLive48Svg = { id: "archAwsElementalMediaLive48Svg", name: "AWS Elemental MediaLive", icon: _archAwsElementalMediaLive48Svg };
export const archAwsElementalMediaPackage48Svg = { id: "archAwsElementalMediaPackage48Svg", name: "AWS Elemental MediaPackage", icon: _archAwsElementalMediaPackage48Svg };
export const archAwsElementalMediaStore48Svg = { id: "archAwsElementalMediaStore48Svg", name: "AWS Elemental MediaStore", icon: _archAwsElementalMediaStore48Svg };
export const archAwsElementalMediaTailor48Svg = { id: "archAwsElementalMediaTailor48Svg", name: "AWS Elemental MediaTailor", icon: _archAwsElementalMediaTailor48Svg };
export const archAwsElementalServer48Svg = { id: "archAwsElementalServer48Svg", name: "AWS Elemental Server", icon: _archAwsElementalServer48Svg };
export const archAmazonElasticTranscoder48Svg = { id: "archAmazonElasticTranscoder48Svg", name: "Amazon Elastic Transcoder", icon: _archAmazonElasticTranscoder48Svg };
export const archAmazonInteractiveVideoService48Svg = { id: "archAmazonInteractiveVideoService48Svg", name: "Amazon Interactive Video Service", icon: _archAmazonInteractiveVideoService48Svg };
export const archAmazonKinesisVideoStreams48Svg = { id: "archAmazonKinesisVideoStreams48Svg", name: "Amazon Kinesis Video Streams", icon: _archAmazonKinesisVideoStreams48Svg };
export const archAmazonNimbleStudio48Svg = { id: "archAmazonNimbleStudio48Svg", name: "Amazon Nimble Studio", icon: _archAmazonNimbleStudio48Svg };
