import _archAwsAppMesh16Svg from './Arch_AWS-App-Mesh_16.svg';
import _archAwsClientVpn16Svg from './Arch_AWS-Client-VPN_16.svg';
import _archAwsCloudMap16Svg from './Arch_AWS-Cloud-Map_16.svg';
import _archAwsCloudWan16Svg from './Arch_AWS-Cloud-WAN_16.svg';
import _archAwsDirectConnect16Svg from './Arch_AWS-Direct-Connect_16.svg';
import _archAwsGlobalAccelerator16Svg from './Arch_AWS-Global-Accelerator_16.svg';
import _archAwsPrivate5G16Svg from './Arch_AWS-Private-5G_16.svg';
import _archAwsPrivateLink16Svg from './Arch_AWS-PrivateLink_16.svg';
import _archAwsSiteToSiteVpn16Svg from './Arch_AWS-Site-to-Site-VPN_16.svg';
import _archAwsTransitGateway16Svg from './Arch_AWS-Transit-Gateway_16.svg';
import _archAmazonCloudDirectory16Svg from './Arch_Amazon-Cloud-Directory_16.svg';
import _archAmazonCloudFront16Svg from './Arch_Amazon-CloudFront_16.svg';
import _archAmazonRoute5316Svg from './Arch_Amazon-Route-53_16.svg';
import _archAmazonVirtualPrivateCloud16Svg from './Arch_Amazon-Virtual-Private-Cloud_16.svg';
import _archElasticLoadBalancing16Svg from './Arch_Elastic-Load-Balancing_16.svg';

export const archAwsAppMesh16Svg = { id: "archAwsAppMesh16Svg", name: "AWS App Mesh", icon: _archAwsAppMesh16Svg };
export const archAwsClientVpn16Svg = { id: "archAwsClientVpn16Svg", name: "AWS Client VPN", icon: _archAwsClientVpn16Svg };
export const archAwsCloudMap16Svg = { id: "archAwsCloudMap16Svg", name: "AWS Cloud Map", icon: _archAwsCloudMap16Svg };
export const archAwsCloudWan16Svg = { id: "archAwsCloudWan16Svg", name: "AWS Cloud WAN", icon: _archAwsCloudWan16Svg };
export const archAwsDirectConnect16Svg = { id: "archAwsDirectConnect16Svg", name: "AWS Direct Connect", icon: _archAwsDirectConnect16Svg };
export const archAwsGlobalAccelerator16Svg = { id: "archAwsGlobalAccelerator16Svg", name: "AWS Global Accelerator", icon: _archAwsGlobalAccelerator16Svg };
export const archAwsPrivate5G16Svg = { id: "archAwsPrivate5G16Svg", name: "AWS Private 5G", icon: _archAwsPrivate5G16Svg };
export const archAwsPrivateLink16Svg = { id: "archAwsPrivateLink16Svg", name: "AWS PrivateLink", icon: _archAwsPrivateLink16Svg };
export const archAwsSiteToSiteVpn16Svg = { id: "archAwsSiteToSiteVpn16Svg", name: "AWS Site to Site VPN", icon: _archAwsSiteToSiteVpn16Svg };
export const archAwsTransitGateway16Svg = { id: "archAwsTransitGateway16Svg", name: "AWS Transit Gateway", icon: _archAwsTransitGateway16Svg };
export const archAmazonCloudDirectory16Svg = { id: "archAmazonCloudDirectory16Svg", name: "Amazon Cloud Directory", icon: _archAmazonCloudDirectory16Svg };
export const archAmazonCloudFront16Svg = { id: "archAmazonCloudFront16Svg", name: "Amazon CloudFront", icon: _archAmazonCloudFront16Svg };
export const archAmazonRoute5316Svg = { id: "archAmazonRoute5316Svg", name: "Amazon Route 53", icon: _archAmazonRoute5316Svg };
export const archAmazonVirtualPrivateCloud16Svg = { id: "archAmazonVirtualPrivateCloud16Svg", name: "Amazon Virtual Private Cloud", icon: _archAmazonVirtualPrivateCloud16Svg };
export const archElasticLoadBalancing16Svg = { id: "archElasticLoadBalancing16Svg", name: "Elastic Load Balancing", icon: _archElasticLoadBalancing16Svg };
