export { default as archAwsFargate16Svg } from './Arch_AWS-Fargate_16.svg';
export { default as archAmazonEcsAnywhere16Svg } from './Arch_Amazon-ECS-Anywhere_16.svg';
export { default as archAmazonEksAnywhere16Svg } from './Arch_Amazon-EKS-Anywhere_16.svg';
export { default as archAmazonEksCloud16Svg } from './Arch_Amazon-EKS-Cloud_16.svg';
export { default as archAmazonEksDistro16Svg } from './Arch_Amazon-EKS-Distro_16.svg';
export { default as archAmazonElasticContainerRegistry16Svg } from './Arch_Amazon-Elastic-Container-Registry_16.svg';
export { default as archAmazonElasticContainerService16Svg } from './Arch_Amazon-Elastic-Container-Service_16.svg';
export { default as archAmazonElasticKubernetesService16Svg } from './Arch_Amazon-Elastic-Kubernetes-Service_16.svg';
export { default as archRedHatOpenShift16Svg } from './Arch_Red-Hat-OpenShift_16.svg';