import _archCategoryAnalytics32Svg from './Arch-Category_Analytics_32.svg';
import _archCategoryApplicationIntegration32Svg from './Arch-Category_Application-Integration_32.svg';
import _archCategoryBlockchain32Svg from './Arch-Category_Blockchain_32.svg';
import _archCategoryBusinessApplications32Svg from './Arch-Category_Business-Applications_32.svg';
import _archCategoryCloudFinancialManagement32Svg from './Arch-Category_Cloud-Financial-Management_32.svg';
import _archCategoryCompute32Svg from './Arch-Category_Compute_32.svg';
import _archCategoryContainers32Svg from './Arch-Category_Containers_32.svg';
import _archCategoryCustomerEnablement32Svg from './Arch-Category_Customer-Enablement_32.svg';
import _archCategoryDatabase32Svg from './Arch-Category_Database_32.svg';
import _archCategoryDeveloperTools32Svg from './Arch-Category_Developer-Tools_32.svg';
import _archCategoryEndUserComputing32Svg from './Arch-Category_End-User-Computing_32.svg';
import _archCategoryFrontEndWebMobile32Svg from './Arch-Category_Front-End-Web-Mobile_32.svg';
import _archCategoryGameTech32Svg from './Arch-Category_Game-Tech_32.svg';
import _archCategoryInternetOfThings32Svg from './Arch-Category_Internet-of-Things_32.svg';
import _archCategoryMachineLearning32Svg from './Arch-Category_Machine-Learning_32.svg';
import _archCategoryManagementGovernance32Svg from './Arch-Category_Management-Governance_32.svg';
import _archCategoryMediaServices32Svg from './Arch-Category_Media-Services_32.svg';
import _archCategoryMigrationTransfer32Svg from './Arch-Category_Migration-Transfer_32.svg';
import _archCategoryNetworkingContentDelivery32Svg from './Arch-Category_Networking-Content-Delivery_32.svg';
import _archCategoryQuantumTechnologies32Svg from './Arch-Category_Quantum-Technologies_32.svg';
import _archCategoryRobotics32Svg from './Arch-Category_Robotics_32.svg';
import _archCategorySatellite32Svg from './Arch-Category_Satellite_32.svg';
import _archCategorySecurityIdentityCompliance32Svg from './Arch-Category_Security-Identity-Compliance_32.svg';
import _archCategoryServerless32Svg from './Arch-Category_Serverless_32.svg';
import _archCategoryStorage32Svg from './Arch-Category_Storage_32.svg';
import _archCategoryVrAr32Svg from './Arch-Category_VR-AR_32.svg';

export const archCategoryAnalytics32Svg = { id: "archCategoryAnalytics32Svg", name: "Analytics", icon: _archCategoryAnalytics32Svg };
export const archCategoryApplicationIntegration32Svg = { id: "archCategoryApplicationIntegration32Svg", name: "Application Integration", icon: _archCategoryApplicationIntegration32Svg };
export const archCategoryBlockchain32Svg = { id: "archCategoryBlockchain32Svg", name: "Blockchain", icon: _archCategoryBlockchain32Svg };
export const archCategoryBusinessApplications32Svg = { id: "archCategoryBusinessApplications32Svg", name: "Business Applications", icon: _archCategoryBusinessApplications32Svg };
export const archCategoryCloudFinancialManagement32Svg = { id: "archCategoryCloudFinancialManagement32Svg", name: "Cloud Financial Management", icon: _archCategoryCloudFinancialManagement32Svg };
export const archCategoryCompute32Svg = { id: "archCategoryCompute32Svg", name: "Compute", icon: _archCategoryCompute32Svg };
export const archCategoryContainers32Svg = { id: "archCategoryContainers32Svg", name: "Containers", icon: _archCategoryContainers32Svg };
export const archCategoryCustomerEnablement32Svg = { id: "archCategoryCustomerEnablement32Svg", name: "Customer Enablement", icon: _archCategoryCustomerEnablement32Svg };
export const archCategoryDatabase32Svg = { id: "archCategoryDatabase32Svg", name: "Database", icon: _archCategoryDatabase32Svg };
export const archCategoryDeveloperTools32Svg = { id: "archCategoryDeveloperTools32Svg", name: "Developer Tools", icon: _archCategoryDeveloperTools32Svg };
export const archCategoryEndUserComputing32Svg = { id: "archCategoryEndUserComputing32Svg", name: "End User Computing", icon: _archCategoryEndUserComputing32Svg };
export const archCategoryFrontEndWebMobile32Svg = { id: "archCategoryFrontEndWebMobile32Svg", name: "Front End Web Mobile", icon: _archCategoryFrontEndWebMobile32Svg };
export const archCategoryGameTech32Svg = { id: "archCategoryGameTech32Svg", name: "Game Tech", icon: _archCategoryGameTech32Svg };
export const archCategoryInternetOfThings32Svg = { id: "archCategoryInternetOfThings32Svg", name: "Internet of Things", icon: _archCategoryInternetOfThings32Svg };
export const archCategoryMachineLearning32Svg = { id: "archCategoryMachineLearning32Svg", name: "Machine Learning", icon: _archCategoryMachineLearning32Svg };
export const archCategoryManagementGovernance32Svg = { id: "archCategoryManagementGovernance32Svg", name: "Management Governance", icon: _archCategoryManagementGovernance32Svg };
export const archCategoryMediaServices32Svg = { id: "archCategoryMediaServices32Svg", name: "Media Services", icon: _archCategoryMediaServices32Svg };
export const archCategoryMigrationTransfer32Svg = { id: "archCategoryMigrationTransfer32Svg", name: "Migration Transfer", icon: _archCategoryMigrationTransfer32Svg };
export const archCategoryNetworkingContentDelivery32Svg = { id: "archCategoryNetworkingContentDelivery32Svg", name: "Networking Content Delivery", icon: _archCategoryNetworkingContentDelivery32Svg };
export const archCategoryQuantumTechnologies32Svg = { id: "archCategoryQuantumTechnologies32Svg", name: "Quantum Technologies", icon: _archCategoryQuantumTechnologies32Svg };
export const archCategoryRobotics32Svg = { id: "archCategoryRobotics32Svg", name: "Robotics", icon: _archCategoryRobotics32Svg };
export const archCategorySatellite32Svg = { id: "archCategorySatellite32Svg", name: "Satellite", icon: _archCategorySatellite32Svg };
export const archCategorySecurityIdentityCompliance32Svg = { id: "archCategorySecurityIdentityCompliance32Svg", name: "Security Identity Compliance", icon: _archCategorySecurityIdentityCompliance32Svg };
export const archCategoryServerless32Svg = { id: "archCategoryServerless32Svg", name: "Serverless", icon: _archCategoryServerless32Svg };
export const archCategoryStorage32Svg = { id: "archCategoryStorage32Svg", name: "Storage", icon: _archCategoryStorage32Svg };
export const archCategoryVrAr32Svg = { id: "archCategoryVrAr32Svg", name: "VR AR", icon: _archCategoryVrAr32Svg };
