import _archAwsAppMesh48Svg from './Arch_AWS-App-Mesh_48.svg';
import _archAwsClientVpn48Svg from './Arch_AWS-Client-VPN_48.svg';
import _archAwsCloudMap48Svg from './Arch_AWS-Cloud-Map_48.svg';
import _archAwsCloudWan48Svg from './Arch_AWS-Cloud-WAN_48.svg';
import _archAwsDirectConnect48Svg from './Arch_AWS-Direct-Connect_48.svg';
import _archAwsGlobalAccelerator48Svg from './Arch_AWS-Global-Accelerator_48.svg';
import _archAwsPrivate5G48Svg from './Arch_AWS-Private-5G_48.svg';
import _archAwsPrivateLink48Svg from './Arch_AWS-PrivateLink_48.svg';
import _archAwsSiteToSiteVpn48Svg from './Arch_AWS-Site-to-Site-VPN_48.svg';
import _archAwsTransitGateway48Svg from './Arch_AWS-Transit-Gateway_48.svg';
import _archAmazonCloudDirectory48Svg from './Arch_Amazon-Cloud-Directory_48.svg';
import _archAmazonCloudFront48Svg from './Arch_Amazon-CloudFront_48.svg';
import _archAmazonRoute5348Svg from './Arch_Amazon-Route-53_48.svg';
import _archAmazonVirtualPrivateCloud48Svg from './Arch_Amazon-Virtual-Private-Cloud_48.svg';
import _archElasticLoadBalancing48Svg from './Arch_Elastic-Load-Balancing_48.svg';

export const archAwsAppMesh48Svg = { id: "archAwsAppMesh48Svg", name: "AWS App Mesh", icon: _archAwsAppMesh48Svg };
export const archAwsClientVpn48Svg = { id: "archAwsClientVpn48Svg", name: "AWS Client VPN", icon: _archAwsClientVpn48Svg };
export const archAwsCloudMap48Svg = { id: "archAwsCloudMap48Svg", name: "AWS Cloud Map", icon: _archAwsCloudMap48Svg };
export const archAwsCloudWan48Svg = { id: "archAwsCloudWan48Svg", name: "AWS Cloud WAN", icon: _archAwsCloudWan48Svg };
export const archAwsDirectConnect48Svg = { id: "archAwsDirectConnect48Svg", name: "AWS Direct Connect", icon: _archAwsDirectConnect48Svg };
export const archAwsGlobalAccelerator48Svg = { id: "archAwsGlobalAccelerator48Svg", name: "AWS Global Accelerator", icon: _archAwsGlobalAccelerator48Svg };
export const archAwsPrivate5G48Svg = { id: "archAwsPrivate5G48Svg", name: "AWS Private 5G", icon: _archAwsPrivate5G48Svg };
export const archAwsPrivateLink48Svg = { id: "archAwsPrivateLink48Svg", name: "AWS PrivateLink", icon: _archAwsPrivateLink48Svg };
export const archAwsSiteToSiteVpn48Svg = { id: "archAwsSiteToSiteVpn48Svg", name: "AWS Site to Site VPN", icon: _archAwsSiteToSiteVpn48Svg };
export const archAwsTransitGateway48Svg = { id: "archAwsTransitGateway48Svg", name: "AWS Transit Gateway", icon: _archAwsTransitGateway48Svg };
export const archAmazonCloudDirectory48Svg = { id: "archAmazonCloudDirectory48Svg", name: "Amazon Cloud Directory", icon: _archAmazonCloudDirectory48Svg };
export const archAmazonCloudFront48Svg = { id: "archAmazonCloudFront48Svg", name: "Amazon CloudFront", icon: _archAmazonCloudFront48Svg };
export const archAmazonRoute5348Svg = { id: "archAmazonRoute5348Svg", name: "Amazon Route 53", icon: _archAmazonRoute5348Svg };
export const archAmazonVirtualPrivateCloud48Svg = { id: "archAmazonVirtualPrivateCloud48Svg", name: "Amazon Virtual Private Cloud", icon: _archAmazonVirtualPrivateCloud48Svg };
export const archElasticLoadBalancing48Svg = { id: "archElasticLoadBalancing48Svg", name: "Elastic Load Balancing", icon: _archElasticLoadBalancing48Svg };
