import _archAwsDatabaseMigrationService48Svg from './Arch_AWS-Database-Migration-Service_48.svg';
import _archAmazonAurora48Svg from './Arch_Amazon-Aurora_48.svg';
import _archAmazonDocumentDb48Svg from './Arch_Amazon-DocumentDB_48.svg';
import _archAmazonDynamoDb48Svg from './Arch_Amazon-DynamoDB_48.svg';
import _archAmazonElastiCache48Svg from './Arch_Amazon-ElastiCache_48.svg';
import _archAmazonKeyspaces48Svg from './Arch_Amazon-Keyspaces_48.svg';
import _archAmazonMemoryDbForRedis48Svg from './Arch_Amazon-MemoryDB-for-Redis_48.svg';
import _archAmazonNeptune48Svg from './Arch_Amazon-Neptune_48.svg';
import _archAmazonQuantumLedgerDatabase48Svg from './Arch_Amazon-Quantum-Ledger-Database_48.svg';
import _archAmazonRdsOnVmware48Svg from './Arch_Amazon-RDS-on-VMware_48.svg';
import _archAmazonRds48Svg from './Arch_Amazon-RDS_48.svg';
import _archAmazonTimestream48Svg from './Arch_Amazon-Timestream_48.svg';

export const archAwsDatabaseMigrationService48Svg = { id: "archAwsDatabaseMigrationService48Svg", name: "AWS Database Migration Service", icon: _archAwsDatabaseMigrationService48Svg };
export const archAmazonAurora48Svg = { id: "archAmazonAurora48Svg", name: "Amazon Aurora", icon: _archAmazonAurora48Svg };
export const archAmazonDocumentDb48Svg = { id: "archAmazonDocumentDb48Svg", name: "Amazon DocumentDB", icon: _archAmazonDocumentDb48Svg };
export const archAmazonDynamoDb48Svg = { id: "archAmazonDynamoDb48Svg", name: "Amazon DynamoDB", icon: _archAmazonDynamoDb48Svg };
export const archAmazonElastiCache48Svg = { id: "archAmazonElastiCache48Svg", name: "Amazon ElastiCache", icon: _archAmazonElastiCache48Svg };
export const archAmazonKeyspaces48Svg = { id: "archAmazonKeyspaces48Svg", name: "Amazon Keyspaces", icon: _archAmazonKeyspaces48Svg };
export const archAmazonMemoryDbForRedis48Svg = { id: "archAmazonMemoryDbForRedis48Svg", name: "Amazon MemoryDB for Redis", icon: _archAmazonMemoryDbForRedis48Svg };
export const archAmazonNeptune48Svg = { id: "archAmazonNeptune48Svg", name: "Amazon Neptune", icon: _archAmazonNeptune48Svg };
export const archAmazonQuantumLedgerDatabase48Svg = { id: "archAmazonQuantumLedgerDatabase48Svg", name: "Amazon Quantum Ledger Database", icon: _archAmazonQuantumLedgerDatabase48Svg };
export const archAmazonRdsOnVmware48Svg = { id: "archAmazonRdsOnVmware48Svg", name: "Amazon RDS on VMware", icon: _archAmazonRdsOnVmware48Svg };
export const archAmazonRds48Svg = { id: "archAmazonRds48Svg", name: "Amazon RDS", icon: _archAmazonRds48Svg };
export const archAmazonTimestream48Svg = { id: "archAmazonTimestream48Svg", name: "Amazon Timestream", icon: _archAmazonTimestream48Svg };
