import _archAwsDataExchange48Svg from './Arch_AWS-Data-Exchange_48.svg';
import _archAwsDataPipeline48Svg from './Arch_AWS-Data-Pipeline_48.svg';
import _archAwsGlueDataBrew48Svg from './Arch_AWS-Glue-DataBrew_48.svg';
import _archAwsGlueElasticViews48Svg from './Arch_AWS-Glue-Elastic-Views_48.svg';
import _archAwsGlue48Svg from './Arch_AWS-Glue_48.svg';
import _archAwsLakeFormation48Svg from './Arch_AWS-Lake-Formation_48.svg';
import _archAmazonAthena48Svg from './Arch_Amazon-Athena_48.svg';
import _archAmazonCloudSearch48Svg from './Arch_Amazon-CloudSearch_48.svg';
import _archAmazonEmr48Svg from './Arch_Amazon-EMR_48.svg';
import _archAmazonFinSpace48Svg from './Arch_Amazon-FinSpace_48.svg';
import _archAmazonKinesisDataAnalytics48Svg from './Arch_Amazon-Kinesis-Data-Analytics_48.svg';
import _archAmazonKinesisDataStreams48Svg from './Arch_Amazon-Kinesis-Data-Streams_48.svg';
import _archAmazonKinesisFirehose48Svg from './Arch_Amazon-Kinesis-Firehose_48.svg';
import _archAmazonKinesisVideoStreams48Svg from './Arch_Amazon-Kinesis-Video-Streams_48.svg';
import _archAmazonKinesis48Svg from './Arch_Amazon-Kinesis_48.svg';
import _archAmazonManagedStreamingForApacheKafka48Svg from './Arch_Amazon-Managed-Streaming-for-Apache-Kafka_48.svg';
import _archAmazonOpenSearchService48Svg from './Arch_Amazon-OpenSearch-Service_48.svg';
import _archAmazonQuickSight48Svg from './Arch_Amazon-QuickSight_48.svg';
import _archAmazonRedshift48Svg from './Arch_Amazon-Redshift_48.svg';

export const archAwsDataExchange48Svg = { id: "archAwsDataExchange48Svg", name: "AWS Data Exchange", icon: _archAwsDataExchange48Svg };
export const archAwsDataPipeline48Svg = { id: "archAwsDataPipeline48Svg", name: "AWS Data Pipeline", icon: _archAwsDataPipeline48Svg };
export const archAwsGlueDataBrew48Svg = { id: "archAwsGlueDataBrew48Svg", name: "AWS Glue DataBrew", icon: _archAwsGlueDataBrew48Svg };
export const archAwsGlueElasticViews48Svg = { id: "archAwsGlueElasticViews48Svg", name: "AWS Glue Elastic Views", icon: _archAwsGlueElasticViews48Svg };
export const archAwsGlue48Svg = { id: "archAwsGlue48Svg", name: "AWS Glue", icon: _archAwsGlue48Svg };
export const archAwsLakeFormation48Svg = { id: "archAwsLakeFormation48Svg", name: "AWS Lake Formation", icon: _archAwsLakeFormation48Svg };
export const archAmazonAthena48Svg = { id: "archAmazonAthena48Svg", name: "Amazon Athena", icon: _archAmazonAthena48Svg };
export const archAmazonCloudSearch48Svg = { id: "archAmazonCloudSearch48Svg", name: "Amazon CloudSearch", icon: _archAmazonCloudSearch48Svg };
export const archAmazonEmr48Svg = { id: "archAmazonEmr48Svg", name: "Amazon EMR", icon: _archAmazonEmr48Svg };
export const archAmazonFinSpace48Svg = { id: "archAmazonFinSpace48Svg", name: "Amazon FinSpace", icon: _archAmazonFinSpace48Svg };
export const archAmazonKinesisDataAnalytics48Svg = { id: "archAmazonKinesisDataAnalytics48Svg", name: "Amazon Kinesis Data Analytics", icon: _archAmazonKinesisDataAnalytics48Svg };
export const archAmazonKinesisDataStreams48Svg = { id: "archAmazonKinesisDataStreams48Svg", name: "Amazon Kinesis Data Streams", icon: _archAmazonKinesisDataStreams48Svg };
export const archAmazonKinesisFirehose48Svg = { id: "archAmazonKinesisFirehose48Svg", name: "Amazon Kinesis Firehose", icon: _archAmazonKinesisFirehose48Svg };
export const archAmazonKinesisVideoStreams48Svg = { id: "archAmazonKinesisVideoStreams48Svg", name: "Amazon Kinesis Video Streams", icon: _archAmazonKinesisVideoStreams48Svg };
export const archAmazonKinesis48Svg = { id: "archAmazonKinesis48Svg", name: "Amazon Kinesis", icon: _archAmazonKinesis48Svg };
export const archAmazonManagedStreamingForApacheKafka48Svg = { id: "archAmazonManagedStreamingForApacheKafka48Svg", name: "Amazon Managed Streaming for Apache Kafka", icon: _archAmazonManagedStreamingForApacheKafka48Svg };
export const archAmazonOpenSearchService48Svg = { id: "archAmazonOpenSearchService48Svg", name: "Amazon OpenSearch Service", icon: _archAmazonOpenSearchService48Svg };
export const archAmazonQuickSight48Svg = { id: "archAmazonQuickSight48Svg", name: "Amazon QuickSight", icon: _archAmazonQuickSight48Svg };
export const archAmazonRedshift48Svg = { id: "archAmazonRedshift48Svg", name: "Amazon Redshift", icon: _archAmazonRedshift48Svg };
