import _archAmazonApiGateway32Svg from './Arch_ Amazon-API-Gateway_32.svg';
import _archAwsAppSync32Svg from './Arch_AWS-AppSync_32.svg';
import _archAwsConsoleMobileApplication32Svg from './Arch_AWS-Console-Mobile-Application _32.svg';
import _archAwsExpressWorkflows32Svg from './Arch_AWS-Express-Workflows_32.svg';
import _archAwsStepFunctions32Svg from './Arch_AWS-Step-Functions_32.svg';
import _archAmazonAppFlow32Svg from './Arch_Amazon-AppFlow_32.svg';
import _archAmazonEventBridge32Svg from './Arch_Amazon-EventBridge_32.svg';
import _archAmazonMq32Svg from './Arch_Amazon-MQ_32.svg';
import _archAmazonManagedWorkflowsForApacheAirflow32Svg from './Arch_Amazon-Managed-Workflows-for-Apache-Airflow_32.svg';
import _archAmazonSimpleNotificationService32Svg from './Arch_Amazon-Simple-Notification-Service_32.svg';
import _archAmazonSimpleQueueService32Svg from './Arch_Amazon-Simple-Queue-Service_32.svg';

export const archAmazonApiGateway32Svg = { id: "archAmazonApiGateway32Svg", name: " Amazon API Gateway", icon: _archAmazonApiGateway32Svg };
export const archAwsAppSync32Svg = { id: "archAwsAppSync32Svg", name: "AWS AppSync", icon: _archAwsAppSync32Svg };
export const archAwsConsoleMobileApplication32Svg = { id: "archAwsConsoleMobileApplication32Svg", name: "AWS Console Mobile Application ", icon: _archAwsConsoleMobileApplication32Svg };
export const archAwsExpressWorkflows32Svg = { id: "archAwsExpressWorkflows32Svg", name: "AWS Express Workflows", icon: _archAwsExpressWorkflows32Svg };
export const archAwsStepFunctions32Svg = { id: "archAwsStepFunctions32Svg", name: "AWS Step Functions", icon: _archAwsStepFunctions32Svg };
export const archAmazonAppFlow32Svg = { id: "archAmazonAppFlow32Svg", name: "Amazon AppFlow", icon: _archAmazonAppFlow32Svg };
export const archAmazonEventBridge32Svg = { id: "archAmazonEventBridge32Svg", name: "Amazon EventBridge", icon: _archAmazonEventBridge32Svg };
export const archAmazonMq32Svg = { id: "archAmazonMq32Svg", name: "Amazon MQ", icon: _archAmazonMq32Svg };
export const archAmazonManagedWorkflowsForApacheAirflow32Svg = { id: "archAmazonManagedWorkflowsForApacheAirflow32Svg", name: "Amazon Managed Workflows for Apache Airflow", icon: _archAmazonManagedWorkflowsForApacheAirflow32Svg };
export const archAmazonSimpleNotificationService32Svg = { id: "archAmazonSimpleNotificationService32Svg", name: "Amazon Simple Notification Service", icon: _archAmazonSimpleNotificationService32Svg };
export const archAmazonSimpleQueueService32Svg = { id: "archAmazonSimpleQueueService32Svg", name: "Amazon Simple Queue Service", icon: _archAmazonSimpleQueueService32Svg };
