import _archAwsDeepLearningAmIs32Svg from './Arch_AWS-Deep-Learning-AMIs_32.svg';
import _archAwsDeepLearningContainers32Svg from './Arch_AWS-Deep-Learning-Containers_32.svg';
import _archAwsDeepComposer32Svg from './Arch_AWS-DeepComposer_32.svg';
import _archAwsDeepLens32Svg from './Arch_AWS-DeepLens_32.svg';
import _archAwsDeepRacer32Svg from './Arch_AWS-DeepRacer_32.svg';
import _archAwsNeuron32Svg from './Arch_AWS-Neuron_32.svg';
import _archAwsPanorama32Svg from './Arch_AWS-Panorama_32.svg';
import _archAmazonAugmentedAiA2I32Svg from './Arch_Amazon-Augmented-AI-A2I_32.svg';
import _archAmazonCodeGuru32Svg from './Arch_Amazon-CodeGuru_32.svg';
import _archAmazonCodeWhisperer32Svg from './Arch_Amazon-CodeWhisperer_32.svg';
import _archAmazonComprehendMedical32Svg from './Arch_Amazon-Comprehend-Medical_32.svg';
import _archAmazonComprehend32Svg from './Arch_Amazon-Comprehend_32.svg';
import _archAmazonDevOpsGuru32Svg from './Arch_Amazon-DevOps-Guru_32.svg';
import _archAmazonElasticInference32Svg from './Arch_Amazon-Elastic-Inference_32.svg';
import _archAmazonForecast32Svg from './Arch_Amazon-Forecast_32.svg';
import _archAmazonFraudDetector32Svg from './Arch_Amazon-Fraud-Detector_32.svg';
import _archAmazonHealthLake32Svg from './Arch_Amazon-HealthLake_32.svg';
import _archAmazonKendra32Svg from './Arch_Amazon-Kendra_32.svg';
import _archAmazonLex32Svg from './Arch_Amazon-Lex_32.svg';
import _archAmazonLookoutForEquipment32Svg from './Arch_Amazon-Lookout-for-Equipment_32.svg';
import _archAmazonLookoutForMetrics32Svg from './Arch_Amazon-Lookout-for-Metrics_32.svg';
import _archAmazonLookoutForVision32Svg from './Arch_Amazon-Lookout-for-Vision_32.svg';
import _archAmazonMonitron32Svg from './Arch_Amazon-Monitron_32.svg';
import _archAmazonPersonalize32Svg from './Arch_Amazon-Personalize_32.svg';
import _archAmazonPolly32Svg from './Arch_Amazon-Polly_32.svg';
import _archAmazonRekognition32Svg from './Arch_Amazon-Rekognition_32.svg';
import _archAmazonSageMakerGroundTruth32Svg from './Arch_Amazon-SageMaker-Ground-Truth_32.svg';
import _archAmazonSageMakerStudioLab32Svg from './Arch_Amazon-SageMaker-Studio-Lab_32.svg';
import _archAmazonSageMaker32Svg from './Arch_Amazon-SageMaker_32.svg';
import _archAmazonTextract32Svg from './Arch_Amazon-Textract_32.svg';
import _archAmazonTranscribe32Svg from './Arch_Amazon-Transcribe_32.svg';
import _archAmazonTranslate32Svg from './Arch_Amazon-Translate_32.svg';
import _archApacheMxNetOnAws32Svg from './Arch_Apache-MXNet-on-AWS_32.svg';
import _archTensorFlowOnAws32Svg from './Arch_TensorFlow-on-AWS_32.svg';
import _archTorchServe32Svg from './Arch_TorchServe_32.svg';

export const archAwsDeepLearningAmIs32Svg = { id: "archAwsDeepLearningAmIs32Svg", name: "AWS Deep Learning AMIs", icon: _archAwsDeepLearningAmIs32Svg };
export const archAwsDeepLearningContainers32Svg = { id: "archAwsDeepLearningContainers32Svg", name: "AWS Deep Learning Containers", icon: _archAwsDeepLearningContainers32Svg };
export const archAwsDeepComposer32Svg = { id: "archAwsDeepComposer32Svg", name: "AWS DeepComposer", icon: _archAwsDeepComposer32Svg };
export const archAwsDeepLens32Svg = { id: "archAwsDeepLens32Svg", name: "AWS DeepLens", icon: _archAwsDeepLens32Svg };
export const archAwsDeepRacer32Svg = { id: "archAwsDeepRacer32Svg", name: "AWS DeepRacer", icon: _archAwsDeepRacer32Svg };
export const archAwsNeuron32Svg = { id: "archAwsNeuron32Svg", name: "AWS Neuron", icon: _archAwsNeuron32Svg };
export const archAwsPanorama32Svg = { id: "archAwsPanorama32Svg", name: "AWS Panorama", icon: _archAwsPanorama32Svg };
export const archAmazonAugmentedAiA2I32Svg = { id: "archAmazonAugmentedAiA2I32Svg", name: "Amazon Augmented AI A2I", icon: _archAmazonAugmentedAiA2I32Svg };
export const archAmazonCodeGuru32Svg = { id: "archAmazonCodeGuru32Svg", name: "Amazon CodeGuru", icon: _archAmazonCodeGuru32Svg };
export const archAmazonCodeWhisperer32Svg = { id: "archAmazonCodeWhisperer32Svg", name: "Amazon CodeWhisperer", icon: _archAmazonCodeWhisperer32Svg };
export const archAmazonComprehendMedical32Svg = { id: "archAmazonComprehendMedical32Svg", name: "Amazon Comprehend Medical", icon: _archAmazonComprehendMedical32Svg };
export const archAmazonComprehend32Svg = { id: "archAmazonComprehend32Svg", name: "Amazon Comprehend", icon: _archAmazonComprehend32Svg };
export const archAmazonDevOpsGuru32Svg = { id: "archAmazonDevOpsGuru32Svg", name: "Amazon DevOps Guru", icon: _archAmazonDevOpsGuru32Svg };
export const archAmazonElasticInference32Svg = { id: "archAmazonElasticInference32Svg", name: "Amazon Elastic Inference", icon: _archAmazonElasticInference32Svg };
export const archAmazonForecast32Svg = { id: "archAmazonForecast32Svg", name: "Amazon Forecast", icon: _archAmazonForecast32Svg };
export const archAmazonFraudDetector32Svg = { id: "archAmazonFraudDetector32Svg", name: "Amazon Fraud Detector", icon: _archAmazonFraudDetector32Svg };
export const archAmazonHealthLake32Svg = { id: "archAmazonHealthLake32Svg", name: "Amazon HealthLake", icon: _archAmazonHealthLake32Svg };
export const archAmazonKendra32Svg = { id: "archAmazonKendra32Svg", name: "Amazon Kendra", icon: _archAmazonKendra32Svg };
export const archAmazonLex32Svg = { id: "archAmazonLex32Svg", name: "Amazon Lex", icon: _archAmazonLex32Svg };
export const archAmazonLookoutForEquipment32Svg = { id: "archAmazonLookoutForEquipment32Svg", name: "Amazon Lookout for Equipment", icon: _archAmazonLookoutForEquipment32Svg };
export const archAmazonLookoutForMetrics32Svg = { id: "archAmazonLookoutForMetrics32Svg", name: "Amazon Lookout for Metrics", icon: _archAmazonLookoutForMetrics32Svg };
export const archAmazonLookoutForVision32Svg = { id: "archAmazonLookoutForVision32Svg", name: "Amazon Lookout for Vision", icon: _archAmazonLookoutForVision32Svg };
export const archAmazonMonitron32Svg = { id: "archAmazonMonitron32Svg", name: "Amazon Monitron", icon: _archAmazonMonitron32Svg };
export const archAmazonPersonalize32Svg = { id: "archAmazonPersonalize32Svg", name: "Amazon Personalize", icon: _archAmazonPersonalize32Svg };
export const archAmazonPolly32Svg = { id: "archAmazonPolly32Svg", name: "Amazon Polly", icon: _archAmazonPolly32Svg };
export const archAmazonRekognition32Svg = { id: "archAmazonRekognition32Svg", name: "Amazon Rekognition", icon: _archAmazonRekognition32Svg };
export const archAmazonSageMakerGroundTruth32Svg = { id: "archAmazonSageMakerGroundTruth32Svg", name: "Amazon SageMaker Ground Truth", icon: _archAmazonSageMakerGroundTruth32Svg };
export const archAmazonSageMakerStudioLab32Svg = { id: "archAmazonSageMakerStudioLab32Svg", name: "Amazon SageMaker Studio Lab", icon: _archAmazonSageMakerStudioLab32Svg };
export const archAmazonSageMaker32Svg = { id: "archAmazonSageMaker32Svg", name: "Amazon SageMaker", icon: _archAmazonSageMaker32Svg };
export const archAmazonTextract32Svg = { id: "archAmazonTextract32Svg", name: "Amazon Textract", icon: _archAmazonTextract32Svg };
export const archAmazonTranscribe32Svg = { id: "archAmazonTranscribe32Svg", name: "Amazon Transcribe", icon: _archAmazonTranscribe32Svg };
export const archAmazonTranslate32Svg = { id: "archAmazonTranslate32Svg", name: "Amazon Translate", icon: _archAmazonTranslate32Svg };
export const archApacheMxNetOnAws32Svg = { id: "archApacheMxNetOnAws32Svg", name: "Apache MXNet on AWS", icon: _archApacheMxNetOnAws32Svg };
export const archTensorFlowOnAws32Svg = { id: "archTensorFlowOnAws32Svg", name: "TensorFlow on AWS", icon: _archTensorFlowOnAws32Svg };
export const archTorchServe32Svg = { id: "archTorchServe32Svg", name: "TorchServe", icon: _archTorchServe32Svg };
