import _archCategoryAnalytics64Svg from './Arch-Category_Analytics_64.svg';
import _archCategoryApplicationIntegration64Svg from './Arch-Category_Application-Integration_64.svg';
import _archCategoryBlockchain64Svg from './Arch-Category_Blockchain_64.svg';
import _archCategoryBusinessApplications64Svg from './Arch-Category_Business-Applications_64.svg';
import _archCategoryCloudFinancialManagement64Svg from './Arch-Category_Cloud-Financial-Management_64.svg';
import _archCategoryCompute64Svg from './Arch-Category_Compute_64.svg';
import _archCategoryContainers64Svg from './Arch-Category_Containers_64.svg';
import _archCategoryCustomerEnablement64Svg from './Arch-Category_Customer-Enablement_64.svg';
import _archCategoryDatabase64Svg from './Arch-Category_Database_64.svg';
import _archCategoryDeveloperTools64Svg from './Arch-Category_Developer-Tools_64.svg';
import _archCategoryEndUserComputing64Svg from './Arch-Category_End-User-Computing_64.svg';
import _archCategoryFrontEndWebMobile64Svg from './Arch-Category_Front-End-Web-Mobile_64.svg';
import _archCategoryGameTech64Svg from './Arch-Category_Game-Tech_64.svg';
import _archCategoryInternetOfThings64Svg from './Arch-Category_Internet-of-Things_64.svg';
import _archCategoryMachineLearning64Svg from './Arch-Category_Machine-Learning_64.svg';
import _archCategoryManagementGovernance64Svg from './Arch-Category_Management-Governance_64.svg';
import _archCategoryMediaServices64Svg from './Arch-Category_Media-Services_64.svg';
import _archCategoryMigrationTransfer64Svg from './Arch-Category_Migration-Transfer_64.svg';
import _archCategoryNetworkingContentDelivery64Svg from './Arch-Category_Networking-Content-Delivery_64.svg';
import _archCategoryQuantumTechnologies64Svg from './Arch-Category_Quantum-Technologies_64.svg';
import _archCategoryRobotics64Svg from './Arch-Category_Robotics_64.svg';
import _archCategorySatellite64Svg from './Arch-Category_Satellite_64.svg';
import _archCategorySecurityIdentityCompliance64Svg from './Arch-Category_Security-Identity-Compliance_64.svg';
import _archCategoryServerless64Svg from './Arch-Category_Serverless_64.svg';
import _archCategoryStorage64Svg from './Arch-Category_Storage_64.svg';
import _archCategoryVrAr64Svg from './Arch-Category_VR-AR_64.svg';

export const archCategoryAnalytics64Svg = { id: "archCategoryAnalytics64Svg", name: "Analytics", icon: _archCategoryAnalytics64Svg };
export const archCategoryApplicationIntegration64Svg = { id: "archCategoryApplicationIntegration64Svg", name: "Application Integration", icon: _archCategoryApplicationIntegration64Svg };
export const archCategoryBlockchain64Svg = { id: "archCategoryBlockchain64Svg", name: "Blockchain", icon: _archCategoryBlockchain64Svg };
export const archCategoryBusinessApplications64Svg = { id: "archCategoryBusinessApplications64Svg", name: "Business Applications", icon: _archCategoryBusinessApplications64Svg };
export const archCategoryCloudFinancialManagement64Svg = { id: "archCategoryCloudFinancialManagement64Svg", name: "Cloud Financial Management", icon: _archCategoryCloudFinancialManagement64Svg };
export const archCategoryCompute64Svg = { id: "archCategoryCompute64Svg", name: "Compute", icon: _archCategoryCompute64Svg };
export const archCategoryContainers64Svg = { id: "archCategoryContainers64Svg", name: "Containers", icon: _archCategoryContainers64Svg };
export const archCategoryCustomerEnablement64Svg = { id: "archCategoryCustomerEnablement64Svg", name: "Customer Enablement", icon: _archCategoryCustomerEnablement64Svg };
export const archCategoryDatabase64Svg = { id: "archCategoryDatabase64Svg", name: "Database", icon: _archCategoryDatabase64Svg };
export const archCategoryDeveloperTools64Svg = { id: "archCategoryDeveloperTools64Svg", name: "Developer Tools", icon: _archCategoryDeveloperTools64Svg };
export const archCategoryEndUserComputing64Svg = { id: "archCategoryEndUserComputing64Svg", name: "End User Computing", icon: _archCategoryEndUserComputing64Svg };
export const archCategoryFrontEndWebMobile64Svg = { id: "archCategoryFrontEndWebMobile64Svg", name: "Front End Web Mobile", icon: _archCategoryFrontEndWebMobile64Svg };
export const archCategoryGameTech64Svg = { id: "archCategoryGameTech64Svg", name: "Game Tech", icon: _archCategoryGameTech64Svg };
export const archCategoryInternetOfThings64Svg = { id: "archCategoryInternetOfThings64Svg", name: "Internet of Things", icon: _archCategoryInternetOfThings64Svg };
export const archCategoryMachineLearning64Svg = { id: "archCategoryMachineLearning64Svg", name: "Machine Learning", icon: _archCategoryMachineLearning64Svg };
export const archCategoryManagementGovernance64Svg = { id: "archCategoryManagementGovernance64Svg", name: "Management Governance", icon: _archCategoryManagementGovernance64Svg };
export const archCategoryMediaServices64Svg = { id: "archCategoryMediaServices64Svg", name: "Media Services", icon: _archCategoryMediaServices64Svg };
export const archCategoryMigrationTransfer64Svg = { id: "archCategoryMigrationTransfer64Svg", name: "Migration Transfer", icon: _archCategoryMigrationTransfer64Svg };
export const archCategoryNetworkingContentDelivery64Svg = { id: "archCategoryNetworkingContentDelivery64Svg", name: "Networking Content Delivery", icon: _archCategoryNetworkingContentDelivery64Svg };
export const archCategoryQuantumTechnologies64Svg = { id: "archCategoryQuantumTechnologies64Svg", name: "Quantum Technologies", icon: _archCategoryQuantumTechnologies64Svg };
export const archCategoryRobotics64Svg = { id: "archCategoryRobotics64Svg", name: "Robotics", icon: _archCategoryRobotics64Svg };
export const archCategorySatellite64Svg = { id: "archCategorySatellite64Svg", name: "Satellite", icon: _archCategorySatellite64Svg };
export const archCategorySecurityIdentityCompliance64Svg = { id: "archCategorySecurityIdentityCompliance64Svg", name: "Security Identity Compliance", icon: _archCategorySecurityIdentityCompliance64Svg };
export const archCategoryServerless64Svg = { id: "archCategoryServerless64Svg", name: "Serverless", icon: _archCategoryServerless64Svg };
export const archCategoryStorage64Svg = { id: "archCategoryStorage64Svg", name: "Storage", icon: _archCategoryStorage64Svg };
export const archCategoryVrAr64Svg = { id: "archCategoryVrAr64Svg", name: "VR AR", icon: _archCategoryVrAr64Svg };
