import _archAwsAppConfig64Svg from './Arch_AWS-AppConfig_64.svg';
import _archAwsApplicationAutoScaling64Svg from './Arch_AWS-Application-Auto-Scaling_64.svg';
import _archAwsAutoScaling64Svg from './Arch_AWS-Auto-Scaling_64.svg';
import _archAwsBackintAgent64Svg from './Arch_AWS-Backint-Agent_64.svg';
import _archAwsChatbot64Svg from './Arch_AWS-Chatbot_64.svg';
import _archAwsCloudFormation64Svg from './Arch_AWS-CloudFormation_64.svg';
import _archAwsCloudTrail64Svg from './Arch_AWS-CloudTrail_64.svg';
import _archAwsConfig64Svg from './Arch_AWS-Config_64.svg';
import _archAwsControlTower64Svg from './Arch_AWS-Control-Tower_64.svg';
import _archAwsDistroForOpenTelemetry64Svg from './Arch_AWS-Distro-for-OpenTelemetry_64.svg';
import _archAwsFaultInjectionSimulator64Svg from './Arch_AWS-Fault-Injection-Simulator_64.svg';
import _archAwsLaunchWizard64Svg from './Arch_AWS-Launch-Wizard_64.svg';
import _archAwsLicenseManager64Svg from './Arch_AWS-License-Manager_64.svg';
import _archAwsManagementConsole64Svg from './Arch_AWS-Management-Console_64.svg';
import _archAwsOpsWorks64Svg from './Arch_AWS-OpsWorks_64.svg';
import _archAwsOrganizations64Svg from './Arch_AWS-Organizations_64.svg';
import _archAwsPersonalHealthDashboard64Svg from './Arch_AWS-Personal-Health-Dashboard_64.svg';
import _archAwsProton64Svg from './Arch_AWS-Proton_64.svg';
import _archAwsResilienceHub64Svg from './Arch_AWS-Resilience-Hub_64.svg';
import _archAwsServiceCatalog64Svg from './Arch_AWS-Service-Catalog_64.svg';
import _archAwsSystemsManagerIncidentManager64Svg from './Arch_AWS-Systems-Manager-Incident-Manager_64.svg';
import _archAwsSystemsManager64Svg from './Arch_AWS-Systems-Manager_64.svg';
import _archAwsTrustedAdvisor64Svg from './Arch_AWS-Trusted-Advisor_64.svg';
import _archAwsWellArchitectedTool64Svg from './Arch_AWS-Well-Architected-Tool_64.svg';
import _archAmazonCloudWatch64Svg from './Arch_Amazon-CloudWatch_64.svg';
import _archAmazonManagedGrafana64Svg from './Arch_Amazon-Managed-Grafana_64.svg';
import _archAmazonManagedServiceForPrometheus64Svg from './Arch_Amazon-Managed-Service-for-Prometheus_64.svg';

export const archAwsAppConfig64Svg = { id: "archAwsAppConfig64Svg", name: "AWS AppConfig", icon: _archAwsAppConfig64Svg };
export const archAwsApplicationAutoScaling64Svg = { id: "archAwsApplicationAutoScaling64Svg", name: "AWS Application Auto Scaling", icon: _archAwsApplicationAutoScaling64Svg };
export const archAwsAutoScaling64Svg = { id: "archAwsAutoScaling64Svg", name: "AWS Auto Scaling", icon: _archAwsAutoScaling64Svg };
export const archAwsBackintAgent64Svg = { id: "archAwsBackintAgent64Svg", name: "AWS Backint Agent", icon: _archAwsBackintAgent64Svg };
export const archAwsChatbot64Svg = { id: "archAwsChatbot64Svg", name: "AWS Chatbot", icon: _archAwsChatbot64Svg };
export const archAwsCloudFormation64Svg = { id: "archAwsCloudFormation64Svg", name: "AWS CloudFormation", icon: _archAwsCloudFormation64Svg };
export const archAwsCloudTrail64Svg = { id: "archAwsCloudTrail64Svg", name: "AWS CloudTrail", icon: _archAwsCloudTrail64Svg };
export const archAwsConfig64Svg = { id: "archAwsConfig64Svg", name: "AWS Config", icon: _archAwsConfig64Svg };
export const archAwsControlTower64Svg = { id: "archAwsControlTower64Svg", name: "AWS Control Tower", icon: _archAwsControlTower64Svg };
export const archAwsDistroForOpenTelemetry64Svg = { id: "archAwsDistroForOpenTelemetry64Svg", name: "AWS Distro for OpenTelemetry", icon: _archAwsDistroForOpenTelemetry64Svg };
export const archAwsFaultInjectionSimulator64Svg = { id: "archAwsFaultInjectionSimulator64Svg", name: "AWS Fault Injection Simulator", icon: _archAwsFaultInjectionSimulator64Svg };
export const archAwsLaunchWizard64Svg = { id: "archAwsLaunchWizard64Svg", name: "AWS Launch Wizard", icon: _archAwsLaunchWizard64Svg };
export const archAwsLicenseManager64Svg = { id: "archAwsLicenseManager64Svg", name: "AWS License Manager", icon: _archAwsLicenseManager64Svg };
export const archAwsManagementConsole64Svg = { id: "archAwsManagementConsole64Svg", name: "AWS Management Console", icon: _archAwsManagementConsole64Svg };
export const archAwsOpsWorks64Svg = { id: "archAwsOpsWorks64Svg", name: "AWS OpsWorks", icon: _archAwsOpsWorks64Svg };
export const archAwsOrganizations64Svg = { id: "archAwsOrganizations64Svg", name: "AWS Organizations", icon: _archAwsOrganizations64Svg };
export const archAwsPersonalHealthDashboard64Svg = { id: "archAwsPersonalHealthDashboard64Svg", name: "AWS Personal Health Dashboard", icon: _archAwsPersonalHealthDashboard64Svg };
export const archAwsProton64Svg = { id: "archAwsProton64Svg", name: "AWS Proton", icon: _archAwsProton64Svg };
export const archAwsResilienceHub64Svg = { id: "archAwsResilienceHub64Svg", name: "AWS Resilience Hub", icon: _archAwsResilienceHub64Svg };
export const archAwsServiceCatalog64Svg = { id: "archAwsServiceCatalog64Svg", name: "AWS Service Catalog", icon: _archAwsServiceCatalog64Svg };
export const archAwsSystemsManagerIncidentManager64Svg = { id: "archAwsSystemsManagerIncidentManager64Svg", name: "AWS Systems Manager Incident Manager", icon: _archAwsSystemsManagerIncidentManager64Svg };
export const archAwsSystemsManager64Svg = { id: "archAwsSystemsManager64Svg", name: "AWS Systems Manager", icon: _archAwsSystemsManager64Svg };
export const archAwsTrustedAdvisor64Svg = { id: "archAwsTrustedAdvisor64Svg", name: "AWS Trusted Advisor", icon: _archAwsTrustedAdvisor64Svg };
export const archAwsWellArchitectedTool64Svg = { id: "archAwsWellArchitectedTool64Svg", name: "AWS Well Architected Tool", icon: _archAwsWellArchitectedTool64Svg };
export const archAmazonCloudWatch64Svg = { id: "archAmazonCloudWatch64Svg", name: "Amazon CloudWatch", icon: _archAmazonCloudWatch64Svg };
export const archAmazonManagedGrafana64Svg = { id: "archAmazonManagedGrafana64Svg", name: "Amazon Managed Grafana", icon: _archAmazonManagedGrafana64Svg };
export const archAmazonManagedServiceForPrometheus64Svg = { id: "archAmazonManagedServiceForPrometheus64Svg", name: "Amazon Managed Service for Prometheus", icon: _archAmazonManagedServiceForPrometheus64Svg };
