import _archAwsDatabaseMigrationService16Svg from './Arch_AWS-Database-Migration-Service_16.svg';
import _archAmazonAurora16Svg from './Arch_Amazon-Aurora_16.svg';
import _archAmazonDocumentDb16Svg from './Arch_Amazon-DocumentDB_16.svg';
import _archAmazonDynamoDb16Svg from './Arch_Amazon-DynamoDB_16.svg';
import _archAmazonElastiCache16Svg from './Arch_Amazon-ElastiCache_16.svg';
import _archAmazonKeyspaces16Svg from './Arch_Amazon-Keyspaces_16.svg';
import _archAmazonMemoryDbForRedis16Svg from './Arch_Amazon-MemoryDB-for-Redis_16.svg';
import _archAmazonNeptune16Svg from './Arch_Amazon-Neptune_16.svg';
import _archAmazonQuantumLedgerDatabase16Svg from './Arch_Amazon-Quantum-Ledger-Database_16.svg';
import _archAmazonRdsOnVmware16Svg from './Arch_Amazon-RDS-on-VMware_16.svg';
import _archAmazonRds16Svg from './Arch_Amazon-RDS_16.svg';
import _archAmazonTimestream16Svg from './Arch_Amazon-Timestream_16.svg';

export const archAwsDatabaseMigrationService16Svg = { id: "archAwsDatabaseMigrationService16Svg", name: "AWS Database Migration Service", icon: _archAwsDatabaseMigrationService16Svg };
export const archAmazonAurora16Svg = { id: "archAmazonAurora16Svg", name: "Amazon Aurora", icon: _archAmazonAurora16Svg };
export const archAmazonDocumentDb16Svg = { id: "archAmazonDocumentDb16Svg", name: "Amazon DocumentDB", icon: _archAmazonDocumentDb16Svg };
export const archAmazonDynamoDb16Svg = { id: "archAmazonDynamoDb16Svg", name: "Amazon DynamoDB", icon: _archAmazonDynamoDb16Svg };
export const archAmazonElastiCache16Svg = { id: "archAmazonElastiCache16Svg", name: "Amazon ElastiCache", icon: _archAmazonElastiCache16Svg };
export const archAmazonKeyspaces16Svg = { id: "archAmazonKeyspaces16Svg", name: "Amazon Keyspaces", icon: _archAmazonKeyspaces16Svg };
export const archAmazonMemoryDbForRedis16Svg = { id: "archAmazonMemoryDbForRedis16Svg", name: "Amazon MemoryDB for Redis", icon: _archAmazonMemoryDbForRedis16Svg };
export const archAmazonNeptune16Svg = { id: "archAmazonNeptune16Svg", name: "Amazon Neptune", icon: _archAmazonNeptune16Svg };
export const archAmazonQuantumLedgerDatabase16Svg = { id: "archAmazonQuantumLedgerDatabase16Svg", name: "Amazon Quantum Ledger Database", icon: _archAmazonQuantumLedgerDatabase16Svg };
export const archAmazonRdsOnVmware16Svg = { id: "archAmazonRdsOnVmware16Svg", name: "Amazon RDS on VMware", icon: _archAmazonRdsOnVmware16Svg };
export const archAmazonRds16Svg = { id: "archAmazonRds16Svg", name: "Amazon RDS", icon: _archAmazonRds16Svg };
export const archAmazonTimestream16Svg = { id: "archAmazonTimestream16Svg", name: "Amazon Timestream", icon: _archAmazonTimestream16Svg };
