import _resAwsAppMeshMesh48LightSvg from './Res_AWS-App-Mesh-Mesh_48_Light.svg';
import _resAwsAppMeshVirtualNode48LightSvg from './Res_AWS-App-Mesh-Virtual-Node_48_Light.svg';
import _resAwsAppMeshVirtualRouter48LightSvg from './Res_AWS-App-Mesh-Virtual-Router_48_Light.svg';
import _resAwsAppMeshVirtualService48LightSvg from './Res_AWS-App-Mesh-Virtual-Service_48_Light.svg';
import _resAwsCloudMapNamespace48LightSvg from './Res_AWS-Cloud-Map-Namespace_48_Light.svg';
import _resAwsCloudMapResource48LightSvg from './Res_AWS-Cloud-Map-Resource_48_Light.svg';
import _resAwsCloudMapService48LightSvg from './Res_AWS-Cloud-Map_Service_48_Light.svg';
import _resAwsCloudWanCoreNetworkEdge48LightSvg from './Res_AWS-Cloud-WAN_Core-Network-Edge_48_Light.svg';
import _resAwsCloudWanSegmentNetwork48LightSvg from './Res_AWS-Cloud-WAN_Segment-Network_48_Light.svg';
import _resAwsCloudWanVirtualPoP48LightSvg from './Res_AWS-Cloud-WAN_Virtual-PoP_48_Light.svg';
import _resAwsDirectConnectGateway48LightSvg from './Res_AWS-Direct-Connect-Gateway_48_Light.svg';
import _resAwsTransitGatewayAttachment48LightSvg from './Res_AWS-Transit-Gateway_Attachment_48_Light.svg';
import _resAmazonCloudFrontDownloadDistribution48LightSvg from './Res_Amazon-CloudFront_Download-Distribution_48_Light.svg';
import _resAmazonCloudFrontEdgeLocation48LightSvg from './Res_Amazon-CloudFront_Edge-Location_48_Light.svg';
import _resAmazonCloudFrontFunctions48LightSvg from './Res_Amazon-CloudFront_Functions_48_Light.svg';
import _resAmazonCloudFrontStreamingDistribution48LightSvg from './Res_Amazon-CloudFront_Streaming-Distribution_48_Light.svg';
import _resAmazonRoute53HostedZone48LightSvg from './Res_Amazon-Route-53-Hosted-Zone_48_Light.svg';
import _resAmazonRoute53ApplicationRecoveryController48LightSvg from './Res_Amazon-Route-53_Application-Recovery-Controller_48_Light.svg';
import _resAmazonRoute53ReadinessChecks48LightSvg from './Res_Amazon-Route-53_Readiness-Checks_48_Light.svg';
import _resAmazonRoute53ResolverDnsFirewall48LightSvg from './Res_Amazon-Route-53_Resolver-DNS-Firewall_48_Light.svg';
import _resAmazonRoute53ResolverQueryLogging48LightSvg from './Res_Amazon-Route-53_Resolver-Query-Logging_48_Light.svg';
import _resAmazonRoute53Resolver48LightSvg from './Res_Amazon-Route-53_Resolver_48_Light.svg';
import _resAmazonRoute53RouteTable48LightSvg from './Res_Amazon-Route-53_Route-Table_48_Light.svg';
import _resAmazonRoute53RoutingControls48LightSvg from './Res_Amazon-Route-53_Routing-Controls_48_Light.svg';
import _resAmazonVpcCarrierGateway48LightSvg from './Res_Amazon-VPC_Carrier-Gateway_48_Light.svg';
import _resAmazonVpcCustomerGateway48LightSvg from './Res_Amazon-VPC_Customer-Gateway_48_Light.svg';
import _resAmazonVpcElasticNetworkAdapter48LightSvg from './Res_Amazon-VPC_Elastic-Network-Adapter_48_Light.svg';
import _resAmazonVpcElasticNetworkInterface48LightSvg from './Res_Amazon-VPC_Elastic-Network-Interface_48_Light.svg';
import _resAmazonVpcEndpoints48LightSvg from './Res_Amazon-VPC_Endpoints_48_Light.svg';
import _resAmazonVpcFlowLogs48LightSvg from './Res_Amazon-VPC_Flow-Logs_48_Light.svg';
import _resAmazonVpcInternetGateway48LightSvg from './Res_Amazon-VPC_Internet-Gateway_48_Light.svg';
import _resAmazonVpcNatGateway48LightSvg from './Res_Amazon-VPC_NAT-Gateway_48_Light.svg';
import _resAmazonVpcNetworkAccessAnalyzer48LightSvg from './Res_Amazon-VPC_Network-Access-Analyzer_48_Light.svg';
import _resAmazonVpcNetworkAccessControlList48LightSvg from './Res_Amazon-VPC_Network-Access-Control-List_48_Light.svg';
import _resAmazonVpcPeeringConnection48LightSvg from './Res_Amazon-VPC_Peering-Connection_48_Light.svg';
import _resAmazonVpcReachabilityAnalyzer48LightSvg from './Res_Amazon-VPC_Reachability-Analyzer_48_Light.svg';
import _resAmazonVpcRouter48LightSvg from './Res_Amazon-VPC_Router_48_Light.svg';
import _resAmazonVpcTrafficMirroring48LightSvg from './Res_Amazon-VPC_Traffic-Mirroring_48_Light.svg';
import _resAmazonVpcVpnConnection48LightSvg from './Res_Amazon-VPC_VPN-Connection_48_Light.svg';
import _resAmazonVpcVpnGateway48LightSvg from './Res_Amazon-VPC_VPN-Gateway_48_Light.svg';
import _resAppMeshVirtualGateway48LightSvg from './Res_App-Mesh_Virtual-Gateway_48_Light.svg';
import _resElasticLoadBalancingApplicationLoadBalancer48LightSvg from './Res_Elastic-Load-Balancing_Application-Load-Balancer_48_Light.svg';
import _resElasticLoadBalancingClassicLoadBalancer48LightSvg from './Res_Elastic-Load-Balancing_Classic-Load-Balancer_48_Light.svg';
import _resElasticLoadBalancingGatewayLoadBalancer48LightSvg from './Res_Elastic-Load-Balancing_Gateway-Load-Balancer_48_Light.svg';
import _resElasticLoadBalancingNetworkLoadBalancer48LightSvg from './Res_Elastic-Load-Balancing_Network-Load-Balancer_48_Light.svg';

export const resAwsAppMeshMesh48LightSvg = { id: "resAwsAppMeshMesh48LightSvg", name: "AWS App Mesh Mesh", icon: _resAwsAppMeshMesh48LightSvg };
export const resAwsAppMeshVirtualNode48LightSvg = { id: "resAwsAppMeshVirtualNode48LightSvg", name: "AWS App Mesh Virtual Node", icon: _resAwsAppMeshVirtualNode48LightSvg };
export const resAwsAppMeshVirtualRouter48LightSvg = { id: "resAwsAppMeshVirtualRouter48LightSvg", name: "AWS App Mesh Virtual Router", icon: _resAwsAppMeshVirtualRouter48LightSvg };
export const resAwsAppMeshVirtualService48LightSvg = { id: "resAwsAppMeshVirtualService48LightSvg", name: "AWS App Mesh Virtual Service", icon: _resAwsAppMeshVirtualService48LightSvg };
export const resAwsCloudMapNamespace48LightSvg = { id: "resAwsCloudMapNamespace48LightSvg", name: "AWS Cloud Map Namespace", icon: _resAwsCloudMapNamespace48LightSvg };
export const resAwsCloudMapResource48LightSvg = { id: "resAwsCloudMapResource48LightSvg", name: "AWS Cloud Map Resource", icon: _resAwsCloudMapResource48LightSvg };
export const resAwsCloudMapService48LightSvg = { id: "resAwsCloudMapService48LightSvg", name: "AWS Cloud Map | Service", icon: _resAwsCloudMapService48LightSvg };
export const resAwsCloudWanCoreNetworkEdge48LightSvg = { id: "resAwsCloudWanCoreNetworkEdge48LightSvg", name: "AWS Cloud WAN | Core Network Edge", icon: _resAwsCloudWanCoreNetworkEdge48LightSvg };
export const resAwsCloudWanSegmentNetwork48LightSvg = { id: "resAwsCloudWanSegmentNetwork48LightSvg", name: "AWS Cloud WAN | Segment Network", icon: _resAwsCloudWanSegmentNetwork48LightSvg };
export const resAwsCloudWanVirtualPoP48LightSvg = { id: "resAwsCloudWanVirtualPoP48LightSvg", name: "AWS Cloud WAN | Virtual PoP", icon: _resAwsCloudWanVirtualPoP48LightSvg };
export const resAwsDirectConnectGateway48LightSvg = { id: "resAwsDirectConnectGateway48LightSvg", name: "AWS Direct Connect Gateway", icon: _resAwsDirectConnectGateway48LightSvg };
export const resAwsTransitGatewayAttachment48LightSvg = { id: "resAwsTransitGatewayAttachment48LightSvg", name: "AWS Transit Gateway | Attachment", icon: _resAwsTransitGatewayAttachment48LightSvg };
export const resAmazonCloudFrontDownloadDistribution48LightSvg = { id: "resAmazonCloudFrontDownloadDistribution48LightSvg", name: "Amazon CloudFront | Download Distribution", icon: _resAmazonCloudFrontDownloadDistribution48LightSvg };
export const resAmazonCloudFrontEdgeLocation48LightSvg = { id: "resAmazonCloudFrontEdgeLocation48LightSvg", name: "Amazon CloudFront | Edge Location", icon: _resAmazonCloudFrontEdgeLocation48LightSvg };
export const resAmazonCloudFrontFunctions48LightSvg = { id: "resAmazonCloudFrontFunctions48LightSvg", name: "Amazon CloudFront | Functions", icon: _resAmazonCloudFrontFunctions48LightSvg };
export const resAmazonCloudFrontStreamingDistribution48LightSvg = { id: "resAmazonCloudFrontStreamingDistribution48LightSvg", name: "Amazon CloudFront | Streaming Distribution", icon: _resAmazonCloudFrontStreamingDistribution48LightSvg };
export const resAmazonRoute53HostedZone48LightSvg = { id: "resAmazonRoute53HostedZone48LightSvg", name: "Amazon Route 53 Hosted Zone", icon: _resAmazonRoute53HostedZone48LightSvg };
export const resAmazonRoute53ApplicationRecoveryController48LightSvg = { id: "resAmazonRoute53ApplicationRecoveryController48LightSvg", name: "Amazon Route 53 | Application Recovery Controller", icon: _resAmazonRoute53ApplicationRecoveryController48LightSvg };
export const resAmazonRoute53ReadinessChecks48LightSvg = { id: "resAmazonRoute53ReadinessChecks48LightSvg", name: "Amazon Route 53 | Readiness Checks", icon: _resAmazonRoute53ReadinessChecks48LightSvg };
export const resAmazonRoute53ResolverDnsFirewall48LightSvg = { id: "resAmazonRoute53ResolverDnsFirewall48LightSvg", name: "Amazon Route 53 | Resolver DNS Firewall", icon: _resAmazonRoute53ResolverDnsFirewall48LightSvg };
export const resAmazonRoute53ResolverQueryLogging48LightSvg = { id: "resAmazonRoute53ResolverQueryLogging48LightSvg", name: "Amazon Route 53 | Resolver Query Logging", icon: _resAmazonRoute53ResolverQueryLogging48LightSvg };
export const resAmazonRoute53Resolver48LightSvg = { id: "resAmazonRoute53Resolver48LightSvg", name: "Amazon Route 53 | Resolver", icon: _resAmazonRoute53Resolver48LightSvg };
export const resAmazonRoute53RouteTable48LightSvg = { id: "resAmazonRoute53RouteTable48LightSvg", name: "Amazon Route 53 | Route Table", icon: _resAmazonRoute53RouteTable48LightSvg };
export const resAmazonRoute53RoutingControls48LightSvg = { id: "resAmazonRoute53RoutingControls48LightSvg", name: "Amazon Route 53 | Routing Controls", icon: _resAmazonRoute53RoutingControls48LightSvg };
export const resAmazonVpcCarrierGateway48LightSvg = { id: "resAmazonVpcCarrierGateway48LightSvg", name: "Amazon VPC | Carrier Gateway", icon: _resAmazonVpcCarrierGateway48LightSvg };
export const resAmazonVpcCustomerGateway48LightSvg = { id: "resAmazonVpcCustomerGateway48LightSvg", name: "Amazon VPC | Customer Gateway", icon: _resAmazonVpcCustomerGateway48LightSvg };
export const resAmazonVpcElasticNetworkAdapter48LightSvg = { id: "resAmazonVpcElasticNetworkAdapter48LightSvg", name: "Amazon VPC | Elastic Network Adapter", icon: _resAmazonVpcElasticNetworkAdapter48LightSvg };
export const resAmazonVpcElasticNetworkInterface48LightSvg = { id: "resAmazonVpcElasticNetworkInterface48LightSvg", name: "Amazon VPC | Elastic Network Interface", icon: _resAmazonVpcElasticNetworkInterface48LightSvg };
export const resAmazonVpcEndpoints48LightSvg = { id: "resAmazonVpcEndpoints48LightSvg", name: "Amazon VPC | Endpoints", icon: _resAmazonVpcEndpoints48LightSvg };
export const resAmazonVpcFlowLogs48LightSvg = { id: "resAmazonVpcFlowLogs48LightSvg", name: "Amazon VPC | Flow Logs", icon: _resAmazonVpcFlowLogs48LightSvg };
export const resAmazonVpcInternetGateway48LightSvg = { id: "resAmazonVpcInternetGateway48LightSvg", name: "Amazon VPC | Internet Gateway", icon: _resAmazonVpcInternetGateway48LightSvg };
export const resAmazonVpcNatGateway48LightSvg = { id: "resAmazonVpcNatGateway48LightSvg", name: "Amazon VPC | NAT Gateway", icon: _resAmazonVpcNatGateway48LightSvg };
export const resAmazonVpcNetworkAccessAnalyzer48LightSvg = { id: "resAmazonVpcNetworkAccessAnalyzer48LightSvg", name: "Amazon VPC | Network Access Analyzer", icon: _resAmazonVpcNetworkAccessAnalyzer48LightSvg };
export const resAmazonVpcNetworkAccessControlList48LightSvg = { id: "resAmazonVpcNetworkAccessControlList48LightSvg", name: "Amazon VPC | Network Access Control List", icon: _resAmazonVpcNetworkAccessControlList48LightSvg };
export const resAmazonVpcPeeringConnection48LightSvg = { id: "resAmazonVpcPeeringConnection48LightSvg", name: "Amazon VPC | Peering Connection", icon: _resAmazonVpcPeeringConnection48LightSvg };
export const resAmazonVpcReachabilityAnalyzer48LightSvg = { id: "resAmazonVpcReachabilityAnalyzer48LightSvg", name: "Amazon VPC | Reachability Analyzer", icon: _resAmazonVpcReachabilityAnalyzer48LightSvg };
export const resAmazonVpcRouter48LightSvg = { id: "resAmazonVpcRouter48LightSvg", name: "Amazon VPC | Router", icon: _resAmazonVpcRouter48LightSvg };
export const resAmazonVpcTrafficMirroring48LightSvg = { id: "resAmazonVpcTrafficMirroring48LightSvg", name: "Amazon VPC | Traffic Mirroring", icon: _resAmazonVpcTrafficMirroring48LightSvg };
export const resAmazonVpcVpnConnection48LightSvg = { id: "resAmazonVpcVpnConnection48LightSvg", name: "Amazon VPC | VPN Connection", icon: _resAmazonVpcVpnConnection48LightSvg };
export const resAmazonVpcVpnGateway48LightSvg = { id: "resAmazonVpcVpnGateway48LightSvg", name: "Amazon VPC | VPN Gateway", icon: _resAmazonVpcVpnGateway48LightSvg };
export const resAppMeshVirtualGateway48LightSvg = { id: "resAppMeshVirtualGateway48LightSvg", name: "App Mesh | Virtual Gateway", icon: _resAppMeshVirtualGateway48LightSvg };
export const resElasticLoadBalancingApplicationLoadBalancer48LightSvg = { id: "resElasticLoadBalancingApplicationLoadBalancer48LightSvg", name: "Elastic Load Balancing | Application Load Balancer", icon: _resElasticLoadBalancingApplicationLoadBalancer48LightSvg };
export const resElasticLoadBalancingClassicLoadBalancer48LightSvg = { id: "resElasticLoadBalancingClassicLoadBalancer48LightSvg", name: "Elastic Load Balancing | Classic Load Balancer", icon: _resElasticLoadBalancingClassicLoadBalancer48LightSvg };
export const resElasticLoadBalancingGatewayLoadBalancer48LightSvg = { id: "resElasticLoadBalancingGatewayLoadBalancer48LightSvg", name: "Elastic Load Balancing | Gateway Load Balancer", icon: _resElasticLoadBalancingGatewayLoadBalancer48LightSvg };
export const resElasticLoadBalancingNetworkLoadBalancer48LightSvg = { id: "resElasticLoadBalancingNetworkLoadBalancer48LightSvg", name: "Elastic Load Balancing | Network Load Balancer", icon: _resElasticLoadBalancingNetworkLoadBalancer48LightSvg };
