import _archAwsAppMesh32Svg from './Arch_AWS-App-Mesh_32.svg';
import _archAwsClientVpn32Svg from './Arch_AWS-Client-VPN_32.svg';
import _archAwsCloudMap32Svg from './Arch_AWS-Cloud-Map_32.svg';
import _archAwsCloudWan32Svg from './Arch_AWS-Cloud-WAN_32.svg';
import _archAwsDirectConnect32Svg from './Arch_AWS-Direct-Connect_32.svg';
import _archAwsGlobalAccelerator32Svg from './Arch_AWS-Global-Accelerator_32.svg';
import _archAwsPrivate5G32Svg from './Arch_AWS-Private-5G_32.svg';
import _archAwsPrivateLink32Svg from './Arch_AWS-PrivateLink_32.svg';
import _archAwsSiteToSiteVpn32Svg from './Arch_AWS-Site-to-Site-VPN_32.svg';
import _archAwsTransitGateway32Svg from './Arch_AWS-Transit-Gateway_32.svg';
import _archAmazonCloudDirectory32Svg from './Arch_Amazon-Cloud-Directory_32.svg';
import _archAmazonCloudFront32Svg from './Arch_Amazon-CloudFront_32.svg';
import _archAmazonRoute5332Svg from './Arch_Amazon-Route-53_32.svg';
import _archAmazonVirtualPrivateCloud32Svg from './Arch_Amazon-Virtual-Private-Cloud_32.svg';
import _archElasticLoadBalancing32Svg from './Arch_Elastic-Load-Balancing_32.svg';

export const archAwsAppMesh32Svg = { id: "archAwsAppMesh32Svg", name: "AWS App Mesh", icon: _archAwsAppMesh32Svg };
export const archAwsClientVpn32Svg = { id: "archAwsClientVpn32Svg", name: "AWS Client VPN", icon: _archAwsClientVpn32Svg };
export const archAwsCloudMap32Svg = { id: "archAwsCloudMap32Svg", name: "AWS Cloud Map", icon: _archAwsCloudMap32Svg };
export const archAwsCloudWan32Svg = { id: "archAwsCloudWan32Svg", name: "AWS Cloud WAN", icon: _archAwsCloudWan32Svg };
export const archAwsDirectConnect32Svg = { id: "archAwsDirectConnect32Svg", name: "AWS Direct Connect", icon: _archAwsDirectConnect32Svg };
export const archAwsGlobalAccelerator32Svg = { id: "archAwsGlobalAccelerator32Svg", name: "AWS Global Accelerator", icon: _archAwsGlobalAccelerator32Svg };
export const archAwsPrivate5G32Svg = { id: "archAwsPrivate5G32Svg", name: "AWS Private 5G", icon: _archAwsPrivate5G32Svg };
export const archAwsPrivateLink32Svg = { id: "archAwsPrivateLink32Svg", name: "AWS PrivateLink", icon: _archAwsPrivateLink32Svg };
export const archAwsSiteToSiteVpn32Svg = { id: "archAwsSiteToSiteVpn32Svg", name: "AWS Site to Site VPN", icon: _archAwsSiteToSiteVpn32Svg };
export const archAwsTransitGateway32Svg = { id: "archAwsTransitGateway32Svg", name: "AWS Transit Gateway", icon: _archAwsTransitGateway32Svg };
export const archAmazonCloudDirectory32Svg = { id: "archAmazonCloudDirectory32Svg", name: "Amazon Cloud Directory", icon: _archAmazonCloudDirectory32Svg };
export const archAmazonCloudFront32Svg = { id: "archAmazonCloudFront32Svg", name: "Amazon CloudFront", icon: _archAmazonCloudFront32Svg };
export const archAmazonRoute5332Svg = { id: "archAmazonRoute5332Svg", name: "Amazon Route 53", icon: _archAmazonRoute5332Svg };
export const archAmazonVirtualPrivateCloud32Svg = { id: "archAmazonVirtualPrivateCloud32Svg", name: "Amazon Virtual Private Cloud", icon: _archAmazonVirtualPrivateCloud32Svg };
export const archElasticLoadBalancing32Svg = { id: "archElasticLoadBalancing32Svg", name: "Elastic Load Balancing", icon: _archElasticLoadBalancing32Svg };
