import _archAwsAppRunner64Svg from './Arch_AWS-App-Runner_64.svg';
import _archAwsBatch64Svg from './Arch_AWS-Batch_64.svg';
import _archAwsComputeOptimizer64Svg from './Arch_AWS-Compute-Optimizer_64.svg';
import _archAwsElasticBeanstalk64Svg from './Arch_AWS-Elastic-Beanstalk_64.svg';
import _archAwsFargate64Svg from './Arch_AWS-Fargate_64.svg';
import _archAwsLambda64Svg from './Arch_AWS-Lambda_64.svg';
import _archAwsLocalZones64Svg from './Arch_AWS-Local-Zones_64.svg';
import _archAwsNitroEnclaves64Svg from './Arch_AWS-Nitro-Enclaves_64.svg';
import _archAwsOutpostsFamily64Svg from './Arch_AWS-Outposts-family_64.svg';
import _archAwsOutpostsRack64Svg from './Arch_AWS-Outposts-rack_64.svg';
import _archAwsOutpostsServers64Svg from './Arch_AWS-Outposts-servers_64.svg';
import _archAwsParallelCluster64Svg from './Arch_AWS-ParallelCluster_64.svg';
import _archAwsServerlessApplicationRepository64Svg from './Arch_AWS-Serverless-Application-Repository_64.svg';
import _archAwsThinkboxDeadline64Svg from './Arch_AWS-Thinkbox-Deadline_64.svg';
import _archAwsThinkboxFrost64Svg from './Arch_AWS-Thinkbox-Frost_64.svg';
import _archAwsThinkboxKrakatoa64Svg from './Arch_AWS-Thinkbox-Krakatoa_64.svg';
import _archAwsThinkboxSequoia64Svg from './Arch_AWS-Thinkbox-Sequoia_64.svg';
import _archAwsThinkboxStoke64Svg from './Arch_AWS-Thinkbox-Stoke_64.svg';
import _archAwsThinkboxXmesh64Svg from './Arch_AWS-Thinkbox-XMesh_64.svg';
import _archAwsWavelength64Svg from './Arch_AWS-Wavelength_64.svg';
import _archAmazonApplicationAutoScaling64Svg from './Arch_Amazon-Application-Auto-Scaling_64.svg';
import _archAmazonEc2AutoScaling64Svg from './Arch_Amazon-EC2-Auto-Scaling_64.svg';
import _archAmazonEc2ImageBuilder64Svg from './Arch_Amazon-EC2-Image-Builder_64.svg';
import _archAmazonEc264Svg from './Arch_Amazon-EC2_64.svg';
import _archAmazonGenomicsCli64Svg from './Arch_Amazon-Genomics-CLI_64.svg';
import _archAmazonLightsail64Svg from './Arch_Amazon-Lightsail_64.svg';
import _archBottlerocket64Svg from './Arch_Bottlerocket_64.svg';
import _archElasticFabricAdapter64Svg from './Arch_Elastic-Fabric-Adapter_64.svg';
import _archNiceDcv64Svg from './Arch_NICE-DCV_64.svg';
import _archNiceEnginFrame64Svg from './Arch_NICE-EnginFrame_64.svg';
import _archVMwareCloudOnAws64Svg from './Arch_VMware-Cloud-on-AWS_64.svg';

export const archAwsAppRunner64Svg = { id: "archAwsAppRunner64Svg", name: "AWS App Runner", icon: _archAwsAppRunner64Svg };
export const archAwsBatch64Svg = { id: "archAwsBatch64Svg", name: "AWS Batch", icon: _archAwsBatch64Svg };
export const archAwsComputeOptimizer64Svg = { id: "archAwsComputeOptimizer64Svg", name: "AWS Compute Optimizer", icon: _archAwsComputeOptimizer64Svg };
export const archAwsElasticBeanstalk64Svg = { id: "archAwsElasticBeanstalk64Svg", name: "AWS Elastic Beanstalk", icon: _archAwsElasticBeanstalk64Svg };
export const archAwsFargate64Svg = { id: "archAwsFargate64Svg", name: "AWS Fargate", icon: _archAwsFargate64Svg };
export const archAwsLambda64Svg = { id: "archAwsLambda64Svg", name: "AWS Lambda", icon: _archAwsLambda64Svg };
export const archAwsLocalZones64Svg = { id: "archAwsLocalZones64Svg", name: "AWS Local Zones", icon: _archAwsLocalZones64Svg };
export const archAwsNitroEnclaves64Svg = { id: "archAwsNitroEnclaves64Svg", name: "AWS Nitro Enclaves", icon: _archAwsNitroEnclaves64Svg };
export const archAwsOutpostsFamily64Svg = { id: "archAwsOutpostsFamily64Svg", name: "AWS Outposts family", icon: _archAwsOutpostsFamily64Svg };
export const archAwsOutpostsRack64Svg = { id: "archAwsOutpostsRack64Svg", name: "AWS Outposts rack", icon: _archAwsOutpostsRack64Svg };
export const archAwsOutpostsServers64Svg = { id: "archAwsOutpostsServers64Svg", name: "AWS Outposts servers", icon: _archAwsOutpostsServers64Svg };
export const archAwsParallelCluster64Svg = { id: "archAwsParallelCluster64Svg", name: "AWS ParallelCluster", icon: _archAwsParallelCluster64Svg };
export const archAwsServerlessApplicationRepository64Svg = { id: "archAwsServerlessApplicationRepository64Svg", name: "AWS Serverless Application Repository", icon: _archAwsServerlessApplicationRepository64Svg };
export const archAwsThinkboxDeadline64Svg = { id: "archAwsThinkboxDeadline64Svg", name: "AWS Thinkbox Deadline", icon: _archAwsThinkboxDeadline64Svg };
export const archAwsThinkboxFrost64Svg = { id: "archAwsThinkboxFrost64Svg", name: "AWS Thinkbox Frost", icon: _archAwsThinkboxFrost64Svg };
export const archAwsThinkboxKrakatoa64Svg = { id: "archAwsThinkboxKrakatoa64Svg", name: "AWS Thinkbox Krakatoa", icon: _archAwsThinkboxKrakatoa64Svg };
export const archAwsThinkboxSequoia64Svg = { id: "archAwsThinkboxSequoia64Svg", name: "AWS Thinkbox Sequoia", icon: _archAwsThinkboxSequoia64Svg };
export const archAwsThinkboxStoke64Svg = { id: "archAwsThinkboxStoke64Svg", name: "AWS Thinkbox Stoke", icon: _archAwsThinkboxStoke64Svg };
export const archAwsThinkboxXmesh64Svg = { id: "archAwsThinkboxXmesh64Svg", name: "AWS Thinkbox XMesh", icon: _archAwsThinkboxXmesh64Svg };
export const archAwsWavelength64Svg = { id: "archAwsWavelength64Svg", name: "AWS Wavelength", icon: _archAwsWavelength64Svg };
export const archAmazonApplicationAutoScaling64Svg = { id: "archAmazonApplicationAutoScaling64Svg", name: "Amazon Application Auto Scaling", icon: _archAmazonApplicationAutoScaling64Svg };
export const archAmazonEc2AutoScaling64Svg = { id: "archAmazonEc2AutoScaling64Svg", name: "Amazon EC2 Auto Scaling", icon: _archAmazonEc2AutoScaling64Svg };
export const archAmazonEc2ImageBuilder64Svg = { id: "archAmazonEc2ImageBuilder64Svg", name: "Amazon EC2 Image Builder", icon: _archAmazonEc2ImageBuilder64Svg };
export const archAmazonEc264Svg = { id: "archAmazonEc264Svg", name: "Amazon EC2", icon: _archAmazonEc264Svg };
export const archAmazonGenomicsCli64Svg = { id: "archAmazonGenomicsCli64Svg", name: "Amazon Genomics CLI", icon: _archAmazonGenomicsCli64Svg };
export const archAmazonLightsail64Svg = { id: "archAmazonLightsail64Svg", name: "Amazon Lightsail", icon: _archAmazonLightsail64Svg };
export const archBottlerocket64Svg = { id: "archBottlerocket64Svg", name: "Bottlerocket", icon: _archBottlerocket64Svg };
export const archElasticFabricAdapter64Svg = { id: "archElasticFabricAdapter64Svg", name: "Elastic Fabric Adapter", icon: _archElasticFabricAdapter64Svg };
export const archNiceDcv64Svg = { id: "archNiceDcv64Svg", name: "NICE DCV", icon: _archNiceDcv64Svg };
export const archNiceEnginFrame64Svg = { id: "archNiceEnginFrame64Svg", name: "NICE EnginFrame", icon: _archNiceEnginFrame64Svg };
export const archVMwareCloudOnAws64Svg = { id: "archVMwareCloudOnAws64Svg", name: "VMware Cloud on AWS", icon: _archVMwareCloudOnAws64Svg };
