import _archAwsArtifact32Svg from './Arch_AWS-Artifact_32.svg';
import _archAwsAuditManager32Svg from './Arch_AWS-Audit-Manager_32.svg';
import _archAwsCertificateManager32Svg from './Arch_AWS-Certificate-Manager_32.svg';
import _archAwsCloudHsm32Svg from './Arch_AWS-CloudHSM_32.svg';
import _archAwsDirectoryService32Svg from './Arch_AWS-Directory-Service_32.svg';
import _archAwsFirewallManager32Svg from './Arch_AWS-Firewall-Manager_32.svg';
import _archAwsIamIdentityCenter32Svg from './Arch_AWS-IAM-Identity-Center_32.svg';
import _archAwsIdentityAndAccessManagement32Svg from './Arch_AWS-Identity-and-Access-Management_32.svg';
import _archAwsKeyManagementService32Svg from './Arch_AWS-Key-Management-Service_32.svg';
import _archAwsNetworkFirewall32Svg from './Arch_AWS-Network-Firewall_32.svg';
import _archAwsResourceAccessManager32Svg from './Arch_AWS-Resource-Access-Manager_32.svg';
import _archAwsSecretsManager32Svg from './Arch_AWS-Secrets-Manager_32.svg';
import _archAwsSecurityHub32Svg from './Arch_AWS-Security-Hub_32.svg';
import _archAwsShield32Svg from './Arch_AWS-Shield_32.svg';
import _archAwsSigner32Svg from './Arch_AWS-Signer_32.svg';
import _archAwsWaf32Svg from './Arch_AWS-WAF_32.svg';
import _archAmazonCloudDirectory32Svg from './Arch_Amazon-Cloud-Directory_32.svg';
import _archAmazonCognito32Svg from './Arch_Amazon-Cognito_32.svg';
import _archAmazonDetective32Svg from './Arch_Amazon-Detective_32.svg';
import _archAmazonGuardDuty32Svg from './Arch_Amazon-GuardDuty_32.svg';
import _archAmazonInspector32Svg from './Arch_Amazon-Inspector_32.svg';
import _archAmazonMacie32Svg from './Arch_Amazon-Macie_32.svg';

export const archAwsArtifact32Svg = { id: "archAwsArtifact32Svg", name: "AWS Artifact", icon: _archAwsArtifact32Svg };
export const archAwsAuditManager32Svg = { id: "archAwsAuditManager32Svg", name: "AWS Audit Manager", icon: _archAwsAuditManager32Svg };
export const archAwsCertificateManager32Svg = { id: "archAwsCertificateManager32Svg", name: "AWS Certificate Manager", icon: _archAwsCertificateManager32Svg };
export const archAwsCloudHsm32Svg = { id: "archAwsCloudHsm32Svg", name: "AWS CloudHSM", icon: _archAwsCloudHsm32Svg };
export const archAwsDirectoryService32Svg = { id: "archAwsDirectoryService32Svg", name: "AWS Directory Service", icon: _archAwsDirectoryService32Svg };
export const archAwsFirewallManager32Svg = { id: "archAwsFirewallManager32Svg", name: "AWS Firewall Manager", icon: _archAwsFirewallManager32Svg };
export const archAwsIamIdentityCenter32Svg = { id: "archAwsIamIdentityCenter32Svg", name: "AWS IAM Identity Center", icon: _archAwsIamIdentityCenter32Svg };
export const archAwsIdentityAndAccessManagement32Svg = { id: "archAwsIdentityAndAccessManagement32Svg", name: "AWS Identity and Access Management", icon: _archAwsIdentityAndAccessManagement32Svg };
export const archAwsKeyManagementService32Svg = { id: "archAwsKeyManagementService32Svg", name: "AWS Key Management Service", icon: _archAwsKeyManagementService32Svg };
export const archAwsNetworkFirewall32Svg = { id: "archAwsNetworkFirewall32Svg", name: "AWS Network Firewall", icon: _archAwsNetworkFirewall32Svg };
export const archAwsResourceAccessManager32Svg = { id: "archAwsResourceAccessManager32Svg", name: "AWS Resource Access Manager", icon: _archAwsResourceAccessManager32Svg };
export const archAwsSecretsManager32Svg = { id: "archAwsSecretsManager32Svg", name: "AWS Secrets Manager", icon: _archAwsSecretsManager32Svg };
export const archAwsSecurityHub32Svg = { id: "archAwsSecurityHub32Svg", name: "AWS Security Hub", icon: _archAwsSecurityHub32Svg };
export const archAwsShield32Svg = { id: "archAwsShield32Svg", name: "AWS Shield", icon: _archAwsShield32Svg };
export const archAwsSigner32Svg = { id: "archAwsSigner32Svg", name: "AWS Signer", icon: _archAwsSigner32Svg };
export const archAwsWaf32Svg = { id: "archAwsWaf32Svg", name: "AWS WAF", icon: _archAwsWaf32Svg };
export const archAmazonCloudDirectory32Svg = { id: "archAmazonCloudDirectory32Svg", name: "Amazon Cloud Directory", icon: _archAmazonCloudDirectory32Svg };
export const archAmazonCognito32Svg = { id: "archAmazonCognito32Svg", name: "Amazon Cognito", icon: _archAmazonCognito32Svg };
export const archAmazonDetective32Svg = { id: "archAmazonDetective32Svg", name: "Amazon Detective", icon: _archAmazonDetective32Svg };
export const archAmazonGuardDuty32Svg = { id: "archAmazonGuardDuty32Svg", name: "Amazon GuardDuty", icon: _archAmazonGuardDuty32Svg };
export const archAmazonInspector32Svg = { id: "archAmazonInspector32Svg", name: "Amazon Inspector", icon: _archAmazonInspector32Svg };
export const archAmazonMacie32Svg = { id: "archAmazonMacie32Svg", name: "Amazon Macie", icon: _archAmazonMacie32Svg };
