import _archAlexaForBusiness64Svg from './Arch_Alexa-For-Business_64.svg';
import _archAmazonChimeSdk64Svg from './Arch_Amazon-Chime-SDK_64.svg';
import _archAmazonChimeVoiceConnector64Svg from './Arch_Amazon-Chime-Voice-Connector_64.svg';
import _archAmazonChime64Svg from './Arch_Amazon-Chime_64.svg';
import _archAmazonConnect64Svg from './Arch_Amazon-Connect_64.svg';
import _archAmazonHoneycode64Svg from './Arch_Amazon-Honeycode_64.svg';
import _archAmazonPinpointApIs64Svg from './Arch_Amazon-Pinpoint-APIs_64.svg';
import _archAmazonPinpoint64Svg from './Arch_Amazon-Pinpoint_64.svg';
import _archAmazonSimpleEmailService64Svg from './Arch_Amazon-Simple-Email-Service_64.svg';
import _archAmazonWorkDocsSdk64Svg from './Arch_Amazon-WorkDocs-SDK_64.svg';
import _archAmazonWorkDocs64Svg from './Arch_Amazon-WorkDocs_64.svg';
import _archAmazonWorkMail64Svg from './Arch_Amazon-WorkMail_64.svg';

export const archAlexaForBusiness64Svg = { id: "archAlexaForBusiness64Svg", name: "Alexa For Business", icon: _archAlexaForBusiness64Svg };
export const archAmazonChimeSdk64Svg = { id: "archAmazonChimeSdk64Svg", name: "Amazon Chime SDK", icon: _archAmazonChimeSdk64Svg };
export const archAmazonChimeVoiceConnector64Svg = { id: "archAmazonChimeVoiceConnector64Svg", name: "Amazon Chime Voice Connector", icon: _archAmazonChimeVoiceConnector64Svg };
export const archAmazonChime64Svg = { id: "archAmazonChime64Svg", name: "Amazon Chime", icon: _archAmazonChime64Svg };
export const archAmazonConnect64Svg = { id: "archAmazonConnect64Svg", name: "Amazon Connect", icon: _archAmazonConnect64Svg };
export const archAmazonHoneycode64Svg = { id: "archAmazonHoneycode64Svg", name: "Amazon Honeycode", icon: _archAmazonHoneycode64Svg };
export const archAmazonPinpointApIs64Svg = { id: "archAmazonPinpointApIs64Svg", name: "Amazon Pinpoint APIs", icon: _archAmazonPinpointApIs64Svg };
export const archAmazonPinpoint64Svg = { id: "archAmazonPinpoint64Svg", name: "Amazon Pinpoint", icon: _archAmazonPinpoint64Svg };
export const archAmazonSimpleEmailService64Svg = { id: "archAmazonSimpleEmailService64Svg", name: "Amazon Simple Email Service", icon: _archAmazonSimpleEmailService64Svg };
export const archAmazonWorkDocsSdk64Svg = { id: "archAmazonWorkDocsSdk64Svg", name: "Amazon WorkDocs SDK", icon: _archAmazonWorkDocsSdk64Svg };
export const archAmazonWorkDocs64Svg = { id: "archAmazonWorkDocs64Svg", name: "Amazon WorkDocs", icon: _archAmazonWorkDocs64Svg };
export const archAmazonWorkMail64Svg = { id: "archAmazonWorkMail64Svg", name: "Amazon WorkMail", icon: _archAmazonWorkMail64Svg };
