import _resAmazonBraketChandelier48DarkSvg from './Res_Amazon-Braket_Chandelier_48_Dark.svg';
import _resAmazonBraketChip48DarkSvg from './Res_Amazon-Braket_Chip_48_Dark.svg';
import _resAmazonBraketEmbeddedSimulator48DarkSvg from './Res_Amazon-Braket_Embedded-Simulator_48_Dark.svg';
import _resAmazonBraketManagedSimulator48DarkSvg from './Res_Amazon-Braket_Managed-Simulator_48_Dark.svg';
import _resAmazonBraketNoiseSimulator48DarkSvg from './Res_Amazon-Braket_Noise-Simulator_48_Dark.svg';
import _resAmazonBraketQpu48DarkSvg from './Res_Amazon-Braket_QPU_48_Dark.svg';
import _resAmazonBraketSimulator148DarkSvg from './Res_Amazon-Braket_Simulator-1_48_Dark.svg';
import _resAmazonBraketSimulator248DarkSvg from './Res_Amazon-Braket_Simulator-2_48_Dark.svg';
import _resAmazonBraketSimulator348DarkSvg from './Res_Amazon-Braket_Simulator-3_48_Dark.svg';
import _resAmazonBraketSimulator448DarkSvg from './Res_Amazon-Braket_Simulator-4_48_Dark.svg';
import _resAmazonBraketSimulator48DarkSvg from './Res_Amazon-Braket_Simulator_48_Dark.svg';
import _resAmazonBraketStateVector48DarkSvg from './Res_Amazon-Braket_State-Vector_48_Dark.svg';
import _resAmazonBraketTensorNetwork48DarkSvg from './Res_Amazon-Braket_Tensor-Network_48_Dark.svg';

export const resAmazonBraketChandelier48DarkSvg = { id: "resAmazonBraketChandelier48DarkSvg", name: "Amazon Braket / Chandelier", icon: _resAmazonBraketChandelier48DarkSvg };
export const resAmazonBraketChip48DarkSvg = { id: "resAmazonBraketChip48DarkSvg", name: "Amazon Braket / Chip", icon: _resAmazonBraketChip48DarkSvg };
export const resAmazonBraketEmbeddedSimulator48DarkSvg = { id: "resAmazonBraketEmbeddedSimulator48DarkSvg", name: "Amazon Braket / Embedded Simulator", icon: _resAmazonBraketEmbeddedSimulator48DarkSvg };
export const resAmazonBraketManagedSimulator48DarkSvg = { id: "resAmazonBraketManagedSimulator48DarkSvg", name: "Amazon Braket / Managed Simulator", icon: _resAmazonBraketManagedSimulator48DarkSvg };
export const resAmazonBraketNoiseSimulator48DarkSvg = { id: "resAmazonBraketNoiseSimulator48DarkSvg", name: "Amazon Braket / Noise Simulator", icon: _resAmazonBraketNoiseSimulator48DarkSvg };
export const resAmazonBraketQpu48DarkSvg = { id: "resAmazonBraketQpu48DarkSvg", name: "Amazon Braket / QPU", icon: _resAmazonBraketQpu48DarkSvg };
export const resAmazonBraketSimulator148DarkSvg = { id: "resAmazonBraketSimulator148DarkSvg", name: "Amazon Braket / Simulator 1", icon: _resAmazonBraketSimulator148DarkSvg };
export const resAmazonBraketSimulator248DarkSvg = { id: "resAmazonBraketSimulator248DarkSvg", name: "Amazon Braket / Simulator 2", icon: _resAmazonBraketSimulator248DarkSvg };
export const resAmazonBraketSimulator348DarkSvg = { id: "resAmazonBraketSimulator348DarkSvg", name: "Amazon Braket / Simulator 3", icon: _resAmazonBraketSimulator348DarkSvg };
export const resAmazonBraketSimulator448DarkSvg = { id: "resAmazonBraketSimulator448DarkSvg", name: "Amazon Braket / Simulator 4", icon: _resAmazonBraketSimulator448DarkSvg };
export const resAmazonBraketSimulator48DarkSvg = { id: "resAmazonBraketSimulator48DarkSvg", name: "Amazon Braket / Simulator", icon: _resAmazonBraketSimulator48DarkSvg };
export const resAmazonBraketStateVector48DarkSvg = { id: "resAmazonBraketStateVector48DarkSvg", name: "Amazon Braket / State Vector", icon: _resAmazonBraketStateVector48DarkSvg };
export const resAmazonBraketTensorNetwork48DarkSvg = { id: "resAmazonBraketTensorNetwork48DarkSvg", name: "Amazon Braket / Tensor Network", icon: _resAmazonBraketTensorNetwork48DarkSvg };
