import _archAwsElementalAppliancesSoftware16Svg from './Arch_AWS-Elemental-Appliances-&-Software_16.svg';
import _archAwsElementalConductor16Svg from './Arch_AWS-Elemental-Conductor_16.svg';
import _archAwsElementalDelta16Svg from './Arch_AWS-Elemental-Delta_16.svg';
import _archAwsElementalLink16Svg from './Arch_AWS-Elemental-Link_16.svg';
import _archAwsElementalLive16Svg from './Arch_AWS-Elemental-Live_16.svg';
import _archAwsElementalMediaConnect16Svg from './Arch_AWS-Elemental-MediaConnect_16.svg';
import _archAwsElementalMediaConvert16Svg from './Arch_AWS-Elemental-MediaConvert_16.svg';
import _archAwsElementalMediaLive16Svg from './Arch_AWS-Elemental-MediaLive_16.svg';
import _archAwsElementalMediaPackage16Svg from './Arch_AWS-Elemental-MediaPackage_16.svg';
import _archAwsElementalMediaStore16Svg from './Arch_AWS-Elemental-MediaStore_16.svg';
import _archAwsElementalMediaTailor16Svg from './Arch_AWS-Elemental-MediaTailor_16.svg';
import _archAwsElementalServer16Svg from './Arch_AWS-Elemental-Server_16.svg';
import _archAmazonElasticTranscoder16Svg from './Arch_Amazon-Elastic-Transcoder_16.svg';
import _archAmazonInteractiveVideoService16Svg from './Arch_Amazon-Interactive-Video-Service_16.svg';
import _archAmazonKinesisVideoStreams16Svg from './Arch_Amazon-Kinesis-Video-Streams_16.svg';
import _archAmazonNimbleStudio16Svg from './Arch_Amazon-Nimble-Studio_16.svg';

export const archAwsElementalAppliancesSoftware16Svg = { id: "archAwsElementalAppliancesSoftware16Svg", name: "AWS Elemental Appliances & Software", icon: _archAwsElementalAppliancesSoftware16Svg };
export const archAwsElementalConductor16Svg = { id: "archAwsElementalConductor16Svg", name: "AWS Elemental Conductor", icon: _archAwsElementalConductor16Svg };
export const archAwsElementalDelta16Svg = { id: "archAwsElementalDelta16Svg", name: "AWS Elemental Delta", icon: _archAwsElementalDelta16Svg };
export const archAwsElementalLink16Svg = { id: "archAwsElementalLink16Svg", name: "AWS Elemental Link", icon: _archAwsElementalLink16Svg };
export const archAwsElementalLive16Svg = { id: "archAwsElementalLive16Svg", name: "AWS Elemental Live", icon: _archAwsElementalLive16Svg };
export const archAwsElementalMediaConnect16Svg = { id: "archAwsElementalMediaConnect16Svg", name: "AWS Elemental MediaConnect", icon: _archAwsElementalMediaConnect16Svg };
export const archAwsElementalMediaConvert16Svg = { id: "archAwsElementalMediaConvert16Svg", name: "AWS Elemental MediaConvert", icon: _archAwsElementalMediaConvert16Svg };
export const archAwsElementalMediaLive16Svg = { id: "archAwsElementalMediaLive16Svg", name: "AWS Elemental MediaLive", icon: _archAwsElementalMediaLive16Svg };
export const archAwsElementalMediaPackage16Svg = { id: "archAwsElementalMediaPackage16Svg", name: "AWS Elemental MediaPackage", icon: _archAwsElementalMediaPackage16Svg };
export const archAwsElementalMediaStore16Svg = { id: "archAwsElementalMediaStore16Svg", name: "AWS Elemental MediaStore", icon: _archAwsElementalMediaStore16Svg };
export const archAwsElementalMediaTailor16Svg = { id: "archAwsElementalMediaTailor16Svg", name: "AWS Elemental MediaTailor", icon: _archAwsElementalMediaTailor16Svg };
export const archAwsElementalServer16Svg = { id: "archAwsElementalServer16Svg", name: "AWS Elemental Server", icon: _archAwsElementalServer16Svg };
export const archAmazonElasticTranscoder16Svg = { id: "archAmazonElasticTranscoder16Svg", name: "Amazon Elastic Transcoder", icon: _archAmazonElasticTranscoder16Svg };
export const archAmazonInteractiveVideoService16Svg = { id: "archAmazonInteractiveVideoService16Svg", name: "Amazon Interactive Video Service", icon: _archAmazonInteractiveVideoService16Svg };
export const archAmazonKinesisVideoStreams16Svg = { id: "archAmazonKinesisVideoStreams16Svg", name: "Amazon Kinesis Video Streams", icon: _archAmazonKinesisVideoStreams16Svg };
export const archAmazonNimbleStudio16Svg = { id: "archAmazonNimbleStudio16Svg", name: "Amazon Nimble Studio", icon: _archAmazonNimbleStudio16Svg };
