import _archAwsAppSync64Svg from './Arch_AWS-AppSync_64.svg';
import _archAwsConsoleMobileApplication64Svg from './Arch_AWS-Console-Mobile-Application_64.svg';
import _archAwsExpressWorkflows64Svg from './Arch_AWS-Express-Workflows_64.svg';
import _archAwsStepFunctions64Svg from './Arch_AWS-Step-Functions_64.svg';
import _archAmazonApiGateway64Svg from './Arch_Amazon-API-Gateway_64.svg';
import _archAmazonAppFlow64Svg from './Arch_Amazon-AppFlow_64.svg';
import _archAmazonEventBridge64Svg from './Arch_Amazon-EventBridge_64.svg';
import _archAmazonMq64Svg from './Arch_Amazon-MQ_64.svg';
import _archAmazonManagedWorkflowsForApacheAirflow64Svg from './Arch_Amazon-Managed-Workflows-for-Apache-Airflow_64.svg';
import _archAmazonSimpleNotificationService64Svg from './Arch_Amazon-Simple-Notification-Service_64.svg';
import _archAmazonSimpleQueueService64Svg from './Arch_Amazon-Simple-Queue-Service_64.svg';

export const archAwsAppSync64Svg = { id: "archAwsAppSync64Svg", name: "AWS AppSync", icon: _archAwsAppSync64Svg };
export const archAwsConsoleMobileApplication64Svg = { id: "archAwsConsoleMobileApplication64Svg", name: "AWS Console Mobile Application", icon: _archAwsConsoleMobileApplication64Svg };
export const archAwsExpressWorkflows64Svg = { id: "archAwsExpressWorkflows64Svg", name: "AWS Express Workflows", icon: _archAwsExpressWorkflows64Svg };
export const archAwsStepFunctions64Svg = { id: "archAwsStepFunctions64Svg", name: "AWS Step Functions", icon: _archAwsStepFunctions64Svg };
export const archAmazonApiGateway64Svg = { id: "archAmazonApiGateway64Svg", name: "Amazon API Gateway", icon: _archAmazonApiGateway64Svg };
export const archAmazonAppFlow64Svg = { id: "archAmazonAppFlow64Svg", name: "Amazon AppFlow", icon: _archAmazonAppFlow64Svg };
export const archAmazonEventBridge64Svg = { id: "archAmazonEventBridge64Svg", name: "Amazon EventBridge", icon: _archAmazonEventBridge64Svg };
export const archAmazonMq64Svg = { id: "archAmazonMq64Svg", name: "Amazon MQ", icon: _archAmazonMq64Svg };
export const archAmazonManagedWorkflowsForApacheAirflow64Svg = { id: "archAmazonManagedWorkflowsForApacheAirflow64Svg", name: "Amazon Managed Workflows for Apache Airflow", icon: _archAmazonManagedWorkflowsForApacheAirflow64Svg };
export const archAmazonSimpleNotificationService64Svg = { id: "archAmazonSimpleNotificationService64Svg", name: "Amazon Simple Notification Service", icon: _archAmazonSimpleNotificationService64Svg };
export const archAmazonSimpleQueueService64Svg = { id: "archAmazonSimpleQueueService64Svg", name: "Amazon Simple Queue Service", icon: _archAmazonSimpleQueueService64Svg };
