import _resAwsIoTAnalyticsChannel48LightSvg from './Res_AWS-IoT-Analytics_Channel_48_Light.svg';
import _resAwsIoTAnalyticsDataStore48LightSvg from './Res_AWS-IoT-Analytics_Data-Store_48_Light.svg';
import _resAwsIoTAnalyticsDataset48LightSvg from './Res_AWS-IoT-Analytics_Dataset_48_Light.svg';
import _resAwsIoTAnalyticsNotebook48LightSvg from './Res_AWS-IoT-Analytics_Notebook_48_Light.svg';
import _resAwsIoTAnalyticsPipeline48LightSvg from './Res_AWS-IoT-Analytics_Pipeline_48_Light.svg';
import _resAwsIoTDeviceDefenderIoTDeviceJobs48LightSvg from './Res_AWS-IoT-Device-Defender_IoT-Device-Jobs_48_Light.svg';
import _resAwsIoTDeviceManagementFleetHub48LightSvg from './Res_AWS-IoT-Device-Management_Fleet-Hub_48_Light.svg';
import _resAwsIoTGreengrassArtifact48LightSvg from './Res_AWS-IoT-Greengrass_Artifact_48_Light.svg';
import _resAwsIoTGreengrassComponentMachineLearning48LightSvg from './Res_AWS-IoT-Greengrass_Component-Machine-Learning_48_Light.svg';
import _resAwsIoTGreengrassComponentNucleus48LightSvg from './Res_AWS-IoT-Greengrass_Component-Nucleus_48_Light.svg';
import _resAwsIoTGreengrassComponentPrivate48LightSvg from './Res_AWS-IoT-Greengrass_Component-Private_48_Light.svg';
import _resAwsIoTGreengrassComponentPublic48LightSvg from './Res_AWS-IoT-Greengrass_Component-Public_48_Light.svg';
import _resAwsIoTGreengrassComponent48LightSvg from './Res_AWS-IoT-Greengrass_Component_48_Light.svg';
import _resAwsIoTGreengrassConnector48LightSvg from './Res_AWS-IoT-Greengrass_Connector_48_Light.svg';
import _resAwsIoTGreengrassInterprocessCommunication48LightSvg from './Res_AWS-IoT-Greengrass_Interprocess-Communication_48_Light.svg';
import _resAwsIoTGreengrassProtocol48LightSvg from './Res_AWS-IoT-Greengrass_Protocol_48_Light.svg';
import _resAwsIoTGreengrassRecipe48LightSvg from './Res_AWS-IoT-Greengrass_Recipe_48_Light.svg';
import _resAwsIoTGreengrassStreamManager48LightSvg from './Res_AWS-IoT-Greengrass_Stream-Manager_48_Light.svg';
import _resAwsIoTHttpProtocol48LightSvg from './Res_AWS-IoT-HTTP_Protocol_48_Light.svg';
import _resAwsIoTHardwareBoard48LightSvg from './Res_AWS-IoT-Hardware-Board_48_Light.svg';
import _resAwsIoTMqttProtocol48LightSvg from './Res_AWS-IoT-MQTT_Protocol_48_Light.svg';
import _resAwsIoTRule48LightSvg from './Res_AWS-IoT-Rule_48_Light.svg';
import _resAwsIoTSiteWiseAssetHierarchy48LightSvg from './Res_AWS-IoT-SiteWise_Asset-Hierarchy_48_Light.svg';
import _resAwsIoTSiteWiseAssetModel48LightSvg from './Res_AWS-IoT-SiteWise_Asset-Model_48_Light.svg';
import _resAwsIoTSiteWiseAssetProperties48LightSvg from './Res_AWS-IoT-SiteWise_Asset-Properties_48_Light.svg';
import _resAwsIoTSiteWiseAsset48LightSvg from './Res_AWS-IoT-SiteWise_Asset_48_Light.svg';
import _resAwsIoTSiteWiseDataStreams48LightSvg from './Res_AWS-IoT-SiteWise_Data-Streams_48_Light.svg';
import _resAwsIoTThingBank48LightSvg from './Res_AWS-IoT-Thing_Bank_48_Light.svg';
import _resAwsIoTThingBicycle48LightSvg from './Res_AWS-IoT-Thing_Bicycle_48_Light.svg';
import _resAwsIoTThingCamera48LightSvg from './Res_AWS-IoT-Thing_Camera_48_Light.svg';
import _resAwsIoTThingCar48LightSvg from './Res_AWS-IoT-Thing_Car_48_Light.svg';
import _resAwsIoTThingCart48LightSvg from './Res_AWS-IoT-Thing_Cart_48_Light.svg';
import _resAwsIoTThingCoffeePot48LightSvg from './Res_AWS-IoT-Thing_Coffee-Pot_48_Light.svg';
import _resAwsIoTThingDoorLock48LightSvg from './Res_AWS-IoT-Thing_Door-Lock_48_Light.svg';
import _resAwsIoTThingFactory48LightSvg from './Res_AWS-IoT-Thing_Factory_48_Light.svg';
import _resAwsIoTThingGeneric48LightSvg from './Res_AWS-IoT-Thing_Generic_48_Light.svg';
import _resAwsIoTThingHouse48LightSvg from './Res_AWS-IoT-Thing_House_48_Light.svg';
import _resAwsIoTThingLightbulb48LightSvg from './Res_AWS-IoT-Thing_Lightbulb_48_Light.svg';
import _resAwsIoTThingMedicalEmergency48LightSvg from './Res_AWS-IoT-Thing_Medical-Emergency_48_Light.svg';
import _resAwsIoTThingPoliceEmergency48LightSvg from './Res_AWS-IoT-Thing_Police-Emergency_48_Light.svg';
import _resAwsIoTThingThermostat48LightSvg from './Res_AWS-IoT-Thing_Thermostat_48_Light.svg';
import _resAwsIoTThingTravel48LightSvg from './Res_AWS-IoT-Thing_Travel_48_Light.svg';
import _resAwsIoTThingUtility48LightSvg from './Res_AWS-IoT-Thing_Utility_48_Light.svg';
import _resAwsIoTThingWindfarm48LightSvg from './Res_AWS-IoT-Thing_Windfarm_48_Light.svg';
import _resAwsIoTAction48LightSvg from './Res_AWS-IoT_Action_48_Light.svg';
import _resAwsIoTActuator48LightSvg from './Res_AWS-IoT_Actuator_48_Light.svg';
import _resAwsIoTAlexaEnabledDevice48LightSvg from './Res_AWS-IoT_Alexa_Enabled-Device_48_Light.svg';
import _resAwsIoTAlexaSkill48LightSvg from './Res_AWS-IoT_Alexa_Skill_48_Light.svg';
import _resAwsIoTAlexaVoiceService48LightSvg from './Res_AWS-IoT_Alexa_Voice-Service_48_Light.svg';
import _resAwsIoTCertificate48LightSvg from './Res_AWS-IoT_Certificate_48_Light.svg';
import _resAwsIoTDesiredState48LightSvg from './Res_AWS-IoT_Desired-State_48_Light.svg';
import _resAwsIoTDeviceGateway48LightSvg from './Res_AWS-IoT_Device-Gateway_48_Light.svg';
import _resAwsIoTEcho48LightSvg from './Res_AWS-IoT_Echo_48_Light.svg';
import _resAwsIoTFireTvStick48LightSvg from './Res_AWS-IoT_Fire-TV_Stick_48_Light.svg';
import _resAwsIoTFireTv48LightSvg from './Res_AWS-IoT_Fire_TV_48_Light.svg';
import _resAwsIoTHttp2Protocol48LightSvg from './Res_AWS-IoT_HTTP2-Protocol_48_Light.svg';
import _resAwsIoTLambdaFunction48LightSvg from './Res_AWS-IoT_Lambda_Function_48_Light.svg';
import _resAwsIoTLoRaWanProtocol48LightSvg from './Res_AWS-IoT_LoRaWAN-Protocol _48_Light.svg';
import _resAwsIoTOverAirUpdate48LightSvg from './Res_AWS-IoT_Over-Air-Update_48_Light.svg';
import _resAwsIoTPolicy48LightSvg from './Res_AWS-IoT_Policy_48_Light.svg';
import _resAwsIoTReportedState48LightSvg from './Res_AWS-IoT_Reported-State_48_Light.svg';
import _resAwsIoTSailboat48LightSvg from './Res_AWS-IoT_Sailboat _48_Light.svg';
import _resAwsIoTSensor48LightSvg from './Res_AWS-IoT_Sensor_48_Light.svg';
import _resAwsIoTServo48LightSvg from './Res_AWS-IoT_Servo_48_Light.svg';
import _resAwsIoTShadow48LightSvg from './Res_AWS-IoT_Shadow_48_Light.svg';
import _resAwsIoTSimulator48LightSvg from './Res_AWS-IoT_Simulator_48_Light.svg';
import _resAwsIoTThingFreeRtosDevice48LightSvg from './Res_AWS-IoT_Thing_FreeRTOS-Device_48_Light.svg';
import _resAwsIoTThingHumiditySensor48LightSvg from './Res_AWS-IoT_Thing_Humidity-Sensor_48_Light.svg';
import _resAwsIoTThingIndustrialPc48LightSvg from './Res_AWS-IoT_Thing_Industrial-PC_48_Light.svg';
import _resAwsIoTThingPlc48LightSvg from './Res_AWS-IoT_Thing_PLC_48_Light.svg';
import _resAwsIoTThingRelay48LightSvg from './Res_AWS-IoT_Thing_Relay_48_Light.svg';
import _resAwsIoTThingStacklight48LightSvg from './Res_AWS-IoT_Thing_Stacklight_48_Light.svg';
import _resAwsIoTThingTemperatureHumiditySensor48LightSvg from './Res_AWS-IoT_Thing_Temperature-Humidity-Sensor_48_Light.svg';
import _resAwsIoTThingTemperatureSensor48LightSvg from './Res_AWS-IoT_Thing_Temperature-Sensor_48_Light.svg';
import _resAwsIoTThingTemperatureVibrationSensor48LightSvg from './Res_AWS-IoT_Thing_Temperature-Vibration-Sensor_48_Light.svg';
import _resAwsIoTThingVibrationSensor48LightSvg from './Res_AWS-IoT_Thing_Vibration-Sensor_48_Light.svg';
import _resAwsIoTTopic48LightSvg from './Res_AWS-IoT_Topic_48_Light.svg';

export const resAwsIoTAnalyticsChannel48LightSvg = { id: "resAwsIoTAnalyticsChannel48LightSvg", name: "AWS IoT Analytics | Channel", icon: _resAwsIoTAnalyticsChannel48LightSvg };
export const resAwsIoTAnalyticsDataStore48LightSvg = { id: "resAwsIoTAnalyticsDataStore48LightSvg", name: "AWS IoT Analytics | Data Store", icon: _resAwsIoTAnalyticsDataStore48LightSvg };
export const resAwsIoTAnalyticsDataset48LightSvg = { id: "resAwsIoTAnalyticsDataset48LightSvg", name: "AWS IoT Analytics | Dataset", icon: _resAwsIoTAnalyticsDataset48LightSvg };
export const resAwsIoTAnalyticsNotebook48LightSvg = { id: "resAwsIoTAnalyticsNotebook48LightSvg", name: "AWS IoT Analytics | Notebook", icon: _resAwsIoTAnalyticsNotebook48LightSvg };
export const resAwsIoTAnalyticsPipeline48LightSvg = { id: "resAwsIoTAnalyticsPipeline48LightSvg", name: "AWS IoT Analytics | Pipeline", icon: _resAwsIoTAnalyticsPipeline48LightSvg };
export const resAwsIoTDeviceDefenderIoTDeviceJobs48LightSvg = { id: "resAwsIoTDeviceDefenderIoTDeviceJobs48LightSvg", name: "AWS IoT Device Defender | IoT Device Jobs", icon: _resAwsIoTDeviceDefenderIoTDeviceJobs48LightSvg };
export const resAwsIoTDeviceManagementFleetHub48LightSvg = { id: "resAwsIoTDeviceManagementFleetHub48LightSvg", name: "AWS IoT Device Management | Fleet Hub", icon: _resAwsIoTDeviceManagementFleetHub48LightSvg };
export const resAwsIoTGreengrassArtifact48LightSvg = { id: "resAwsIoTGreengrassArtifact48LightSvg", name: "AWS IoT Greengrass | Artifact", icon: _resAwsIoTGreengrassArtifact48LightSvg };
export const resAwsIoTGreengrassComponentMachineLearning48LightSvg = { id: "resAwsIoTGreengrassComponentMachineLearning48LightSvg", name: "AWS IoT Greengrass | Component Machine Learning", icon: _resAwsIoTGreengrassComponentMachineLearning48LightSvg };
export const resAwsIoTGreengrassComponentNucleus48LightSvg = { id: "resAwsIoTGreengrassComponentNucleus48LightSvg", name: "AWS IoT Greengrass | Component Nucleus", icon: _resAwsIoTGreengrassComponentNucleus48LightSvg };
export const resAwsIoTGreengrassComponentPrivate48LightSvg = { id: "resAwsIoTGreengrassComponentPrivate48LightSvg", name: "AWS IoT Greengrass | Component Private", icon: _resAwsIoTGreengrassComponentPrivate48LightSvg };
export const resAwsIoTGreengrassComponentPublic48LightSvg = { id: "resAwsIoTGreengrassComponentPublic48LightSvg", name: "AWS IoT Greengrass | Component Public", icon: _resAwsIoTGreengrassComponentPublic48LightSvg };
export const resAwsIoTGreengrassComponent48LightSvg = { id: "resAwsIoTGreengrassComponent48LightSvg", name: "AWS IoT Greengrass | Component", icon: _resAwsIoTGreengrassComponent48LightSvg };
export const resAwsIoTGreengrassConnector48LightSvg = { id: "resAwsIoTGreengrassConnector48LightSvg", name: "AWS IoT Greengrass | Connector", icon: _resAwsIoTGreengrassConnector48LightSvg };
export const resAwsIoTGreengrassInterprocessCommunication48LightSvg = { id: "resAwsIoTGreengrassInterprocessCommunication48LightSvg", name: "AWS IoT Greengrass | Interprocess Communication", icon: _resAwsIoTGreengrassInterprocessCommunication48LightSvg };
export const resAwsIoTGreengrassProtocol48LightSvg = { id: "resAwsIoTGreengrassProtocol48LightSvg", name: "AWS IoT Greengrass | Protocol", icon: _resAwsIoTGreengrassProtocol48LightSvg };
export const resAwsIoTGreengrassRecipe48LightSvg = { id: "resAwsIoTGreengrassRecipe48LightSvg", name: "AWS IoT Greengrass | Recipe", icon: _resAwsIoTGreengrassRecipe48LightSvg };
export const resAwsIoTGreengrassStreamManager48LightSvg = { id: "resAwsIoTGreengrassStreamManager48LightSvg", name: "AWS IoT Greengrass | Stream Manager", icon: _resAwsIoTGreengrassStreamManager48LightSvg };
export const resAwsIoTHttpProtocol48LightSvg = { id: "resAwsIoTHttpProtocol48LightSvg", name: "AWS IoT HTTP | Protocol", icon: _resAwsIoTHttpProtocol48LightSvg };
export const resAwsIoTHardwareBoard48LightSvg = { id: "resAwsIoTHardwareBoard48LightSvg", name: "AWS IoT Hardware Board", icon: _resAwsIoTHardwareBoard48LightSvg };
export const resAwsIoTMqttProtocol48LightSvg = { id: "resAwsIoTMqttProtocol48LightSvg", name: "AWS IoT MQTT | Protocol", icon: _resAwsIoTMqttProtocol48LightSvg };
export const resAwsIoTRule48LightSvg = { id: "resAwsIoTRule48LightSvg", name: "AWS IoT Rule", icon: _resAwsIoTRule48LightSvg };
export const resAwsIoTSiteWiseAssetHierarchy48LightSvg = { id: "resAwsIoTSiteWiseAssetHierarchy48LightSvg", name: "AWS IoT SiteWise | Asset Hierarchy", icon: _resAwsIoTSiteWiseAssetHierarchy48LightSvg };
export const resAwsIoTSiteWiseAssetModel48LightSvg = { id: "resAwsIoTSiteWiseAssetModel48LightSvg", name: "AWS IoT SiteWise | Asset Model", icon: _resAwsIoTSiteWiseAssetModel48LightSvg };
export const resAwsIoTSiteWiseAssetProperties48LightSvg = { id: "resAwsIoTSiteWiseAssetProperties48LightSvg", name: "AWS IoT SiteWise | Asset Properties", icon: _resAwsIoTSiteWiseAssetProperties48LightSvg };
export const resAwsIoTSiteWiseAsset48LightSvg = { id: "resAwsIoTSiteWiseAsset48LightSvg", name: "AWS IoT SiteWise | Asset", icon: _resAwsIoTSiteWiseAsset48LightSvg };
export const resAwsIoTSiteWiseDataStreams48LightSvg = { id: "resAwsIoTSiteWiseDataStreams48LightSvg", name: "AWS IoT SiteWise | Data Streams", icon: _resAwsIoTSiteWiseDataStreams48LightSvg };
export const resAwsIoTThingBank48LightSvg = { id: "resAwsIoTThingBank48LightSvg", name: "AWS IoT Thing | Bank", icon: _resAwsIoTThingBank48LightSvg };
export const resAwsIoTThingBicycle48LightSvg = { id: "resAwsIoTThingBicycle48LightSvg", name: "AWS IoT Thing | Bicycle", icon: _resAwsIoTThingBicycle48LightSvg };
export const resAwsIoTThingCamera48LightSvg = { id: "resAwsIoTThingCamera48LightSvg", name: "AWS IoT Thing | Camera", icon: _resAwsIoTThingCamera48LightSvg };
export const resAwsIoTThingCar48LightSvg = { id: "resAwsIoTThingCar48LightSvg", name: "AWS IoT Thing | Car", icon: _resAwsIoTThingCar48LightSvg };
export const resAwsIoTThingCart48LightSvg = { id: "resAwsIoTThingCart48LightSvg", name: "AWS IoT Thing | Cart", icon: _resAwsIoTThingCart48LightSvg };
export const resAwsIoTThingCoffeePot48LightSvg = { id: "resAwsIoTThingCoffeePot48LightSvg", name: "AWS IoT Thing | Coffee Pot", icon: _resAwsIoTThingCoffeePot48LightSvg };
export const resAwsIoTThingDoorLock48LightSvg = { id: "resAwsIoTThingDoorLock48LightSvg", name: "AWS IoT Thing | Door Lock", icon: _resAwsIoTThingDoorLock48LightSvg };
export const resAwsIoTThingFactory48LightSvg = { id: "resAwsIoTThingFactory48LightSvg", name: "AWS IoT Thing | Factory", icon: _resAwsIoTThingFactory48LightSvg };
export const resAwsIoTThingGeneric48LightSvg = { id: "resAwsIoTThingGeneric48LightSvg", name: "AWS IoT Thing | Generic", icon: _resAwsIoTThingGeneric48LightSvg };
export const resAwsIoTThingHouse48LightSvg = { id: "resAwsIoTThingHouse48LightSvg", name: "AWS IoT Thing | House", icon: _resAwsIoTThingHouse48LightSvg };
export const resAwsIoTThingLightbulb48LightSvg = { id: "resAwsIoTThingLightbulb48LightSvg", name: "AWS IoT Thing | Lightbulb", icon: _resAwsIoTThingLightbulb48LightSvg };
export const resAwsIoTThingMedicalEmergency48LightSvg = { id: "resAwsIoTThingMedicalEmergency48LightSvg", name: "AWS IoT Thing | Medical Emergency", icon: _resAwsIoTThingMedicalEmergency48LightSvg };
export const resAwsIoTThingPoliceEmergency48LightSvg = { id: "resAwsIoTThingPoliceEmergency48LightSvg", name: "AWS IoT Thing | Police Emergency", icon: _resAwsIoTThingPoliceEmergency48LightSvg };
export const resAwsIoTThingThermostat48LightSvg = { id: "resAwsIoTThingThermostat48LightSvg", name: "AWS IoT Thing | Thermostat", icon: _resAwsIoTThingThermostat48LightSvg };
export const resAwsIoTThingTravel48LightSvg = { id: "resAwsIoTThingTravel48LightSvg", name: "AWS IoT Thing | Travel", icon: _resAwsIoTThingTravel48LightSvg };
export const resAwsIoTThingUtility48LightSvg = { id: "resAwsIoTThingUtility48LightSvg", name: "AWS IoT Thing | Utility", icon: _resAwsIoTThingUtility48LightSvg };
export const resAwsIoTThingWindfarm48LightSvg = { id: "resAwsIoTThingWindfarm48LightSvg", name: "AWS IoT Thing | Windfarm", icon: _resAwsIoTThingWindfarm48LightSvg };
export const resAwsIoTAction48LightSvg = { id: "resAwsIoTAction48LightSvg", name: "AWS IoT | Action", icon: _resAwsIoTAction48LightSvg };
export const resAwsIoTActuator48LightSvg = { id: "resAwsIoTActuator48LightSvg", name: "AWS IoT | Actuator", icon: _resAwsIoTActuator48LightSvg };
export const resAwsIoTAlexaEnabledDevice48LightSvg = { id: "resAwsIoTAlexaEnabledDevice48LightSvg", name: "AWS IoT | Alexa | Enabled Device", icon: _resAwsIoTAlexaEnabledDevice48LightSvg };
export const resAwsIoTAlexaSkill48LightSvg = { id: "resAwsIoTAlexaSkill48LightSvg", name: "AWS IoT | Alexa | Skill", icon: _resAwsIoTAlexaSkill48LightSvg };
export const resAwsIoTAlexaVoiceService48LightSvg = { id: "resAwsIoTAlexaVoiceService48LightSvg", name: "AWS IoT | Alexa | Voice Service", icon: _resAwsIoTAlexaVoiceService48LightSvg };
export const resAwsIoTCertificate48LightSvg = { id: "resAwsIoTCertificate48LightSvg", name: "AWS IoT | Certificate", icon: _resAwsIoTCertificate48LightSvg };
export const resAwsIoTDesiredState48LightSvg = { id: "resAwsIoTDesiredState48LightSvg", name: "AWS IoT | Desired State", icon: _resAwsIoTDesiredState48LightSvg };
export const resAwsIoTDeviceGateway48LightSvg = { id: "resAwsIoTDeviceGateway48LightSvg", name: "AWS IoT | Device Gateway", icon: _resAwsIoTDeviceGateway48LightSvg };
export const resAwsIoTEcho48LightSvg = { id: "resAwsIoTEcho48LightSvg", name: "AWS IoT | Echo", icon: _resAwsIoTEcho48LightSvg };
export const resAwsIoTFireTvStick48LightSvg = { id: "resAwsIoTFireTvStick48LightSvg", name: "AWS IoT | Fire TV | Stick", icon: _resAwsIoTFireTvStick48LightSvg };
export const resAwsIoTFireTv48LightSvg = { id: "resAwsIoTFireTv48LightSvg", name: "AWS IoT | Fire | TV", icon: _resAwsIoTFireTv48LightSvg };
export const resAwsIoTHttp2Protocol48LightSvg = { id: "resAwsIoTHttp2Protocol48LightSvg", name: "AWS IoT | HTTP2 Protocol", icon: _resAwsIoTHttp2Protocol48LightSvg };
export const resAwsIoTLambdaFunction48LightSvg = { id: "resAwsIoTLambdaFunction48LightSvg", name: "AWS IoT | Lambda | Function", icon: _resAwsIoTLambdaFunction48LightSvg };
export const resAwsIoTLoRaWanProtocol48LightSvg = { id: "resAwsIoTLoRaWanProtocol48LightSvg", name: "AWS IoT | LoRaWAN Protocol ", icon: _resAwsIoTLoRaWanProtocol48LightSvg };
export const resAwsIoTOverAirUpdate48LightSvg = { id: "resAwsIoTOverAirUpdate48LightSvg", name: "AWS IoT | Over Air Update", icon: _resAwsIoTOverAirUpdate48LightSvg };
export const resAwsIoTPolicy48LightSvg = { id: "resAwsIoTPolicy48LightSvg", name: "AWS IoT | Policy", icon: _resAwsIoTPolicy48LightSvg };
export const resAwsIoTReportedState48LightSvg = { id: "resAwsIoTReportedState48LightSvg", name: "AWS IoT | Reported State", icon: _resAwsIoTReportedState48LightSvg };
export const resAwsIoTSailboat48LightSvg = { id: "resAwsIoTSailboat48LightSvg", name: "AWS IoT | Sailboat ", icon: _resAwsIoTSailboat48LightSvg };
export const resAwsIoTSensor48LightSvg = { id: "resAwsIoTSensor48LightSvg", name: "AWS IoT | Sensor", icon: _resAwsIoTSensor48LightSvg };
export const resAwsIoTServo48LightSvg = { id: "resAwsIoTServo48LightSvg", name: "AWS IoT | Servo", icon: _resAwsIoTServo48LightSvg };
export const resAwsIoTShadow48LightSvg = { id: "resAwsIoTShadow48LightSvg", name: "AWS IoT | Shadow", icon: _resAwsIoTShadow48LightSvg };
export const resAwsIoTSimulator48LightSvg = { id: "resAwsIoTSimulator48LightSvg", name: "AWS IoT | Simulator", icon: _resAwsIoTSimulator48LightSvg };
export const resAwsIoTThingFreeRtosDevice48LightSvg = { id: "resAwsIoTThingFreeRtosDevice48LightSvg", name: "AWS IoT | Thing | FreeRTOS Device", icon: _resAwsIoTThingFreeRtosDevice48LightSvg };
export const resAwsIoTThingHumiditySensor48LightSvg = { id: "resAwsIoTThingHumiditySensor48LightSvg", name: "AWS IoT | Thing | Humidity Sensor", icon: _resAwsIoTThingHumiditySensor48LightSvg };
export const resAwsIoTThingIndustrialPc48LightSvg = { id: "resAwsIoTThingIndustrialPc48LightSvg", name: "AWS IoT | Thing | Industrial PC", icon: _resAwsIoTThingIndustrialPc48LightSvg };
export const resAwsIoTThingPlc48LightSvg = { id: "resAwsIoTThingPlc48LightSvg", name: "AWS IoT | Thing | PLC", icon: _resAwsIoTThingPlc48LightSvg };
export const resAwsIoTThingRelay48LightSvg = { id: "resAwsIoTThingRelay48LightSvg", name: "AWS IoT | Thing | Relay", icon: _resAwsIoTThingRelay48LightSvg };
export const resAwsIoTThingStacklight48LightSvg = { id: "resAwsIoTThingStacklight48LightSvg", name: "AWS IoT | Thing | Stacklight", icon: _resAwsIoTThingStacklight48LightSvg };
export const resAwsIoTThingTemperatureHumiditySensor48LightSvg = { id: "resAwsIoTThingTemperatureHumiditySensor48LightSvg", name: "AWS IoT | Thing | Temperature Humidity Sensor", icon: _resAwsIoTThingTemperatureHumiditySensor48LightSvg };
export const resAwsIoTThingTemperatureSensor48LightSvg = { id: "resAwsIoTThingTemperatureSensor48LightSvg", name: "AWS IoT | Thing | Temperature Sensor", icon: _resAwsIoTThingTemperatureSensor48LightSvg };
export const resAwsIoTThingTemperatureVibrationSensor48LightSvg = { id: "resAwsIoTThingTemperatureVibrationSensor48LightSvg", name: "AWS IoT | Thing | Temperature Vibration Sensor", icon: _resAwsIoTThingTemperatureVibrationSensor48LightSvg };
export const resAwsIoTThingVibrationSensor48LightSvg = { id: "resAwsIoTThingVibrationSensor48LightSvg", name: "AWS IoT | Thing | Vibration Sensor", icon: _resAwsIoTThingVibrationSensor48LightSvg };
export const resAwsIoTTopic48LightSvg = { id: "resAwsIoTTopic48LightSvg", name: "AWS IoT | Topic", icon: _resAwsIoTTopic48LightSvg };
