import _archAwsIoT1Click48Svg from './Arch_AWS-IoT-1-Click_48.svg';
import _archAwsIoTAnalytics48Svg from './Arch_AWS-IoT-Analytics_48.svg';
import _archAwsIoTButton48Svg from './Arch_AWS-IoT-Button_48.svg';
import _archAwsIoTCore48Svg from './Arch_AWS-IoT-Core_48.svg';
import _archAwsIoTDeviceDefender48Svg from './Arch_AWS-IoT-Device-Defender_48.svg';
import _archAwsIoTDeviceManagement48Svg from './Arch_AWS-IoT-Device-Management_48.svg';
import _archAwsIoTEduKit48Svg from './Arch_AWS-IoT-EduKit_48.svg';
import _archAwsIoTEvents48Svg from './Arch_AWS-IoT-Events_48.svg';
import _archAwsIoTExpressLink48Svg from './Arch_AWS-IoT-ExpressLink_48.svg';
import _archAwsIoTFleetWise48Svg from './Arch_AWS-IoT-FleetWise_48.svg';
import _archAwsIoTGreengrass48Svg from './Arch_AWS-IoT-Greengrass_48.svg';
import _archAwsIoTRoboRunner48Svg from './Arch_AWS-IoT-RoboRunner_48.svg';
import _archAwsIoTSiteWise48Svg from './Arch_AWS-IoT-SiteWise_48.svg';
import _archAwsIoTThingsGraph48Svg from './Arch_AWS-IoT-Things-Graph_48.svg';
import _archAwsIoTTwinMaker48Svg from './Arch_AWS-IoT-TwinMaker_48.svg';
import _archFreeRtos48Svg from './Arch_FreeRTOS_48.svg';

export const archAwsIoT1Click48Svg = { id: "archAwsIoT1Click48Svg", name: "AWS IoT 1 Click", icon: _archAwsIoT1Click48Svg };
export const archAwsIoTAnalytics48Svg = { id: "archAwsIoTAnalytics48Svg", name: "AWS IoT Analytics", icon: _archAwsIoTAnalytics48Svg };
export const archAwsIoTButton48Svg = { id: "archAwsIoTButton48Svg", name: "AWS IoT Button", icon: _archAwsIoTButton48Svg };
export const archAwsIoTCore48Svg = { id: "archAwsIoTCore48Svg", name: "AWS IoT Core", icon: _archAwsIoTCore48Svg };
export const archAwsIoTDeviceDefender48Svg = { id: "archAwsIoTDeviceDefender48Svg", name: "AWS IoT Device Defender", icon: _archAwsIoTDeviceDefender48Svg };
export const archAwsIoTDeviceManagement48Svg = { id: "archAwsIoTDeviceManagement48Svg", name: "AWS IoT Device Management", icon: _archAwsIoTDeviceManagement48Svg };
export const archAwsIoTEduKit48Svg = { id: "archAwsIoTEduKit48Svg", name: "AWS IoT EduKit", icon: _archAwsIoTEduKit48Svg };
export const archAwsIoTEvents48Svg = { id: "archAwsIoTEvents48Svg", name: "AWS IoT Events", icon: _archAwsIoTEvents48Svg };
export const archAwsIoTExpressLink48Svg = { id: "archAwsIoTExpressLink48Svg", name: "AWS IoT ExpressLink", icon: _archAwsIoTExpressLink48Svg };
export const archAwsIoTFleetWise48Svg = { id: "archAwsIoTFleetWise48Svg", name: "AWS IoT FleetWise", icon: _archAwsIoTFleetWise48Svg };
export const archAwsIoTGreengrass48Svg = { id: "archAwsIoTGreengrass48Svg", name: "AWS IoT Greengrass", icon: _archAwsIoTGreengrass48Svg };
export const archAwsIoTRoboRunner48Svg = { id: "archAwsIoTRoboRunner48Svg", name: "AWS IoT RoboRunner", icon: _archAwsIoTRoboRunner48Svg };
export const archAwsIoTSiteWise48Svg = { id: "archAwsIoTSiteWise48Svg", name: "AWS IoT SiteWise", icon: _archAwsIoTSiteWise48Svg };
export const archAwsIoTThingsGraph48Svg = { id: "archAwsIoTThingsGraph48Svg", name: "AWS IoT Things Graph", icon: _archAwsIoTThingsGraph48Svg };
export const archAwsIoTTwinMaker48Svg = { id: "archAwsIoTTwinMaker48Svg", name: "AWS IoT TwinMaker", icon: _archAwsIoTTwinMaker48Svg };
export const archFreeRtos48Svg = { id: "archFreeRtos48Svg", name: "FreeRTOS", icon: _archFreeRtos48Svg };
