import _resAwsManagementConsole48LightSvg from './Res_AWS-Management-Console_48_Light.svg';
import _resAlert48LightSvg from './Res_Alert_48_Light.svg';
import _resCamera48LightSvg from './Res_Camera_48_Light.svg';
import _resChat48LightSvg from './Res_Chat_48_Light.svg';
import _resClient48LightSvg from './Res_Client_48_Light.svg';
import _resDisk48LightSvg from './Res_Disk_48_Light.svg';
import _resDocument48LightSvg from './Res_Document_48_Light.svg';
import _resDocuments48LightSvg from './Res_Documents_48_Light.svg';
import _resEmail48LightSvg from './Res_Email_48_Light.svg';
import _resFirewall48LightSvg from './Res_Firewall_48_Light.svg';
import _resFolder48LightSvg from './Res_Folder_48_Light.svg';
import _resFolders48LightSvg from './Res_Folders_48_Light.svg';
import _resForums48LightSvg from './Res_Forums_48_Light.svg';
import _resGear48LightSvg from './Res_Gear_48_Light.svg';
import _resGenericApplication48LightSvg from './Res_Generic-Application_48_Light.svg';
import _resGenericDatabase48LightSvg from './Res_Generic-database_48_Light.svg';
import _resGitRepository48LightSvg from './Res_Git-Repository_48_Light.svg';
import _resGlobe48LightSvg from './Res_Globe_48_Light.svg';
import _resInternetAlt148LightSvg from './Res_Internet-alt1_48_Light.svg';
import _resInternetAlt248LightSvg from './Res_Internet-alt2_48_Light.svg';
import _resInternet48LightSvg from './Res_Internet_48_Light.svg';
import _resMagnifyingGlass48LightSvg from './Res_Magnifying-Glass_48_Light.svg';
import _resMobileClient48LightSvg from './Res_Mobile-client_48_Light.svg';
import _resMultimedia48LightSvg from './Res_Multimedia_48_Light.svg';
import _resOfficeBuilding48LightSvg from './Res_Office-building_48_Light.svg';
import _resQuestion48LightSvg from './Res_Question_48_Light.svg';
import _resRecover48LightSvg from './Res_Recover_48_Light.svg';
import _resSamlToken48LightSvg from './Res_SAML-token_48_Light.svg';
import _resSdk48LightSvg from './Res_SDK_48_Light.svg';
import _resSslPadlock48LightSvg from './Res_SSL-padlock_48_Light.svg';
import _resServers48LightSvg from './Res_Servers_48_Light.svg';
import _resShield48LightSvg from './Res_Shield_48_Light.svg';
import _resSourceCode48LightSvg from './Res_Source-Code_48_Light.svg';
import _resTapeStorage48LightSvg from './Res_Tape-storage_48_Light.svg';
import _resToolkit48LightSvg from './Res_Toolkit_48_Light.svg';
import _resTraditionalServer48LightSvg from './Res_Traditional-server_48_Light.svg';
import _resUser48LightSvg from './Res_User_48_Light.svg';
import _resUsers48LightSvg from './Res_Users_48_Light.svg';

export const resAwsManagementConsole48LightSvg = { id: "resAwsManagementConsole48LightSvg", name: "AWS Management Console", icon: _resAwsManagementConsole48LightSvg };
export const resAlert48LightSvg = { id: "resAlert48LightSvg", name: "Alert", icon: _resAlert48LightSvg };
export const resCamera48LightSvg = { id: "resCamera48LightSvg", name: "Camera", icon: _resCamera48LightSvg };
export const resChat48LightSvg = { id: "resChat48LightSvg", name: "Chat", icon: _resChat48LightSvg };
export const resClient48LightSvg = { id: "resClient48LightSvg", name: "Client", icon: _resClient48LightSvg };
export const resDisk48LightSvg = { id: "resDisk48LightSvg", name: "Disk", icon: _resDisk48LightSvg };
export const resDocument48LightSvg = { id: "resDocument48LightSvg", name: "Document", icon: _resDocument48LightSvg };
export const resDocuments48LightSvg = { id: "resDocuments48LightSvg", name: "Documents", icon: _resDocuments48LightSvg };
export const resEmail48LightSvg = { id: "resEmail48LightSvg", name: "Email", icon: _resEmail48LightSvg };
export const resFirewall48LightSvg = { id: "resFirewall48LightSvg", name: "Firewall", icon: _resFirewall48LightSvg };
export const resFolder48LightSvg = { id: "resFolder48LightSvg", name: "Folder", icon: _resFolder48LightSvg };
export const resFolders48LightSvg = { id: "resFolders48LightSvg", name: "Folders", icon: _resFolders48LightSvg };
export const resForums48LightSvg = { id: "resForums48LightSvg", name: "Forums", icon: _resForums48LightSvg };
export const resGear48LightSvg = { id: "resGear48LightSvg", name: "Gear", icon: _resGear48LightSvg };
export const resGenericApplication48LightSvg = { id: "resGenericApplication48LightSvg", name: "Generic Application", icon: _resGenericApplication48LightSvg };
export const resGenericDatabase48LightSvg = { id: "resGenericDatabase48LightSvg", name: "Generic database", icon: _resGenericDatabase48LightSvg };
export const resGitRepository48LightSvg = { id: "resGitRepository48LightSvg", name: "Git Repository", icon: _resGitRepository48LightSvg };
export const resGlobe48LightSvg = { id: "resGlobe48LightSvg", name: "Globe", icon: _resGlobe48LightSvg };
export const resInternetAlt148LightSvg = { id: "resInternetAlt148LightSvg", name: "Internet alt1", icon: _resInternetAlt148LightSvg };
export const resInternetAlt248LightSvg = { id: "resInternetAlt248LightSvg", name: "Internet alt2", icon: _resInternetAlt248LightSvg };
export const resInternet48LightSvg = { id: "resInternet48LightSvg", name: "Internet", icon: _resInternet48LightSvg };
export const resMagnifyingGlass48LightSvg = { id: "resMagnifyingGlass48LightSvg", name: "Magnifying Glass", icon: _resMagnifyingGlass48LightSvg };
export const resMobileClient48LightSvg = { id: "resMobileClient48LightSvg", name: "Mobile client", icon: _resMobileClient48LightSvg };
export const resMultimedia48LightSvg = { id: "resMultimedia48LightSvg", name: "Multimedia", icon: _resMultimedia48LightSvg };
export const resOfficeBuilding48LightSvg = { id: "resOfficeBuilding48LightSvg", name: "Office building", icon: _resOfficeBuilding48LightSvg };
export const resQuestion48LightSvg = { id: "resQuestion48LightSvg", name: "Question", icon: _resQuestion48LightSvg };
export const resRecover48LightSvg = { id: "resRecover48LightSvg", name: "Recover", icon: _resRecover48LightSvg };
export const resSamlToken48LightSvg = { id: "resSamlToken48LightSvg", name: "SAML token", icon: _resSamlToken48LightSvg };
export const resSdk48LightSvg = { id: "resSdk48LightSvg", name: "SDK", icon: _resSdk48LightSvg };
export const resSslPadlock48LightSvg = { id: "resSslPadlock48LightSvg", name: "SSL padlock", icon: _resSslPadlock48LightSvg };
export const resServers48LightSvg = { id: "resServers48LightSvg", name: "Servers", icon: _resServers48LightSvg };
export const resShield48LightSvg = { id: "resShield48LightSvg", name: "Shield", icon: _resShield48LightSvg };
export const resSourceCode48LightSvg = { id: "resSourceCode48LightSvg", name: "Source Code", icon: _resSourceCode48LightSvg };
export const resTapeStorage48LightSvg = { id: "resTapeStorage48LightSvg", name: "Tape storage", icon: _resTapeStorage48LightSvg };
export const resToolkit48LightSvg = { id: "resToolkit48LightSvg", name: "Toolkit", icon: _resToolkit48LightSvg };
export const resTraditionalServer48LightSvg = { id: "resTraditionalServer48LightSvg", name: "Traditional server", icon: _resTraditionalServer48LightSvg };
export const resUser48LightSvg = { id: "resUser48LightSvg", name: "User", icon: _resUser48LightSvg };
export const resUsers48LightSvg = { id: "resUsers48LightSvg", name: "Users", icon: _resUsers48LightSvg };
