import _archAwsBackup32Svg from './Arch_AWS-Backup_32.svg';
import _archAwsSnowballEdge32Svg from './Arch_AWS-Snowball-Edge_32.svg';
import _archAwsSnowball32Svg from './Arch_AWS-Snowball_32.svg';
import _archAwsSnowcone32Svg from './Arch_AWS-Snowcone_32.svg';
import _archAwsSnowmobile32Svg from './Arch_AWS-Snowmobile_32.svg';
import _archAwsStorageGateway32Svg from './Arch_AWS-Storage-Gateway_32.svg';
import _archAmazonEfs32Svg from './Arch_Amazon-EFS_32.svg';
import _archAmazonElasticBlockStore32Svg from './Arch_Amazon-Elastic-Block-Store_32.svg';
import _archAmazonFsxForLustre32Svg from './Arch_Amazon-FSx-for-Lustre_32.svg';
import _archAmazonFsxForNetAppOntap32Svg from './Arch_Amazon-FSx-for-NetApp-ONTAP_32.svg';
import _archAmazonFsxForOpenZfs32Svg from './Arch_Amazon-FSx-for-OpenZFS_32.svg';
import _archAmazonFsxForWfs32Svg from './Arch_Amazon-FSx-for-WFS_32.svg';
import _archAmazonFsx32Svg from './Arch_Amazon-FSx_32.svg';
import _archAmazonS3OnOutposts32Svg from './Arch_Amazon-S3-on-Outposts_32.svg';
import _archAmazonSimpleStorageServiceGlacier32Svg from './Arch_Amazon-Simple-Storage-Service-Glacier_32.svg';
import _archAmazonSimpleStorageService32Svg from './Arch_Amazon-Simple-Storage-Service_32.svg';
import _archCloudEndureDisasterRecovery32Svg from './Arch_CloudEndure-Disaster-Recovery_32.svg';

export const archAwsBackup32Svg = { id: "archAwsBackup32Svg", name: "AWS Backup", icon: _archAwsBackup32Svg };
export const archAwsSnowballEdge32Svg = { id: "archAwsSnowballEdge32Svg", name: "AWS Snowball Edge", icon: _archAwsSnowballEdge32Svg };
export const archAwsSnowball32Svg = { id: "archAwsSnowball32Svg", name: "AWS Snowball", icon: _archAwsSnowball32Svg };
export const archAwsSnowcone32Svg = { id: "archAwsSnowcone32Svg", name: "AWS Snowcone", icon: _archAwsSnowcone32Svg };
export const archAwsSnowmobile32Svg = { id: "archAwsSnowmobile32Svg", name: "AWS Snowmobile", icon: _archAwsSnowmobile32Svg };
export const archAwsStorageGateway32Svg = { id: "archAwsStorageGateway32Svg", name: "AWS Storage Gateway", icon: _archAwsStorageGateway32Svg };
export const archAmazonEfs32Svg = { id: "archAmazonEfs32Svg", name: "Amazon EFS", icon: _archAmazonEfs32Svg };
export const archAmazonElasticBlockStore32Svg = { id: "archAmazonElasticBlockStore32Svg", name: "Amazon Elastic Block Store", icon: _archAmazonElasticBlockStore32Svg };
export const archAmazonFsxForLustre32Svg = { id: "archAmazonFsxForLustre32Svg", name: "Amazon FSx for Lustre", icon: _archAmazonFsxForLustre32Svg };
export const archAmazonFsxForNetAppOntap32Svg = { id: "archAmazonFsxForNetAppOntap32Svg", name: "Amazon FSx for NetApp ONTAP", icon: _archAmazonFsxForNetAppOntap32Svg };
export const archAmazonFsxForOpenZfs32Svg = { id: "archAmazonFsxForOpenZfs32Svg", name: "Amazon FSx for OpenZFS", icon: _archAmazonFsxForOpenZfs32Svg };
export const archAmazonFsxForWfs32Svg = { id: "archAmazonFsxForWfs32Svg", name: "Amazon FSx for WFS", icon: _archAmazonFsxForWfs32Svg };
export const archAmazonFsx32Svg = { id: "archAmazonFsx32Svg", name: "Amazon FSx", icon: _archAmazonFsx32Svg };
export const archAmazonS3OnOutposts32Svg = { id: "archAmazonS3OnOutposts32Svg", name: "Amazon S3 on Outposts", icon: _archAmazonS3OnOutposts32Svg };
export const archAmazonSimpleStorageServiceGlacier32Svg = { id: "archAmazonSimpleStorageServiceGlacier32Svg", name: "Amazon Simple Storage Service Glacier", icon: _archAmazonSimpleStorageServiceGlacier32Svg };
export const archAmazonSimpleStorageService32Svg = { id: "archAmazonSimpleStorageService32Svg", name: "Amazon Simple Storage Service", icon: _archAmazonSimpleStorageService32Svg };
export const archCloudEndureDisasterRecovery32Svg = { id: "archCloudEndureDisasterRecovery32Svg", name: "CloudEndure Disaster Recovery", icon: _archCloudEndureDisasterRecovery32Svg };
