import _archAwsBackup64Svg from './Arch_AWS-Backup_64.svg';
import _archAwsSnowballEdge64Svg from './Arch_AWS-Snowball-Edge_64.svg';
import _archAwsSnowball64Svg from './Arch_AWS-Snowball_64.svg';
import _archAwsSnowcone64Svg from './Arch_AWS-Snowcone_64.svg';
import _archAwsSnowmobile64Svg from './Arch_AWS-Snowmobile_64.svg';
import _archAwsStorageGateway64Svg from './Arch_AWS-Storage-Gateway_64.svg';
import _archAmazonEfs64Svg from './Arch_Amazon-EFS_64.svg';
import _archAmazonElasticBlockStore64Svg from './Arch_Amazon-Elastic-Block-Store_64.svg';
import _archAmazonFsxForLustre64Svg from './Arch_Amazon-FSx-for-Lustre_64.svg';
import _archAmazonFsxForNetAppOntap64Svg from './Arch_Amazon-FSx-for-NetApp-ONTAP_64.svg';
import _archAmazonFsxForOpenZfs64Svg from './Arch_Amazon-FSx-for-OpenZFS_64.svg';
import _archAmazonFsxForWfs64Svg from './Arch_Amazon-FSx-for-WFS_64.svg';
import _archAmazonFsx64Svg from './Arch_Amazon-FSx_64.svg';
import _archAmazonS3OnOutposts64Svg from './Arch_Amazon-S3-on-Outposts_64.svg';
import _archAmazonSimpleStorageServiceGlacier64Svg from './Arch_Amazon-Simple-Storage-Service-Glacier_64.svg';
import _archAmazonSimpleStorageService64Svg from './Arch_Amazon-Simple-Storage-Service_64.svg';
import _archCloudEndureDisasterRecovery64Svg from './Arch_CloudEndure-Disaster-Recovery_64.svg';

export const archAwsBackup64Svg = { id: "archAwsBackup64Svg", name: "AWS Backup", icon: _archAwsBackup64Svg };
export const archAwsSnowballEdge64Svg = { id: "archAwsSnowballEdge64Svg", name: "AWS Snowball Edge", icon: _archAwsSnowballEdge64Svg };
export const archAwsSnowball64Svg = { id: "archAwsSnowball64Svg", name: "AWS Snowball", icon: _archAwsSnowball64Svg };
export const archAwsSnowcone64Svg = { id: "archAwsSnowcone64Svg", name: "AWS Snowcone", icon: _archAwsSnowcone64Svg };
export const archAwsSnowmobile64Svg = { id: "archAwsSnowmobile64Svg", name: "AWS Snowmobile", icon: _archAwsSnowmobile64Svg };
export const archAwsStorageGateway64Svg = { id: "archAwsStorageGateway64Svg", name: "AWS Storage Gateway", icon: _archAwsStorageGateway64Svg };
export const archAmazonEfs64Svg = { id: "archAmazonEfs64Svg", name: "Amazon EFS", icon: _archAmazonEfs64Svg };
export const archAmazonElasticBlockStore64Svg = { id: "archAmazonElasticBlockStore64Svg", name: "Amazon Elastic Block Store", icon: _archAmazonElasticBlockStore64Svg };
export const archAmazonFsxForLustre64Svg = { id: "archAmazonFsxForLustre64Svg", name: "Amazon FSx for Lustre", icon: _archAmazonFsxForLustre64Svg };
export const archAmazonFsxForNetAppOntap64Svg = { id: "archAmazonFsxForNetAppOntap64Svg", name: "Amazon FSx for NetApp ONTAP", icon: _archAmazonFsxForNetAppOntap64Svg };
export const archAmazonFsxForOpenZfs64Svg = { id: "archAmazonFsxForOpenZfs64Svg", name: "Amazon FSx for OpenZFS", icon: _archAmazonFsxForOpenZfs64Svg };
export const archAmazonFsxForWfs64Svg = { id: "archAmazonFsxForWfs64Svg", name: "Amazon FSx for WFS", icon: _archAmazonFsxForWfs64Svg };
export const archAmazonFsx64Svg = { id: "archAmazonFsx64Svg", name: "Amazon FSx", icon: _archAmazonFsx64Svg };
export const archAmazonS3OnOutposts64Svg = { id: "archAmazonS3OnOutposts64Svg", name: "Amazon S3 on Outposts", icon: _archAmazonS3OnOutposts64Svg };
export const archAmazonSimpleStorageServiceGlacier64Svg = { id: "archAmazonSimpleStorageServiceGlacier64Svg", name: "Amazon Simple Storage Service Glacier", icon: _archAmazonSimpleStorageServiceGlacier64Svg };
export const archAmazonSimpleStorageService64Svg = { id: "archAmazonSimpleStorageService64Svg", name: "Amazon Simple Storage Service", icon: _archAmazonSimpleStorageService64Svg };
export const archCloudEndureDisasterRecovery64Svg = { id: "archCloudEndureDisasterRecovery64Svg", name: "CloudEndure Disaster Recovery", icon: _archCloudEndureDisasterRecovery64Svg };
