import _resAwsBackupAwsBackupSupportForAmazonFsxForNetAppOntap48LightSvg from './Res_AWS-Backup_AWS-Backup-support-for-Amazon-FSx-for-NetApp-ONTAP_48_Light.svg';
import _resAwsBackupAwsBackupSupportForAmazonS348LightSvg from './Res_AWS-Backup_AWS-Backup-support-for-Amazon-S3_48_Light.svg';
import _resAwsBackupAwsBackupSupportForVmwareWorkloads48LightSvg from './Res_AWS-Backup_AWS-Backup-support-for-VMware-Workloads_48_Light.svg';
import _resAwsBackupBackupPlan48LightSvg from './Res_AWS-Backup_Backup-Plan_48_Light.svg';
import _resAwsBackupBackupRestore48LightSvg from './Res_AWS-Backup_Backup-Restore_48_Light.svg';
import _resAwsBackupBackupVault48LightSvg from './Res_AWS-Backup_Backup-Vault_48_Light.svg';
import _resAwsBackupComplianceReporting48LightSvg from './Res_AWS-Backup_Compliance-Reporting_48_Light.svg';
import _resAwsBackupCompute48LightSvg from './Res_AWS-Backup_Compute_48_Light.svg';
import _resAwsBackupDatabase48LightSvg from './Res_AWS-Backup_Database_48_Light.svg';
import _resAwsBackupGateway48LightSvg from './Res_AWS-Backup_Gateway_48_Light.svg';
import _resAwsBackupRecoveryPointObjective48LightSvg from './Res_AWS-Backup_Recovery-Point-Objective_48_Light.svg';
import _resAwsBackupRecoveryTimeObjective48LightSvg from './Res_AWS-Backup_Recovery-Time-Objective_48_Light.svg';
import _resAwsBackupStorage48LightSvg from './Res_AWS-Backup_Storage_48_Light.svg';
import _resAwsBackupVirtualMachineMonitor48LightSvg from './Res_AWS-Backup_Virtual-Machine-Monitor_48_Light.svg';
import _resAwsBackupVirtualMachine48LightSvg from './Res_AWS-Backup_Virtual-Machine_48_Light.svg';
import _resAwsSnowballSnowballImportExport48LightSvg from './Res_AWS-Snowball_Snowball-Import-Export_48_Light.svg';
import _resAwsStorageGatewayAmazonFsxFileGateway48LightSvg from './Res_AWS-Storage-Gateway_Amazon-FSx-File-Gateway_48_Light.svg';
import _resAwsStorageGatewayAmazonS3FileGateway48LightSvg from './Res_AWS-Storage-Gateway_Amazon-S3-File-Gateway_48_Light.svg';
import _resAwsStorageGatewayCachedVolume48LightSvg from './Res_AWS-Storage-Gateway_Cached-Volume_48_Light.svg';
import _resAwsStorageGatewayFileGateway48LightSvg from './Res_AWS-Storage-Gateway_File-Gateway_48_Light.svg';
import _resAwsStorageGatewayNoncachedVolume48LightSvg from './Res_AWS-Storage-Gateway_Noncached-Volume_48_Light.svg';
import _resAwsStorageGatewayTapeGateway48LightSvg from './Res_AWS-Storage-Gateway_Tape-Gateway_48_Light.svg';
import _resAwsStorageGatewayVirtualTapeLibrary48LightSvg from './Res_AWS-Storage-Gateway_Virtual-Tape-Library_48_Light.svg';
import _resAwsStorageGatewayVolumeGateway48LightSvg from './Res_AWS-Storage-Gateway_Volume-Gateway_48_Light.svg';
import _resAmazonElasticBlockStoreAmazonDataLifecycleManager48LightSvg from './Res_Amazon-Elastic-Block-Store_Amazon-Data-Lifecycle-Manager_48_Light.svg';
import _resAmazonElasticBlockStoreMultipleVolumes48LightSvg from './Res_Amazon-Elastic-Block-Store_Multiple-Volumes_48_Light.svg';
import _resAmazonElasticBlockStoreSnapshot48LightSvg from './Res_Amazon-Elastic-Block-Store_Snapshot_48_Light.svg';
import _resAmazonElasticBlockStoreVolumeGp348LightSvg from './Res_Amazon-Elastic-Block-Store_Volume-gp3_48_Light.svg';
import _resAmazonElasticBlockStoreVolume48LightSvg from './Res_Amazon-Elastic-Block-Store_Volume_48_Light.svg';
import _resAmazonElasticFileSystemFileSystem48LightSvg from './Res_Amazon-Elastic-File-System_File-System_48_Light.svg';
import _resAmazonElasticFileSystemIntelligentTiering48LightSvg from './Res_Amazon-Elastic-File-System_Intelligent-Tiering_48_Light.svg';
import _resAmazonElasticFileSystemOneZoneInfrequentAccess48LightSvg from './Res_Amazon-Elastic-File-System_One-Zone-Infrequent-Access_48_Light.svg';
import _resAmazonElasticFileSystemOneZone48LightSvg from './Res_Amazon-Elastic-File-System_One-Zone_48_Light.svg';
import _resAmazonElasticFileSystemStandardInfrequentAccess48LightSvg from './Res_Amazon-Elastic-File-System_Standard-Infrequent-Access_48_Light.svg';
import _resAmazonElasticFileSystemStandard48LightSvg from './Res_Amazon-Elastic-File-System_Standard_48_Light.svg';
import _resAmazonSimpleStorageServiceGlacierArchive48LightSvg from './Res_Amazon-Simple-Storage-Service-Glacier_Archive_48_Light.svg';
import _resAmazonSimpleStorageServiceGlacierVault48LightSvg from './Res_Amazon-Simple-Storage-Service-Glacier_Vault_48_Light.svg';
import _resAmazonSimpleStorageServiceBucketWithObjects48LightSvg from './Res_Amazon-Simple-Storage-Service_Bucket-With-Objects_48_Light.svg';
import _resAmazonSimpleStorageServiceBucket48LightSvg from './Res_Amazon-Simple-Storage-Service_Bucket_48_Light.svg';
import _resAmazonSimpleStorageServiceGeneralAccessPoints48LightSvg from './Res_Amazon-Simple-Storage-Service_General-Access-Points_48_Light.svg';
import _resAmazonSimpleStorageServiceObject48LightSvg from './Res_Amazon-Simple-Storage-Service_Object_48_Light.svg';
import _resAmazonSimpleStorageServiceS3GlacierDeepArchive48LightSvg from './Res_Amazon-Simple-Storage-Service_S3-Glacier-Deep-Archive_48_Light.svg';
import _resAmazonSimpleStorageServiceS3GlacierFlexibleRetrieval48LightSvg from './Res_Amazon-Simple-Storage-Service_S3-Glacier-Flexible-Retrieval_48_Light.svg';
import _resAmazonSimpleStorageServiceS3GlacierInstantRetrieval48LightSvg from './Res_Amazon-Simple-Storage-Service_S3-Glacier-Instant-Retrieval_48_Light.svg';
import _resAmazonSimpleStorageServiceS3IntelligentTiering48LightSvg from './Res_Amazon-Simple-Storage-Service_S3-Intelligent-Tiering_48_Light.svg';
import _resAmazonSimpleStorageServiceS3ObjectLambdaAccessPoints48LightSvg from './Res_Amazon-Simple-Storage-Service_S3-Object-Lambda-Access-Points_48_Light.svg';
import _resAmazonSimpleStorageServiceS3ObjectLambda48LightSvg from './Res_Amazon-Simple-Storage-Service_S3-Object-Lambda_48_Light.svg';
import _resAmazonSimpleStorageServiceS3OnOutposts48LightSvg from './Res_Amazon-Simple-Storage-Service_S3-On-Outposts_48_Light.svg';
import _resAmazonSimpleStorageServiceS3OneZoneIa48LightSvg from './Res_Amazon-Simple-Storage-Service_S3-One-Zone-IA_48_Light.svg';
import _resAmazonSimpleStorageServiceS3ReplicationTimeControl48LightSvg from './Res_Amazon-Simple-Storage-Service_S3-Replication-Time-Control_48_Light.svg';
import _resAmazonSimpleStorageServiceS3Replication48LightSvg from './Res_Amazon-Simple-Storage-Service_S3-Replication_48_Light.svg';
import _resAmazonSimpleStorageServiceS3StandardIa48LightSvg from './Res_Amazon-Simple-Storage-Service_S3-Standard-IA_48_Light.svg';
import _resAmazonSimpleStorageServiceS3Standard48LightSvg from './Res_Amazon-Simple-Storage-Service_S3-Standard_48_Light.svg';
import _resAmazonSimpleStorageServiceS3StorageLens48LightSvg from './Res_Amazon-Simple-Storage-Service_S3-Storage-Lens_48_Light.svg';
import _resAmazonSimpleStorageServiceVpcAccessPoints48LightSvg from './Res_Amazon-Simple-Storage-Service_VPC-Access-Points_48_Light.svg';

export const resAwsBackupAwsBackupSupportForAmazonFsxForNetAppOntap48LightSvg = { id: "resAwsBackupAwsBackupSupportForAmazonFsxForNetAppOntap48LightSvg", name: "AWS Backup | AWS Backup support for Amazon FSx for NetApp ONTAP", icon: _resAwsBackupAwsBackupSupportForAmazonFsxForNetAppOntap48LightSvg };
export const resAwsBackupAwsBackupSupportForAmazonS348LightSvg = { id: "resAwsBackupAwsBackupSupportForAmazonS348LightSvg", name: "AWS Backup | AWS Backup support for Amazon S3", icon: _resAwsBackupAwsBackupSupportForAmazonS348LightSvg };
export const resAwsBackupAwsBackupSupportForVmwareWorkloads48LightSvg = { id: "resAwsBackupAwsBackupSupportForVmwareWorkloads48LightSvg", name: "AWS Backup | AWS Backup support for VMware Workloads", icon: _resAwsBackupAwsBackupSupportForVmwareWorkloads48LightSvg };
export const resAwsBackupBackupPlan48LightSvg = { id: "resAwsBackupBackupPlan48LightSvg", name: "AWS Backup | Backup Plan", icon: _resAwsBackupBackupPlan48LightSvg };
export const resAwsBackupBackupRestore48LightSvg = { id: "resAwsBackupBackupRestore48LightSvg", name: "AWS Backup | Backup Restore", icon: _resAwsBackupBackupRestore48LightSvg };
export const resAwsBackupBackupVault48LightSvg = { id: "resAwsBackupBackupVault48LightSvg", name: "AWS Backup | Backup Vault", icon: _resAwsBackupBackupVault48LightSvg };
export const resAwsBackupComplianceReporting48LightSvg = { id: "resAwsBackupComplianceReporting48LightSvg", name: "AWS Backup | Compliance Reporting", icon: _resAwsBackupComplianceReporting48LightSvg };
export const resAwsBackupCompute48LightSvg = { id: "resAwsBackupCompute48LightSvg", name: "AWS Backup | Compute", icon: _resAwsBackupCompute48LightSvg };
export const resAwsBackupDatabase48LightSvg = { id: "resAwsBackupDatabase48LightSvg", name: "AWS Backup | Database", icon: _resAwsBackupDatabase48LightSvg };
export const resAwsBackupGateway48LightSvg = { id: "resAwsBackupGateway48LightSvg", name: "AWS Backup | Gateway", icon: _resAwsBackupGateway48LightSvg };
export const resAwsBackupRecoveryPointObjective48LightSvg = { id: "resAwsBackupRecoveryPointObjective48LightSvg", name: "AWS Backup | Recovery Point Objective", icon: _resAwsBackupRecoveryPointObjective48LightSvg };
export const resAwsBackupRecoveryTimeObjective48LightSvg = { id: "resAwsBackupRecoveryTimeObjective48LightSvg", name: "AWS Backup | Recovery Time Objective", icon: _resAwsBackupRecoveryTimeObjective48LightSvg };
export const resAwsBackupStorage48LightSvg = { id: "resAwsBackupStorage48LightSvg", name: "AWS Backup | Storage", icon: _resAwsBackupStorage48LightSvg };
export const resAwsBackupVirtualMachineMonitor48LightSvg = { id: "resAwsBackupVirtualMachineMonitor48LightSvg", name: "AWS Backup | Virtual Machine Monitor", icon: _resAwsBackupVirtualMachineMonitor48LightSvg };
export const resAwsBackupVirtualMachine48LightSvg = { id: "resAwsBackupVirtualMachine48LightSvg", name: "AWS Backup | Virtual Machine", icon: _resAwsBackupVirtualMachine48LightSvg };
export const resAwsSnowballSnowballImportExport48LightSvg = { id: "resAwsSnowballSnowballImportExport48LightSvg", name: "AWS Snowball | Snowball Import Export", icon: _resAwsSnowballSnowballImportExport48LightSvg };
export const resAwsStorageGatewayAmazonFsxFileGateway48LightSvg = { id: "resAwsStorageGatewayAmazonFsxFileGateway48LightSvg", name: "AWS Storage Gateway | Amazon FSx File Gateway", icon: _resAwsStorageGatewayAmazonFsxFileGateway48LightSvg };
export const resAwsStorageGatewayAmazonS3FileGateway48LightSvg = { id: "resAwsStorageGatewayAmazonS3FileGateway48LightSvg", name: "AWS Storage Gateway | Amazon S3 File Gateway", icon: _resAwsStorageGatewayAmazonS3FileGateway48LightSvg };
export const resAwsStorageGatewayCachedVolume48LightSvg = { id: "resAwsStorageGatewayCachedVolume48LightSvg", name: "AWS Storage Gateway | Cached Volume", icon: _resAwsStorageGatewayCachedVolume48LightSvg };
export const resAwsStorageGatewayFileGateway48LightSvg = { id: "resAwsStorageGatewayFileGateway48LightSvg", name: "AWS Storage Gateway | File Gateway", icon: _resAwsStorageGatewayFileGateway48LightSvg };
export const resAwsStorageGatewayNoncachedVolume48LightSvg = { id: "resAwsStorageGatewayNoncachedVolume48LightSvg", name: "AWS Storage Gateway | Noncached Volume", icon: _resAwsStorageGatewayNoncachedVolume48LightSvg };
export const resAwsStorageGatewayTapeGateway48LightSvg = { id: "resAwsStorageGatewayTapeGateway48LightSvg", name: "AWS Storage Gateway | Tape Gateway", icon: _resAwsStorageGatewayTapeGateway48LightSvg };
export const resAwsStorageGatewayVirtualTapeLibrary48LightSvg = { id: "resAwsStorageGatewayVirtualTapeLibrary48LightSvg", name: "AWS Storage Gateway | Virtual Tape Library", icon: _resAwsStorageGatewayVirtualTapeLibrary48LightSvg };
export const resAwsStorageGatewayVolumeGateway48LightSvg = { id: "resAwsStorageGatewayVolumeGateway48LightSvg", name: "AWS Storage Gateway | Volume Gateway", icon: _resAwsStorageGatewayVolumeGateway48LightSvg };
export const resAmazonElasticBlockStoreAmazonDataLifecycleManager48LightSvg = { id: "resAmazonElasticBlockStoreAmazonDataLifecycleManager48LightSvg", name: "Amazon Elastic Block Store | Amazon Data Lifecycle Manager", icon: _resAmazonElasticBlockStoreAmazonDataLifecycleManager48LightSvg };
export const resAmazonElasticBlockStoreMultipleVolumes48LightSvg = { id: "resAmazonElasticBlockStoreMultipleVolumes48LightSvg", name: "Amazon Elastic Block Store | Multiple Volumes", icon: _resAmazonElasticBlockStoreMultipleVolumes48LightSvg };
export const resAmazonElasticBlockStoreSnapshot48LightSvg = { id: "resAmazonElasticBlockStoreSnapshot48LightSvg", name: "Amazon Elastic Block Store | Snapshot", icon: _resAmazonElasticBlockStoreSnapshot48LightSvg };
export const resAmazonElasticBlockStoreVolumeGp348LightSvg = { id: "resAmazonElasticBlockStoreVolumeGp348LightSvg", name: "Amazon Elastic Block Store | Volume gp3", icon: _resAmazonElasticBlockStoreVolumeGp348LightSvg };
export const resAmazonElasticBlockStoreVolume48LightSvg = { id: "resAmazonElasticBlockStoreVolume48LightSvg", name: "Amazon Elastic Block Store | Volume", icon: _resAmazonElasticBlockStoreVolume48LightSvg };
export const resAmazonElasticFileSystemFileSystem48LightSvg = { id: "resAmazonElasticFileSystemFileSystem48LightSvg", name: "Amazon Elastic File System | File System", icon: _resAmazonElasticFileSystemFileSystem48LightSvg };
export const resAmazonElasticFileSystemIntelligentTiering48LightSvg = { id: "resAmazonElasticFileSystemIntelligentTiering48LightSvg", name: "Amazon Elastic File System | Intelligent Tiering", icon: _resAmazonElasticFileSystemIntelligentTiering48LightSvg };
export const resAmazonElasticFileSystemOneZoneInfrequentAccess48LightSvg = { id: "resAmazonElasticFileSystemOneZoneInfrequentAccess48LightSvg", name: "Amazon Elastic File System | One Zone Infrequent Access", icon: _resAmazonElasticFileSystemOneZoneInfrequentAccess48LightSvg };
export const resAmazonElasticFileSystemOneZone48LightSvg = { id: "resAmazonElasticFileSystemOneZone48LightSvg", name: "Amazon Elastic File System | One Zone", icon: _resAmazonElasticFileSystemOneZone48LightSvg };
export const resAmazonElasticFileSystemStandardInfrequentAccess48LightSvg = { id: "resAmazonElasticFileSystemStandardInfrequentAccess48LightSvg", name: "Amazon Elastic File System | Standard Infrequent Access", icon: _resAmazonElasticFileSystemStandardInfrequentAccess48LightSvg };
export const resAmazonElasticFileSystemStandard48LightSvg = { id: "resAmazonElasticFileSystemStandard48LightSvg", name: "Amazon Elastic File System | Standard", icon: _resAmazonElasticFileSystemStandard48LightSvg };
export const resAmazonSimpleStorageServiceGlacierArchive48LightSvg = { id: "resAmazonSimpleStorageServiceGlacierArchive48LightSvg", name: "Amazon Simple Storage Service Glacier | Archive", icon: _resAmazonSimpleStorageServiceGlacierArchive48LightSvg };
export const resAmazonSimpleStorageServiceGlacierVault48LightSvg = { id: "resAmazonSimpleStorageServiceGlacierVault48LightSvg", name: "Amazon Simple Storage Service Glacier | Vault", icon: _resAmazonSimpleStorageServiceGlacierVault48LightSvg };
export const resAmazonSimpleStorageServiceBucketWithObjects48LightSvg = { id: "resAmazonSimpleStorageServiceBucketWithObjects48LightSvg", name: "Amazon Simple Storage Service | Bucket With Objects", icon: _resAmazonSimpleStorageServiceBucketWithObjects48LightSvg };
export const resAmazonSimpleStorageServiceBucket48LightSvg = { id: "resAmazonSimpleStorageServiceBucket48LightSvg", name: "Amazon Simple Storage Service | Bucket", icon: _resAmazonSimpleStorageServiceBucket48LightSvg };
export const resAmazonSimpleStorageServiceGeneralAccessPoints48LightSvg = { id: "resAmazonSimpleStorageServiceGeneralAccessPoints48LightSvg", name: "Amazon Simple Storage Service | General Access Points", icon: _resAmazonSimpleStorageServiceGeneralAccessPoints48LightSvg };
export const resAmazonSimpleStorageServiceObject48LightSvg = { id: "resAmazonSimpleStorageServiceObject48LightSvg", name: "Amazon Simple Storage Service | Object", icon: _resAmazonSimpleStorageServiceObject48LightSvg };
export const resAmazonSimpleStorageServiceS3GlacierDeepArchive48LightSvg = { id: "resAmazonSimpleStorageServiceS3GlacierDeepArchive48LightSvg", name: "Amazon Simple Storage Service | S3 Glacier Deep Archive", icon: _resAmazonSimpleStorageServiceS3GlacierDeepArchive48LightSvg };
export const resAmazonSimpleStorageServiceS3GlacierFlexibleRetrieval48LightSvg = { id: "resAmazonSimpleStorageServiceS3GlacierFlexibleRetrieval48LightSvg", name: "Amazon Simple Storage Service | S3 Glacier Flexible Retrieval", icon: _resAmazonSimpleStorageServiceS3GlacierFlexibleRetrieval48LightSvg };
export const resAmazonSimpleStorageServiceS3GlacierInstantRetrieval48LightSvg = { id: "resAmazonSimpleStorageServiceS3GlacierInstantRetrieval48LightSvg", name: "Amazon Simple Storage Service | S3 Glacier Instant Retrieval", icon: _resAmazonSimpleStorageServiceS3GlacierInstantRetrieval48LightSvg };
export const resAmazonSimpleStorageServiceS3IntelligentTiering48LightSvg = { id: "resAmazonSimpleStorageServiceS3IntelligentTiering48LightSvg", name: "Amazon Simple Storage Service | S3 Intelligent Tiering", icon: _resAmazonSimpleStorageServiceS3IntelligentTiering48LightSvg };
export const resAmazonSimpleStorageServiceS3ObjectLambdaAccessPoints48LightSvg = { id: "resAmazonSimpleStorageServiceS3ObjectLambdaAccessPoints48LightSvg", name: "Amazon Simple Storage Service | S3 Object Lambda Access Points", icon: _resAmazonSimpleStorageServiceS3ObjectLambdaAccessPoints48LightSvg };
export const resAmazonSimpleStorageServiceS3ObjectLambda48LightSvg = { id: "resAmazonSimpleStorageServiceS3ObjectLambda48LightSvg", name: "Amazon Simple Storage Service | S3 Object Lambda", icon: _resAmazonSimpleStorageServiceS3ObjectLambda48LightSvg };
export const resAmazonSimpleStorageServiceS3OnOutposts48LightSvg = { id: "resAmazonSimpleStorageServiceS3OnOutposts48LightSvg", name: "Amazon Simple Storage Service | S3 On Outposts", icon: _resAmazonSimpleStorageServiceS3OnOutposts48LightSvg };
export const resAmazonSimpleStorageServiceS3OneZoneIa48LightSvg = { id: "resAmazonSimpleStorageServiceS3OneZoneIa48LightSvg", name: "Amazon Simple Storage Service | S3 One Zone IA", icon: _resAmazonSimpleStorageServiceS3OneZoneIa48LightSvg };
export const resAmazonSimpleStorageServiceS3ReplicationTimeControl48LightSvg = { id: "resAmazonSimpleStorageServiceS3ReplicationTimeControl48LightSvg", name: "Amazon Simple Storage Service | S3 Replication Time Control", icon: _resAmazonSimpleStorageServiceS3ReplicationTimeControl48LightSvg };
export const resAmazonSimpleStorageServiceS3Replication48LightSvg = { id: "resAmazonSimpleStorageServiceS3Replication48LightSvg", name: "Amazon Simple Storage Service | S3 Replication", icon: _resAmazonSimpleStorageServiceS3Replication48LightSvg };
export const resAmazonSimpleStorageServiceS3StandardIa48LightSvg = { id: "resAmazonSimpleStorageServiceS3StandardIa48LightSvg", name: "Amazon Simple Storage Service | S3 Standard IA", icon: _resAmazonSimpleStorageServiceS3StandardIa48LightSvg };
export const resAmazonSimpleStorageServiceS3Standard48LightSvg = { id: "resAmazonSimpleStorageServiceS3Standard48LightSvg", name: "Amazon Simple Storage Service | S3 Standard", icon: _resAmazonSimpleStorageServiceS3Standard48LightSvg };
export const resAmazonSimpleStorageServiceS3StorageLens48LightSvg = { id: "resAmazonSimpleStorageServiceS3StorageLens48LightSvg", name: "Amazon Simple Storage Service | S3 Storage Lens", icon: _resAmazonSimpleStorageServiceS3StorageLens48LightSvg };
export const resAmazonSimpleStorageServiceVpcAccessPoints48LightSvg = { id: "resAmazonSimpleStorageServiceVpcAccessPoints48LightSvg", name: "Amazon Simple Storage Service | VPC Access Points", icon: _resAmazonSimpleStorageServiceVpcAccessPoints48LightSvg };
