import _archCategoryAnalytics16Svg from './Arch-Category_Analytics_16.svg';
import _archCategoryApplicationIntegration16Svg from './Arch-Category_Application-Integration_16.svg';
import _archCategoryBlockchain16Svg from './Arch-Category_Blockchain_16.svg';
import _archCategoryBusinessApplications16Svg from './Arch-Category_Business-Applications_16.svg';
import _archCategoryCloudFinancialManagement16Svg from './Arch-Category_Cloud-Financial-Management_16.svg';
import _archCategoryCompute16Svg from './Arch-Category_Compute_16.svg';
import _archCategoryContainers16Svg from './Arch-Category_Containers_16.svg';
import _archCategoryCustomerEnablement16Svg from './Arch-Category_Customer-Enablement_16.svg';
import _archCategoryDatabase16Svg from './Arch-Category_Database_16.svg';
import _archCategoryDeveloperTools16Svg from './Arch-Category_Developer-Tools_16.svg';
import _archCategoryEndUserComputing16Svg from './Arch-Category_End-User-Computing_16.svg';
import _archCategoryFrontEndWebMobile16Svg from './Arch-Category_Front-End-Web-Mobile_16.svg';
import _archCategoryGameTech16Svg from './Arch-Category_Game-Tech_16.svg';
import _archCategoryInternetOfThings16Svg from './Arch-Category_Internet-of-Things_16.svg';
import _archCategoryMachineLearning16Svg from './Arch-Category_Machine-Learning_16.svg';
import _archCategoryManagementGovernance16Svg from './Arch-Category_Management-Governance_16.svg';
import _archCategoryMediaServices16Svg from './Arch-Category_Media-Services_16.svg';
import _archCategoryMigrationTransfer16Svg from './Arch-Category_Migration-Transfer_16.svg';
import _archCategoryNetworkingContentDelivery16Svg from './Arch-Category_Networking-Content-Delivery_16.svg';
import _archCategoryQuantumTechnologies16Svg from './Arch-Category_Quantum-Technologies_16.svg';
import _archCategoryRobotics16Svg from './Arch-Category_Robotics_16.svg';
import _archCategorySatellite16Svg from './Arch-Category_Satellite_16.svg';
import _archCategorySecurityIdentityCompliance16Svg from './Arch-Category_Security-Identity-Compliance_16.svg';
import _archCategoryServerless16Svg from './Arch-Category_Serverless_16.svg';
import _archCategoryStorage16Svg from './Arch-Category_Storage_16.svg';
import _archCategoryVrAr16Svg from './Arch-Category_VR-AR_16.svg';

export const archCategoryAnalytics16Svg = { id: "archCategoryAnalytics16Svg", name: "Analytics", icon: _archCategoryAnalytics16Svg };
export const archCategoryApplicationIntegration16Svg = { id: "archCategoryApplicationIntegration16Svg", name: "Application Integration", icon: _archCategoryApplicationIntegration16Svg };
export const archCategoryBlockchain16Svg = { id: "archCategoryBlockchain16Svg", name: "Blockchain", icon: _archCategoryBlockchain16Svg };
export const archCategoryBusinessApplications16Svg = { id: "archCategoryBusinessApplications16Svg", name: "Business Applications", icon: _archCategoryBusinessApplications16Svg };
export const archCategoryCloudFinancialManagement16Svg = { id: "archCategoryCloudFinancialManagement16Svg", name: "Cloud Financial Management", icon: _archCategoryCloudFinancialManagement16Svg };
export const archCategoryCompute16Svg = { id: "archCategoryCompute16Svg", name: "Compute", icon: _archCategoryCompute16Svg };
export const archCategoryContainers16Svg = { id: "archCategoryContainers16Svg", name: "Containers", icon: _archCategoryContainers16Svg };
export const archCategoryCustomerEnablement16Svg = { id: "archCategoryCustomerEnablement16Svg", name: "Customer Enablement", icon: _archCategoryCustomerEnablement16Svg };
export const archCategoryDatabase16Svg = { id: "archCategoryDatabase16Svg", name: "Database", icon: _archCategoryDatabase16Svg };
export const archCategoryDeveloperTools16Svg = { id: "archCategoryDeveloperTools16Svg", name: "Developer Tools", icon: _archCategoryDeveloperTools16Svg };
export const archCategoryEndUserComputing16Svg = { id: "archCategoryEndUserComputing16Svg", name: "End User Computing", icon: _archCategoryEndUserComputing16Svg };
export const archCategoryFrontEndWebMobile16Svg = { id: "archCategoryFrontEndWebMobile16Svg", name: "Front End Web Mobile", icon: _archCategoryFrontEndWebMobile16Svg };
export const archCategoryGameTech16Svg = { id: "archCategoryGameTech16Svg", name: "Game Tech", icon: _archCategoryGameTech16Svg };
export const archCategoryInternetOfThings16Svg = { id: "archCategoryInternetOfThings16Svg", name: "Internet of Things", icon: _archCategoryInternetOfThings16Svg };
export const archCategoryMachineLearning16Svg = { id: "archCategoryMachineLearning16Svg", name: "Machine Learning", icon: _archCategoryMachineLearning16Svg };
export const archCategoryManagementGovernance16Svg = { id: "archCategoryManagementGovernance16Svg", name: "Management Governance", icon: _archCategoryManagementGovernance16Svg };
export const archCategoryMediaServices16Svg = { id: "archCategoryMediaServices16Svg", name: "Media Services", icon: _archCategoryMediaServices16Svg };
export const archCategoryMigrationTransfer16Svg = { id: "archCategoryMigrationTransfer16Svg", name: "Migration Transfer", icon: _archCategoryMigrationTransfer16Svg };
export const archCategoryNetworkingContentDelivery16Svg = { id: "archCategoryNetworkingContentDelivery16Svg", name: "Networking Content Delivery", icon: _archCategoryNetworkingContentDelivery16Svg };
export const archCategoryQuantumTechnologies16Svg = { id: "archCategoryQuantumTechnologies16Svg", name: "Quantum Technologies", icon: _archCategoryQuantumTechnologies16Svg };
export const archCategoryRobotics16Svg = { id: "archCategoryRobotics16Svg", name: "Robotics", icon: _archCategoryRobotics16Svg };
export const archCategorySatellite16Svg = { id: "archCategorySatellite16Svg", name: "Satellite", icon: _archCategorySatellite16Svg };
export const archCategorySecurityIdentityCompliance16Svg = { id: "archCategorySecurityIdentityCompliance16Svg", name: "Security Identity Compliance", icon: _archCategorySecurityIdentityCompliance16Svg };
export const archCategoryServerless16Svg = { id: "archCategoryServerless16Svg", name: "Serverless", icon: _archCategoryServerless16Svg };
export const archCategoryStorage16Svg = { id: "archCategoryStorage16Svg", name: "Storage", icon: _archCategoryStorage16Svg };
export const archCategoryVrAr16Svg = { id: "archCategoryVrAr16Svg", name: "VR AR", icon: _archCategoryVrAr16Svg };
