import _archAwsDeepLearningAmIs48Svg from './Arch_AWS-Deep-Learning-AMIs_48.svg';
import _archAwsDeepLearningContainers48Svg from './Arch_AWS-Deep-Learning-Containers_48.svg';
import _archAwsDeepComposer48Svg from './Arch_AWS-DeepComposer_48.svg';
import _archAwsDeepLens48Svg from './Arch_AWS-DeepLens_48.svg';
import _archAwsDeepRacer48Svg from './Arch_AWS-DeepRacer_48.svg';
import _archAwsNeuron48Svg from './Arch_AWS-Neuron_48.svg';
import _archAwsPanorama48Svg from './Arch_AWS-Panorama_48.svg';
import _archAmazonAugmentedAiA2I48Svg from './Arch_Amazon-Augmented-AI-A2I_48.svg';
import _archAmazonCodeGuru48Svg from './Arch_Amazon-CodeGuru_48.svg';
import _archAmazonCodeWhisperer48Svg from './Arch_Amazon-CodeWhisperer_48.svg';
import _archAmazonComprehendMedical48Svg from './Arch_Amazon-Comprehend-Medical_48.svg';
import _archAmazonComprehend48Svg from './Arch_Amazon-Comprehend_48.svg';
import _archAmazonDevOpsGuru48Svg from './Arch_Amazon-DevOps-Guru_48.svg';
import _archAmazonElasticInference48Svg from './Arch_Amazon-Elastic-Inference_48.svg';
import _archAmazonForecast48Svg from './Arch_Amazon-Forecast_48.svg';
import _archAmazonFraudDetector48Svg from './Arch_Amazon-Fraud-Detector_48.svg';
import _archAmazonHealthLake48Svg from './Arch_Amazon-HealthLake_48.svg';
import _archAmazonKendra48Svg from './Arch_Amazon-Kendra_48.svg';
import _archAmazonLex48Svg from './Arch_Amazon-Lex_48.svg';
import _archAmazonLookoutForEquipment48Svg from './Arch_Amazon-Lookout-for-Equipment_48.svg';
import _archAmazonLookoutForMetrics48Svg from './Arch_Amazon-Lookout-for-Metrics_48.svg';
import _archAmazonLookoutForVision48Svg from './Arch_Amazon-Lookout-for-Vision_48.svg';
import _archAmazonMonitron48Svg from './Arch_Amazon-Monitron_48.svg';
import _archAmazonPersonalize48Svg from './Arch_Amazon-Personalize_48.svg';
import _archAmazonPolly48Svg from './Arch_Amazon-Polly_48.svg';
import _archAmazonRekognition48Svg from './Arch_Amazon-Rekognition_48.svg';
import _archAmazonSageMakerGroundTruth48Svg from './Arch_Amazon-SageMaker-Ground-Truth_48.svg';
import _archAmazonSageMakerStudioLab48Svg from './Arch_Amazon-SageMaker-Studio-Lab_48.svg';
import _archAmazonSageMaker48Svg from './Arch_Amazon-SageMaker_48.svg';
import _archAmazonTextract48Svg from './Arch_Amazon-Textract_48.svg';
import _archAmazonTranscribe48Svg from './Arch_Amazon-Transcribe_48.svg';
import _archAmazonTranslate48Svg from './Arch_Amazon-Translate_48.svg';
import _archApacheMxNetOnAws48Svg from './Arch_Apache-MXNet-on-AWS_48.svg';
import _archTensorFlowOnAws48Svg from './Arch_TensorFlow-on-AWS_48.svg';
import _archTorchServe48Svg from './Arch_TorchServe_48.svg';

export const archAwsDeepLearningAmIs48Svg = { id: "archAwsDeepLearningAmIs48Svg", name: "AWS Deep Learning AMIs", icon: _archAwsDeepLearningAmIs48Svg };
export const archAwsDeepLearningContainers48Svg = { id: "archAwsDeepLearningContainers48Svg", name: "AWS Deep Learning Containers", icon: _archAwsDeepLearningContainers48Svg };
export const archAwsDeepComposer48Svg = { id: "archAwsDeepComposer48Svg", name: "AWS DeepComposer", icon: _archAwsDeepComposer48Svg };
export const archAwsDeepLens48Svg = { id: "archAwsDeepLens48Svg", name: "AWS DeepLens", icon: _archAwsDeepLens48Svg };
export const archAwsDeepRacer48Svg = { id: "archAwsDeepRacer48Svg", name: "AWS DeepRacer", icon: _archAwsDeepRacer48Svg };
export const archAwsNeuron48Svg = { id: "archAwsNeuron48Svg", name: "AWS Neuron", icon: _archAwsNeuron48Svg };
export const archAwsPanorama48Svg = { id: "archAwsPanorama48Svg", name: "AWS Panorama", icon: _archAwsPanorama48Svg };
export const archAmazonAugmentedAiA2I48Svg = { id: "archAmazonAugmentedAiA2I48Svg", name: "Amazon Augmented AI A2I", icon: _archAmazonAugmentedAiA2I48Svg };
export const archAmazonCodeGuru48Svg = { id: "archAmazonCodeGuru48Svg", name: "Amazon CodeGuru", icon: _archAmazonCodeGuru48Svg };
export const archAmazonCodeWhisperer48Svg = { id: "archAmazonCodeWhisperer48Svg", name: "Amazon CodeWhisperer", icon: _archAmazonCodeWhisperer48Svg };
export const archAmazonComprehendMedical48Svg = { id: "archAmazonComprehendMedical48Svg", name: "Amazon Comprehend Medical", icon: _archAmazonComprehendMedical48Svg };
export const archAmazonComprehend48Svg = { id: "archAmazonComprehend48Svg", name: "Amazon Comprehend", icon: _archAmazonComprehend48Svg };
export const archAmazonDevOpsGuru48Svg = { id: "archAmazonDevOpsGuru48Svg", name: "Amazon DevOps Guru", icon: _archAmazonDevOpsGuru48Svg };
export const archAmazonElasticInference48Svg = { id: "archAmazonElasticInference48Svg", name: "Amazon Elastic Inference", icon: _archAmazonElasticInference48Svg };
export const archAmazonForecast48Svg = { id: "archAmazonForecast48Svg", name: "Amazon Forecast", icon: _archAmazonForecast48Svg };
export const archAmazonFraudDetector48Svg = { id: "archAmazonFraudDetector48Svg", name: "Amazon Fraud Detector", icon: _archAmazonFraudDetector48Svg };
export const archAmazonHealthLake48Svg = { id: "archAmazonHealthLake48Svg", name: "Amazon HealthLake", icon: _archAmazonHealthLake48Svg };
export const archAmazonKendra48Svg = { id: "archAmazonKendra48Svg", name: "Amazon Kendra", icon: _archAmazonKendra48Svg };
export const archAmazonLex48Svg = { id: "archAmazonLex48Svg", name: "Amazon Lex", icon: _archAmazonLex48Svg };
export const archAmazonLookoutForEquipment48Svg = { id: "archAmazonLookoutForEquipment48Svg", name: "Amazon Lookout for Equipment", icon: _archAmazonLookoutForEquipment48Svg };
export const archAmazonLookoutForMetrics48Svg = { id: "archAmazonLookoutForMetrics48Svg", name: "Amazon Lookout for Metrics", icon: _archAmazonLookoutForMetrics48Svg };
export const archAmazonLookoutForVision48Svg = { id: "archAmazonLookoutForVision48Svg", name: "Amazon Lookout for Vision", icon: _archAmazonLookoutForVision48Svg };
export const archAmazonMonitron48Svg = { id: "archAmazonMonitron48Svg", name: "Amazon Monitron", icon: _archAmazonMonitron48Svg };
export const archAmazonPersonalize48Svg = { id: "archAmazonPersonalize48Svg", name: "Amazon Personalize", icon: _archAmazonPersonalize48Svg };
export const archAmazonPolly48Svg = { id: "archAmazonPolly48Svg", name: "Amazon Polly", icon: _archAmazonPolly48Svg };
export const archAmazonRekognition48Svg = { id: "archAmazonRekognition48Svg", name: "Amazon Rekognition", icon: _archAmazonRekognition48Svg };
export const archAmazonSageMakerGroundTruth48Svg = { id: "archAmazonSageMakerGroundTruth48Svg", name: "Amazon SageMaker Ground Truth", icon: _archAmazonSageMakerGroundTruth48Svg };
export const archAmazonSageMakerStudioLab48Svg = { id: "archAmazonSageMakerStudioLab48Svg", name: "Amazon SageMaker Studio Lab", icon: _archAmazonSageMakerStudioLab48Svg };
export const archAmazonSageMaker48Svg = { id: "archAmazonSageMaker48Svg", name: "Amazon SageMaker", icon: _archAmazonSageMaker48Svg };
export const archAmazonTextract48Svg = { id: "archAmazonTextract48Svg", name: "Amazon Textract", icon: _archAmazonTextract48Svg };
export const archAmazonTranscribe48Svg = { id: "archAmazonTranscribe48Svg", name: "Amazon Transcribe", icon: _archAmazonTranscribe48Svg };
export const archAmazonTranslate48Svg = { id: "archAmazonTranslate48Svg", name: "Amazon Translate", icon: _archAmazonTranslate48Svg };
export const archApacheMxNetOnAws48Svg = { id: "archApacheMxNetOnAws48Svg", name: "Apache MXNet on AWS", icon: _archApacheMxNetOnAws48Svg };
export const archTensorFlowOnAws48Svg = { id: "archTensorFlowOnAws48Svg", name: "TensorFlow on AWS", icon: _archTensorFlowOnAws48Svg };
export const archTorchServe48Svg = { id: "archTorchServe48Svg", name: "TorchServe", icon: _archTorchServe48Svg };
