import _archAwsCloudControlApi48Svg from './Arch_AWS-Cloud-Control-API_48.svg';
import _archAwsCloudDevelopmentKit48Svg from './Arch_AWS-Cloud-Development-Kit_48.svg';
import _archAwsCloud948Svg from './Arch_AWS-Cloud9_48.svg';
import _archAwsCloudShell48Svg from './Arch_AWS-CloudShell_48.svg';
import _archAwsCodeArtifact48Svg from './Arch_AWS-CodeArtifact_48.svg';
import _archAwsCodeBuild48Svg from './Arch_AWS-CodeBuild_48.svg';
import _archAwsCodeCommit48Svg from './Arch_AWS-CodeCommit_48.svg';
import _archAwsCodeDeploy48Svg from './Arch_AWS-CodeDeploy_48.svg';
import _archAwsCodePipeline48Svg from './Arch_AWS-CodePipeline_48.svg';
import _archAwsCodeStar48Svg from './Arch_AWS-CodeStar_48.svg';
import _archAwsCommandLineInterface48Svg from './Arch_AWS-Command-Line-Interface_48.svg';
import _archAwsToolsAndSdKs48Svg from './Arch_AWS-Tools-and-SDKs_48.svg';
import _archAwsXRay48Svg from './Arch_AWS-X-Ray_48.svg';
import _archAmazonCorretto48Svg from './Arch_Amazon-Corretto_48.svg';

export const archAwsCloudControlApi48Svg = { id: "archAwsCloudControlApi48Svg", name: "AWS Cloud Control API", icon: _archAwsCloudControlApi48Svg };
export const archAwsCloudDevelopmentKit48Svg = { id: "archAwsCloudDevelopmentKit48Svg", name: "AWS Cloud Development Kit", icon: _archAwsCloudDevelopmentKit48Svg };
export const archAwsCloud948Svg = { id: "archAwsCloud948Svg", name: "AWS Cloud9", icon: _archAwsCloud948Svg };
export const archAwsCloudShell48Svg = { id: "archAwsCloudShell48Svg", name: "AWS CloudShell", icon: _archAwsCloudShell48Svg };
export const archAwsCodeArtifact48Svg = { id: "archAwsCodeArtifact48Svg", name: "AWS CodeArtifact", icon: _archAwsCodeArtifact48Svg };
export const archAwsCodeBuild48Svg = { id: "archAwsCodeBuild48Svg", name: "AWS CodeBuild", icon: _archAwsCodeBuild48Svg };
export const archAwsCodeCommit48Svg = { id: "archAwsCodeCommit48Svg", name: "AWS CodeCommit", icon: _archAwsCodeCommit48Svg };
export const archAwsCodeDeploy48Svg = { id: "archAwsCodeDeploy48Svg", name: "AWS CodeDeploy", icon: _archAwsCodeDeploy48Svg };
export const archAwsCodePipeline48Svg = { id: "archAwsCodePipeline48Svg", name: "AWS CodePipeline", icon: _archAwsCodePipeline48Svg };
export const archAwsCodeStar48Svg = { id: "archAwsCodeStar48Svg", name: "AWS CodeStar", icon: _archAwsCodeStar48Svg };
export const archAwsCommandLineInterface48Svg = { id: "archAwsCommandLineInterface48Svg", name: "AWS Command Line Interface", icon: _archAwsCommandLineInterface48Svg };
export const archAwsToolsAndSdKs48Svg = { id: "archAwsToolsAndSdKs48Svg", name: "AWS Tools and SDKs", icon: _archAwsToolsAndSdKs48Svg };
export const archAwsXRay48Svg = { id: "archAwsXRay48Svg", name: "AWS X Ray", icon: _archAwsXRay48Svg };
export const archAmazonCorretto48Svg = { id: "archAmazonCorretto48Svg", name: "Amazon Corretto", icon: _archAmazonCorretto48Svg };
