import _resAwsElasticBeanstalkApplication48LightSvg from './Res_AWS-Elastic-Beanstalk_Application_48_Light.svg';
import _resAwsElasticBeanstalkDeployment48LightSvg from './Res_AWS-Elastic-Beanstalk_Deployment_48_Light.svg';
import _resAwsLambdaLambdaFunction48LightSvg from './Res_AWS-Lambda_Lambda-Function_48_Light.svg';
import _resAmazonEc2A1Instance48LightSvg from './Res_Amazon-EC2_A1-Instance_48_Light.svg';
import _resAmazonEc2Ami48LightSvg from './Res_Amazon-EC2_AMI_48_Light.svg';
import _resAmazonEc2AwsInferentia48LightSvg from './Res_Amazon-EC2_AWS-Inferentia_48_Light.svg';
import _resAmazonEc2AwsMicroserviceExtractorForNet48LightSvg from './Res_Amazon-EC2_AWS-Microservice-Extractor-for-.NET_48_Light.svg';
import _resAmazonEc2AutoScaling48LightSvg from './Res_Amazon-EC2_Auto-Scaling_48_Light.svg';
import _resAmazonEc2C4Instance48LightSvg from './Res_Amazon-EC2_C4-Instance_48_Light.svg';
import _resAmazonEc2C5Instance48LightSvg from './Res_Amazon-EC2_C5-Instance_48_Light.svg';
import _resAmazonEc2C5AInstance48LightSvg from './Res_Amazon-EC2_C5a-Instance_48_Light.svg';
import _resAmazonEc2C5AdInstance48LightSvg from './Res_Amazon-EC2_C5ad-Instance_48_Light.svg';
import _resAmazonEc2C5DInstance48LightSvg from './Res_Amazon-EC2_C5d-Instance_48_Light.svg';
import _resAmazonEc2C5NInstance48LightSvg from './Res_Amazon-EC2_C5n-Instance_48_Light.svg';
import _resAmazonEc2C6AInstance48LightSvg from './Res_Amazon-EC2_C6a-Instance_48_Light.svg';
import _resAmazonEc2C6GInstance48LightSvg from './Res_Amazon-EC2_C6g-Instance_48_Light.svg';
import _resAmazonEc2C6GdInstance48LightSvg from './Res_Amazon-EC2_C6gd-Instance_48_Light.svg';
import _resAmazonEc2C6GnInstance48LightSvg from './Res_Amazon-EC2_C6gn-Instance_48_Light.svg';
import _resAmazonEc2C6IInstance48LightSvg from './Res_Amazon-EC2_C6i-Instance_48_Light.svg';
import _resAmazonEc2C7GInstance48LightSvg from './Res_Amazon-EC2_C7g-Instance_48_Light.svg';
import _resAmazonEc2D2Instance48LightSvg from './Res_Amazon-EC2_D2-Instance_48_Light.svg';
import _resAmazonEc2D3Instance48LightSvg from './Res_Amazon-EC2_D3-Instance_48_Light.svg';
import _resAmazonEc2D3EnInstance48LightSvg from './Res_Amazon-EC2_D3en-Instance_48_Light.svg';
import _resAmazonEc2DbInstance48LightSvg from './Res_Amazon-EC2_DB-Instance_48_Light.svg';
import _resAmazonEc2Dl1Instance48LightSvg from './Res_Amazon-EC2_DL1-Instance_48_Light.svg';
import _resAmazonEc2ElasticIpAddress48LightSvg from './Res_Amazon-EC2_Elastic-IP-Address_48_Light.svg';
import _resAmazonEc2F1Instance48LightSvg from './Res_Amazon-EC2_F1-Instance_48_Light.svg';
import _resAmazonEc2G3Instance48LightSvg from './Res_Amazon-EC2_G3-Instance_48_Light.svg';
import _resAmazonEc2G4AdInstance48LightSvg from './Res_Amazon-EC2_G4ad-Instance_48_Light.svg';
import _resAmazonEc2G4DnInstance48LightSvg from './Res_Amazon-EC2_G4dn-Instance_48_Light.svg';
import _resAmazonEc2G5Instance48LightSvg from './Res_Amazon-EC2_G5-Instance_48_Light.svg';
import _resAmazonEc2G5GInstance48LightSvg from './Res_Amazon-EC2_G5g-Instance_48_Light.svg';
import _resAmazonEc2H1Instance48LightSvg from './Res_Amazon-EC2_H1-Instance_48_Light.svg';
import _resAmazonEc2HmiInstance48LightSvg from './Res_Amazon-EC2_HMI-Instance_48_Light.svg';
import _resAmazonEc2HabanaGaudiInstance48LightSvg from './Res_Amazon-EC2_Habana-Gaudi-Instance_48_Light.svg';
import _resAmazonEc2Hpc6AInstance48LightSvg from './Res_Amazon-EC2_Hpc6a-Instance_48_Light.svg';
import _resAmazonEc2I2Instance48LightSvg from './Res_Amazon-EC2_I2-Instance_48_Light.svg';
import _resAmazonEc2I3Instance48LightSvg from './Res_Amazon-EC2_I3-Instance_48_Light.svg';
import _resAmazonEc2I3EnInstance48LightSvg from './Res_Amazon-EC2_I3en-Instance_48_Light.svg';
import _resAmazonEc2I4IInstance48LightSvg from './Res_Amazon-EC2_I4i-Instance_48_Light.svg';
import _resAmazonEc2Im4GnInstance48LightSvg from './Res_Amazon-EC2_Im4gn-Instance_48_Light.svg';
import _resAmazonEc2Inf1Instance48LightSvg from './Res_Amazon-EC2_Inf1-Instance_48_Light.svg';
import _resAmazonEc2InstanceWithCloudWatch48LightSvg from './Res_Amazon-EC2_Instance-with-CloudWatch_48_Light.svg';
import _resAmazonEc2Instance48LightSvg from './Res_Amazon-EC2_Instance_48_Light.svg';
import _resAmazonEc2Instances48LightSvg from './Res_Amazon-EC2_Instances_48_Light.svg';
import _resAmazonEc2Is4GenInstance48LightSvg from './Res_Amazon-EC2_Is4gen-Instance_48_Light.svg';
import _resAmazonEc2M1MacInstance48LightSvg from './Res_Amazon-EC2_M1-Mac-Instance_48_Light.svg';
import _resAmazonEc2M4Instance48LightSvg from './Res_Amazon-EC2_M4-Instance_48_Light.svg';
import _resAmazonEc2M5Instance48LightSvg from './Res_Amazon-EC2_M5-Instance_48_Light.svg';
import _resAmazonEc2M5AInstance48LightSvg from './Res_Amazon-EC2_M5a-Instance_48_Light.svg';
import _resAmazonEc2M5DInstance48LightSvg from './Res_Amazon-EC2_M5d-Instance_48_Light.svg';
import _resAmazonEc2M5DnInstance48LightSvg from './Res_Amazon-EC2_M5dn-Instance_48_Light.svg';
import _resAmazonEc2M5NInstance48LightSvg from './Res_Amazon-EC2_M5n-Instance_48_Light.svg';
import _resAmazonEc2M5ZnInstance48LightSvg from './Res_Amazon-EC2_M5zn-Instance_48_Light.svg';
import _resAmazonEc2M6AInstance48LightSvg from './Res_Amazon-EC2_M6a-Instance_48_Light.svg';
import _resAmazonEc2M6GInstance48LightSvg from './Res_Amazon-EC2_M6g-Instance_48_Light.svg';
import _resAmazonEc2M6GdInstance48LightSvg from './Res_Amazon-EC2_M6gd-Instance_48_Light.svg';
import _resAmazonEc2M6IInstance48LightSvg from './Res_Amazon-EC2_M6i-Instance_48_Light.svg';
import _resAmazonEc2MacInstance48LightSvg from './Res_Amazon-EC2_Mac-Instance_48_Light.svg';
import _resAmazonEc2P2Instance48LightSvg from './Res_Amazon-EC2_P2-Instance_48_Light.svg';
import _resAmazonEc2P3Instance48LightSvg from './Res_Amazon-EC2_P3-Instance_48_Light.svg';
import _resAmazonEc2P3DnInstance48LightSvg from './Res_Amazon-EC2_P3dn-Instance_48_Light.svg';
import _resAmazonEc2P4Instance48LightSvg from './Res_Amazon-EC2_P4-Instance_48_Light.svg';
import _resAmazonEc2P4DInstance48LightSvg from './Res_Amazon-EC2_P4d-Instance_48_Light.svg';
import _resAmazonEc2P4DeInstance48LightSvg from './Res_Amazon-EC2_P4de-Instance_48_Light.svg';
import _resAmazonEc2R4Instance48LightSvg from './Res_Amazon-EC2_R4-Instance_48_Light.svg';
import _resAmazonEc2R5Instance48LightSvg from './Res_Amazon-EC2_R5-Instance_48_Light.svg';
import _resAmazonEc2R5AInstance48LightSvg from './Res_Amazon-EC2_R5a-Instance_48_Light.svg';
import _resAmazonEc2R5AdInstance48LightSvg from './Res_Amazon-EC2_R5ad-Instance_48_Light.svg';
import _resAmazonEc2R5BInstance48LightSvg from './Res_Amazon-EC2_R5b-Instance _48_Light.svg';
import _resAmazonEc2R5DInstance48LightSvg from './Res_Amazon-EC2_R5d-Instance_48_Light.svg';
import _resAmazonEc2R5GdInstance48LightSvg from './Res_Amazon-EC2_R5gd-Instance_48_Light.svg';
import _resAmazonEc2R5NInstance48LightSvg from './Res_Amazon-EC2_R5n-Instance_48_Light.svg';
import _resAmazonEc2R6GInstance48LightSvg from './Res_Amazon-EC2_R6g-Instance_48_Light.svg';
import _resAmazonEc2R6IInstance48LightSvg from './Res_Amazon-EC2_R6i-Instance_48_Light.svg';
import _resAmazonEc2RdnInstance48LightSvg from './Res_Amazon-EC2_Rdn-Instance_48_Light.svg';
import _resAmazonEc2Rescue48LightSvg from './Res_Amazon-EC2_Rescue_48_Light.svg';
import _resAmazonEc2SpotInstance48LightSvg from './Res_Amazon-EC2_Spot-Instance_48_Light.svg';
import _resAmazonEc2T2Instance48LightSvg from './Res_Amazon-EC2_T2-Instance_48_Light.svg';
import _resAmazonEc2T3Instance48LightSvg from './Res_Amazon-EC2_T3-Instance_48_Light.svg';
import _resAmazonEc2T3AInstance48LightSvg from './Res_Amazon-EC2_T3a-Instance_48_Light.svg';
import _resAmazonEc2T4GInstance48LightSvg from './Res_Amazon-EC2_T4g-Instance_48_Light.svg';
import _resAmazonEc2TrainiumInstance48LightSvg from './Res_Amazon-EC2_Trainium-Instance_48_Light.svg';
import _resAmazonEc2Trn1Instance48LightSvg from './Res_Amazon-EC2_Trn1-Instance_48_Light.svg';
import _resAmazonEc2Vt1Instance48LightSvg from './Res_Amazon-EC2_VT1-Instance_48_Light.svg';
import _resAmazonEc2X1Instance48LightSvg from './Res_Amazon-EC2_X1-Instance_48_Light.svg';
import _resAmazonEc2X1EInstance48LightSvg from './Res_Amazon-EC2_X1e-Instance_48_Light.svg';
import _resAmazonEc2X2GdInstance48LightSvg from './Res_Amazon-EC2_X2gd-Instance_48_Light.svg';
import _resAmazonEc2X2IdnInstance48LightSvg from './Res_Amazon-EC2_X2idn-Instance_48_Light.svg';
import _resAmazonEc2X2IednInstance48LightSvg from './Res_Amazon-EC2_X2iedn-Instance_48_Light.svg';
import _resAmazonEc2X2IeznInstance48LightSvg from './Res_Amazon-EC2_X2iezn-Instance_48_Light.svg';
import _resAmazonEc2Z1DInstance48LightSvg from './Res_Amazon-EC2_z1d-Instance_48_Light.svg';

export const resAwsElasticBeanstalkApplication48LightSvg = { id: "resAwsElasticBeanstalkApplication48LightSvg", name: "AWS Elastic Beanstalk / Application", icon: _resAwsElasticBeanstalkApplication48LightSvg };
export const resAwsElasticBeanstalkDeployment48LightSvg = { id: "resAwsElasticBeanstalkDeployment48LightSvg", name: "AWS Elastic Beanstalk / Deployment", icon: _resAwsElasticBeanstalkDeployment48LightSvg };
export const resAwsLambdaLambdaFunction48LightSvg = { id: "resAwsLambdaLambdaFunction48LightSvg", name: "AWS Lambda / Lambda Function", icon: _resAwsLambdaLambdaFunction48LightSvg };
export const resAmazonEc2A1Instance48LightSvg = { id: "resAmazonEc2A1Instance48LightSvg", name: "Amazon EC2 / A1 Instance", icon: _resAmazonEc2A1Instance48LightSvg };
export const resAmazonEc2Ami48LightSvg = { id: "resAmazonEc2Ami48LightSvg", name: "Amazon EC2 / AMI", icon: _resAmazonEc2Ami48LightSvg };
export const resAmazonEc2AwsInferentia48LightSvg = { id: "resAmazonEc2AwsInferentia48LightSvg", name: "Amazon EC2 / AWS Inferentia", icon: _resAmazonEc2AwsInferentia48LightSvg };
export const resAmazonEc2AwsMicroserviceExtractorForNet48LightSvg = { id: "resAmazonEc2AwsMicroserviceExtractorForNet48LightSvg", name: "Amazon EC2 / AWS Microservice Extractor for .NET", icon: _resAmazonEc2AwsMicroserviceExtractorForNet48LightSvg };
export const resAmazonEc2AutoScaling48LightSvg = { id: "resAmazonEc2AutoScaling48LightSvg", name: "Amazon EC2 / Auto Scaling", icon: _resAmazonEc2AutoScaling48LightSvg };
export const resAmazonEc2C4Instance48LightSvg = { id: "resAmazonEc2C4Instance48LightSvg", name: "Amazon EC2 / C4 Instance", icon: _resAmazonEc2C4Instance48LightSvg };
export const resAmazonEc2C5Instance48LightSvg = { id: "resAmazonEc2C5Instance48LightSvg", name: "Amazon EC2 / C5 Instance", icon: _resAmazonEc2C5Instance48LightSvg };
export const resAmazonEc2C5AInstance48LightSvg = { id: "resAmazonEc2C5AInstance48LightSvg", name: "Amazon EC2 / C5a Instance", icon: _resAmazonEc2C5AInstance48LightSvg };
export const resAmazonEc2C5AdInstance48LightSvg = { id: "resAmazonEc2C5AdInstance48LightSvg", name: "Amazon EC2 / C5ad Instance", icon: _resAmazonEc2C5AdInstance48LightSvg };
export const resAmazonEc2C5DInstance48LightSvg = { id: "resAmazonEc2C5DInstance48LightSvg", name: "Amazon EC2 / C5d Instance", icon: _resAmazonEc2C5DInstance48LightSvg };
export const resAmazonEc2C5NInstance48LightSvg = { id: "resAmazonEc2C5NInstance48LightSvg", name: "Amazon EC2 / C5n Instance", icon: _resAmazonEc2C5NInstance48LightSvg };
export const resAmazonEc2C6AInstance48LightSvg = { id: "resAmazonEc2C6AInstance48LightSvg", name: "Amazon EC2 / C6a Instance", icon: _resAmazonEc2C6AInstance48LightSvg };
export const resAmazonEc2C6GInstance48LightSvg = { id: "resAmazonEc2C6GInstance48LightSvg", name: "Amazon EC2 / C6g Instance", icon: _resAmazonEc2C6GInstance48LightSvg };
export const resAmazonEc2C6GdInstance48LightSvg = { id: "resAmazonEc2C6GdInstance48LightSvg", name: "Amazon EC2 / C6gd Instance", icon: _resAmazonEc2C6GdInstance48LightSvg };
export const resAmazonEc2C6GnInstance48LightSvg = { id: "resAmazonEc2C6GnInstance48LightSvg", name: "Amazon EC2 / C6gn Instance", icon: _resAmazonEc2C6GnInstance48LightSvg };
export const resAmazonEc2C6IInstance48LightSvg = { id: "resAmazonEc2C6IInstance48LightSvg", name: "Amazon EC2 / C6i Instance", icon: _resAmazonEc2C6IInstance48LightSvg };
export const resAmazonEc2C7GInstance48LightSvg = { id: "resAmazonEc2C7GInstance48LightSvg", name: "Amazon EC2 / C7g Instance", icon: _resAmazonEc2C7GInstance48LightSvg };
export const resAmazonEc2D2Instance48LightSvg = { id: "resAmazonEc2D2Instance48LightSvg", name: "Amazon EC2 / D2 Instance", icon: _resAmazonEc2D2Instance48LightSvg };
export const resAmazonEc2D3Instance48LightSvg = { id: "resAmazonEc2D3Instance48LightSvg", name: "Amazon EC2 / D3 Instance", icon: _resAmazonEc2D3Instance48LightSvg };
export const resAmazonEc2D3EnInstance48LightSvg = { id: "resAmazonEc2D3EnInstance48LightSvg", name: "Amazon EC2 / D3en Instance", icon: _resAmazonEc2D3EnInstance48LightSvg };
export const resAmazonEc2DbInstance48LightSvg = { id: "resAmazonEc2DbInstance48LightSvg", name: "Amazon EC2 / DB Instance", icon: _resAmazonEc2DbInstance48LightSvg };
export const resAmazonEc2Dl1Instance48LightSvg = { id: "resAmazonEc2Dl1Instance48LightSvg", name: "Amazon EC2 / DL1 Instance", icon: _resAmazonEc2Dl1Instance48LightSvg };
export const resAmazonEc2ElasticIpAddress48LightSvg = { id: "resAmazonEc2ElasticIpAddress48LightSvg", name: "Amazon EC2 / Elastic IP Address", icon: _resAmazonEc2ElasticIpAddress48LightSvg };
export const resAmazonEc2F1Instance48LightSvg = { id: "resAmazonEc2F1Instance48LightSvg", name: "Amazon EC2 / F1 Instance", icon: _resAmazonEc2F1Instance48LightSvg };
export const resAmazonEc2G3Instance48LightSvg = { id: "resAmazonEc2G3Instance48LightSvg", name: "Amazon EC2 / G3 Instance", icon: _resAmazonEc2G3Instance48LightSvg };
export const resAmazonEc2G4AdInstance48LightSvg = { id: "resAmazonEc2G4AdInstance48LightSvg", name: "Amazon EC2 / G4ad Instance", icon: _resAmazonEc2G4AdInstance48LightSvg };
export const resAmazonEc2G4DnInstance48LightSvg = { id: "resAmazonEc2G4DnInstance48LightSvg", name: "Amazon EC2 / G4dn Instance", icon: _resAmazonEc2G4DnInstance48LightSvg };
export const resAmazonEc2G5Instance48LightSvg = { id: "resAmazonEc2G5Instance48LightSvg", name: "Amazon EC2 / G5 Instance", icon: _resAmazonEc2G5Instance48LightSvg };
export const resAmazonEc2G5GInstance48LightSvg = { id: "resAmazonEc2G5GInstance48LightSvg", name: "Amazon EC2 / G5g Instance", icon: _resAmazonEc2G5GInstance48LightSvg };
export const resAmazonEc2H1Instance48LightSvg = { id: "resAmazonEc2H1Instance48LightSvg", name: "Amazon EC2 / H1 Instance", icon: _resAmazonEc2H1Instance48LightSvg };
export const resAmazonEc2HmiInstance48LightSvg = { id: "resAmazonEc2HmiInstance48LightSvg", name: "Amazon EC2 / HMI Instance", icon: _resAmazonEc2HmiInstance48LightSvg };
export const resAmazonEc2HabanaGaudiInstance48LightSvg = { id: "resAmazonEc2HabanaGaudiInstance48LightSvg", name: "Amazon EC2 / Habana Gaudi Instance", icon: _resAmazonEc2HabanaGaudiInstance48LightSvg };
export const resAmazonEc2Hpc6AInstance48LightSvg = { id: "resAmazonEc2Hpc6AInstance48LightSvg", name: "Amazon EC2 / Hpc6a Instance", icon: _resAmazonEc2Hpc6AInstance48LightSvg };
export const resAmazonEc2I2Instance48LightSvg = { id: "resAmazonEc2I2Instance48LightSvg", name: "Amazon EC2 / I2 Instance", icon: _resAmazonEc2I2Instance48LightSvg };
export const resAmazonEc2I3Instance48LightSvg = { id: "resAmazonEc2I3Instance48LightSvg", name: "Amazon EC2 / I3 Instance", icon: _resAmazonEc2I3Instance48LightSvg };
export const resAmazonEc2I3EnInstance48LightSvg = { id: "resAmazonEc2I3EnInstance48LightSvg", name: "Amazon EC2 / I3en Instance", icon: _resAmazonEc2I3EnInstance48LightSvg };
export const resAmazonEc2I4IInstance48LightSvg = { id: "resAmazonEc2I4IInstance48LightSvg", name: "Amazon EC2 / I4i Instance", icon: _resAmazonEc2I4IInstance48LightSvg };
export const resAmazonEc2Im4GnInstance48LightSvg = { id: "resAmazonEc2Im4GnInstance48LightSvg", name: "Amazon EC2 / Im4gn Instance", icon: _resAmazonEc2Im4GnInstance48LightSvg };
export const resAmazonEc2Inf1Instance48LightSvg = { id: "resAmazonEc2Inf1Instance48LightSvg", name: "Amazon EC2 / Inf1 Instance", icon: _resAmazonEc2Inf1Instance48LightSvg };
export const resAmazonEc2InstanceWithCloudWatch48LightSvg = { id: "resAmazonEc2InstanceWithCloudWatch48LightSvg", name: "Amazon EC2 / Instance with CloudWatch", icon: _resAmazonEc2InstanceWithCloudWatch48LightSvg };
export const resAmazonEc2Instance48LightSvg = { id: "resAmazonEc2Instance48LightSvg", name: "Amazon EC2 / Instance", icon: _resAmazonEc2Instance48LightSvg };
export const resAmazonEc2Instances48LightSvg = { id: "resAmazonEc2Instances48LightSvg", name: "Amazon EC2 / Instances", icon: _resAmazonEc2Instances48LightSvg };
export const resAmazonEc2Is4GenInstance48LightSvg = { id: "resAmazonEc2Is4GenInstance48LightSvg", name: "Amazon EC2 / Is4gen Instance", icon: _resAmazonEc2Is4GenInstance48LightSvg };
export const resAmazonEc2M1MacInstance48LightSvg = { id: "resAmazonEc2M1MacInstance48LightSvg", name: "Amazon EC2 / M1 Mac Instance", icon: _resAmazonEc2M1MacInstance48LightSvg };
export const resAmazonEc2M4Instance48LightSvg = { id: "resAmazonEc2M4Instance48LightSvg", name: "Amazon EC2 / M4 Instance", icon: _resAmazonEc2M4Instance48LightSvg };
export const resAmazonEc2M5Instance48LightSvg = { id: "resAmazonEc2M5Instance48LightSvg", name: "Amazon EC2 / M5 Instance", icon: _resAmazonEc2M5Instance48LightSvg };
export const resAmazonEc2M5AInstance48LightSvg = { id: "resAmazonEc2M5AInstance48LightSvg", name: "Amazon EC2 / M5a Instance", icon: _resAmazonEc2M5AInstance48LightSvg };
export const resAmazonEc2M5DInstance48LightSvg = { id: "resAmazonEc2M5DInstance48LightSvg", name: "Amazon EC2 / M5d Instance", icon: _resAmazonEc2M5DInstance48LightSvg };
export const resAmazonEc2M5DnInstance48LightSvg = { id: "resAmazonEc2M5DnInstance48LightSvg", name: "Amazon EC2 / M5dn Instance", icon: _resAmazonEc2M5DnInstance48LightSvg };
export const resAmazonEc2M5NInstance48LightSvg = { id: "resAmazonEc2M5NInstance48LightSvg", name: "Amazon EC2 / M5n Instance", icon: _resAmazonEc2M5NInstance48LightSvg };
export const resAmazonEc2M5ZnInstance48LightSvg = { id: "resAmazonEc2M5ZnInstance48LightSvg", name: "Amazon EC2 / M5zn Instance", icon: _resAmazonEc2M5ZnInstance48LightSvg };
export const resAmazonEc2M6AInstance48LightSvg = { id: "resAmazonEc2M6AInstance48LightSvg", name: "Amazon EC2 / M6a Instance", icon: _resAmazonEc2M6AInstance48LightSvg };
export const resAmazonEc2M6GInstance48LightSvg = { id: "resAmazonEc2M6GInstance48LightSvg", name: "Amazon EC2 / M6g Instance", icon: _resAmazonEc2M6GInstance48LightSvg };
export const resAmazonEc2M6GdInstance48LightSvg = { id: "resAmazonEc2M6GdInstance48LightSvg", name: "Amazon EC2 / M6gd Instance", icon: _resAmazonEc2M6GdInstance48LightSvg };
export const resAmazonEc2M6IInstance48LightSvg = { id: "resAmazonEc2M6IInstance48LightSvg", name: "Amazon EC2 / M6i Instance", icon: _resAmazonEc2M6IInstance48LightSvg };
export const resAmazonEc2MacInstance48LightSvg = { id: "resAmazonEc2MacInstance48LightSvg", name: "Amazon EC2 / Mac Instance", icon: _resAmazonEc2MacInstance48LightSvg };
export const resAmazonEc2P2Instance48LightSvg = { id: "resAmazonEc2P2Instance48LightSvg", name: "Amazon EC2 / P2 Instance", icon: _resAmazonEc2P2Instance48LightSvg };
export const resAmazonEc2P3Instance48LightSvg = { id: "resAmazonEc2P3Instance48LightSvg", name: "Amazon EC2 / P3 Instance", icon: _resAmazonEc2P3Instance48LightSvg };
export const resAmazonEc2P3DnInstance48LightSvg = { id: "resAmazonEc2P3DnInstance48LightSvg", name: "Amazon EC2 / P3dn Instance", icon: _resAmazonEc2P3DnInstance48LightSvg };
export const resAmazonEc2P4Instance48LightSvg = { id: "resAmazonEc2P4Instance48LightSvg", name: "Amazon EC2 / P4 Instance", icon: _resAmazonEc2P4Instance48LightSvg };
export const resAmazonEc2P4DInstance48LightSvg = { id: "resAmazonEc2P4DInstance48LightSvg", name: "Amazon EC2 / P4d Instance", icon: _resAmazonEc2P4DInstance48LightSvg };
export const resAmazonEc2P4DeInstance48LightSvg = { id: "resAmazonEc2P4DeInstance48LightSvg", name: "Amazon EC2 / P4de Instance", icon: _resAmazonEc2P4DeInstance48LightSvg };
export const resAmazonEc2R4Instance48LightSvg = { id: "resAmazonEc2R4Instance48LightSvg", name: "Amazon EC2 / R4 Instance", icon: _resAmazonEc2R4Instance48LightSvg };
export const resAmazonEc2R5Instance48LightSvg = { id: "resAmazonEc2R5Instance48LightSvg", name: "Amazon EC2 / R5 Instance", icon: _resAmazonEc2R5Instance48LightSvg };
export const resAmazonEc2R5AInstance48LightSvg = { id: "resAmazonEc2R5AInstance48LightSvg", name: "Amazon EC2 / R5a Instance", icon: _resAmazonEc2R5AInstance48LightSvg };
export const resAmazonEc2R5AdInstance48LightSvg = { id: "resAmazonEc2R5AdInstance48LightSvg", name: "Amazon EC2 / R5ad Instance", icon: _resAmazonEc2R5AdInstance48LightSvg };
export const resAmazonEc2R5BInstance48LightSvg = { id: "resAmazonEc2R5BInstance48LightSvg", name: "Amazon EC2 / R5b Instance ", icon: _resAmazonEc2R5BInstance48LightSvg };
export const resAmazonEc2R5DInstance48LightSvg = { id: "resAmazonEc2R5DInstance48LightSvg", name: "Amazon EC2 / R5d Instance", icon: _resAmazonEc2R5DInstance48LightSvg };
export const resAmazonEc2R5GdInstance48LightSvg = { id: "resAmazonEc2R5GdInstance48LightSvg", name: "Amazon EC2 / R5gd Instance", icon: _resAmazonEc2R5GdInstance48LightSvg };
export const resAmazonEc2R5NInstance48LightSvg = { id: "resAmazonEc2R5NInstance48LightSvg", name: "Amazon EC2 / R5n Instance", icon: _resAmazonEc2R5NInstance48LightSvg };
export const resAmazonEc2R6GInstance48LightSvg = { id: "resAmazonEc2R6GInstance48LightSvg", name: "Amazon EC2 / R6g Instance", icon: _resAmazonEc2R6GInstance48LightSvg };
export const resAmazonEc2R6IInstance48LightSvg = { id: "resAmazonEc2R6IInstance48LightSvg", name: "Amazon EC2 / R6i Instance", icon: _resAmazonEc2R6IInstance48LightSvg };
export const resAmazonEc2RdnInstance48LightSvg = { id: "resAmazonEc2RdnInstance48LightSvg", name: "Amazon EC2 / Rdn Instance", icon: _resAmazonEc2RdnInstance48LightSvg };
export const resAmazonEc2Rescue48LightSvg = { id: "resAmazonEc2Rescue48LightSvg", name: "Amazon EC2 / Rescue", icon: _resAmazonEc2Rescue48LightSvg };
export const resAmazonEc2SpotInstance48LightSvg = { id: "resAmazonEc2SpotInstance48LightSvg", name: "Amazon EC2 / Spot Instance", icon: _resAmazonEc2SpotInstance48LightSvg };
export const resAmazonEc2T2Instance48LightSvg = { id: "resAmazonEc2T2Instance48LightSvg", name: "Amazon EC2 / T2 Instance", icon: _resAmazonEc2T2Instance48LightSvg };
export const resAmazonEc2T3Instance48LightSvg = { id: "resAmazonEc2T3Instance48LightSvg", name: "Amazon EC2 / T3 Instance", icon: _resAmazonEc2T3Instance48LightSvg };
export const resAmazonEc2T3AInstance48LightSvg = { id: "resAmazonEc2T3AInstance48LightSvg", name: "Amazon EC2 / T3a Instance", icon: _resAmazonEc2T3AInstance48LightSvg };
export const resAmazonEc2T4GInstance48LightSvg = { id: "resAmazonEc2T4GInstance48LightSvg", name: "Amazon EC2 / T4g Instance", icon: _resAmazonEc2T4GInstance48LightSvg };
export const resAmazonEc2TrainiumInstance48LightSvg = { id: "resAmazonEc2TrainiumInstance48LightSvg", name: "Amazon EC2 / Trainium Instance", icon: _resAmazonEc2TrainiumInstance48LightSvg };
export const resAmazonEc2Trn1Instance48LightSvg = { id: "resAmazonEc2Trn1Instance48LightSvg", name: "Amazon EC2 / Trn1 Instance", icon: _resAmazonEc2Trn1Instance48LightSvg };
export const resAmazonEc2Vt1Instance48LightSvg = { id: "resAmazonEc2Vt1Instance48LightSvg", name: "Amazon EC2 / VT1 Instance", icon: _resAmazonEc2Vt1Instance48LightSvg };
export const resAmazonEc2X1Instance48LightSvg = { id: "resAmazonEc2X1Instance48LightSvg", name: "Amazon EC2 / X1 Instance", icon: _resAmazonEc2X1Instance48LightSvg };
export const resAmazonEc2X1EInstance48LightSvg = { id: "resAmazonEc2X1EInstance48LightSvg", name: "Amazon EC2 / X1e Instance", icon: _resAmazonEc2X1EInstance48LightSvg };
export const resAmazonEc2X2GdInstance48LightSvg = { id: "resAmazonEc2X2GdInstance48LightSvg", name: "Amazon EC2 / X2gd Instance", icon: _resAmazonEc2X2GdInstance48LightSvg };
export const resAmazonEc2X2IdnInstance48LightSvg = { id: "resAmazonEc2X2IdnInstance48LightSvg", name: "Amazon EC2 / X2idn Instance", icon: _resAmazonEc2X2IdnInstance48LightSvg };
export const resAmazonEc2X2IednInstance48LightSvg = { id: "resAmazonEc2X2IednInstance48LightSvg", name: "Amazon EC2 / X2iedn Instance", icon: _resAmazonEc2X2IednInstance48LightSvg };
export const resAmazonEc2X2IeznInstance48LightSvg = { id: "resAmazonEc2X2IeznInstance48LightSvg", name: "Amazon EC2 / X2iezn Instance", icon: _resAmazonEc2X2IeznInstance48LightSvg };
export const resAmazonEc2Z1DInstance48LightSvg = { id: "resAmazonEc2Z1DInstance48LightSvg", name: "Amazon EC2 / z1d Instance", icon: _resAmazonEc2Z1DInstance48LightSvg };
