export { ReactComponent as archAwsFargate48Svg } from './Arch_AWS-Fargate_48.svg';
export { ReactComponent as archAmazonEcsAnywhere48Svg } from './Arch_Amazon-ECS-Anywhere_48.svg';
export { ReactComponent as archAmazonEksAnywhere48Svg } from './Arch_Amazon-EKS-Anywhere_48.svg';
export { ReactComponent as archAmazonEksCloud48Svg } from './Arch_Amazon-EKS-Cloud_48.svg';
export { ReactComponent as archAmazonEksDistro48Svg } from './Arch_Amazon-EKS-Distro_48.svg';
export { ReactComponent as archAmazonElasticContainerRegistry48Svg } from './Arch_Amazon-Elastic-Container-Registry_48.svg';
export { ReactComponent as archAmazonElasticContainerService48Svg } from './Arch_Amazon-Elastic-Container-Service_48.svg';
export { ReactComponent as archAmazonElasticKubernetesService48Svg } from './Arch_Amazon-Elastic-Kubernetes-Service_48.svg';
export { ReactComponent as archRedHatOpenShift48Svg } from './Arch_Red-Hat-OpenShift_48.svg';