export { default as archAwsFargate48Svg } from './Arch_AWS-Fargate_48.svg';
export { default as archAmazonEcsAnywhere48Svg } from './Arch_Amazon-ECS-Anywhere_48.svg';
export { default as archAmazonEksAnywhere48Svg } from './Arch_Amazon-EKS-Anywhere_48.svg';
export { default as archAmazonEksCloud48Svg } from './Arch_Amazon-EKS-Cloud_48.svg';
export { default as archAmazonEksDistro48Svg } from './Arch_Amazon-EKS-Distro_48.svg';
export { default as archAmazonElasticContainerRegistry48Svg } from './Arch_Amazon-Elastic-Container-Registry_48.svg';
export { default as archAmazonElasticContainerService48Svg } from './Arch_Amazon-Elastic-Container-Service_48.svg';
export { default as archAmazonElasticKubernetesService48Svg } from './Arch_Amazon-Elastic-Kubernetes-Service_48.svg';
export { default as archRedHatOpenShift48Svg } from './Arch_Red-Hat-OpenShift_48.svg';