import _resAwsManagementConsole48DarkSvg from './Res_AWS-Management-Console_48_Dark.svg';
import _resAlert48DarkSvg from './Res_Alert_48_Dark.svg';
import _resCamera48DarkSvg from './Res_Camera_48_Dark.svg';
import _resChat48DarkSvg from './Res_Chat_48_Dark.svg';
import _resClient48DarkSvg from './Res_Client_48_Dark.svg';
import _resDisk48DarkSvg from './Res_Disk_48_Dark.svg';
import _resDocument48DarkSvg from './Res_Document_48_Dark.svg';
import _resDocuments48DarkSvg from './Res_Documents_48_Dark.svg';
import _resEmail48DarkSvg from './Res_Email_48_Dark.svg';
import _resFirewall48DarkSvg from './Res_Firewall_48_Dark.svg';
import _resFolder48DarkSvg from './Res_Folder_48_Dark.svg';
import _resFolders48DarkSvg from './Res_Folders_48_Dark.svg';
import _resForums48DarkSvg from './Res_Forums_48_Dark.svg';
import _resGear48DarkSvg from './Res_Gear_48_Dark.svg';
import _resGenericApplication48DarkSvg from './Res_Generic-Application_48_Dark.svg';
import _resGenericDatabase48DarkSvg from './Res_Generic-database_48_Dark.svg';
import _resGitRepository48DarkSvg from './Res_Git-Repository_48_Dark.svg';
import _resGlobe48DarkSvg from './Res_Globe_48_Dark.svg';
import _resInternetAlt148DarkSvg from './Res_Internet-alt1_48_Dark.svg';
import _resInternetAlt248DarkSvg from './Res_Internet-alt2_48_Dark.svg';
import _resInternet48DarkSvg from './Res_Internet_48_Dark.svg';
import _resMagnifyingGlass48DarkSvg from './Res_Magnifying-Glass_48_Dark.svg';
import _resMobileClient48DarkSvg from './Res_Mobile-client_48_Dark.svg';
import _resMultimedia48DarkSvg from './Res_Multimedia_48_Dark.svg';
import _resOfficeBuilding48DarkSvg from './Res_Office-building_48_Dark.svg';
import _resQuestion48DarkSvg from './Res_Question_48_Dark.svg';
import _resRecover48DarkSvg from './Res_Recover_48_Dark.svg';
import _resSamlToken48DarkSvg from './Res_SAML-token_48_Dark.svg';
import _resSdk48DarkSvg from './Res_SDK_48_Dark.svg';
import _resSslPadlock48DarkSvg from './Res_SSL-padlock_48_Dark.svg';
import _resServers48DarkSvg from './Res_Servers_48_Dark.svg';
import _resShield48DarkSvg from './Res_Shield_48_Dark.svg';
import _resSourceCode48DarkSvg from './Res_Source-Code_48_Dark.svg';
import _resTapeStorage48DarkSvg from './Res_Tape-storage_48_Dark.svg';
import _resToolkit48DarkSvg from './Res_Toolkit_48_Dark.svg';
import _resTraditionalServer48DarkSvg from './Res_Traditional-server_48_Dark.svg';
import _resUser48DarkSvg from './Res_User_48_Dark.svg';
import _resUsers48DarkSvg from './Res_Users_48_Dark.svg';

export const resAwsManagementConsole48DarkSvg = { id: "resAwsManagementConsole48DarkSvg", name: "AWS Management Console", icon: _resAwsManagementConsole48DarkSvg };
export const resAlert48DarkSvg = { id: "resAlert48DarkSvg", name: "Alert", icon: _resAlert48DarkSvg };
export const resCamera48DarkSvg = { id: "resCamera48DarkSvg", name: "Camera", icon: _resCamera48DarkSvg };
export const resChat48DarkSvg = { id: "resChat48DarkSvg", name: "Chat", icon: _resChat48DarkSvg };
export const resClient48DarkSvg = { id: "resClient48DarkSvg", name: "Client", icon: _resClient48DarkSvg };
export const resDisk48DarkSvg = { id: "resDisk48DarkSvg", name: "Disk", icon: _resDisk48DarkSvg };
export const resDocument48DarkSvg = { id: "resDocument48DarkSvg", name: "Document", icon: _resDocument48DarkSvg };
export const resDocuments48DarkSvg = { id: "resDocuments48DarkSvg", name: "Documents", icon: _resDocuments48DarkSvg };
export const resEmail48DarkSvg = { id: "resEmail48DarkSvg", name: "Email", icon: _resEmail48DarkSvg };
export const resFirewall48DarkSvg = { id: "resFirewall48DarkSvg", name: "Firewall", icon: _resFirewall48DarkSvg };
export const resFolder48DarkSvg = { id: "resFolder48DarkSvg", name: "Folder", icon: _resFolder48DarkSvg };
export const resFolders48DarkSvg = { id: "resFolders48DarkSvg", name: "Folders", icon: _resFolders48DarkSvg };
export const resForums48DarkSvg = { id: "resForums48DarkSvg", name: "Forums", icon: _resForums48DarkSvg };
export const resGear48DarkSvg = { id: "resGear48DarkSvg", name: "Gear", icon: _resGear48DarkSvg };
export const resGenericApplication48DarkSvg = { id: "resGenericApplication48DarkSvg", name: "Generic Application", icon: _resGenericApplication48DarkSvg };
export const resGenericDatabase48DarkSvg = { id: "resGenericDatabase48DarkSvg", name: "Generic database", icon: _resGenericDatabase48DarkSvg };
export const resGitRepository48DarkSvg = { id: "resGitRepository48DarkSvg", name: "Git Repository", icon: _resGitRepository48DarkSvg };
export const resGlobe48DarkSvg = { id: "resGlobe48DarkSvg", name: "Globe", icon: _resGlobe48DarkSvg };
export const resInternetAlt148DarkSvg = { id: "resInternetAlt148DarkSvg", name: "Internet alt1", icon: _resInternetAlt148DarkSvg };
export const resInternetAlt248DarkSvg = { id: "resInternetAlt248DarkSvg", name: "Internet alt2", icon: _resInternetAlt248DarkSvg };
export const resInternet48DarkSvg = { id: "resInternet48DarkSvg", name: "Internet", icon: _resInternet48DarkSvg };
export const resMagnifyingGlass48DarkSvg = { id: "resMagnifyingGlass48DarkSvg", name: "Magnifying Glass", icon: _resMagnifyingGlass48DarkSvg };
export const resMobileClient48DarkSvg = { id: "resMobileClient48DarkSvg", name: "Mobile client", icon: _resMobileClient48DarkSvg };
export const resMultimedia48DarkSvg = { id: "resMultimedia48DarkSvg", name: "Multimedia", icon: _resMultimedia48DarkSvg };
export const resOfficeBuilding48DarkSvg = { id: "resOfficeBuilding48DarkSvg", name: "Office building", icon: _resOfficeBuilding48DarkSvg };
export const resQuestion48DarkSvg = { id: "resQuestion48DarkSvg", name: "Question", icon: _resQuestion48DarkSvg };
export const resRecover48DarkSvg = { id: "resRecover48DarkSvg", name: "Recover", icon: _resRecover48DarkSvg };
export const resSamlToken48DarkSvg = { id: "resSamlToken48DarkSvg", name: "SAML token", icon: _resSamlToken48DarkSvg };
export const resSdk48DarkSvg = { id: "resSdk48DarkSvg", name: "SDK", icon: _resSdk48DarkSvg };
export const resSslPadlock48DarkSvg = { id: "resSslPadlock48DarkSvg", name: "SSL padlock", icon: _resSslPadlock48DarkSvg };
export const resServers48DarkSvg = { id: "resServers48DarkSvg", name: "Servers", icon: _resServers48DarkSvg };
export const resShield48DarkSvg = { id: "resShield48DarkSvg", name: "Shield", icon: _resShield48DarkSvg };
export const resSourceCode48DarkSvg = { id: "resSourceCode48DarkSvg", name: "Source Code", icon: _resSourceCode48DarkSvg };
export const resTapeStorage48DarkSvg = { id: "resTapeStorage48DarkSvg", name: "Tape storage", icon: _resTapeStorage48DarkSvg };
export const resToolkit48DarkSvg = { id: "resToolkit48DarkSvg", name: "Toolkit", icon: _resToolkit48DarkSvg };
export const resTraditionalServer48DarkSvg = { id: "resTraditionalServer48DarkSvg", name: "Traditional server", icon: _resTraditionalServer48DarkSvg };
export const resUser48DarkSvg = { id: "resUser48DarkSvg", name: "User", icon: _resUser48DarkSvg };
export const resUsers48DarkSvg = { id: "resUsers48DarkSvg", name: "Users", icon: _resUsers48DarkSvg };
