import _resAwsDatasyncAgent48DarkSvg from './Res_AWS-Datasync_Agent_48_Dark.svg';
import _resAwsMainframeModernizationAnalyzer48DarkSvg from './Res_AWS-Mainframe-Modernization_Analyzer_48_Dark.svg';
import _resAwsMainframeModernizationCompiler48DarkSvg from './Res_AWS-Mainframe-Modernization_Compiler_48_Dark.svg';
import _resAwsMainframeModernizationConverter48DarkSvg from './Res_AWS-Mainframe-Modernization_Converter_48_Dark.svg';
import _resAwsMainframeModernizationDeveloper48DarkSvg from './Res_AWS-Mainframe-Modernization_Developer_48_Dark.svg';
import _resAwsMainframeModernizationRuntime48DarkSvg from './Res_AWS-Mainframe-Modernization_Runtime_48_Dark.svg';
import _resAwsMigrationHubRefactorSpacesApplications48DarkSvg from './Res_AWS-Migration-Hub_Refactor-Spaces-Applications_48_Dark.svg';
import _resAwsMigrationHubRefactorSpacesEnvironments48DarkSvg from './Res_AWS-Migration-Hub_Refactor-Spaces-Environments_48_Dark.svg';
import _resAwsMigrationHubRefactorSpacesServices48DarkSvg from './Res_AWS-Migration-Hub_Refactor-Spaces-Services_48_Dark.svg';
import _resAwsTransferFamilyAwsFtps48DarkSvg from './Res_AWS-Transfer-Family_AWS-FTPS_48_Dark.svg';
import _resAwsTransferFamilyAwsFtp48DarkSvg from './Res_AWS-Transfer-Family_AWS-FTP_48_Dark.svg';
import _resAwsTransferFamilyAwsSftp48DarkSvg from './Res_AWS-Transfer-Family_AWS-SFTP_48_Dark.svg';

export const resAwsDatasyncAgent48DarkSvg = { id: "resAwsDatasyncAgent48DarkSvg", name: "AWS Datasync / Agent", icon: _resAwsDatasyncAgent48DarkSvg };
export const resAwsMainframeModernizationAnalyzer48DarkSvg = { id: "resAwsMainframeModernizationAnalyzer48DarkSvg", name: "AWS Mainframe Modernization / Analyzer", icon: _resAwsMainframeModernizationAnalyzer48DarkSvg };
export const resAwsMainframeModernizationCompiler48DarkSvg = { id: "resAwsMainframeModernizationCompiler48DarkSvg", name: "AWS Mainframe Modernization / Compiler", icon: _resAwsMainframeModernizationCompiler48DarkSvg };
export const resAwsMainframeModernizationConverter48DarkSvg = { id: "resAwsMainframeModernizationConverter48DarkSvg", name: "AWS Mainframe Modernization / Converter", icon: _resAwsMainframeModernizationConverter48DarkSvg };
export const resAwsMainframeModernizationDeveloper48DarkSvg = { id: "resAwsMainframeModernizationDeveloper48DarkSvg", name: "AWS Mainframe Modernization / Developer", icon: _resAwsMainframeModernizationDeveloper48DarkSvg };
export const resAwsMainframeModernizationRuntime48DarkSvg = { id: "resAwsMainframeModernizationRuntime48DarkSvg", name: "AWS Mainframe Modernization / Runtime", icon: _resAwsMainframeModernizationRuntime48DarkSvg };
export const resAwsMigrationHubRefactorSpacesApplications48DarkSvg = { id: "resAwsMigrationHubRefactorSpacesApplications48DarkSvg", name: "AWS Migration Hub / Refactor Spaces Applications", icon: _resAwsMigrationHubRefactorSpacesApplications48DarkSvg };
export const resAwsMigrationHubRefactorSpacesEnvironments48DarkSvg = { id: "resAwsMigrationHubRefactorSpacesEnvironments48DarkSvg", name: "AWS Migration Hub / Refactor Spaces Environments", icon: _resAwsMigrationHubRefactorSpacesEnvironments48DarkSvg };
export const resAwsMigrationHubRefactorSpacesServices48DarkSvg = { id: "resAwsMigrationHubRefactorSpacesServices48DarkSvg", name: "AWS Migration Hub / Refactor Spaces Services", icon: _resAwsMigrationHubRefactorSpacesServices48DarkSvg };
export const resAwsTransferFamilyAwsFtps48DarkSvg = { id: "resAwsTransferFamilyAwsFtps48DarkSvg", name: "AWS Transfer Family / AWS FTPS", icon: _resAwsTransferFamilyAwsFtps48DarkSvg };
export const resAwsTransferFamilyAwsFtp48DarkSvg = { id: "resAwsTransferFamilyAwsFtp48DarkSvg", name: "AWS Transfer Family / AWS FTP", icon: _resAwsTransferFamilyAwsFtp48DarkSvg };
export const resAwsTransferFamilyAwsSftp48DarkSvg = { id: "resAwsTransferFamilyAwsSftp48DarkSvg", name: "AWS Transfer Family / AWS SFTP", icon: _resAwsTransferFamilyAwsSftp48DarkSvg };
