import _archAwsBackup16Svg from './Arch_AWS-Backup_16.svg';
import _archAwsSnowballEdge16Svg from './Arch_AWS-Snowball-Edge_16.svg';
import _archAwsSnowball16Svg from './Arch_AWS-Snowball_16.svg';
import _archAwsSnowcone16Svg from './Arch_AWS-Snowcone_16.svg';
import _archAwsSnowmobile16Svg from './Arch_AWS-Snowmobile_16.svg';
import _archAwsStorageGateway16Svg from './Arch_AWS-Storage-Gateway_16.svg';
import _archAmazonEfs16Svg from './Arch_Amazon-EFS_16.svg';
import _archAmazonElasticBlockStore16Svg from './Arch_Amazon-Elastic-Block-Store_16.svg';
import _archAmazonFsxForLustre16Svg from './Arch_Amazon-FSx-for-Lustre_16.svg';
import _archAmazonFsxForNetAppOntap16Svg from './Arch_Amazon-FSx-for-NetApp-ONTAP_16.svg';
import _archAmazonFsxForOpenZfs16Svg from './Arch_Amazon-FSx-for-OpenZFS_16.svg';
import _archAmazonFsxForWfs16Svg from './Arch_Amazon-FSx-for-WFS_16.svg';
import _archAmazonFsx16Svg from './Arch_Amazon-FSx_16.svg';
import _archAmazonS3OnOutposts16Svg from './Arch_Amazon-S3-on-Outposts_16.svg';
import _archAmazonSimpleStorageServiceGlacier16Svg from './Arch_Amazon-Simple-Storage-Service-Glacier_16.svg';
import _archAmazonSimpleStorageService16Svg from './Arch_Amazon-Simple-Storage-Service_16.svg';
import _archCloudEndureDisasterRecovery16Svg from './Arch_CloudEndure-Disaster-Recovery_16.svg';

export const archAwsBackup16Svg = { id: "archAwsBackup16Svg", name: "AWS Backup", icon: _archAwsBackup16Svg };
export const archAwsSnowballEdge16Svg = { id: "archAwsSnowballEdge16Svg", name: "AWS Snowball Edge", icon: _archAwsSnowballEdge16Svg };
export const archAwsSnowball16Svg = { id: "archAwsSnowball16Svg", name: "AWS Snowball", icon: _archAwsSnowball16Svg };
export const archAwsSnowcone16Svg = { id: "archAwsSnowcone16Svg", name: "AWS Snowcone", icon: _archAwsSnowcone16Svg };
export const archAwsSnowmobile16Svg = { id: "archAwsSnowmobile16Svg", name: "AWS Snowmobile", icon: _archAwsSnowmobile16Svg };
export const archAwsStorageGateway16Svg = { id: "archAwsStorageGateway16Svg", name: "AWS Storage Gateway", icon: _archAwsStorageGateway16Svg };
export const archAmazonEfs16Svg = { id: "archAmazonEfs16Svg", name: "Amazon EFS", icon: _archAmazonEfs16Svg };
export const archAmazonElasticBlockStore16Svg = { id: "archAmazonElasticBlockStore16Svg", name: "Amazon Elastic Block Store", icon: _archAmazonElasticBlockStore16Svg };
export const archAmazonFsxForLustre16Svg = { id: "archAmazonFsxForLustre16Svg", name: "Amazon FSx for Lustre", icon: _archAmazonFsxForLustre16Svg };
export const archAmazonFsxForNetAppOntap16Svg = { id: "archAmazonFsxForNetAppOntap16Svg", name: "Amazon FSx for NetApp ONTAP", icon: _archAmazonFsxForNetAppOntap16Svg };
export const archAmazonFsxForOpenZfs16Svg = { id: "archAmazonFsxForOpenZfs16Svg", name: "Amazon FSx for OpenZFS", icon: _archAmazonFsxForOpenZfs16Svg };
export const archAmazonFsxForWfs16Svg = { id: "archAmazonFsxForWfs16Svg", name: "Amazon FSx for WFS", icon: _archAmazonFsxForWfs16Svg };
export const archAmazonFsx16Svg = { id: "archAmazonFsx16Svg", name: "Amazon FSx", icon: _archAmazonFsx16Svg };
export const archAmazonS3OnOutposts16Svg = { id: "archAmazonS3OnOutposts16Svg", name: "Amazon S3 on Outposts", icon: _archAmazonS3OnOutposts16Svg };
export const archAmazonSimpleStorageServiceGlacier16Svg = { id: "archAmazonSimpleStorageServiceGlacier16Svg", name: "Amazon Simple Storage Service Glacier", icon: _archAmazonSimpleStorageServiceGlacier16Svg };
export const archAmazonSimpleStorageService16Svg = { id: "archAmazonSimpleStorageService16Svg", name: "Amazon Simple Storage Service", icon: _archAmazonSimpleStorageService16Svg };
export const archCloudEndureDisasterRecovery16Svg = { id: "archCloudEndureDisasterRecovery16Svg", name: "CloudEndure Disaster Recovery", icon: _archCloudEndureDisasterRecovery16Svg };
